### ISSUE TITLE
XML Out of Memory Exception >100MB(approx)

### ISSUE THREAD

**Issue by mkarthi** [danielpalme/ReportGenerator#100]
Report Generator throws Out of Memory Exception for Large XML in XDocument.Load(reportFile)

**Comment by danielpalme** [comment]
Will have an Look at thus next week.
Can you share one of these large files?

**Comment by mkarthi** [comment]
if we try to access any xml file >100MB it throws exception

**Comment by friederschueler** [comment]
I would like to reopen this issues, as I have the same problem. I will send you an email with a link for a ftp-server of my company, because the problematic result file is ~800mb.

**Comment by danielpalme** [comment]
@friederschueler:
You can send me the link by email (danielpalme82@gmail.com).
I can try to load the coverage file on my machine, but probably it's just too big for `XDocument.Load`. But let's try.

**Comment by friederschueler** [comment]
Using the .net core version works even for large files:
`dotnet reportgenerator.4.0.4\tools\netcoreapp2.0\ReportGenerator.dll 
-reports:opencover.xml -targetdir:out`

**Comment by christianbumann** [comment]
@danielpalme I have the same issue, but my file is 2.3GB. Would it possible to use XmlReader instead of the XDocument?

**Comment by danielpalme** [comment]
@christianbumann 
Does the _dotnetcore_ version work for you ?

Using _XMLReader_ should be possible, but I would have to rewrite the parsing code.
I have to find some time for that, which is not easy....
I keep you updated if I make some progress.

**Comment by christianbumann** [comment]
@danielpalme dotnetcore works and also if I run the .Net version in 64bit. So it would be ok for me. So please don't spend too lot time on this. Thank you very much for your advise

**Comment by danielpalme** [comment]
Great. So I won't waste any time on this.

**Comment by Amrin-Taj** [comment]
@danielpalme , @christianbumann  i am still facing the issue with larger xml files. And with netcoreapp3.1 also facing the issue. We have 750 files of size ranging from 100mb to 1.5gb. It is peaking up 16GB memory after processing 200 files. Any help will be appreciated.

**Comment by danielpalme** [comment]
Some ideas:
Try to reduce the number of coverage files. Maybe you can execute your tests in one or at least fewer runs?

If this is not possible, you can try to merge the files into fewer files. E.g.

- Merge file 1-150 into Merged1.xml
- Merge file 151-300 into Merged2.xml
- Merge file 301-450into Merged3.xml
- Merge file 451-600into Merged4.xml
- Merge file 601-750 into Merged5.xml

Merging can be done with ReportGenerator: 
```
ReportGenerator.exe -reports:coverage*.xml -targetdir:merged1 -reporttypes:Coberatura
ReportGenerator.exe -reports:coverage*.xml -targetdir:merged2 -reporttypes:Coberatura
ReportGenerator.exe -reports:coverage*.xml -targetdir:merged3 -reporttypes:Coberatura
```

Now execute _ReportGenerator_ on the five merged files.

```
ReportGenerator.exe -reports:merged*/Coberatura.xml -targetdir:final -reporttypes:Html
```

**Comment by christianbumann** [comment]
@Amrin-Taj The main issue for us was running in 32bit and reach the 4Gb limit - which results in an out of memory exception. So running 64bit helped to avoid this exception, but the high memory usage is still there. It‘s currently not a problem as we splitted up the tests in different test runs (category based). Finally we are using SonarQube - there it is possible to pass multi report files too…

**Comment by Amrin-Taj** [comment]
> ReportGenerator.exe -reports:coverage*.xml -targetdir:merged1 -reporttypes:Coberatura

@danielpalme i tried this with reporttypes:'xmlSummary' but it didn't work for me, And while using corbetura, i got the error
"Unknown report type 'Coberatura'", should we do some other processing as well for coverage.xml files?

**Comment by Amrin-Taj** [comment]
> @Amrin-Taj The main issue for us was running in 32bit and reach the 4Gb limit - which results in an out of memory exception. So running 64bit helped to avoid this exception, but the high memory usage is still there. It‘s was not a problem as we splitted up the tests in different test runs (category based). Finally we are using SonarQube (ReportGenerator is no longer used)- there it is possible to pass multi report files too…

Thanks @christianbumann , just curious to know, that means you use report generator to generate the merge xml's module wise and sonarQube for passing multiple report files?. Or is there any feature in SonarCube for combining multiple summary xml's

**Comment by danielpalme** [comment]
> > ReportGenerator.exe -reports:coverage*.xml -targetdir:merged1 -reporttypes:Coberatura
> 
> @danielpalme i tried this with reporttypes:'xmlSummary' but it didn't work for me, And while using corbetura, i got the error "Unknown report type 'Coberatura'", should we do some other processing as well for coverage.xml files? Any other report types we can try to merge the coverage xml?

I had a spelling mistake. Please try again with `Cobertura` not `Coberatura`.
`XmlSummary` is the wrong format for your needs.

**Comment by christianbumann** [comment]
> > @Amrin-Taj The main issue for us was running in 32bit and reach the 4Gb limit - which results in an out of memory exception. So running 64bit helped to avoid this exception, but the high memory usage is still there. It‘s was not a problem as we splitted up the tests in different test runs (category based). Finally we are using SonarQube (ReportGenerator is no longer used)- there it is possible to pass multi report files too…
> 
> Thanks @christianbumann , just curious to know, that means you use report generator to generate the merge xml's module wise and sonarQube for passing multiple report files?. Or is there any feature in SonarCube for combining multiple summary xml's

No we no longer use ReportGenerator, but SonarQube.

**Comment by Amrin-Taj** [comment]
> ReportGenerator.exe -reports:merged*/Cobertura.xml -targetdir:final -reporttypes:Html

@danielpalme , with this when i merge somefiles using reporttype Cobertura  and then generate html report, i have covered lines and others as zero as in below picture
![image](https://user-images.githubusercontent.com/75828491/143850837-fad62057-a041-4d41-accf-b9e1f311de10.png)
not sure what i am missing.

**Comment by danielpalme** [comment]
The report has a class count of 1593.
I guess ReportGenerator can not find the corresponding files.

Can you check one of the file paths in the Cobertura file? Is the path correct? Does the file (still) exist?
Maybe you have to specify the source directory with the command line parameter `-sourcedirs:`
