### ISSUE TITLE
[Question]Do we need else block for each if block we declare? Why Opencover shows 1 of 2 branches covered if we have only one if block? Because of this open cover does not display branch coverage correctly.

### ISSUE THREAD

**Issue by pallaviSaga** [danielpalme/ReportGenerator#103]

**Comment by danielpalme** [comment]
If your code contains an if statement, then you have two branches, since the condition can evaluate to true or false.
So can you have two cases/branches, no matter if you have an else block or not.

Case1: If condition evaluates to true
Case2: If condition evaluates to false

**Comment by pallaviSaga** [comment]
If i understand correctly, if 'else' block is not available the branch coverage would be less. Also i have one more question related to try catch block.

Which branch is missing in below mentioned code
![branch issue](https://user-images.githubusercontent.com/32294716/30898143-5a8f3154-a377-11e7-9dde-675e6b75a838.png)

**Comment by danielpalme** [comment]
> If i understand correctly, if 'else' block is not available the branch coverage would be less. Also i have one more question related to try catch block.

The branch coverage does not depend on the availability of an _else_ block.
Branch coverage depends on your unit tests. To cover both branches you need two tests. One which evaluates to true and another one which evaluates to false.

> Which branch is missing in below mentioned code

Your _catch_ statement contains several OR statements (ArgumentNullException OR SecurityException OR PathTooLogException).
Your tests probably don't cover all of these exceptions.

**Comment by pallaviSaga** [comment]
Ok thank you for clarifying !
