### ISSUE TITLE
Why Report Generator Report still shows that 1 of 2 branches only covered even after covering all exception from UT

### ISSUE THREAD

**Issue by pallaviSaga** [danielpalme/ReportGenerator#104]
![image](https://user-images.githubusercontent.com/32294716/31169314-cc3782a4-a915-11e7-8c52-79ac8989d8c6.png)

I have covered all exceptions thorugh my UT. But still report generator shows me that 
1 of 2 branches are covered ?

**Comment by danielpalme** [comment]
_ReportGenerator_ just parses the branch information from the XML generated by _OpenCover_.
_ReportGenerator_ does not decide what a branch is and whether it is covered or not.

So I can't help here. _OpenCover_ uses _Mono.Cecil_ to determine the branches in the code, so probably you should have a look at the generated IL code to understand the different branches.
