### ISSUE TITLE
History Reports not reading all xml files

### ISSUE THREAD

**Issue by wiseman13** [danielpalme/ReportGenerator#107]
So I had a break in my code coverage reports and now that I have it up and running again I am finding that the ReportGenerator is not reading all of the history files in the directory to generate the line graph. Running with verbose I just see that it is reading, but there are no errors logged about why it is not reading all of them and which files it is reading. Any ideas on how to debug? I just updated to 3.0.2.0 to see if that would help, but it did not.

**Comment by danielpalme** [comment]
There are two things you need to know regarding history files:
-Only the latest 100 coverage files are read
-If coverage does not change over several executions, ReportGenerator only shows the first execution in the history charts and drop the executions that have the same coverage

Does this explain fewer points in history than you might expect?

**Comment by wiseman13** [comment]
I only have 86 history files dating back a year and a half ago, but I am only seeing one dot on the chart. It does appear that there is a change in the files that assemblies use to not have .dll at the end of their names so that could be an issue.

**Comment by danielpalme** [comment]
Assembly names and class names have to match, otherwise the mapping is not possible.

**Comment by wiseman13** [comment]
Do you know at what version it changed to add .dll to the end in the xml elements? Also even with that said I cannot get multiple dots to show up for a build that runs 10-15 times a day.

**Comment by danielpalme** [comment]
The *.dll text in the xml elements depends on the tool you are using.
Which coverage tool are you using (OpenCover, PartCover, dotCover, Visual Studio, NCover, Cobertura, Mbprof)?

Could you please try this beta release:
https://www.nuget.org/packages/ReportGenerator/3.0.3-beta2 

Do you still have issues?
If yes:
Can you provide me the latest history file and an older one?
My email: danielpalme82@gmail.com

**Comment by wiseman13** [comment]
Ah that might be my issue. I think the old reports ran using OpenCover, but the new one is with Visual Studio so I bet that is why they will not pick up. On the new Visual Studio history reports I bet the coverage is not changing, so it is not adding a new entry.

**Comment by danielpalme** [comment]
That's a good explanation.

If you upgrade to latest beta release, the summary report will contain better results (it ignores the assembly and class names from history files):
https://www.nuget.org/packages/ReportGenerator/3.0.3-beta2
