### ISSUE TITLE
History Chart: Dynamically Set Lower and Upper Bounds

### ISSUE THREAD

**Issue by jatouma** [danielpalme/ReportGenerator#110]
Currently those bounds are between 0 and 100. Is there a way to change that?

This is an issue because, if your repo has hundreds of thousands of code, then one commit won't show any fluctuation in the line, and it will look like a straight line.

I think, e.g. a good way to do this would be to dynamically set those bounds to the lowest and highest coverage point in history.

**Comment by danielpalme** [comment]
I understand your point.
On the other hand, fixed bounds have the advantage, that you see the coverage rate at first sight without having to look at the axis.
I'm not sure if everybody would like this change.

**Comment by jatouma** [comment]
Agreed, fixed bounds are good. But then maybe we can add the ability to set those bounds, keeping them 0 and 100 by default?

**Comment by danielpalme** [comment]
I'm considering adding a zoom button

**Comment by danielpalme** [comment]
Maybe you want to try this new beta release:
https://www.nuget.org/packages/ReportGenerator/3.0.3-beta1

This is how the zoom function looks like:
![historyzoom](https://user-images.githubusercontent.com/859606/31851442-05293c6c-b666-11e7-91f4-af444efe97b7.gif)

**Comment by jatouma** [comment]
I just tried this out on our solution. I think it helps :)
Thank you so much for addressing my issue so quickly!!
