### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by andrericardo** [danielpalme/ReportGenerator#112]
This is not really an issue, just wonder if you considered this?

Someone started the question on [Reddit .NET Code coverage tools for Linux/Ubuntu?](https://www.reddit.com/r/dotnet/comments/7b86pl/net_code_coverage_tools_for_linuxubuntu/)

At the moment there is not a single coverage tool for dotnet core https://github.com/dotnet/corefx/issues/17107
But seems OpenCover is on track to have dotnet core support soon https://github.com/OpenCover/opencover/issues/703

After that I think it would be nice to be able to generate the report with ReportGenerator :)

Without any changes to ReportGenerator I was able to ran it from Visual Studio Community 2017 Mac using Mono.
<img width="1280" alt="screen shot 2017-11-07 at 22 45 40" src="https://user-images.githubusercontent.com/171730/32523051-b0e06298-c411-11e7-8e32-603409f984a8.png">

Not sure how much work it is to convert a Mono to dotnet project.

At the moment learned that you can deploy dotnet core by adding the RuntimeIdentifiers

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    **<RuntimeIdentifiers>osx.10.12-x64</RuntimeIdentifiers>**
  </PropertyGroup>

</Project>
```

Publish it with
`$ dotnet publish -c release -r osx.10.12-x64`

Then you get a console application runnable from bash

`$ /Users/andre/Projects/SampleCoreConsole/bin/Release/netcoreapp2.0/osx.10.12-x64/publish/SampleCoreConsole`

<img width="665" alt="screen shot 2017-11-07 at 23 26 45" src="https://user-images.githubusercontent.com/171730/32523470-4eab467c-c413-11e7-81ff-6e772b0e6254.png">

**Comment by andrericardo** [comment]
Using the file the test file for [OpenCover.xml](https://github.com/danielpalme/ReportGenerator/blob/master/src/Testprojects/CSharp/Reports/OpenCover.xml)

With the parameters
"-reports:/Users/andre/Projects/ReportGenerator/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:/Users/andre/Projects/temp"

Managed to generate the report :D
<img width="808" alt="screen shot 2017-11-07 at 23 51 58" src="https://user-images.githubusercontent.com/171730/32524250-b0f64414-c416-11e7-9b77-541e9d88a6bc.png">

**Comment by danielpalme** [comment]
As you said, you can execute ReportGenerator with Mono
This is possible for >2 years now, after dropping the dependency to log4net. See #26 

But a **dotnet core** version of ReportGenerator totally makes sense.
I will see what I can do about that.

**Comment by danielpalme** [comment]
I just tried to migrate the code base to _dotnet core_.
I got it working with some modifications.

What I would suggest:
- Create a _netstandard2.0_ library called _ReportGenerator.Core.dll_. This can be used directly with _dotnet core_
- Create a _net461_ console application _ReportGenerator.exe_, which is actually a wrapper for users who work with the full .NET Framework

**Disadvantages**:
Since _ReportGenerator.exe_ would be dependent on a _netstandard2.0_ library, it would require at least version 4.6.1 of the .NET Framework instead of version 4.0 (which is available almost everywhere).

**Comment by andrericardo** [comment]
Changed the title as ReportGenerator already supports Mac and Linux using Mono, was not aware of that. Thanks for pointing it out!

**Comment by danielpalme** [comment]
I released a first version which supports .NET Core:
https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha2

Usage is described here:
https://github.com/danielpalme/ReportGenerator/tree/v4#usage

**Comment by andrericardo** [comment]
Had issues with dotnet --version 2.0.0 upgraded to latest 2.1.104 and it worked with

`dotnet build src/ReportGenerator.Console.NetCore/ReportGenerator.Console.NetCore.csproj`

`dotnet src/target/bin/Debug/ReportGenerator.dll "-reports:src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:temp"`

Generated the report with some complains about code not found in c:\temp.
`File 'C:\temp\AbstractClass.cs' does not exist (any more).`

`dotnet test src/ReportGenerator.Core.Test/ReportGenerator.Core.Test.csproj`

Total tests: 167. Passed: 132. Failed: 35. Skipped: 0.
Test Run Failed.
Test execution time: 3.9705 Seconds

**Comment by danielpalme** [comment]
To build the project you could also use `src\build.bat`.

What's more interesting to me:
Did you install the Nuget package (https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha2) and generate a report using:
```
dotnet ReportGenerator.dll "-reports:coverage.xml" "-targetdir:C:\report"
```

**Comment by andrericardo** [comment]
@danielpalme git cloned the repo, changed to branch v4 and built from source using `dotnet build src/ReportGenerator.Console.NetCore/ReportGenerator.Console.NetCore.csproj` 

Then ran using `dotnet src/target/bin/Debug/ReportGenerator.dll "-reports:src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:temp"`

<img width="940" alt="screen shot 2018-04-17 at 20 01 14" src="https://user-images.githubusercontent.com/171730/38890747-2d0cdffe-427a-11e8-8e05-ffb4c8500117.png">

**Comment by andrericardo** [comment]
Managed to quickly setup in Travis to run the tests with dotnet in Unix environment 
https://travis-ci.org/andrericardo/ReportGenerator/jobs/367893170#L1314

**Comment by andrericardo** [comment]
Added Visual Studio and Ubuntu image to AppVeyor, in Windows only 2 tests fail, for Linux 37 are failing.
https://ci.appveyor.com/project/andrericardo/reportgenerator

@danielpalme would you be interested in a pull request of the Travis/AppVeyor configs?

**Comment by danielpalme** [comment]
As mentioned above, the build on _Windows_ works best with `src\build.bat`.
The all tests will pass.

On _Linux_ many tests fail because all tests are based on _Windows_ file paths, which don't exist on _Linux_.

Currently a don't need any Travis/AppVeyor configs. I build and publish the Nuget packages with my local machine.

**What would be much more interesting to me**: Does the published Nuget-package work for you on _Linux_?

**Comment by xtiancapil** [comment]
@danielpalme I used the pre-release nuget (4.0.0-alpha2) successfully on a linux machine (jenkins linux agent actually)! The only error I ran into was when trying to create a badge, it couldn't find the Verdana font.

**Comment by danielpalme** [comment]
@xtiancapil:
Thanks for your feedback. Would _Arial_ be available? If yes, I would change the font.

**Comment by andrericardo** [comment]
```
dotnet --version
2.1.104

OSX version
10.13.4
```

Created a new project with  
`dotnet new console`

Installed ReportGenerator with command shown in Nuget.org
`dotnet add package ReportGenerator --version 4.0.0-alpha2`

One minor issue arguments do not support ~

<img width="797" alt="screen shot 2018-04-20 at 08 36 49" src="https://user-images.githubusercontent.com/171730/39036637-016aa522-4476-11e8-91a7-f8f6af5d1b54.png">

Using full path
```
dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha2/tools/ReportGenerator.dll "-reports:/Users/andre/Projects/ReportGenerator/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:temp"
```

Report generated successfully on my Mac, console output
```
Loading report '/Users/andre/Projects/ReportGenerator/src/Testprojects/CSharp/Reports/OpenCover.xml'
 Preprocessing report
 Initiating parser for OpenCover
  Current Assembly: Test
Initializing report builders for report types: Html
Analyzing 17 classes
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractClass)
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl1)
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractGenericClass`2)
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl2)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 5/17 (Assembly: Test, Class: Test.AnalyzerTestClass)
 Creating report 7/17 (Assembly: Test, Class: Test.ClassWithExcludes)
 Creating report 8/17 (Assembly: Test, Class: Test.CodeContract_Contract)
 File 'C:\temp\ClassWithExcludes.cs' does not exist (any more).
 File 'C:\temp\AnalyzerTestClass.cs' does not exist (any more).
 File 'C:\temp\CodeContract_Contract.cs' does not exist (any more).
 Creating report 6/17 (Assembly: Test, Class: Test.AsyncClass)
 File 'C:\temp\AsyncClass.cs' does not exist (any more).
 Creating report 9/17 (Assembly: Test, Class: Test.CodeContract_Target)
 File 'C:\temp\CodeContract_Target.cs' does not exist (any more).
 Creating report 12/17 (Assembly: Test, Class: Test.PartialClassWithAutoProperties)
 Creating report 10/17 (Assembly: Test, Class: Test.GenericClass`2)
 File 'C:\temp\PartialClassWithAutoProperties.cs' does not exist (any more).
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 File 'C:\temp\PartialClassWithAutoProperties2.cs' does not exist (any more).
 Creating report 11/17 (Assembly: Test, Class: Test.PartialClass)
 File 'C:\temp\PartialClass.cs' does not exist (any more).
 File 'C:\temp\PartialClass2.cs' does not exist (any more).
 Creating report 13/17 (Assembly: Test, Class: Test.Program)
 Creating report 14/17 (Assembly: Test, Class: Test.SomeModel)
 File 'C:\temp\Program.cs' does not exist (any more).
 Creating report 15/17 (Assembly: Test, Class: Test.SomeClass)
 File 'C:\temp\NotMatchingFileName.cs' does not exist (any more).
 Creating report 16/17 (Assembly: Test, Class: Test.TestClass)
 File 'C:\temp\TestClass.cs' does not exist (any more).
 Creating report 17/17 (Assembly: Test, Class: Test.TestClass2)
 File 'C:\temp\TestClass2.cs' does not exist (any more).
 Creating summary
Report generation took 0.3 seconds
```

Index in Firefox
<img width="1170" alt="screen shot 2018-04-20 at 08 41 58" src="https://user-images.githubusercontent.com/171730/39036885-d082abde-4476-11e8-9a37-e16e59c6123e.png">

Badges generated successfully
`dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha2/tools/ReportGenerator.dll "-reports:/Users/andre/Projects/ReportGenerator/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:temp" -reporttypes:Badges`

<img width="896" alt="screen shot 2018-04-20 at 08 49 29" src="https://user-images.githubusercontent.com/171730/39037229-c3d0c6c2-4477-11e8-97bc-ccb6d1b715f4.png">

**Comment by andrericardo** [comment]
Could not get src\build.bat to build
https://ci.appveyor.com/project/andrericardo/reportgenerator/build/job/4u97879vkbuq4lj2

Similar issue locally, would you be able to help?

First `msbuild Testprojects/CSharp/Project/Test_CSharp.csproj /t:Restore /v:m` worked:
```
Microsoft (R) Build Engine version 15.4.0.0 (xplat-master/67e8006d Thu Mar  8 17:15:24 EST 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 54.79 ms for /Users/andre/Projects/ReportGenerator/src/Testprojects/CSharp/Project/Test_CSharp.csproj.

```

Second `msbuild build.proj /t:Restore /v:m`
```
Microsoft (R) Build Engine version 15.4.0.0 (xplat-master/67e8006d Thu Mar  8 17:15:24 EST 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/andre/Projects/ReportGenerator/src/build.proj(23,3): error MSB4019: The imported project "/.nuget/packages/msbuildtasks/1.5.0.235/tools/MSBuild.Community.Tasks.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by andrericardo** [comment]
Using Docker and Ubuntu Linux

Start Docker
```
docker run -it ubuntu bash
```

within the container install sudo
```
apt-get update && \
      apt-get -y install sudo

sudo apt-get install curl -y
```

Microsoft instructions from [Get started with .NET for Linux](https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04)

```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
```

Installed dotnet core
```
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.105
```

Created a new sample project and added ReportGenerator
```
dotnet new console -o myApp
cd myApp
dotnet add package ReportGenerator --version 4.0.0-alpha2
```

Get ReportGenerator files to test
```
cd
curl -LOk https://github.com/danielpalme/ReportGenerator/archive/v4.tar.gz
tar -zxvf v4.tar.gz
```

Generate report for OpenCover ran ok, output below
```
$ dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha2/tools/ReportGenerator.dll "-reports:/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:/tmp"
```
```
$ dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha2/tools/ReportGenerator.dll "-reports:/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:/tmp" -reporttypes:Badges
Loading report '/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml'
 Preprocessing report
 Initiating parser for OpenCover
  Current Assembly: Test
Initializing report builders for report types: Badges
Analyzing 17 classes
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass)
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl1)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 3/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl2)
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractGenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 5/17 (Assembly: Test, Class: Test.AnalyzerTestClass)
 File 'C:\temp\AnalyzerTestClass.cs' does not exist (any more).
 Creating report 6/17 (Assembly: Test, Class: Test.AsyncClass)
 File 'C:\temp\AsyncClass.cs' does not exist (any more).
 Creating report 7/17 (Assembly: Test, Class: Test.ClassWithExcludes)
 File 'C:\temp\ClassWithExcludes.cs' does not exist (any more).
 Creating report 8/17 (Assembly: Test, Class: Test.CodeContract_Contract)
 File 'C:\temp\CodeContract_Contract.cs' does not exist (any more).
 Creating report 9/17 (Assembly: Test, Class: Test.CodeContract_Target)
 File 'C:\temp\CodeContract_Target.cs' does not exist (any more).
 Creating report 10/17 (Assembly: Test, Class: Test.GenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 11/17 (Assembly: Test, Class: Test.PartialClass)
 File 'C:\temp\PartialClass.cs' does not exist (any more).
 File 'C:\temp\PartialClass2.cs' does not exist (any more).
 Creating report 12/17 (Assembly: Test, Class: Test.PartialClassWithAutoProperties)
 File 'C:\temp\PartialClassWithAutoProperties.cs' does not exist (any more).
 File 'C:\temp\PartialClassWithAutoProperties2.cs' does not exist (any more).
 Creating report 13/17 (Assembly: Test, Class: Test.Program)
 File 'C:\temp\Program.cs' does not exist (any more).
 Creating report 14/17 (Assembly: Test, Class: Test.SomeClass)
 File 'C:\temp\NotMatchingFileName.cs' does not exist (any more).
 Creating report 15/17 (Assembly: Test, Class: Test.SomeModel)
 Creating report 16/17 (Assembly: Test, Class: Test.TestClass)
 File 'C:\temp\TestClass.cs' does not exist (any more).
 Creating report 17/17 (Assembly: Test, Class: Test.TestClass2)
 File 'C:\temp\TestClass2.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating summary
  Error during rendering summary report (Report type: 'Badges'): Verdana could not be found
Report generation took 0.5 seconds
```
Same issue with Verdana. I think there are no fonts installed in this Docker image
```
$ fc-list
bash: fc-list: command not found
```

Copy generated report into host machine, "dotnet" is the name of the container
```docker cp dotnet:/tmp/DockerReportGenerator/ /tmp/DockerReportGenerator```

Firefox
<img width="1178" alt="screen shot 2018-04-20 at 11 01 39" src="https://user-images.githubusercontent.com/171730/39045269-5246ff5e-448a-11e8-8368-3d38e07e6ed7.png">

**Comment by andrericardo** [comment]
Tried to find out if .Net knew the fonts folder, InstalledFontCollection (under System.Drawing.Text) is not available in .Net Core

```C#
using System;

namespace FontsConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello Fonts!");
            Console.WriteLine("GetFontsPath: {0}", 
                 Environment.GetFolderPath(Environment.SpecialFolder.Fonts));
        }
    }
}
```

OSX 
```Shell
dotnet run
Hello Fonts!
GetFontsPath: /Users/andre/Library/Fonts
```

Docker Ubuntu there is no fonts folder
```Shell
root@40bb926b92c2:/Docker/FontsConsole# dotnet run
Hello Fonts!
GetFontsPath:
root@40bb926b92c2:/Docker/FontsConsole#
```

**Comment by danielpalme** [comment]
@xtiancapil 
I replaced _Verdana_ with _Arial_. Arial should be available on every system. Docker can't be supported here.

@andrericardo 
I fixed the problem "Second msbuild build.proj /t:Restore /v:m" you mentioned here: https://github.com/danielpalme/ReportGenerator/issues/112#issuecomment-381717315
`src\built.bat` should now work.

New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha3

**Comment by andrericardo** [comment]
@danielpalme 
I'm going to try to install some fonts in the default Docker Ubuntu image to test the badges.
Still seeing issues with build.bat, care to have a look?
```
cd src
.\build.bat
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
C:\projects\reportgenerator\src\Testprojects\CSharp\Project\Test_CSharp.csproj : error MSB4057: The target "Restore" does not exist in the project.
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property is not set for project 'build.proj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\projects\reportgenerator\src\build.proj]
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property is not set for project 'build.proj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\projects\reportgenerator\src\build.proj]
Command exited with code 1
```
https://ci.appveyor.com/project/andrericardo/reportgenerator/build/8/job/ud8aavn74yy4hkvy

**Comment by andrericardo** [comment]
After installing Microsoft fonts with
```
apt-get install ttf-mscorefonts-installer
```
Even in Docker Ubuntu generated the badges fine with Verdana for 4.0.0-alpha2
```
dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha2/tools/ReportGenerator.dll "-reports:/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:/Docker/DockerReportGenerator" -reporttypes:"Html;Badges"
Loading report '/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml'
 Preprocessing report
 Initiating parser for OpenCover
  Current Assembly: Test
Initializing report builders for report types: Html, Badges
Analyzing 17 classes
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl1)
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 3/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl2)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractGenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 5/17 (Assembly: Test, Class: Test.AnalyzerTestClass)
 File 'C:\temp\AnalyzerTestClass.cs' does not exist (any more).
 Creating report 6/17 (Assembly: Test, Class: Test.AsyncClass)
 File 'C:\temp\AsyncClass.cs' does not exist (any more).
 Creating report 7/17 (Assembly: Test, Class: Test.CodeContract_Contract)
 File 'C:\temp\CodeContract_Contract.cs' does not exist (any more).
 Creating report 8/17 (Assembly: Test, Class: Test.ClassWithExcludes)
 File 'C:\temp\ClassWithExcludes.cs' does not exist (any more).
 Creating report 9/17 (Assembly: Test, Class: Test.CodeContract_Target)
 File 'C:\temp\CodeContract_Target.cs' does not exist (any more).
 Creating report 10/17 (Assembly: Test, Class: Test.PartialClass)
 File 'C:\temp\PartialClass.cs' does not exist (any more).
 File 'C:\temp\PartialClass2.cs' does not exist (any more).
 Creating report 11/17 (Assembly: Test, Class: Test.GenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 12/17 (Assembly: Test, Class: Test.Program)
 File 'C:\temp\Program.cs' does not exist (any more).
 Creating report 13/17 (Assembly: Test, Class: Test.PartialClassWithAutoProperties)
 File 'C:\temp\PartialClassWithAutoProperties.cs' does not exist (any more).
 File 'C:\temp\PartialClassWithAutoProperties2.cs' does not exist (any more).
 Creating report 14/17 (Assembly: Test, Class: Test.SomeClass)
 File 'C:\temp\NotMatchingFileName.cs' does not exist (any more).
 Creating report 15/17 (Assembly: Test, Class: Test.SomeModel)
 Creating report 16/17 (Assembly: Test, Class: Test.TestClass)
 File 'C:\temp\TestClass.cs' does not exist (any more).
 Creating report 17/17 (Assembly: Test, Class: Test.TestClass2)
 File 'C:\temp\TestClass2.cs' does not exist (any more).
 Creating summary
Report generation took 1.1 seconds
```
<img width="848" alt="screen shot 2018-04-21 at 10 44 48" src="https://user-images.githubusercontent.com/171730/39082822-0cf652ca-4551-11e8-8e17-ff12e9f8f57a.png">

Alpha3
<img width="858" alt="screen shot 2018-04-21 at 10 47 52" src="https://user-images.githubusercontent.com/171730/39082838-787badf6-4551-11e8-8b7f-611909bac304.png">

```
dotnet ~/.nuget/packages/reportgenerator/4.0.0-alpha3/tools/ReportGenerator.dll "-reports:/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml" "-targetdir:/Docker/DockerReportGenerator-alpha3" -reporttypes:"Html;Badges"
Loading report '/root/ReportGenerator-4/src/Testprojects/CSharp/Reports/OpenCover.xml'
 Preprocessing report
 Initiating parser for OpenCover
  Current Assembly: Test
Initializing report builders for report types: Html, Badges
Analyzing 17 classes
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass)
 Creating report 2/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl1)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 3/17 (Assembly: Test, Class: Test.AbstractClass_SampleImpl2)
 File 'C:\temp\AbstractClass.cs' does not exist (any more).
 Creating report 4/17 (Assembly: Test, Class: Test.AbstractGenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 5/17 (Assembly: Test, Class: Test.AnalyzerTestClass)
 File 'C:\temp\AnalyzerTestClass.cs' does not exist (any more).
 Creating report 6/17 (Assembly: Test, Class: Test.AsyncClass)
 File 'C:\temp\AsyncClass.cs' does not exist (any more).
 Creating report 7/17 (Assembly: Test, Class: Test.ClassWithExcludes)
 Creating report 8/17 (Assembly: Test, Class: Test.CodeContract_Target)
 File 'C:\temp\CodeContract_Target.cs' does not exist (any more).
 File 'C:\temp\ClassWithExcludes.cs' does not exist (any more).
 Creating report 9/17 (Assembly: Test, Class: Test.CodeContract_Contract)
 File 'C:\temp\CodeContract_Contract.cs' does not exist (any more).
 Creating report 10/17 (Assembly: Test, Class: Test.GenericClass`2)
 File 'C:\temp\GenericClass.cs' does not exist (any more).
 Creating report 11/17 (Assembly: Test, Class: Test.PartialClass)
 File 'C:\temp\PartialClass.cs' does not exist (any more).
 File 'C:\temp\PartialClass2.cs' does not exist (any more).
 Creating report 12/17 (Assembly: Test, Class: Test.Program)
 File 'C:\temp\Program.cs' does not exist (any more).
 Creating report 13/17 (Assembly: Test, Class: Test.PartialClassWithAutoProperties)
 File 'C:\temp\PartialClassWithAutoProperties.cs' does not exist (any more).
 File 'C:\temp\PartialClassWithAutoProperties2.cs' does not exist (any more).
 Creating report 14/17 (Assembly: Test, Class: Test.SomeClass)
 File 'C:\temp\NotMatchingFileName.cs' does not exist (any more).
 Creating report 15/17 (Assembly: Test, Class: Test.SomeModel)
 Creating report 16/17 (Assembly: Test, Class: Test.TestClass)
 File 'C:\temp\TestClass.cs' does not exist (any more).
 Creating report 17/17 (Assembly: Test, Class: Test.TestClass2)
 File 'C:\temp\TestClass2.cs' does not exist (any more).
 Creating summary
Report generation took 1.0 seconds
```

**Comment by danielpalme** [comment]
I'm closing this as the distributed package seems to work on Linux.
Building the project on Linux currently in not working (especially test execution), but this is not an issue for users of *ReportGenerator*.

**Comment by arpit-nagar** [comment]
Hi @danielpalme 
I am using version 4.0.0-alpha3 on Linux CentOS and I am still getting error - Error during rendering summary report (Report type: 'Badges'): Arial could not be found.

**Comment by arpit-nagar** [comment]
Thanks, @danielpalme for information.
I will install fonts.

**Comment by Hermain** [comment]
Is it normal that I have to use the dll explicitly?
I would love to be able to do `dotnet ReportGenerator.dll "-reports:coverage.xml" "-targetdir:C:\report"` but instead I'm doing `dotnet /root/.nuget/packages/reportgenerator/4.0.0-alpha8/tools/netcoreapp2.0/ReportGenerator.dll` and it seems like everyone here is doing the same. 

I am running this in the microsoft/dotnet:2.0-sdk linux container and install the nuget package with `dotnet add package ReportGenerator --version 4.0.0-alpha8`

**Comment by danielpalme** [comment]
@Hermain 
Please have a look at these two packages:

- https://www.nuget.org/packages/dotnet-reportgenerator-cli
- https://www.nuget.org/packages/dotnet-reportgenerator-globaltool

How to use the packages is described in the description of the nuget pages or here:
https://github.com/danielpalme/ReportGenerator/tree/v4#available-packages

The global tool only works if you already installed _.NET Core 2.1 Preview_.

**Comment by Hermain** [comment]
I added it to my project using `dotnet add package dotnet-reportgenerator-cli --version 4.0.0-alpha6` , restored and rebuilt the project but I still get `No executable found matching command "dotnet-reportgenerator"` maybe I should create a new issue for this?

**Comment by danielpalme** [comment]
@Hermain 
As mentioned in the description, you have to add this manually to your project file:
```
<DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.0.0-alpha6" />
```

A _CliTool_ is installed differently than a regular package.
Does this work for you?

**Comment by xtiancapil** [comment]
@danielpalme will we have a new pre-release that supports the just released dotnet core 2.1 version? I saw that global tools built with the 2.1 rc must be recompiled to work with the released version.

**Comment by danielpalme** [comment]
@xtiancapil 
Just published this new version:
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-alpha10

Does this work for you?

**Comment by xtiancapil** [comment]
@danielpalme it works great! Thanks!

**Comment by parivshah** [comment]
Hello @danielpalme,

I am trying to setup ReportGenerator using command line. I am also getting same error as mentioned in above thread related to "No executable found matching command "dotnet-reportgenerator.dll".  I am using 4.0.0-rc3 version and trying to run using VSTS build agent (Linux Hosted Preview).

I have attached unit test project file and build pipeline settings for your reference. 

![image](https://user-images.githubusercontent.com/36068928/44698217-9e2a6a00-aa9c-11e8-851c-96da056d4d1c.png)

![image](https://user-images.githubusercontent.com/36068928/44698299-fc574d00-aa9c-11e8-875f-f6ae080f0910.png)

Could you please let me know, if I am missing any configuration?

**Comment by parivshah** [comment]
@danielpalme  - Thanks for your help. Once I have setup Working directory then it's working as expected. Thanks a lot.

I have one more query regarding input reports files.

All code coverage files generated by coverlet tool are placed in their respective unit test directory. Is there any way where ReportGenerator tool can look for all files having name "coverage.cobertura.xml" in given working directory.

I had tried with below command but it didn't fetch all coverage files from all sub folders and so on.

dotnet reportgenerator "-reports:$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml" "-targetdir:$(System.DefaultWorkingDirectory)/testresults/coverage/reports" "-reporttypes:Cobertura"

With above command, it had fetch only single coverage.cobetura.xml file. Looks like tool didn't look into sub directories at all.

Kindly let me know if it possible or not.

**Comment by danielpalme** [comment]
> With above command, it had fetch only single coverage.cobetura.xml file. Looks like tool didn't look into sub directories at all.

> Kindly let me know if it possible or not.

You can use wilcards `*` in the path definition. It is currently not possible to use double wilcards ``**`.
If you solution/project has a structure like:
```
Project_1/testresults/coverage.cobertura.xml
Project_2/testresults/coverage.cobertura.xml
...
Project_N/testresults/coverage.cobertura.xml
```

you should be able to use a pattern like: `*/testresults/coverage.cobertura.xml`
