### ISSUE TITLE
<Question> I'm trying to understand the values displayed in a report

### ISSUE THREAD

**Issue by mshafer-NI** [danielpalme/ReportGenerator#114]
A default html result shows a number to the left of some lines (to the left of the line number).  Digging into the xml I get out of OpenCover and use as input to ReportGenerator, I see that it appears to match the vc propertey on a SequencePoint. Is this just the start of a sequence in the compiled code? or the number of times that line was run? 

I searched OpenCover's docs and couldn't find it, and it's not labeled in the report.

**Comment by danielpalme** [comment]
The number of times the line was executed.

**Comment by mshafer-NI** [comment]
Thank you so much – I’ve spent most of the afternoon trying to confirm that suspicion. (Thanks for the quick response too).

**Comment by Sebastriani** [comment]
@danielpalme IMO it would be good to add this question/anser in the FAQ.
