### ISSUE TITLE
enable filtering on overview is not applicable

### ISSUE THREAD

**Issue by LymanZerga** [danielpalme/ReportGenerator#116]
Hi,

we have an issue with our generated overview of our opencover results. We have covered about 15 assemblies so we want to collapse all of them in the overview. But this always hangs or is extremly slow. Also collapsing one assembly hangs. Seems to be an issue with the underlaying java command or the amount of data but we have no glue how to solve this. 

Does anybody knowing this problem?

**Comment by danielpalme** [comment]
Could you please send me your index.html and the corresponding combined.js file?

danielpalme82@gmail.com

**Comment by LymanZerga** [comment]
This email address danielpalme82@gmail.com is not correct. I always get i mailer deamon.

**Comment by danielpalme** [comment]
The address is correct.

**Comment by LymanZerga** [comment]
Hi Daniel,

 

regarding my issue I have attached the data and replaced some namespace literals with A,B,C,D due to sensible data. 

 

Hope this helps.

 

Regards Marcus

 

Gesendet: Dienstag, 28. November 2017 um 09:50 Uhr
Von: "Daniel Palme" <notifications@github.com>
An: danielpalme/ReportGenerator <ReportGenerator@noreply.github.com>
Cc: LymanZerga <rollerfreak2@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [danielpalme/ReportGenerator] enable filtering on overview is not applicable (#116)


Could you please send me your index.html and the corresponding combined.js file?

danielpalme82@gmail.com

**Comment by LymanZerga** [comment]
The content of the mail contains potential security issue. I have zipped it. Any idea how to pass the data?

**Comment by LymanZerga** [comment]
I have uploaded the data on a share and you should got a mail with the link.

**Comment by danielpalme** [comment]
Just received your sample report. Will have a look at it and see if performance can be improved.

**Comment by LymanZerga** [comment]
Any news from your side?

**Comment by danielpalme** [comment]
I can confirm, that is the page is pretty slow. The problem is not the filtering itself.
The rendering of the table takes most of the time.

I have to check, if there is a way to speed things up. But this will not happen within the next days.
At the moment I'm too busy to take care of that.

**Comment by LymanZerga** [comment]
Thanks for the update.
I will try it out when I am back in office (07.02). Keep you informed.

**Comment by LymanZerga** [comment]
I have tried the new package 4.0.11 and it turned out that the performance for Collapse all | Expand all on the summary page is much better than before. 
You can close this issue.
