### ISSUE TITLE
Add unitness analysis

### ISSUE THREAD

**Issue by lukas-lansky** [danielpalme/ReportGenerator#118]
I would like to try add support for [an analysis I played with](https://programming.lansky.name/analysing-unitness/) some time ago at my blog. It tries to shed a light on how big part of the coverage is caused by tests that are "small" in terms of their individual coverage.

Do you think it would be useful?

**Comment by danielpalme** [comment]
@lukas-lansky 
I think this might me a nice feature.

Before you start with an implementation:
I have plans to make some fundamental changes in the code base. So I think it makes sense to wait until I have finished to avoid integration problems.

**Comment by lukas-lansky** [comment]
Superb, thanks for the heads up.

**Comment by danielpalme** [comment]
It's been a while...
I recently finished v4 and if you like, you can give this feature a try.

Let me know when you need help.
The HTML reports are not easy to understand since several variations exist and some components are written in React and AngularJs.
