### ISSUE TITLE
Files no longer linked in Summary

### ISSUE THREAD

**Issue by stevospinks** [danielpalme/ReportGenerator#12]
I have just upgraded from 1.9.1 to 2.1.4 - great work with branch coverage, by the way!

When the report is generated now, all the required files are generated, but they are not linked in the Summary page.
Here's an example with sensitive information crudely removed in paint.
![image](https://cloud.githubusercontent.com/assets/11633557/6806311/caad6df4-d23f-11e4-9c9e-4e6aaf72fd8f.png)

I was previously using this call (inside a batch file):
````
..\packages\ReportGenerator.2.1.4.0\ReportGenerator.exe^
 -reports:.\report\output.xml^
 -targetdir:.\report^
 -reporttypes:Html,HtmlSummary^
 -historydir:.\report\history^
 -filters:-UnitTests*
````
but had to change `-reporttypes:Html,HtmlSummary` to `-reporttypes:Html;HtmlSummary` to get it to work again. Could this be the issue?

Is there something I'm missing here?

**Comment by danielpalme** [comment]
**HtmlSummary** creates a single HTML file (without links). 
**Html** creates the summary (with links) and detailed reports for each class.

So you should just change to ```-reporttypes:Html```

**Comment by stevospinks** [comment]
That's worked!

Thanks for such a quick response (and sorry for wasting your time with something I should have been able to work out myself...)
