### ISSUE TITLE
Compiler Generated classes are not recognized correctly

### ISSUE THREAD

**Issue by marek-safar** [danielpalme/ReportGenerator#120]
In the HTML output page I can see entries like

```
Microsoft.CSharp.RuntimeBinder.SymbolTable
Microsoft.CSharp.RuntimeBinder.SymbolTable.&lt;&gt;c__DisplayClass13_1
Microsoft.CSharp.RuntimeBinder.SymbolTable.&lt;&gt;c__DisplayClass28_0
Microsoft.CSharp.RuntimeBinder.SymbolTable.&lt;&gt;c__DisplayClass50_0
```

only the first type `Microsoft.CSharp.RuntimeBinder.SymbolTable` is user visible and has the source code for all nested `*DisplayClass*` entries which should not be displayed but inlined into `Microsoft.CSharp.RuntimeBinder.SymbolTable`.

**Comment by danielpalme** [comment]
Can you please send me your coverage file by mail (danielpalme82@gmail.com)?

**Comment by marek-safar** [comment]
I noticed there is escaping issue in the source xml file, will try to resolve it first

**Comment by danielpalme** [comment]
I'm closing this for now. Please reopen if you need further support
