### ISSUE TITLE
HTMLChart;PngChart are not working

### ISSUE THREAD

**Issue by firatoltulu** [danielpalme/ReportGenerator#121]
[CoverageHistory.zip](https://github.com/danielpalme/ReportGenerator/files/1677793/CoverageHistory.zip)

Hi,

I use ReportGenerator with parameters "-reporttypes:LatexSummary;PngChart;HtmlChart;Html" 
Than I opened CoverageHistory.htm but i dont see anything, i thing run wrong parameters with ReportGenerator

I added CoverageHistory.zip with this post

Parameters,

"%ReportGeneratorExe%" ^
 -reports:"%~dp0\GeneratedReports\CoverageReport.xml" ^
 -targetdir:"%~dp0\GeneratedReports\ReportGenerator" ^
 -reporttypes:LatexSummary;PngChart;HtmlChart;Html

**Comment by danielpalme** [comment]
The 'PngChart' and 'HtmlChart' reporttypes shows a chart containing historic coverage information.
To see some meaningful data you have to set the following parameter:
-historydir:SOME_PERSISTENT_DIRECTORY

**Comment by firatoltulu** [comment]
Hi,
Thank you for answer, i will try it.

**Comment by danielpalme** [comment]
Did the new parameter help?

**Comment by firatoltulu** [comment]
Hi,

Sorry for late, yes it works.  
thank you so much.
