### ISSUE TITLE
Question : 

### ISSUE THREAD

**Issue by roozbehid-ic** [danielpalme/ReportGenerator#124]
Can you explain what is block?
When I am looking into blocks covered and not covered. What are they? Compared to lines covered.
I am trying to write a program that diffs different reports to find out code coverage changes, so I was wondering should I go for lines or blocks?

**Comment by danielpalme** [comment]
Please have a look at the following:

-  #32
- VS uses blocks, see some explanation here: http://stackoverflow.com/questions/4958209/the-blocks-in-code-coverage-with-vs2010
