### ISSUE TITLE
Difference in branch coverage results from OpenCover

### ISSUE THREAD

**Issue by urarus** [danielpalme/ReportGenerator#125]
Hello. I've got the following question, worrying me:

OpenCover.xml for my project contains branchCoverage="83.95", which is acceptable metric. From other side, Report Generator html report displays: Branch coverage: | 75.1%. Who should I trust? Why Report Generator makes  own calculations?

**Comment by danielpalme** [comment]
The last paragraph **Branch coverage** explains the difference:
https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details
