### ISSUE TITLE
The same coverage presented in different formats gives different results

### ISSUE THREAD

**Issue by SteveGilham** [danielpalme/ReportGenerator#127]
Take the following code
```
let Example (x : int option) =
    x
    |> Option.iter (fun i -> Seq.initInfinite id
                             |> Seq.take i
                             |> Seq.iter (printfn "%A"))

[<EntryPoint>]
let main argv = 
    printfn "CLR Version %A" <| System.Environment.Version.ToString()
    Example None
    printfn "Done"
    0
```
in which the lambda expression is not executed.  Building an x86 executable to .net 2.0, NCover 1.5.8 yields (stripped to its essentials)
```
<seqpnt visitcount="1" line="2" column="5" endline="5" endcolumn="57" 
<seqpnt visitcount="1" line="9" column="5" endline="9" endcolumn="29" 
<seqpnt visitcount="1" line="10" column="5" endline="10" endcolumn="17" 
<seqpnt visitcount="1" line="11" column="5" endline="11" endcolumn="19" 
<seqpnt visitcount="1" line="12" column="5" endline="12" endcolumn="6" 
<seqpnt visitcount="0" line="3" column="30" endline="5" endcolumn="56" 
<seqpnt visitcount="0" line="3" column="47" endline="3" endcolumn="49" 
<seqpnt visitcount="0" line="5" column="43" endline="5" endcolumn="55" 
```
Running the same executable under OpenCover 4.6.519 gives, similarly,
<SequencePoint vc="1" sl="2" sc="5" el="5" ec="57"
<SequencePoint vc="1" sl="9" sc="5" el="9" ec="29"
<SequencePoint vc="1" sl="10" sc="5" el="10" ec="17"
<SequencePoint vc="1" sl="11" sc="5" el="11" ec="19"
<SequencePoint vc="1" sl="12" sc="5" el="12" ec="6"
<SequencePoint vc="0" sl="3" sc="47" el="3" ec="49"
<SequencePoint vc="0" sl="5" sc="43" el="5" ec="55"
<SequencePoint vc="0" sl="3" sc="30" el="5" ec="56"
which differs only in that the unvisited sequence point representing the lambda body starting at line 3 col 30 has dropped two places to come in last.

Using ReportGenerator 3.1.2, the former gives a report with 71.4% coverage, the latter gives a rather flattering (if incorrect) 100% coverage.  Conversely, the former report suggests that line 2 has been visited 4 times (and line 4 -1 time), whereas the latter gives a 1 for each line of code.
 
Supporting data
[miscover.zip](https://github.com/danielpalme/ReportGenerator/files/1833504/miscover.zip)

**Comment by danielpalme** [comment]
Thanks for reporting this and thanks for the good example!
The report for _NCover_ is incorrect. I had a bug in the calculation if a _seqpnt_ spanned several lines.

**Comment by SteveGilham** [comment]
In the role of someone who needs to get over a %age covered target set from above, then the OpenCover style answer would be the one I would want presented in dashboard reports being pushed out by the build server for consumption by management.

But speaking as an engineer looking for gaps in my testing, the current NCover style result is the more useful, even if I have to scan for where the visit count numbers are less than or equal to zero in a sea of green after seeing the lower headline number.

Of course, if I get my dashboard numbers using [coveralls.net](https://github.com/csMACnz/coveralls.net), I end up with a coverage value that is somewhere between the two :)

**Comment by danielpalme** [comment]
I released a new version which fixes this issue:
https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha2
