### ISSUE TITLE
Guidance on integrating with TeamCity

### ISSUE THREAD

**Issue by qujck** [danielpalme/ReportGenerator#13]
Hi Daniel,

please can you offer any guidance on how I should integrate a coverage report with TeamCity v9?

I've tried a couple of different things in the artifacts path box in *Build Configuration Settings* -> *General Settings* but nothing seems to work particularly well:

    ..\Artifacts\%build.counter%\Coverage\index.htm

has no css

and

    ..\Artifacts\%build.counter%\Coverage\index.htm
    ..\Artifacts\%build.counter%\Coverage\*.*

list all htm files and index.htm only displays the table at the top of the page (I think I fixed this when using Cruise Control by running a power shell script to remove script from the page)

Any help will be greatly appreciated.

Peter

**Comment by danielpalme** [comment]
I use the following "Artifact path": ..\Artifacts\%build.counter%\Coverage/*.* => Coverage.zip

This approach has the following advantages:
* You can download the full report as a ZIP file.
* You can view the report in TC

After creating the report I always rename `index.htm` to `index.html`.
I don't know if this is still necessary, but in older versions of TC it was not possible to view the report with a `.htm` extension.

**Comment by qujck** [comment]
Thanks, I've got that bit working and I now see `coverage.zip` on the *Artifacts* tab - is there some way to get the full report to display nicely somewhere on the TeamCity screens?

**Comment by danielpalme** [comment]
Yes, cou can click on the `+` next to `coverage.zip` in your artifacts page. Then you see the files in the ZIP archive. Scroll down to `index.html` and you can display it with a click

**Comment by qujck** [comment]
Oh yes (face-palm) - do I need to run `RemoveScriptsFromReport.ps1` to stop the main list from disappearing as it is rendered?

**Comment by danielpalme** [comment]
`RemoveScriptsFromReport.ps1` is only a workaround for CruiseControl. TC does not require this script.

**Comment by qujck** [comment]
Sure, you are right, I've tried it in Firefox and it displays as expected. The report does not display correctly in IE9.

Cheers,

Peter

**Comment by danielpalme** [comment]
As far as I remember you IE9 is no longer supported by ReportGenerator.
With IE 11 it works as expected.

**Comment by qujck** [comment]
Sure, I am limited to IE9 as this is the corporate standard (many desktops are still XP/IE8) - thanks for your help :-)
