### ISSUE TITLE
Method summaries are not very useful when there are multiple overloads of a name

### ISSUE THREAD

**Issue by SteveGilham** [danielpalme/ReportGenerator#131]
This is especially true in F# code where the compiler is can generate scores of nested function types with methods called "Invoke".  With just the name, not even the (perhaps less ambiguous argument signature), it's not at all obvious which part of the codebase is being indicated.  A link to the line in the source where the method starts would be great (or even just the line number in the table.
[_UnitTestWithAltCoverCoreRunner.zip](https://github.com/danielpalme/ReportGenerator/files/1976558/_UnitTestWithAltCoverCoreRunner.zip)

**Comment by danielpalme** [comment]
I linked the method names to the corresponding code positions.
Could you please try again with this pre-release:
https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha4

Hint: The package structure changed a bit. `ReportGenerator.exe` is now in the `tools\net47` directory.

**Comment by SteveGilham** [comment]
That works very nicely, thank you.  I can now see what piece of code (which particular lambda expression) it is that is being reported with a high complexity.
