### ISSUE TITLE
Branch coverage summary column in index.htm only briefly visible for some report sets

### ISSUE THREAD

**Issue by SteveGilham** [danielpalme/ReportGenerator#132]
Affects 3.1.2 and the latest 4.0.0 pre-release combining these reports with the rest of the command line being 
`-reporttypes:Html;XmlSummary  -verbosity:Verbose`

[_Reports.zip](https://github.com/danielpalme/ReportGenerator/files/1996402/_Reports.zip)

The brief glimpse of branch coverage looks plausible (varying amounts of red and green); and there's nothing immediately obvious as to why these files behave differently to others -- there are no warnings emitted during the report generation, for example.

**Comment by danielpalme** [comment]
I generated the reports for your files with the following script;
```
ReportGenerator.exe -reports:ShadowTestWithAltCoverCoreRunner.xml -reporttypes:Html;XmlSummary -verbosity:Verbose -targetdir:ShadowTestWithAltCoverCoreRunner
ReportGenerator.exe -reports:UnitTestWithAltCoverCoreRunner.xml -reporttypes:Html;XmlSummary -verbosity:Verbose -targetdir:UnitTestWithAltCoverCoreRunner
ReportGenerator.exe -reports:XTestWithAltCoverCoreRunner.xml -reporttypes:Html;XmlSummary -verbosity:Verbose -targetdir:XTestWithAltCoverCoreRunner
```
The following ZIP archive contains the results:
[Reports.zip](https://github.com/danielpalme/ReportGenerator/files/1997742/Reports.zip)

Can you explain what's wrong with these reports? I don't understand your problem yet.
Maybe a screenshot helps?!

**Comment by SteveGilham** [comment]
What I get when generating a combined report of all three, the result looks like this with the table truncated after the line coverage column
![132a](https://user-images.githubusercontent.com/7460854/39960370-b891834c-5619-11e8-99eb-76af50648e02.png) -- a still snapshot of course doesn't capture the brief flicker of the branch coverage column.  Presumably something in the JavaScript is doing something to remove them.

This is where things get more confusing, as, if I copy the report files to another folder, the branch coverage column does show up. It doesn't seem to be related to the either whole path length or containing directory name length, though, as copying the generated report to paths of the same or greater length fixes things as much as copying to shorter ones.

**Comment by danielpalme** [comment]
The HTML contains a static version of the table.
As soon as the included JavaScript is loaded, the table is rendered again with filtering capabilities.
If you disable JavaScript you should always see the table including the branch column.

I also created a combined report of all three files you provided, I can't reproduce the issue on my machine.

**Comment by SteveGilham** [comment]
The effect has been quite durable, through browser restarts, deleting the directory tree, and different builds of the code from which the coverage information was gathered.  I shall start digging through the code myself, and if I find what might be causing this, I'll re-open with detailed information.
