### ISSUE TITLE
Generate empty Risk Hotspots section when no risk hotspots

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator#133]
I would add an (empty) Risk Hotspots section in **Risk Hotspots - free analysis** to emphasize the lack of them.

Project **with** Risk Hotspots
![with](https://user-images.githubusercontent.com/11148519/40222115-c6199bd0-5a7e-11e8-9cf7-fc1ac4b41f17.PNG)

Project **without** Risk Hotspots
![without](https://user-images.githubusercontent.com/11148519/40222126-cce067e6-5a7e-11e8-8ce8-7d748b1ecc22.PNG)

**Comment by danielpalme** [comment]
There are two reason why no risk hotspot exists:
* Coverage tool does not create any metrics
* No threshold has been exceeded

I'm not sure if the first group should get a message that no hotspot exists. That may be misleading.

**Comment by eduherminio** [comment]
It definitely shouldn't, so the challenge would be discerning between those two situations.
Congrats on the project, BTW.

**Comment by danielpalme** [comment]
Thanks!
New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha6
