### ISSUE TITLE
[v4] MSBuild Refactor

### ISSUE THREAD

**Issue by hunterjm** [danielpalme/ReportGenerator#134]
@danielpalme - I'm getting ready to look into creating a new MSBuild project that targets both core and standard to be able to run ReportGenerator in a build pipeline.  This is coming about due to comments on https://github.com/tonerdo/coverlet/pull/105.  Before I started, I wanted to get your thoughts.  Would you be up for also including a ReportGenerator.MSBuild package that basically moves the build task out of the .NET Standard console app and (hopefully) works for both core and standard?

**Comment by danielpalme** [comment]
I guess that this should be doable. Coverlet also provides a _netstandard2.0_ 
 msbuild package: https://www.nuget.org/packages/coverlet.msbuild/

Creating another nuget package sounds reasonable.

**Comment by danielpalme** [comment]
Starting with this [release](https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc1) _ReportGenerator_ now also contains a [props file](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package).

When you install the package you can do something like this with MSBuild:
```
<ReportGenerator ReportFiles="OpenCover.xml" ReportTypes="Html;Badges" TargetDirectory="target\reports\coverage" HistoryDirectory="target\reports\coveragehistory" />
```
