### ISSUE TITLE
Method metrics use decimals instead of doubles

### ISSUE THREAD

**Issue by mahalex** [danielpalme/ReportGenerator#135]
ReportGenerator uses decimal.Parse to parse line rate, branch rate, and cyclomatic complexity from Cobertura-produced XML files (see `SetMethodMetrics()` in `src/ReportGenerator.Console/Parser/CoberturaParser.cs`). However, Cobertura actually [uses](https://github.com/cobertura/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/reporting/xml/XMLReport.java) [doubles](https://github.com/cobertura/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/coveragedata/CoverageDataContainer.java) for those fields. This leads to bugs: it may happen that a perfectly proper Cobertura XML file contains 'NaN' as line rate, which is a valid double that can be parsed using double.Parse, but this won't be accepted by ReportGenerator (and throw an unhandled exception), since it is not a valid decimal.

**Comment by danielpalme** [comment]
Did you ever see a _NaN_ in a real world Cobertura file?!

**Comment by mahalex** [comment]
Yes, I did: MATLAB's [built-in unit test framework](https://www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.codecoverageplugin-class.html) produces coverage reports that can contain NaNs.

**Comment by danielpalme** [comment]
I will take care of this.

**Comment by mahalex** [comment]
It works, thanks!
