### ISSUE TITLE
Cobertura parser expects for non-existent fields

### ISSUE THREAD

**Issue by deeptowncitizen** [danielpalme/ReportGenerator#136]
I'm trying to generate report from cobertura produced by:
- [Istnabul ](https://www.npmjs.com/package/karma-coverage-istanbul-reporter)reporter (angular + typescript)
- [OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter)

The problem is that I'm not getting branch coverage information (Html report type) because it is not available (I suppose).

In both output files I have lines e.g.:

    <line number="6" hits="2" branch="true" condition-coverage="66.66666666666666% (2/3)"/>

This line contains branch coverage information. In the same time ReportGenerator expects to have [sub-items](https://github.com/danielpalme/ReportGenerator/blob/a5ddb46b972718b52d1f6e3e0fa7bbe49f839791/src/Testprojects/Java/Reports/Cobertura2.1.1.xml#L142) for this node, and does not use `condition-coverage` attribute.

I'm not sure is this the latest format version, but I believe istanbul and OpenCoverToCobertura can dictate the `correct` format

**Comment by danielpalme** [comment]
I don't know if there is an official version of the _correct_ format. I have seen different output formats especially for the _Cobertura_ format.

I will have a look if I can improve ReportGenerator to work without the `<condition` subelements.
But it will take 1-2 weeks to get this finished.

By the way: If you have reports in _OpenCover_ format, there is no need to convert them to _Cobertura_ format with _OpenCoverToCoberturaConverter_. _ReportGenerator_ supports the _OpenCover_ format out of the box.

**Comment by danielpalme** [comment]
Do you have a full coverage file generated by _Instanbul_ which you can share?

**Comment by danielpalme** [comment]
Version 0.3.3 of _OpenCoverToCoberturaConverter_ now also adds `<condition>` elements to the generated _Cobertura_ file.
https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.3.3
