### ISSUE TITLE
Unknown report type 'Html'.

### ISSUE THREAD

**Issue by samrules** [danielpalme/ReportGenerator#137]
Hi, 

I downloaded the project, built it and then executed it command. 

ReportGenerator.exe "-reports:test.coveragexml" "-targetdir:report"

and I am getting  "Unknown report type 'Html'.".

Can you please tell me what am I missing.

**Comment by danielpalme** [comment]
I assume you downloaded the "master" branch.
Make sure that the "ReportGenerator.Reporting.dll" is located in the same directory as "ReportGenerator.exe". It should be copied automatically, but seems to be missing in your case.

**Comment by samrules** [comment]
Thanks. This solved the problem.
