### ISSUE TITLE
Configurable Risk HotSpot thresholds for v4

### ISSUE THREAD

**Issue by lokalan** [danielpalme/ReportGenerator#138]
It looks like the Risk HotSpot thresholds are hardcoded in v4?

https://github.com/danielpalme/ReportGenerator/blob/v4/src/ReportGenerator.Core/Reporting/CodeAnalysis/RiskHotspotsAnalysis.cs#L16

Shouldn't they be configurable like the previous version?

Also if we want to configure them via the `dotnet-reportgenerator-cli` package, would they need to be command line arguments?

**Comment by danielpalme** [comment]
They are currently hardcoded. But v4 is still in development and I plan to change that before the final release.

**Comment by danielpalme** [comment]
In latest (pre-)release the thresholds can be changed in `appsettings.json` or by supplying command line parameter(s):

```
riskHotspotsAnalysisThresholds:metricThresholdForCyclomaticComplexity=30
riskHotspotsAnalysisThresholds:metricThresholdForCrapScore=15
riskHotspotsAnalysisThresholds:metricThresholdForNPathComplexity=200
  ```

https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha11
