### ISSUE TITLE
Question: History marker for each class in the HTML-report

### ISSUE THREAD

**Issue by ScottGenius** [danielpalme/ReportGenerator#141]
I setup OpenCover with the ReportGenerator on a Jenkins frequently build. It works already satisfying. 
But for the practical needs following addon could be quite helpful:

A history function for comparison to the last build.
Each class in the HTML-report-table should get an additional delta-column (red-marked when higher 0) for the columns "Uncovered and Coverable".
With that function all recent changes would be marked and highlighted to control if there should be done some more in the unit tests.
The Cobertura-Plugin also works fine, but does only show general values of the sum of all classes.
[Wiki: Custom history storage](https://github.com/danielpalme/ReportGenerator/wiki/Custom-history-storage) also describes a history-diagram-function quite similar to Cobertura, but difficult to to maintain.

Makes it sense to have this function, or can it get realized with the exisiting modules with adequate effort?

**Comment by danielpalme** [comment]
Comparing with the last run is **only** helpful if you have few builds. In a team environment with a build for every check in this won't be helpful, to many changes would get lost.
ReportGenerator already generates a charts for every class (tiny in overview, big if you open class report).
![history](https://user-images.githubusercontent.com/859606/41727775-749dcd50-7575-11e8-847f-b9dc3bea5a89.png)
To see these charts, you have to set the parameter -history:%SOME_PERSISTENT_FOLDER%
No need to create a custom history storage in your situation.

**Comment by ScottGenius** [comment]
I understand, when the line rises it also marks modifications.
Actual I don't get the history diagram displayed with the unmodified program versions.
The HistoryFiles.xml are collected in the historydir, but not displayed in the index.htm.

Batch-file to run in Jeninks:

```
:: OpenCover 4.6.519
%codeCoverToolsDir%\OpenCover\OpenCover.Console.exe ^
 -register:Path64 ^
 -target:"nunit3-console.exe" ^
 -targetargs:"%ASSEMBLIES%" ^
 -filter:"+[*]* -[*UnitTest*]*" ^
 -output:"%reportsDir%\1_OpenCover\OpenCoverOutput.xml"

:: ReportGenerator 3.1.2.0
%codeCoverToolsDir%\ReportGenerator\ReportGenerator.exe ^
 -reports:"%reportsDir%\1_OpenCover\OpenCoverOutput.xml" ^
 -targetdir:"%reportsDir%\2_ReportGenerator" ^
 -historydir:"C:\Temp" ^
 -reportTypes:"Html;HtmlChart;HtmlSummary;HTMLInline;MHTML"
```

Jenkins ReportGenerator Post-build-plugin config:

HTML directory to archive: trunk\Output\UnitTest\Reports\2_ReportGenerator\
Index page[s]: index.htm
Keep past HTML reports: checked
Include files: **/*

Is something wrong at my configuration?

**Comment by stefantinger** [comment]
I think the idea is not that bad and we are going to start a project soon, where we get some kind of information, that the coverage for a certain area (namespace, class, etc.) has dropped (not really specified right now).

Our problem with only the history chart right now is, that it is not easily possible (several 100k LOC) to find the area where the coverage has dropped (you need to compare an old report with the new one and look through it and its quite some work with that large code base). Idea: possibility to compare the current build with a history entry (or compare two history entries) and it shows you all areas where the coverage has dropped. And maybe also including a diff of the un-/covered source code between the selected executions. (But I think the implementation effort will be pretty much for such a feature...)

**Comment by ScottGenius** [comment]
Nice that you take my idea to consider.

But for the fast solution I want make the suggested, existing history-diagrams run.
When I use the setting of my last post I receive only the main-diagram with only 2 datasets, but no one of the single classes diagram.
I already have 25 *.xml files with data in the -historydir.
Can you tell me what is the minimal effort to display the complete history diagrams?

index.htm :
![index-htm](https://user-images.githubusercontent.com/40466294/41776345-ae14bf00-7627-11e8-91ef-b1f35990f51c.png)

CoverageHistory.htm :
![coveragehistory-htm](https://user-images.githubusercontent.com/40466294/41776351-b4745cb6-7627-11e8-8a9d-6ecc9851f91b.png)

Summary.htm :
![summary-htm](https://user-images.githubusercontent.com/40466294/41776373-cde11680-7627-11e8-87c8-c60d536e44ce.png)

**Comment by danielpalme** [comment]
@ScottGenius 
The tiny chart is only visible if there are at least two different coverage rates for a class.
You can force this by modifying on of the numbers in a history file for a class.

The same applies to the big charts:
Only if coverage changes, a new point is added to the chart and if you hover the point, you can see some details (especially the date when coverage changed).

**Comment by danielpalme** [comment]
@ScottGenius 
Did my last comment help?

@stefantinger 
You are right, the chart it not suitable to get an overview of coverage changes in a large code base.
I'm thinking about about adding a separate view (or extending the existing overview) so you can set a baseline to which the current coverage is compared.

**Comment by ScottGenius** [comment]
Yes, I also became the idea to fake some data-changes into the history files, short before I read your answer. And now the small charts appear at the rows of changed classes. That's also a nice indicator to differ between recent small changes and no changes.

As report type I like the HTMLInline, because it combines links with the history info in one report.

Only last small problem was the Jenkins restrictions which display Javascript-HTML-pages without formats.
But following change in Jenkins configuration allows links to Javascript-HTML-pages:
File ...\Jenkins\jenkins.xml
Tag: executable>%BASE%\jre\bin\java</executable>
Add Argument: -Dhudson.model.DirectoryBrowserSupport.CSP

Finally I'm happy with the present functionalities of CodeCover + ReportGenerator.
When you add the improvement in the next versions, I will like them, too.

Greetings from the Badenser-Ländle.
