### ISSUE TITLE
Merging output reports

### ISSUE THREAD

**Issue by corentinaltepe** [danielpalme/ReportGenerator#142]
Hi,

**Problem**
I have a need to merge OpenCover's output reports AFTER running tests coverage analysis separately. The reason behind this is I have a list of unit tests and a list of integration tests. I run coverage for each separately, generate reports, then I combine both reports for a global coverage. I use ReportGenerator to generate the reports, and it merges OpenCover reports well. However, Jenkins doesn't have an OpenCover plugin to nicely integrate the coverage reports, so I publish the ReportGenerator HTML reports into Jenkins.

I also use an OpenCover-to-Cobertura converter, and then use Jenkins' Cobertura plugin to pulish the results in a nice format in Jenkins, but that works for only 1 report (either Units Tests list or Integration Tests).
I would like to merge the Unit Tests and Integration Tests results of OpenCover, to then convert it to Cobertura for an easy publishing to Jenkins. I have looked at merging Cobertura reports as an alternative but without luck.

**Implementation**
Looking at OpenCover XML report structure, it should be quite easy to do :
1 . Copy/Paste the _Modules_ lists from each report to the merged report.
2. Compute the _Summary_ of each report, and this is where there is a bit of business logic to implement and will need maintenance later on. From my understanding : 
- _numSequencePoints_, _visitedSequencePoints_, _numBranchPoints_, _visitedBranchPoints_, _visitedClasses_, _numClasses_, _visitedMethods_, _numMethods_ are simply sums of each report's _Summary_ respective attributes
- _maxCyclomaticComplexity_ and _minCyclomaticComplexity_ are the min/max of all reports
- _sequenceCoverage_, _branchCoverage_ are trickier, would you explain how I can compute them properly ?
- Am I forgetting something ?

**Question**
Do you think a merging feature would have its place in OpenCover ? I would see it as a command line verb action such as : _opencover merge -source:unit.tests.xml,integration.tests.xml -output:global.xml_

I personnally believe such feature should be part of OpenCover's core, and not as a peripheral tool, because it's code should evolve with the core's business logic (if, for example, the sequence and brancheCoverage computation rules evolve or new ones are added).

Would you accept such pull request ?

**Comment by corentinaltepe** [comment]
Appologies,
this should go to OpenCover project.

**Comment by danielpalme** [comment]
Have a look at the latest release of ReportGenerator: https://www.nuget.org/packages/ReportGenerator/4.0.0-alpha12

It also supports _Cobertura_ as an output format. Perhaps this is useful for integration into Jenkins?
