### ISSUE TITLE
Exception Thrown While Generating Report

### ISSUE THREAD

**Issue by acgritt** [danielpalme/ReportGenerator#145]
The following exception is generated when attempting to generate a report with Version 3.1.2.0:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Palmmedia.ReportGenerator.Parser.OpenCoverParser.<>c.<ProcessClass>b__13_5(XElement m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Palmmedia.ReportGenerator.Parser.OpenCoverParser.ProcessClass(Dictionary`2 fileIdsByFilename, Assembly assembly, String className)
   at Palmmedia.ReportGenerator.Parser.OpenCoverParser.<>c__DisplayClass12_0.<ProcessAssembly>b__9(String className)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```
The Coverage file was generated using AltCover and it seems to stem from the fact that some of the `FileRef` elements exist without a `uid` attribute in the XML file. Such that the element exists solely as:
```xml
<Method skippedDueTo="Filter" visited="false" cyclomaticComplexity="4" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false" crapScore="0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" minCrapScore="0" maxCrapScore="0" />
  <MetadataToken>100663332</MetadataToken>
  <Name>...some name...</Name>
  <FileRef />
  <SequencePoints />
  <BranchPoints />
  <MethodPoint vc="0" uspid="100663332" ordinal="0" offset="0" />
</Method>
```

I have pulled down the V4 branch and tested that and it has the same issue.  I have been able to get this working locally in that branch and if you want I can submit a PR for it later.  Otherwise it seems to be related to OpenCoverParser.cs lines 156 and 316.

**Comment by danielpalme** [comment]
Thanks for you detailed issue description and analysis.
I will take care of this.
Probably those elements have to be ignored, since it's not possible to get the corresponding file.

**Comment by acgritt** [comment]
All of the ones that didn't have a `FileRef` did have the attribute `skippedDueTo="Filter"` on the `Method` element so it would probably be better to filter on that attribute instead of only the existence of the `FileRef` element.

**Comment by danielpalme** [comment]
Could you please try this new release:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc2

The error should no longer occur.

**Comment by acgritt** [comment]
That release worked perfectly.
