### ISSUE TITLE
Issue generating coverage with AttributeFilter

### ISSUE THREAD

**Issue by manemarron** [danielpalme/ReportGenerator#146]
I have many test projects in my solution so I am using AltCover as my coverage calculator for each project and ReportGenerator (https://github.com/danielpalme/ReportGenerator) as my coverage aggregator. When I run 

```bash
$  dotnet test /p:AltCover=true /p:AltCoverAttributeFilter=ExcludeFromCodeCoverage
$ dotnet reportgenerator "-reports:coverage.xml" "-targetdir:coverage" "-reporttypes:Html;Xml"
```

on any project, the coverage file is generated but ReportGenerator can't parse it (it throws an Object Reference exception). When I remove the attribute filter, everything works fine.

I am using the latest version of altcover and reportgenerator-cli

I have reported the issue both here and in https://github.com/SteveGilham/altcover/issues/28

**Comment by danielpalme** [comment]
Seems to be related to #145. Probably a missing attribute in the generated XML.
Can you share a sample XML?

**Comment by danielpalme** [comment]
I'm closing this since it will be fixed in altcover.
