### ISSUE TITLE
allow-same-origin

### ISSUE THREAD

**Issue by jadaml** [danielpalme/ReportGenerator#149]
In your Wiki, you are missing `allow-same-origin' after `sandbox` and `allow-scripts` for Jenkins integration options; otherwise the HTML output doesn't load properly:

~~~
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-scripts allow-same-origin; default-src 'self';")
~~~

**Comment by danielpalme** [comment]
Thanks. I updated the Wiki.
