### ISSUE TITLE
Turn ReportGenerator into a single EXE with no dependent assemblies.

### ISSUE THREAD

**Issue by danielpalme** [danielpalme/ReportGenerator#15]
Reference:  
http://www.digitallycreated.net/Blog/61/combining-multiple-assemblies-into-a-single-exe-for-a-wpf-application

1. Move everything from ReportGenerator into ReportGenerator.Core.dll
    a. Expose a new entry point Main Method.

2. Simplify ReportGenerator.exe to 
   a. Reference ReportGenerator.Core.dll
   b. Extent of source code in ReportGenerator.exe
```
internal static int Main(string[] args)
{
   return ReportGenerator.Core.Main(args);
}
```

This will keep your stuff at status quo, as RerportGenerator.exe still exists for everyone, with the addition of a new ReportGenerator.Core.DLL.

This will allow me to make my own FatReportGenerator.exe that has all the assemblies embedded as resources, thus making deployments my build servers less error prone.  It turns into a single exe.

https://github.com/ghstahl/ReportGenerator

**Comment by danielpalme** [comment]
If ```ReportGenerator.Core.dll``` and ```ReportGenerator.Reporting.dll``` are embedded into ```ReportGenerator.exe```, then it will no longer be possible to add a reference to those projects in a third party solution.
This would make it harder/impossible to create custom report plugins.
Therefore I will not combine everything into a single executable.

I don't think that several DLLs are a big issue. If done right, a build server restores the Nuget package of *ReportGenerator* and calls ```ReportGenerator.exe``` to create the report. It does not matter if there are several files in the package directory.

**Comment by tomkuijsten** [comment]
If this is really something you want, you should consider ILMerge. You will be able to support both scenario's (one exe to publish, and still a seperate dll for plugins).

http://research.microsoft.com/en-us/people/mbarnett/ilmerge.aspx

**Comment by danielpalme** [comment]
I don't want to merge everything into a single EXE. I think 99% can handle several files.
