### ISSUE TITLE
discrepency of coverage percent in report based on multiple opencover files

### ISSUE THREAD

**Issue by zvikab1** [danielpalme/ReportGenerator#150]
Hello
I use ReportGenerator (last release) and love it, still, I have the following problem:
I have two coverage files created by OpenCover :
1.	One created from running unit tests
2.	On created by running system tests
Some classes have 0% coverage in the first file and X coverage in the 2nd file
When I run ReportGenerator on file1 I get 0% coverage for this class in the report. OK.
When I run second file I get X% coverage. OK.
BUT,  when I run ReportGenerator on both of files (i.e. merge) instead of getting X+0=X, I get less than X
When I compare HTML report of file2 with HTML report of merge, I see the following:
1.	The class's #covered lines remained the same
2.	#total lines remains the same
3.	The class' #coverable lines has increased by a small number hence the percentage (division of covered/coverable) was decremented by 0.1-0.7%

This happen consistently on a small number of the classes in my tested binaries.
Any idea what may cause it ? (I really need the precision as I have automation that compares the values from different runs and fails the build if the coverage dropped by even 0.1%)

Thanks
Zvika

**Comment by danielpalme** [comment]
Can you share your coverage file? I don't need your source code.
You can also remove all irrelevant classes from your coverage files. You can also rename your classes/namespaces.
Without a sample it's hard to figure out the problem.

You can send your files by email: danielpalme82@gmail.com.
I will threat them confidentially and delete your email after debugging.

**Comment by danielpalme** [comment]
Thanks for the files. Will have a look within the next days.
