### ISSUE TITLE
Red and green colors are too bright

### ISSUE THREAD

**Issue by reduckted** [danielpalme/ReportGenerator#151]
I find the green color used in the HTML reports to be very bright. 

![image](https://user-images.githubusercontent.com/10321525/43832813-fc4aa9f2-9b4b-11e8-9f21-17576b68cfc1.png)

The red isn't too bad, but I think it could probably be toned down a bit as well.

Would you be open to changing the red and green colors to be less bright? Something like the red and green used in the new badges would be great (or maybe somewhere in between).

![badge_branchcoverage](https://user-images.githubusercontent.com/10321525/43832835-0f38672a-9b4c-11e8-8bc7-6b23e6a9889e.png)

I'm happy to submit a PR for this if you're OK for this change to go ahead. 😄

**Comment by danielpalme** [comment]
I changed the colors in the HTML and Latex reports.
Will be part of the next release.

**Comment by reduckted** [comment]
That's awesome, thanks!
