### ISSUE TITLE
Provide documentation on how to actually run this outside of the Package Manager console

### ISSUE THREAD

**Issue by FrankyBoy** [danielpalme/ReportGenerator#152]
Hi!

I can run this tool from inside the package manager console, but how it would work on a CI server is beyond me. I've tried all kinds of variations of the `dotnet msbuild` command as well as trying to execute directly in some way, all with the same result (can't find executable).

Please provide some insights into how this should actually be accomplished (because obviously running on a CI server is the main point of a tool like this in my eyes).

I.e.

1. Install nuget package
2. Add build step ???
3. View output here: [...]

Cheers!

**Comment by danielpalme** [comment]
First see this [wiki page ](https://github.com/danielpalme/ReportGenerator/wiki/Integration) which provides some information about integration into VSTS, Jenkins and TeamCity.

The configuration depends a lot on your setup. E.g.
- Which _test framework_ are you using (NUnit, XUnit, MSTest, ...)
- Which _coverage tool_ do you use (OpenCover, altcover, dotcover, ...)
- Which _Nuget package_ of ReportGenerator do you use? ([ReportGenerator](https://www.nuget.org/packages/ReportGenerator/), [Global tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/), [DotnetCliTool](https://www.nuget.org/packages/dotnet-reportgenerator-cli/))

Let's assume you are using _OpenCover_ and the results of _OpenCover_ are available in `OpenCover.xml`.
Let's further assume you are using the regular [ReportGenerator](https://www.nuget.org/packages/ReportGenerator/) package by using the following package reference in your `*.csproj`:
```
<PackageReference Include="ReportGenerator">
    <Version>4.0.0-rc3</Version>
</PackageReference>
```

Now you should be able to generate the report in [HTML format](https://github.com/danielpalme/ReportGenerator/wiki/Output-formats) with the following command in your build process. The report files will be generated in the directory `coveragereport`:
```
%userprofile%\.nuget\packages\reportgenerator\4.0.0-rc3\tools\net47\ReportGenerator.exe -reporttypes:HTMLInline "-reports:OpenCover.xml" "-targetdir:coveragereport"
```

Does this help?

**Comment by FrankyBoy** [comment]
Hey, didn't know there was a DotnetCliTool ... I think that sould work perfectly, need to try it out (can we have those mentioned in the Readme somewhere?).

For now I actually modified my build target to store nuget packages in a sane places (i.e. `dotnet build [...] --packages .\packages` and then run from there. But having a properly integrated CLI tool should be waaay nicer.

**Comment by FrankyBoy** [comment]
Tried the dotnet-reportgenerator-cli now, sadly gives me an error (No executable found matching command "dotnet-reportgenerator"). Installed ReportGenerator 4.0.0-rc3 as well in case it's an implicit dependency but no success. 

Back to my ugly solution for now I guess.

**Comment by FrankyBoy** [comment]
PS: maybe I'm "holding it wrong" (in fact that is very likely considering I didn't work with tools that have a setup like this before :D )

**Comment by danielpalme** [comment]
> Hey, didn't know there was a DotnetCliTool ... I think that sould work perfectly, need to try it out (can we have those mentioned in the Readme somewhere?).

It is already mentioned in the [v4 README](https://github.com/danielpalme/ReportGenerator/tree/v4#available-packages).

> Tried the dotnet-reportgenerator-cli now, sadly gives me an error (No executable found matching command "dotnet-reportgenerator"). Installed ReportGenerator 4.0.0-rc3 as well in case it's an implicit dependency but no success.

See issue https://github.com/danielpalme/ReportGenerator/issues/148. Probably your working directory is not correct.
Your working directory has to be the directory which contains the `*.csproj` or you have to specify the directory.

**Comment by FrankyBoy** [comment]
> Probably your working directory is not correct.

Seems highly likely. Will try setting that tomorrow.  Cheers from your southern neighbours.

**Comment by danielpalme** [comment]
Did you resolve the problem?

**Comment by FrankyBoy** [comment]
Hi! You were right, the path is the problem. This works fine:

    cd .\MyTests\ 
    dotnet reportgenerator [...]

Would be really cool if something like `dotnet reportGenerator .\MyTests\MyTests.csproj` (similar to how `dotnet test .\MyTests\MyTests.csproj` is executed relative to that csproj location :)
