### ISSUE TITLE
consumed cobertura file does not match produced cobertura file

### ISSUE THREAD

**Issue by paspratt22** [danielpalme/ReportGenerator#153]
I am feeding in a Coverlet-generated cobertura.xml file into ReportGenerator and then producing both an output cobertura.xml file along with an HTMLInline report.  The output Cobertura file appears to have used an incorrect value for the 'lines-valid' attribute.

Here is the input cobertura snippet:

`<coverage line-rate="0.781" branch-rate="0.595" version="1.9" timestamp="1534776363" lines-covered="676" lines-valid="866" branches-covered="238" branches-valid="400">`

And here is the output cobertura snippet:

`<coverage line-rate="78" branch-rate="0" lines-covered="676" lines-valid="2316" branches-covered="0" branches-valid="0" complexity="NaN" version="0" timestamp="1534758364">`

And in the HTML coverage report:

![capture](https://user-images.githubusercontent.com/42552813/44361065-614dea00-a482-11e8-9f0a-1b4caa3ff7da.PNG)

Notice that the output cobertura file's lines-valid is equal to the report's Total Lines.  The result is that, in TFS, line-rate becomes very low when using the output cobertura file since TFS uses lines-covered / lines-valid to calculate coverage % (as opposed to just using line-rate in the cobertura file).

Note that I am using the output Cobertura file, since I am leaning on ReportGenerator to do the merging of multiple input Cobertura files.

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
I will fix this next week.

**Comment by paspratt22** [comment]
Daniel, as far as I can tell, the fix is in CoberturaReportBuilder.cs, line 139:

`            rootElement.Add(new XAttribute("**lines-valid**", summaryResult.CoverableLines.ToString(CultureInfo.InvariantCulture)));
`

**Comment by paspratt22** [comment]
Fix confirmed.  Thanks!
