### ISSUE TITLE
coverage for inner private class not shown (no filters used)

### ISSUE THREAD

**Issue by zvikab1** [danielpalme/ReportGenerator#154]
Hi 
I have sample code that call one class "Class1" and one inner (nested class) "Nested"
I run the following commands
OpenCover.Console.exe  -target:NestedClassesTest.exe -targetdir:d:\tmp -output:D:\tmp\test1.xml -threshold:1
ReportGenerator.exe -reporttypes:CsvSummary  -reports:D:\tmp\test1.xml -targetdir:d:\tmp 
The resulting csv has coverage data for "Program,", "Class1" but not for "Nested".
The class count is 2 instead of 3
[Program.cs.txt](https://github.com/danielpalme/ReportGenerator/files/2310534/Program.cs.txt)

As can be seen, I'm not using filters at all.
What am I missing?
Thanks
Zvika
[summary.txt](https://github.com/danielpalme/ReportGenerator/files/2310526/summary.txt)

**Comment by danielpalme** [comment]
The coverage results of nested classes are merged into the parent class.
You can visualize that by generating the HTML report.
Nested classes are not listed separately

**Comment by zvikab1** [comment]
Thanks
