### ISSUE TITLE
Suggested pipeline for VSTS

### ISSUE THREAD

**Issue by jhgoodwin** [danielpalme/ReportGenerator#156]
Hi @danielpalme thanks for making these tools.

I had a question about the suggested pipeline for how to use your tools properly in a VSTS build.

I'm using the YAML builds and I came up with the attached yaml definition, but I'm not quite satisfied. There are a few artifacts. First, I'd like to come up with a pattern that allows me to add test projects w/o adding to the list of tasks.

Second, with the pattern I'm using now, I'm noticing that my test projects sometimes show up in the build output. When I tried to remove them using the extended exclude options using a comma, it was not interpreting it correctly, even with quotations, escaping quotes, so on.

Thanks so much for your efforts.

John
[vsts-ci.yml.txt](https://github.com/danielpalme/ReportGenerator/files/2332678/vsts-ci.yml.txt)

**Comment by danielpalme** [comment]
> First, I'd like to come up with a pattern that allows me to add test projects w/o adding to the list of tasks.

If you use `dotnet test` you have to run this on every project (See this issue: https://github.com/Microsoft/vstest/issues/411).
Maybe this helps: https://github.com/aspnet/DotNetTools/issues/247

> Second, with the pattern I'm using now, I'm noticing that my test projects sometimes show up in the build output. When I tried to remove them using the extended exclude options using a comma, it was not interpreting it correctly, even with quotations, escaping quotes, so on.

Filters have to be separated by a semicolon `;` not a comma `,`.
Something like this should work in your case:
`"-assemblyfilters:-MetadataService.Server.Oracle.Tests;-MetadataService.WebApi.Tests"`

Maybe this is helpful for the command line parameters of _ReportGenerator_: https://danielpalme.github.io/ReportGenerator/usage.html

**Comment by danielpalme** [comment]
By the way:
_ReportGenerator_ also supports generating `Coberatura` as output format.
This may be helpful since with [OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter) you can only convert **one** _OpenCover_ file to a _Cobertura_ file.
With _ReportGenerator_ you can convert **several** _OpenCover_ files to a **single** _Cobertura_ file.

So if you want to merge your coverage results in a single Cobertura file this would be worth a try. Just use:
`-reporttypes:HTMLInline;Cobertura`

**Comment by jhgoodwin** [comment]
Hi @danielpalme Thanks for the reply.

I noticed the dotnet test globbing, but unless I was doing something wrong, I noticed it seemed to be only getting the test coverage of a single test assembly, not the entire set. Is there a way around this? Perhaps I was doing it wrong?

In regards to the Cobertura vs OpenCover, I noticed the report output was superior from the opencover report as it supported branch coverage. Unless there's a better way, I was using the Coverlet project: https://github.com/tonerdo/coverlet

Your idea of using the dual report types is a good idea. How will I know what the cobertura output filename will be?

**Comment by danielpalme** [comment]
> I noticed the dotnet test globbing, but unless I was doing something wrong, I noticed it seemed to be only getting the test coverage of a single test assembly, not the entire set. Is there a way around this? Perhaps I was doing it wrong?

Sorry, I don't know.

>In regards to the Cobertura vs OpenCover, I noticed the report output was superior from the opencover report as it supported branch coverage. Unless there's a better way, I was using the Coverlet project: https://github.com/tonerdo/coverlet

>Your idea of using the dual report types is a good idea. How will I know what the cobertura output filename will be?

Yes the OpenCover output of coverlet is definitively superior than the Cobertura format.
The file name of the merged Cobertura output from ReportGenerator is simply `Cobertura.xml`
