### ISSUE TITLE
MSBuild Task Not Working on V4

### ISSUE THREAD

**Issue by paspratt22** [danielpalme/ReportGenerator#159]
I tried to invoke ReportGenerator (V4, rc4) as an MSBuild task, and got the following error:

     [exec] xxxxxxxxxx(41,17): error MSB4002: There was a failure retrieving the attributes for parameters in the "ReportGenerator" task. Could not load type 'Microsoft.Build.Framework.IBuildEngine5' from assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
     [exec] xxxxxxxxxx(41,17): error MSB4060: The "ReportGenerator" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.

I also tried to revert back to 3.1.2, and it worked.  However, 3.1.2 does not support generation of Cobertura format, which I need.

**Comment by danielpalme** [comment]
Can you supply some details?

- Are you using DotNet Core or the full framework?
- How did you call ReportGenerator?
- Can you create a minimum sample project?

**Comment by paspratt22** [comment]
Thanks for the quick response.

- This is against full framework
- Here is my MSBuild file (edited):

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="GenCodeCoverage" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
...
                <ReportGeneratorExe>$(PackagesDir)ReportGenerator.4.0.0-rc4\tools\net47\ReportGenerator.exe</ReportGeneratorExe>
	</PropertyGroup>

        <UsingTask AssemblyFile="$(ReportGeneratorExe)" TaskName="ReportGenerator" />
	<Target Name="GenCodeCoverage">
                <ItemGroup>
                        <CoverageFiles Include="$(OpenCoverOutputFile)" />
                </ItemGroup>
                <ReportGenerator 
                        ReportFiles="@(CoverageFiles)" 
                        TargetDirectory="$(ReportsDir)" 
                        ReportTypes="HtmlInline;Cobertura" />
        </Target>
</Project>

**Comment by danielpalme** [comment]
I created a sample file which works on my machine.
Maybe you have to adjust some paths on your machine.

I create the reports in two ways:
- Using `ReportGenerator.exe` directly with the  `Exec ` command.
- The `MsBuild`-Task which is integrated into ReportGenerator

This is my MSbuild script
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Coverage">

  <UsingTask TaskName="ReportGenerator" AssemblyFile="$(UserProfile)\.nuget\packages\reportgenerator\4.0.0-rc4\tools\net47\ReportGenerator.exe" />
  
  <PropertyGroup>
    <ReportGeneratorExe>$(UserProfile)\.nuget\packages\reportgenerator\4.0.0-rc4\tools\net47\ReportGenerator.exe</ReportGeneratorExe>
  </PropertyGroup>
  
  <Target Name="Coverage">
    <!-- EXE -->
    <Exec Command="$(ReportGeneratorExe) -reports:opencover.xml -targetdir:reports_exe -reporttypes:HtmlInline;Cobertura" />
    
    <!-- MSBuild -->
    <Exec Command="$(ReportGeneratorExe) -reports:opencover.xml -targetdir:reports_exe -reporttypes:HtmlInline;Cobertura" />
    <ReportGenerator ReportFiles="opencover.xml" TargetDirectory="reports_msbuild" ReportTypes="HtmlInline;Cobertura" />
  </Target> 
</Project>
```

Here the files: [Sample.zip](https://github.com/danielpalme/ReportGenerator/files/2385782/Sample.zip)

**Comment by paspratt22** [comment]
I was able to get it working through the EXE.  Thank you!

**Comment by danielpalme** [comment]
Did you try the MsBuild task too?
It only works if you habe the `<UsingTask ... />` statement in place.

**Comment by paspratt22** [comment]
Yes, but with the same issue as above.
