### ISSUE TITLE
Formatting breaks when printing HTML report

### ISSUE THREAD

**Issue by DAndreChampagne** [danielpalme/ReportGenerator#16]
Reports look perfect when displayed on screen, however when I print the HTML version of an OpenCover report (archaic, I know) the formatting completely breaks and the print becomes 100+ pages, when it should be 4 or 5.

Report as I'm looking at it:
![htmlonscreen](https://cloud.githubusercontent.com/assets/2564427/7944975/f44b2d9e-093b-11e5-8137-9a817f0ac95c.png)

After it is printed:
![asprinted](https://cloud.githubusercontent.com/assets/2564427/7944979/f7e185c0-093b-11e5-81fe-873563f1c3d2.png)

**Comment by danielpalme** [comment]
I will look into this, but it will take some time.

**Comment by DAndreChampagne** [comment]
This is a "nice to have" kind of feature (mostly because my company wants print outs of everything). I have a work around for now, so there is no rush from my perspective!

**Comment by danielpalme** [comment]
Could you please try the latest release 2.1.5.0.
It should work much better now. I have tested with Chrome and IE 11.

**Comment by DAndreChampagne** [comment]
I just reran it with Firefox 38.0.5 and it looks great! Thank you so much
for addressing this so quickly!

**Comment by DAndreChampagne** [comment]
One thing I just noticed is that the indicator bars for coverage do not
print. The text percentage does, and that's all I need. But for a future
enhancement maybe!

**Comment by danielpalme** [comment]
I think this depends on you browser/print settings. If you enable "Print background colors/images" (or simiilar) it should work.

**Comment by DAndreChampagne** [comment]
That did the trick! Thank you again!
