### ISSUE TITLE
Support JaCoCo format

### ISSUE THREAD

**Issue by Thilas** [danielpalme/ReportGenerator#160]
It would be great if ReportGenerator could support JaCoCo code coverage format as an input.

Thanks for this great tool!

**Comment by danielpalme** [comment]
Good idea.
Can you help?
It would be great if you could create a JaCoCo coverage report for this project:
https://github.com/danielpalme/ReportGenerator/tree/master/src/Testprojects/Java/Project/test

**Comment by Thilas** [comment]
Sorry but I can't do that (I mean create a JaCoCo coverage report) since I really don't know a thing about Java.

The reason why I asked is because I'm using [Pester](https://github.com/pester/Pester/wiki/Code-Coverage) for my PowerShell testing and it generates a JaCoCo output. That's the only thing I can easily provide.

Let me know if I can help with anything else.

**Comment by danielpalme** [comment]
A sample report generated by Pester would be great.

**Comment by Thilas** [comment]
For now, Pester generates very basic report (onyl high level stats for the whole scope) but a PR has started to enhance this part: https://github.com/pester/Pester/pull/920. So I don't think it will be of some help here.

Instead, you can get a more usefull sample from JaCoCo website: https://www.jacoco.org/jacoco/ => `Download`. In the archive, have a look at `coverage\jacoco.xml`.

**Comment by danielpalme** [comment]
Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc7
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc7
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc7

You have to use the command line parameter `-sourcedirs:MY_DIRECTORY` to tell ReportGenerator about the location of your source code.

**Comment by Thilas** [comment]
Sure, will do right away!

**Comment by Thilas** [comment]
Still on it. It's taking longer than expected because I also have to work on the JaCoCo report generation from Pester so that it is valid (and complete). I'll send a PR for you as soon as I've been able to finish my tests.

**Comment by Thilas** [comment]
As promised, I sent you a PR with some changes. Let me know.

**Comment by danielpalme** [comment]
I'm closing this issue as JaCoCo support is now available. The details can be discussed in your PR.
