### ISSUE TITLE
HtmlInline report does not show coverage history in VSTS

### ISSUE THREAD

**Issue by Thilas** [danielpalme/ReportGenerator#164]
Because the chart is rendered browser-side thanks to chartist.js and because VSTS prevents js from running when displaying code coverage report, the coverage history section is empty.

Do you have any workaround or fix for that?

**Comment by danielpalme** [comment]
Charts only work with JS enabled. No way around that.

**Comment by Thilas** [comment]
I saw that there is a [node-chartist](https://www.npmjs.com/package/node-chartist) npm package that could allow to render charts server-side. And this could you used thanks to [edge.js](https://github.com/tjanczuk/edge) for instance.

Any thoughts about this (except than VSTS should allow js 😛)?

**Comment by danielpalme** [comment]
The HTML reports now contain history chart as inline SVG to show chart when JS is disabled.
No need to use edge.js to create the SVG.

**Comment by danielpalme** [comment]
Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc9
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc9
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc9

The static SVG is rendered in a `<noscript>` tag. I have not tested if this tag gets displayed in VSTS.
Would be great if you could test this.

**Comment by Thilas** [comment]
I just started to test this. I'll let you know tomorrow or in the coming days. Thanks for your work on this!

**Comment by Thilas** [comment]
Sorry but it seems that VSTS removes the `<noscript>` tag. Why did you put the inlined svg in such tag along side with the former `mainHistoryChart` div? Why not putting only the inlined svg?

**Comment by danielpalme** [comment]
I removed the <noscript> tag and found an alternative solution, this should work on VSTS

Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc10
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc10
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc10

**Comment by Thilas** [comment]
This is really disappointing from Microsoft but the svg gets truncated:
![image](https://user-images.githubusercontent.com/3749820/46903842-7754b580-cedb-11e8-8504-eb3154b4e7bb.png)
Unfortunately, I don't see what you can do about it...

**Comment by Thilas** [comment]
FYI, I created https://github.com/Microsoft/vsts-tasks/issues/8452 in parallel to have Microsoft improve these limitations.

**Comment by Thilas** [comment]
No (more) surprises, it works now. Thank you very much for this @danielpalme.

**Comment by danielpalme** [comment]
I had to make this new feature optional (see #170).
You can enable the feature in the `appsettings.json` file of _ReportGenerator_ or with the command line parameter `settings:renderPngFallBackImagesForHistoryCharts=true`
