### ISSUE TITLE
Limit report files path lengths

### ISSUE THREAD

**Issue by tedvanderveen** [danielpalme/ReportGenerator#165]
Currently we run in an issue when using the VSTS Publish code coverage results task to publish the HTMLInline report. The HTML files generated have paths longer than 259 chars and this causes the task to fail.
I know this is not a situation caused by ReportGenerator, but is there a way to reduce file path lengths? Like for example use short hashes instead of full assembly/class/method names and nestings?
See also https://github.com/Microsoft/vsts-tasks/issues/8368

**Comment by danielpalme** [comment]
I limited the length of the file names to ~100 characters.
Next (pre-)release will contain the fix. I will publish the new package within the next days.

**Comment by tedvanderveen** [comment]
Great work @danielpalme! Thanks

**Comment by danielpalme** [comment]
Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc7
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc7
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc7

**Comment by tedvanderveen** [comment]
Hi @danielpalme I now get this
```
Loading report 'D:\weg\coverage\cobertura-results.xml' 1/1
 Preprocessing report
 Initiating parser for Cobertura
  Current Assembly: Jobbird.Domain.Core
  Current Assembly: Jobbird.Functions
  Current Assembly: Jobbird.Infrastructure
 Error during reading report 'D:\weg\coverage\cobertura-results.xml' (Size: 1.6MB): Multiple errors
An item with the same key has already been added. Key: 9
An item with the same key has already been added. Key: 11
An item with the same key has already been added. Key: 9
An item with the same key has already been added. Key: 9

Coverage report parsing took 0.3 seconds
Initializing report builders for report types: HTMLInline, HTMLChart
Analyzing 0 classes
 Creating summary
Report generation took 1.0 seconds
```
I have incuded the source cobertura-results.xml file
[cobertura-results.zip](https://github.com/danielpalme/ReportGenerator/files/2453681/cobertura-results.zip)

**Comment by danielpalme** [comment]
That another issue and you are right, the duplicate keys are caused by merging several files.

Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc8
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc8
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc8

**Comment by tedvanderveen** [comment]
@danielpalme I tried rc8 release right away, but still same issue with duplicate keys. Did you target that problem in rc8? Or is there no support (yet) for merged results?

**Comment by danielpalme** [comment]
I have tested with your XML file. Did you use a different file?

**Comment by tedvanderveen** [comment]
@danielpalme Locally I still had the issue, maybe rc7 is still deployed somehow. But in VSTS hosted (clean) ageant it all works just fine now! Many thanks for your work!!
