### ISSUE TITLE
Merging cobertura files does not fill <source> element

### ISSUE THREAD

**Issue by PeterRockstars** [danielpalme/ReportGenerator#167]
I am feeding in a numbr of Coverlet-generated cobertura.xml files into ReportGenerator and then producing an output cobertura.xml file. The output Cobertura file appears to have used an incorrect value for the 'sources' attribute.

Here is the input cobertura snippet from one of the :

```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.017" branch-rate="0.013" version="1.9" timestamp="1539077184" lines-covered="135" lines-valid="8065" branches-covered="62" branches-valid="4887">
  <sources>
    <source>C:\<path to solution dir>\src\</source>
  </sources>
  <packages>
...
```

And here is the output cobertura snippet:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="0.243532722156667" branch-rate="0.123097483109362" lines-covered="5366" lines-valid="22034" branches-covered="1658" branches-valid="13469" complexity="NaN" version="0" timestamp="1539084391">
  <sources />
  <packages>
...
```

I'm trying to publish the merged cobertura report to VSTS and it's giving me a warning, saying 
`##[warning]No coverage data found. Check the build errors/warnings for more details.`

When I publish a single one of the generated Cobertura files, this warning is not given. So far the most notable difference between the files is the missing information in the <sources> element.

**Comment by danielpalme** [comment]
Will have a look at it. But won't be easy to solve in all possible situations.

**Comment by PeterRockstars** [comment]
I understand, if you could get it working for Cobertura->Cobertura that would be great!

**Comment by danielpalme** [comment]
I have fixed the problem. All source directories from all `Cobertura` input files will also be available in the output.

**Comment by PeterRockstars** [comment]
Fantastic! Thanks for the amazingly quick reply

**Comment by PeterRockstars** [comment]
Is there a way I can subscribe to be notified when the new version is available?

**Comment by danielpalme** [comment]
I'll let you know. I will post post a message in this thread.

**Comment by PeterRockstars** [comment]
Thanks a million 👍

**Comment by danielpalme** [comment]
Could you please try this new release and let me know if it works for you:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc9
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.0-rc9
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.0-rc9
