### ISSUE TITLE
OpenCover and ReportGenerator filters don't seem to work.

### ISSUE THREAD

**Issue by dparvin** [danielpalme/ReportGenerator#17]
I am not sure if I am doing this wrong, but when I have open cover run my tests and then have report generator create the report, the report does not seem to filter out any assembly that has a *test* filer layout.  It worked fine when I was using VS code coverage to create the coverage information and then report generator would filter the assemblies.  I switched to open cover because some of my tests were causing VS Code Coverage to throw out of memory errors.  Open cover works great (a little slower) but the tests then are not filtered out of the data by report generator.  I am planning to look into filtering them in open cover, but I expected both sources of data to filter the data the same way and was surprised when they didn't.

**Comment by danielpalme** [comment]
ReportGenerator shows all assemblies/classes it can find in the OpenCover report.
You can use the ```-filter``` option to remove those assemblies from the report.
E.g.
```
-filters:-*Test
```

OpenCover also has a filtering mechanism.

**Comment by dparvin** [comment]
Ok.  I was using the  filters on ReportGenerator and it was not filtering, and now it is.  No idea why it started working, but I am going to close this issue.
