### ISSUE TITLE
Report generation is ~25x times slower in v4.0 than v.3.1

### ISSUE THREAD

**Issue by riccardomerlin** [danielpalme/ReportGenerator#170]
I updated today to version 4.0 and the time taken to analyze the coverage result produced by OpenCover takes now ~160s.
I was using version 3.1 and with the same configuration the report generation was down to ~6s.

I ran them several times in different machines with the same results.

Here are the two logs for each version running on a machine with 6 cores and 32GB of RAM with the following configuration:
```
reportgeneator -reports:./coverage/reports/coverageResult.xml -targetdir:./coverage/reports/ -historydir:./coverage/reports/history -verbosity:info
```

### v3.1 Report generation took 6.2 seconds
```
Test Run Summary
  Overall result: Failed
  Test Count: 3672, Passed: 3671, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 0, Invalid: 0
  Start time: 2018-10-25 14:37:42Z
    End time: 2018-10-25 14:38:19Z
    Duration: 37.836 seconds

Results (nunit3) saved as TestResult.xml
Committing...
Visited Classes 1057 of 3365 (31.41)
Visited Methods 2953 of 12225 (24.16)
Visited Points 15012 of 72967 (20.57)
Visited Branches 5332 of 26850 (19.86)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 1536 of 5168 (29.72)
Alternative Visited Methods 4373 of 19856 (22.02)

Loading report 'F:\Development\coverage\coverageResult.xml'
Reading historic reports
Initializing report builders for report types: Html
Analyzing 1649 classes
Creating history report
Report generation took 6.2 seconds
```
### v4.0 Report generation took 160.3 seconds
```
Test Run Summary
  Overall result: Passed
  Test Count: 3672, Passed: 3672, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-10-25 14:42:47Z
    End time: 2018-10-25 14:43:23Z
    Duration: 36.342 seconds

Results (nunit3) saved as TestResult.xml
Committing...

Visited Classes 1057 of 4702 (22.48)
Visited Methods 2953 of 18067 (16.34)
Visited Points 15012 of 111551 (13.46)
Visited Branches 5332 of 40576 (13.14)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 1536 of 7555 (20.33)
Alternative Visited Methods 4373 of 29824 (14.66)

Loading report 'F:\Development\coverage\coverageResult.xml' 1/1
Reading historic reports
Initializing report builders for report types: Html
Analyzing 1649 classes
Creating history report
Report generation took 160.3 seconds
```

**Comment by danielpalme** [comment]
That's strange. In generell the performance in 4.0 should be better. Here are my performance results:

![46227197-bd980980-c35e-11e8-96db-a27c63c85531](https://user-images.githubusercontent.com/859606/47520814-894a3700-d891-11e8-8201-a9addb3f2bea.png)

Can you share your `coverageResult.xml` so I can debug what's going wrong?
You can send it by email (danielpalme82@gmail.com).

**Comment by danielpalme** [comment]
I found the reason:
I recently added PNG history charts which get displayed when JavaScript is disabled (see #164).

The rendering takes a lot of time. I think I will make this optional.

**Comment by danielpalme** [comment]
Version 4.0.1 should be much faster:
https://www.nuget.org/packages/ReportGenerator/4.0.1
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.1
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.1

**Comment by riccardomerlin** [comment]
Thanks for that! I upgraded to v4.0.2 and I confirm that the problem is fixed
