### ISSUE TITLE
Plans to support lcov?

### ISSUE THREAD

**Issue by MisinformedDNA** [danielpalme/ReportGenerator#171]
Do you have plans to support lcov? I'm investigating the idea of running and reporting code coverage on JavaScript. I'm new to this area, so let me know if there is something else that you would recommend.

**Comment by danielpalme** [comment]
I have no plans to support _lcov_.
But you you can use [istanbul](https://github.com/istanbuljs/nyc).

_istanbul_ is able to generate a cobertura report which can be processed by _ReportGenerator_:
https://istanbul.js.org/docs/advanced/alternative-reporters/#cobertura

**Comment by MisinformedDNA** [comment]
Awesome! Thanks.
