### ISSUE TITLE
Cannot run tool on Azure Pipelines linux VM

### ISSUE THREAD

**Issue by ChrisSaintyFG** [danielpalme/ReportGenerator#178]
Hi,

I've been fighting for the last 4 hours trying to generate a report for my test coverage results. But I'm hitting the same error over and over and I just can't get past it. 

```
2018-11-15T13:31:29.8244858Z You can invoke the tool using the following command: reportgenerator
2018-11-15T13:31:29.8246465Z Tool 'dotnet-reportgenerator-globaltool' (version '4.0.4') was successfully installed.
2018-11-15T13:31:29.8363926Z The application to execute does not exist: '/home/vsts/work/1/s/..//home/vsts/work/1/s/.store/dotnet-reportgenerator-globaltool/4.0.4/dotnet-reportgenerator-globaltool/4.0.4/tools/netcoreapp2.1/any/ReportGenerator.dll'.
2018-11-15T13:31:29.8420062Z ##[error]Bash exited with code '154'.
```

My YAML task looks like this

```
- script: |
    dotnet test --configuration $(buildConfiguration) --no-build --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/codecoverage/ $(Build.SourcesDirectory)/test/Web.IntegrationTests
    dotnet tool install --tool-path . dotnet-reportgenerator-globaltool
    ./reportgenerator "-reports:$(Build.SourcesDirectory)/codecoverage/coverage.cobertura.xml" "-targetdir:codecoverage" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Running Tests...'
```

Am I trying to do something that's not supported here? Or have I made a mistake somewhere?

**Comment by danielpalme** [comment]
Did this work for you?

**Comment by danielpalme** [comment]
Yes. I'm having the same problem. But not in every _Azure Devops Pipeline_, only some of them are affected.

See also:
https://stackoverflow.com/questions/53306592/code-coverage-screen-hangs-in-azure-pipeline-build

**Comment by danielpalme** [comment]
I opened an issue here: https://developercommunity.visualstudio.com/content/problem/385331/code-coverage-results-not-rendered-in-build-result.html

**Comment by ChrisSaintyFG** [comment]
Yes, that is exactly is issue and error I'm getting. Thanks for the links, I'll keep an eye on them for a resolution. Thanks for the help.
