### ISSUE TITLE
Nested types are getting ignored

### ISSUE THREAD

**Issue by stephentoub** [danielpalme/ReportGenerator#18]
ReportGenerator appears to be ignoring nested types:
https://github.com/danielpalme/ReportGenerator/blob/master/ReportGenerator/Parser/OpenCoverParser.cs#L191

We use ReportGenerator on https://github.com/dotnet/corefx, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/ , and the reports are getting skewed due to no nested types showing up.  You can see this with things like Enumerators nested in collection types, the interop code we use (the majority of which is in nested types), etc.

Can this be fixed?

**Comment by danielpalme** [comment]
Hi Stephen,

nested types are not ignored.
ReportGenerator processes coverage reports in the following order:
1. Collect classes of assembly (without nested classes), see [line 191](https://github.com/danielpalme/ReportGenerator/blob/master/ReportGenerator/Parser/OpenCoverParser.cs#L191)
2. Then every class with all nested types is processed, see [line 274](https://github.com/danielpalme/ReportGenerator/blob/master/ReportGenerator/Parser/OpenCoverParser.cs#L191)

That means that the summary page only shows the main classes. But if you take a look at a class report, also the nested classes are included.
E.g. have a look at [```ConcurrentBag```](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/System.Collections.Concurrent_ConcurrentBag_1.htm). Only the main class shows up in [index.htm](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/), but nested types like ```Node``` or ```ThreadLocalList``` show coverage information as well. 
See lines 837-1001 in [ConcurrentBag_1.htm](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/System.Collections.Concurrent_ConcurrentBag_1.htm)

**Comment by stephentoub** [comment]
Thanks for following up, Daniel! I should have been clear that there are different issues for different nested types. I can understand that it's a design choice that ones like you mentioned don't show up in the main list of types. But, for example, this code https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/BCrypt/Interop.BCryptGenRandom.cs is in System.Security.Cryptography.RandomNumberGenerator, and it's type shows up in the OpenCover output XML file, but I can't find Interop or BCrypt anywhere in the report for that library. Am I just missing it?

**Comment by danielpalme** [comment]
Can you please provide me the corresponding OpenCover XML?
Perhaps something is wrong with partial nested classes.

I have to debug this with the report.

**Comment by stephentoub** [comment]
Thanks:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/artifact/bin/tests/coverage/System.Security.Cryptography.RandomNumberGenerator.Tests.coverage.xml

**Comment by danielpalme** [comment]
The problem is, that the outer class ```Interop``` does not contain any methods, constructors etc.
It only contains the nested class ```BCrypt ```.

When *ReportGenerator* collects the name of all classes (see my [comment](https://github.com/danielpalme/ReportGenerator/issues/18#issuecomment-109893968) above), the class ```Interop``` is not taken into account, because the *OpenCover* report does not contain any information about this class.
Therefore the nested class ```BCrypt ``` is not considered too.

I think I can change this in *ReportGenerator* wihin the next 2-3 days.

**Comment by stephentoub** [comment]
Thanks, Daniel.

**Comment by danielpalme** [comment]
Could you please test again with version 2.1.6.0?
It should work as expected.

I created a sample nested class myself. OpenCover tracked the wrapper class, although it did not have any members. Strange that this does not happen for your ```Interop``` class.

**Comment by stephentoub** [comment]
Thanks, @danielpalme!  Seems to be fixed.
