### ISSUE TITLE
Support SourceLink source files (remote)

### ISSUE THREAD

**Issue by ViktorHofer** [danielpalme/ReportGenerator#180]
If using SourceLink, source file paths aren't located on the disk but on a remote endpoint. It would be sweet if ReportGenerator could support fetching files stored remotely.

cc @tonerdo @danmosemsft @jkotas

**Comment by danielpalme** [comment]
That makes sense and I'm willing to add support to it.
We only have to make sure how the path is formatted in the various output formats (e.g. Cobertura or OpenCover). Currently the path is just a file on the local disk.

**Comment by ViktorHofer** [comment]
The path in the output formats, i.e. OpenCover will look like this one: `https://raw.githubusercontent.com/dotnet/coreclr/5feb0389f1e1ba715fba5560c979ac6362b1bcf8/...`. It should be a normal web link. I'm open to contribute the necessary changes. Currently I'm determining with @tonerdo if changes in Coverlet are also necessary (I believe so).

**Comment by danielpalme** [comment]
Will take care of that (probably next week)

**Comment by danielpalme** [comment]
I'll let you know.

**Comment by danielpalme** [comment]
I added support for remote files in this (pre-)release:
https://www.nuget.org/packages/ReportGenerator/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.5-rc1

Let me know if this works for you.

**Comment by danielpalme** [comment]
Created global instance of _HttpClient_ in [4.0.5-rc2](https://www.nuget.org/packages/ReportGenerator/4.0.5-rc2)

**Comment by ViktorHofer** [comment]
Changes look good to me. Thanks again!
