### ISSUE TITLE
Text extending a certain line length gets cut off in output report

### ISSUE THREAD

**Issue by danielhuber3008** [danielpalme/ReportGenerator#182]
Hi!

When creating a coverage report, the text / source code of lines extending a certain length is simply cut off in the resulting report. 
The following image illustrates this issue (see line 14):
![linecutoff](https://user-images.githubusercontent.com/22657708/49570263-7a49b080-f936-11e8-8b34-84252cf457b3.png)

Version: ReportGenerator 4.0.4
Output Format: HTML (default)
The input was created with OpenCover.Console 4.6.519. 

Is there a possibility to support the visualization of longer lines? 
Thanks for your help!

**Comment by danielpalme** [comment]
That's currently not supported.
