### ISSUE TITLE
ReportGenerator should print the path to the report

### ISSUE THREAD

**Issue by ViktorHofer** [danielpalme/ReportGenerator#183]
If the report is successfully created, the path to the report should be printed. Currently in corefx we use verbosity level `Info` and missing that information. Talking about the console/global tool.

**Comment by danielpalme** [comment]
I added logging for all files that are generated in this (pre-)release:
https://www.nuget.org/packages/ReportGenerator/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.5-rc1

Please use verbosity level `Debug` to see those new log messages.

**Comment by ViktorHofer** [comment]
That's a ton of output that we don't want in our CI / in the console. Can we raise the log level of the index.htm file as it is the entry point of the whole report and therefore the most important file?

**Comment by ViktorHofer** [comment]
My specific ask is to log the index.htm file in at least Info and of course all more verbose logging levels.

**Comment by danielpalme** [comment]
I try this (pre-)release:
https://www.nuget.org/packages/ReportGenerator/4.0.5-rc2
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.5-rc2
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.5-rc2

Now with `-Verbosity:Info` only the main file is logged.
If you use `-Verbosity:Verbose` all paths are logged.

**Comment by ViktorHofer** [comment]
Awesome, thansk Daniel!!

**Comment by ViktorHofer** [comment]
Just tried. Works as expected. Closing.
