### ISSUE TITLE
targetdir with trailing slash fails if directory does not exist

### ISSUE THREAD

**Issue by ViktorHofer** [danielpalme/ReportGenerator#184]
Passing in a targetdir path with a trailing slash fails if the directory doesn't exist.

```
C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64>C:\git\corefx\artifacts\tools\reportgenerator "-reports:coverage.xml" "-targetdir:C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report\" "-reporttypes:Html" "-verbosity:Info"
The target directory 'C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report" -reporttypes:Html -verbosity:Info' could not be created: The filename, directory name, or volume label syntax is incorrect : 'C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report" -reporttypes:Html -verbosity:Info'

C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64>C:\git\corefx\artifacts\tools\reportgenerator "-reports:coverage.xml" "-targetdir:C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report" "-reporttypes:Html" "-verbosity:Info"
```

**Comment by danielpalme** [comment]
I tried to reproduce on my machine. But it's working even with a trailing slash.
I tried the latest version [4.0.4](https://www.nuget.org/packages/ReportGenerator/) on Windows 10.

Which version of _ReportGenerator_ are you using?
What operating system do you use?

**Comment by danielpalme** [comment]
I now trimming trailing slashes in this (pre-)release:
https://www.nuget.org/packages/ReportGenerator/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.5-rc1
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.0.5-rc1

Let me know if this works for you.

**Comment by ViktorHofer** [comment]
Hey Daniel, thanks for looking into this. I use 4.0.4, the global tool one. I'm passing an absolute path in, maybe that's important to know. Unfortunately that change doesn't fix the issue. Let me post the command again:

```
C:\git\corefx\artifacts\tools\reportgenerator "-reports:coverage.xml" "-targetdir:C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report\" "-reporttypes:Html" "-verbosity:Debug"
```

and the error:
```
The target directory 'C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report" -reporttypes:Html -verbosity:Debug' could not be created: The filename, directory name, or volume label syntax is incorrect : 'C:\git\corefx\artifacts\bin\tests\System.Runtime.Extensions.Tests\netcoreapp-Windows_NT-Debug-x64\report" -reporttypes:Html -verbosity:Debug'
```

It seems that the targetdir is parsed wrong when it ends with a trailing slash. Note that in the output here the trailing slash is not shown (probably because of your trimming).

**Comment by ViktorHofer** [comment]
Ok that's not part of ReportGenerator but just the way command line arguments are passed. If the path ends with a backslash and the whole argument has quotes around it the backslash is considered as an escape character `\"`.

**Comment by danielpalme** [comment]
Correct. You have to remove the trailing slash in the command line parameters.
