### ISSUE TITLE
History graph loading is very slow

### ISSUE THREAD

**Issue by riccardomerlin** [danielpalme/ReportGenerator#185]
I noticed that the more history data are collected, the slower is the history graph to load in the Summary page. My history folder contains ~150 xml entries at the moment.

I attached Chrome profiler results.

[Profile-20181130T170728.zip](https://github.com/danielpalme/ReportGenerator/files/2663504/Profile-20181130T170728.zip)

**Comment by riccardomerlin** [comment]
Also other actions in the Coverage area in the Summary page are taking a long time to execute with no feedback to the user that something is happening (e.g. expand/collapse, filtering, ordering)

**Comment by danielpalme** [comment]
Perhaps related to #116
Can you share your coverage files and the history files?
I don't need the source code.

danielpalme82@gmail.com

**Comment by danielpalme** [comment]
Thanks for the files. Will have look within the next 2-3 weeks.

**Comment by danielpalme** [comment]
The slow history rendering is not related to the number of history files.
The history chart gets rendered after the table below is fully created (which takes a long time).

I'm closing this issue because the root problem is already tracked in #116 
I guess I finally have to rewrite that code.
