### ISSUE TITLE
Summary coverage does not reflect individual assembly coverage

### ISSUE THREAD

**Issue by riccardomerlin** [danielpalme/ReportGenerator#186]
Looking at each individual assembly coverage the total coverage should be higher:
Line Coverage: `45.84%` instead of 29.1%
Branch Coverage: `36.07%` instead of 23.4%

How is that calculated?

The coverage of a single assembly compared to each individual methods/classes seems correct.

Coverage summary of each assembly
![detail-coverage](https://user-images.githubusercontent.com/13499635/49739674-62519400-fc8a-11e8-82cd-ec45b118c937.jpg)

Coverage summary
![summary-coverage](https://user-images.githubusercontent.com/13499635/49739672-6087d080-fc8a-11e8-9fd9-e8266a98169f.jpg)

**Comment by danielpalme** [comment]
Looks fine for me. E.g. line coverage:
```
Line coverage = Covered Lines / Coverable lines
29.1% = 14613 / 50202
```

How did you calculate 45.84%?

**Comment by riccardomerlin** [comment]
Apologies, your calculation is right, I picked wrong numbers.
