### ISSUE TITLE
Question: How to enable the fully featured report

### ISSUE THREAD

**Issue by ViktorHofer** [danielpalme/ReportGenerator#187]
How do I enable the fully featured report that can be seen here https://github.com/danielpalme/ReportGenerator#screenshots instead of the one that we currently produce in corefx in a full build by merging all generated opencover reports together: https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/. 

When I produce a report with just one report file it has all these features but the full one in corefx does not. What is deciding which features are available in the report?

**Comment by danielpalme** [comment]
Jenkins blocks JavaScript content by default.
To enable the advanced features you have to turn it on:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#jenkins

**Comment by ViktorHofer** [comment]
Thanks a lot!
