### ISSUE TITLE
Add a possibility to find classes faster, where coverage dropped

### ISSUE THREAD

**Issue by morli94** [danielpalme/ReportGenerator#188]
Hi!
With this feature https://github.com/danielpalme/ReportGenerator/issues/141 you added a way to compare the current coverage result with an older one which is pretty nice.

We want to use this to figure out where the coverage has decreased.
Our problem now: We have a lot of coverage data (many namespaces, classes, etc) and it is pretty hard to only get the classes where the coverage has dropped. 
The 'changes only' checkbox is a good idea but does not really help in our case because it shows all changes positive and negative ones.

Would it be possible to add another checkbox to only show classes where the line or branch coverage has decreased or even better for our needs would be the possibility to sort the table by the coverage difference.

**Comment by danielpalme** [comment]
Adding an extra checkbox or dropdown should be possible.
But it will take some time since I'm pretty busy at the moment.

**Comment by danielpalme** [comment]
Please have a look at this new (pre-)release: https://www.nuget.org/packages/ReportGenerator/4.0.5-rc3

You now have some more filtering options:
![filter](https://user-images.githubusercontent.com/859606/50386551-2c2ffd80-06e9-11e9-8b67-d6a9ca7134d5.png)


Does this work for you?

**Comment by morli94** [comment]
Hi. Thx for implementing that so fast it is exactly what we need! And sorry for my late answer was a little bit busy the last weeks. 
Have a nice day!
