### ISSUE TITLE
Problem installing package with VS 2015 RC

### ISSUE THREAD

**Issue by giggio** [danielpalme/ReportGenerator#19]
If you try to install ReportGenerator to a project on VS 2015 RC (latest available at the moment) using nuget you get this error message:

````
Could not install package 'ReportGenerator 2.1.6.0'. You are trying to install this package into a project that targets '.NETFramework, Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0
````

I think there might be a problem on the way the nuget pkg is structured. Maybe you need a tools folder?

Some references:
https://docs.nuget.org/create/enforced-package-conventions
https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
I have to look into this and update the package structure.

**Comment by danielpalme** [comment]
The problem is fixed in the latest beta.
```ReportGenerator.exe``` is now located in ```tools``` subfolder.

**Comment by giggio** [comment]
Just tested, it worked perfectly.
