### ISSUE TITLE
Trying to include ReportGenerator in VSTS (Azure Devops) can't find summary summary1096 file

### ISSUE THREAD

**Issue by devedse** [danielpalme/ReportGenerator#190]
I've created a DockerImage that run reportgenerator to create a code coverage report using these commands in an sh file:

```
echo "RunTestCoverage.sh: Running test coverage..."
dotnet test "Platform.Tests.sln" "--logger:trx;LogFileName=/results/coveragerun-test-results-core.xml" "/p:CollectCoverage=true" "/p:CoverletOutputFormat=cobertura" "/p:CoverletOutput=/results/coveragerun-coverage-results-core.xml"
echo "RunTestCoverage.sh: Running report creation..."
reportgenerator "-reports:/results/coveragerun-coverage-results-core.xml" "-targetdir:/results/ReportGenerator" "-reporttypes:HtmlInline_AzurePipelines" "-sourcedirs:/src/"
```

This works great and outputs the following directory:

![image](https://user-images.githubusercontent.com/2350015/50230649-5c0b9800-03ad-11e9-8e29-e9bc2ac92236.png)

However when I now try to publish these test results with VSTS:

![image](https://user-images.githubusercontent.com/2350015/50230697-78a7d000-03ad-11e9-885d-c48cfd417008.png)

I keep running into this error:

```
2018-12-19T15:40:33.4676645Z ##[warning]Error occurred while publishing code coverage files. Error: Access to the path '/home/vsts/work/1/a/tests-results/ReportGenerator/summary1096' is denied.
```

For some reason it seems to look for a summary1096 file which does not exist. How do I create this file with ReportGenerator? Or is this more of a VSTS issue where it should simply skip this file and just upload the whole directory?

**Comment by danielpalme** [comment]
Seems like a VSTS issue. ReportGenerator does not generate a directory or file named "summary1096 ".

Instead of using a Docker image with ReportGenerator you could also use this extension directly in VSTS:
https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator

**Comment by devedse** [comment]
I tried that extension but because we do the builds in the docker container we don't have access to the source files in an easy way.

I've submitted an issue in the VSTS tasks repo:
https://github.com/Microsoft/azure-pipelines-tasks/issues/9127

Let's hope they come back as fast as you did :smile:, thanks for the update.
