### ISSUE TITLE
ReportGenerator branch coverage does not match Cobertura input file

### ISSUE THREAD

**Issue by ToastyMallows** [danielpalme/ReportGenerator#191]
I'm running ReportGenerator on a Cobertura XML file and the file contains this:

`<coverage line-rate="0.859" branch-rate="0.758" version="1.9" timestamp="1546449905" lines-covered="275" lines-valid="320" branches-covered="50" branches-valid="66">`

When I view the report, ReportGenerator is saying that my Branch coverage is 88% and not 75.8%:

![image](https://user-images.githubusercontent.com/4356159/50606527-0eeef200-0e94-11e9-8b59-f8fed685aa22.png)

I'm not merging any output files or anything fancy.  I just have one Cobertura file that gets generated and I pass that directly in to ReportGenerator.  Why is this happening?

Version:  ReportGenerator 4.0.4

**Comment by danielpalme** [comment]
I don't know how _Cobertura_ calculates this ratio.

_ReportGenerator_ calculates it based on the _number of covered branches_ divided by the _number of total branches_.

The following Cobertura snippet contains 4 branches, 1 of the is covered:

```xml
<method name="SampleFunction" signature="()V" line-rate="0.8571428571428571" branch-rate="0.25" complexity="0">
    <lines>
        <line number="7" hits="1" branch="false"/>
        <line number="12" hits="1" branch="false"/>
        <line number="13" hits="1" branch="false"/>
        <line number="15" hits="1" branch="true" condition-coverage="25% (1/4)">
            <conditions>
                <condition number="0" type="jump" coverage="50%"/>
                <condition number="1" type="jump" coverage="0%"/>
            </conditions>
        </line>
        <line number="17" hits="1" branch="false"/>
        <line number="20" hits="0" branch="false"/>
        <line number="26" hits="1" branch="false"/>
    </lines>
</method>

```

**Comment by ToastyMallows** [comment]
By looking at the numbers, Cobertura calculates the `branch-rate` by dividing the `branches-covered` by `branches-valid`, in this case, 50/66 = 0.75757575757 ≈ 0.758.  These numbers are found in the original code snippet I posted, they come from the root `<coverage>` node.

So ReportGenerator is looking at all of the Method XML nodes inside of all of the Class XML nodes and calculating this again?  I will have through my Cobertura file to see what total I get and see if that matches what ReportGenerator is saying.

**Comment by ToastyMallows** [comment]
Ok, if I add up all of the `condition-coverage` nodes that I can find in my Cobertura file, I get 88/100 = 0.88.  I'm not sure how Cobertura is getting the numbers 50 and 66 for `branches-covered` and `branches-valid`.

**Comment by danielpalme** [comment]
Yes _ReportGenerator_ does not reuse the numbers of the Cobertura file.

Reasons:
- The numbers are not always easy to understand (see above)
- _ReportGenerator_  also supports other input formats (not only Cobertura), which have other metrics
- _ReportGenerator_  supports merging of several files

**Comment by ToastyMallows** [comment]
Ok that makes sense.  Thanks for the explanation @danielpalme!
