### ISSUE TITLE
Reportgenerator not able to parse Cobertura file generated by nyc (latest version)

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#192]
[cobertura.log](https://github.com/danielpalme/ReportGenerator/files/2737427/cobertura.log)
Attaching a sample cobertura xml file. I don't see any exception but the html file doesn't have info about test class, methods etc.

**Comment by danielpalme** [comment]
The XML file is does not comply with the DTD (http://cobertura.sourceforge.net/xml/coverage-04.dtd).
E.g. the `<packages>` element should contain a `<package>` element.
The `<package>` element should contain a `<classes>` element.

This is not the case here.

**Comment by acesiddhu** [comment]
thanks @danielpalme looks like it related to this issue https://github.com/istanbuljs/istanbuljs/issues/14. I will follow up on nyc repo

**Comment by danielpalme** [comment]
The latest release now supports handling those invalid files:
https://www.nuget.org/packages/ReportGenerator/4.0.12

**Comment by acesiddhu** [comment]
Thanks @danielpalme so will Reportgenerator parse these files fine or will we just throw an error?

**Comment by danielpalme** [comment]
ReportGenerator shows a warning on the command line and continues parsing the file.
