### ISSUE TITLE
Clover Support in Report Generator

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#193]
Are there plans to support clover format in Report Generator?

**Comment by danielpalme** [comment]
The clover format seems to be quite easy to support.
I will try to add support for it within the next 1-2 weeks.

**Comment by danielpalme** [comment]
Please give this new (pre-) release a try:
https://www.nuget.org/packages/ReportGenerator/4.0.6-rc1

If your _clover_ file contains relative paths, make sure to supply the root directory with the following command line parameter:
`-sourcedirs:C:\MYROOTDIRECTORY`

Please let me know if this works for you.

**Comment by acesiddhu** [comment]
thanks @danielpalme I have question. I have this clover xml. reportgenerator is asking for source directory always `No source directories supplied for 'Clover' coverage file` even if the xml has absolute path to source directory (check below). is it known?
```
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1547632309902" clover="3.2.0">
  <project timestamp="1547632309902" name="All files">
    <metrics statements="4" coveredstatements="2" conditionals="0" coveredconditionals="0" methods="2" coveredmethods="0" elements="6" coveredelements="2" complexity="0" loc="4" ncloc="4" packages="2" files="2" classes="2">
      <package name="src">
        <metrics statements="2" coveredstatements="1" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="0"/>
        <file name="source.js" path="D:\jesttest\src\source.js">
          <metrics statements="2" coveredstatements="1" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="0"/>
          <line num="1" count="1" type="stmt"/>
          <line num="2" count="0" type="stmt"/>
        </file>
      </package>
      <package name="src.src2">
        <metrics statements="2" coveredstatements="1" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="0"/>
        <file name="source.js" path="D:\jesttest\src\src2\source.js">
          <metrics statements="2" coveredstatements="1" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="0"/>
          <line num="1" count="1" type="stmt"/>
          <line num="2" count="0" type="stmt"/>
        </file>
      </package>
    </metrics>
  </project>
</coverage>
```

**Comment by danielpalme** [comment]
I'm aware of that. The warning is always emitted.
You can ignore it in that case.

Does the coverage report get generated?

**Comment by acesiddhu** [comment]
It does work and the html has the content. Thanks for adding this support
