### ISSUE TITLE
Generating ReportGenerator Html from cobertura or any other htmls produced by Code coverage tools that are available

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#195]
Today Reportgenerator supports generating HTML reports by reading various code coverage xmls and source code from local machine or remotely. What are your thoughts on generating html directly from html that code coverage tool generates. 
Asking this because I want to get rid of reading source files from local machine or remote location(as source code is not available with me) and directly get source from html that the tool generated.

**Comment by danielpalme** [comment]
I won't implement anything like that. Reading the source code files is much easier and reliable than parsing some HTML.

**Comment by acesiddhu** [comment]
Make sense. HTML doesn't have a schema as such so it would be flaky and prone to issues
