### ISSUE TITLE
Generate coverage comparison

### ISSUE THREAD

**Issue by Igorbek** [danielpalme/ReportGenerator#200]
It will be useful to generate coverage report that not only show the historical chart but compare two code coverage results.

Particularly, with a standard PR development flow, what we usually want to see is not just the build's coverage but comparison to the target's branch code coverage.

So the feature request would be to have an extra option which is location of base code coverage data to compare to (similarly to historical data). If the option is passed, the tool needs to generate a report which will have comparison of the two inputs.

- class/file coverage as a diff
  - here's a difficulty what exactly to show if source code changed along with its coverage
  - a simplest version is to only show diff in the summary tables (per file/class) without actual source code diff
- a bonus summary report with change information
- can additionally accept names of base report (name of target branch) and current report

Thank you

**Comment by danielpalme** [comment]
Well I guess that's a quite a lot of work. You should have a look at https://coveralls.io/.
It's free for OpenSource projects and affordable for companies.

But if you are using the `-historydir:` command line parameter you already get some of the features you requested.
First of all there's the history chart and you also can compare the current coverage to another execution in the past.

Example:
![image](https://user-images.githubusercontent.com/859606/51560608-3e868e00-1e85-11e9-9757-8a8751b9068d.png)

**Comment by Igorbek** [comment]
Thank you, that is interesting. That should work for us.
Also thank you for recommendation of the service.
