### ISSUE TITLE
x64 platform

### ISSUE THREAD

**Issue by Thilas** [danielpalme/ReportGenerator#201]
I'm using ReportGenerator (v4.0.6, targeting .NET Framework) and I'm getting an `OutOfMemoryException` due to a big number of xml coverage files but most of all because of huge source code files.

Quick question: although ReportGenerator is build againt AnyCPU platform, I am wondering why it is set to prefer 32-bit? x64 would definitely fix my issue...

**Comment by danielpalme** [comment]
Thanks for you hint. I will change this in the next release.

**Comment by danielpalme** [comment]
New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.0.8

**Comment by Thilas** [comment]
Thanks, that was so fast ! 😄
Gonna test it right away.

**Comment by Thilas** [comment]
I confirm it's alright. Thanks again!
