### ISSUE TITLE
[Feature request] Command line parameter to open html links in new window

### ISSUE THREAD

**Issue by nikosatwork** [danielpalme/ReportGenerator#208]
Hi @danielpalme!

Thanks for your time in making the ReportGenerator such a great tool!

I have a small request. I would like to be able to pass a new `settings:openHtmlLinksInNewWindow=true` [setting ](https://github.com/danielpalme/ReportGenerator/wiki/Settings) which will add `target="_blank"` to the href html tags in index.htm so that links will open in a new window. That way the summary/index page will not have to be reloaded/reset when moving between pages.

Best Regards,
Nikos

**Comment by danielpalme** [comment]
Thanks for your feedback 👍 

I try to avoid adding settings for every little detail that are only used by very few persons.

Are you aware, that you can use press `CTRL` while clicking the link or by clicking it with the middle mouse button you can already open it within a new tab/window?
With that possibility everybody can chose how to open the link.

**Comment by unity-nikos** [comment]
Makes sense, thanks Daniel.
