### ISSUE TITLE
ReportGenerator does not have strong name.

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#210]
Is there a reason why Reportgenerator dlls are not strongly named. can we make them strongly named?

**Comment by danielpalme** [comment]
What would be the advantage?

**Comment by acesiddhu** [comment]
I was trying to use report generator in our build system which has a restriction to consume only strongly named dlls. Hence the ask.

**Comment by danielpalme** [comment]
ok, but that would mean that all dependencies have to be signed as well.
That's currently not the case: See https://github.com/SixLabors/ImageSharp/issues/738

**Comment by danielpalme** [comment]
I was finally able to sign the ReportGenerator DLLs with a strong name.

Release 4.6.0 contains the changes:
https://www.nuget.org/packages/ReportGenerator/4.6.0
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.6.0
https://www.nuget.org/packages/ReportGenerator.Core/4.6.0
