### ISSUE TITLE
Support for .NET Core 2.2 (ReportGenerator.DotnetCliTool)

### ISSUE THREAD

**Issue by Jsparham777** [danielpalme/ReportGenerator#211]
Could you add .NET Core 2.2 support for the ResportGenerator CLI Tool?

**Comment by danielpalme** [comment]
Do I really have to add special support for it?

I just tried the following:
- Created a new project wit `dotnet new console` (with `<TargetFramework>netcoreapp2.2</TargetFramework>`)
- Added the package:
```
<ItemGroup>
  <DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.0.12" />
</ItemGroup>
```
- Successfully executed ReportGenerator with `dotnet reportgenerator [options]` 

I used the following `global.json` configuration:
```
{
    "sdk": {
      "version": "2.2.103"
    }
}
```

What's different on you machine that it does not work out of the box?

**Comment by danielpalme** [comment]
I just tried on a machine with only SDK v2.2.104 installed.
It worked out of the box even without targeting 2.2

If it really doesn't work for you, please reopen the issue and provide some information about your environment.
