### ISSUE TITLE
SonarQube Format - Output file name

### ISSUE THREAD

**Issue by XREvo** [danielpalme/ReportGenerator#212]
Hi,

First of all, I've discovered this project only today and i'd like to give a big **THANK YOU** to all the contributors of this project, for the awesome work that they have done. It's amazing!

I've a question about the output file name for SonarQube.
Why does the file name use a 'C', instead of a 'Q' ? (it's _sonar_**q**_ube_ and not _sonar_**c**_ube_) [HERE](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Reporting/Builders/SonarQubeBuilder.cs#L90)
I'm using the VSTS Build Task, and I've spent few minutes trying to figure out why the file was not uploadable before seeing the typo in the file name. 
In the end, I was just wondering why? (Is it done voluntarily?)

Bye

**Comment by danielpalme** [comment]
Thanks for your feedback!

The naming of the file is incorrect (just a typo). I will change that in the next release.

**Comment by danielpalme** [comment]
The issue is fixed in the latest release, so you probably have to change your Azure DevOps/VSTS settings.

**Comment by XREvo** [comment]
Thank you @danielpalme 
I'll do it tomorrow 😃
