### ISSUE TITLE
Cobertura Html report generation doesn't use Source folder correctly

### ISSUE THREAD

**Issue by nigurr** [danielpalme/ReportGenerator#213]
Hi,

When we try to generate "Html" report using "Cobertura.xml", the source paths are being not used properly while reading the source files.

We are properly reading the source folder: https://github.com/danielpalme/ReportGenerator/blob/1f4fb6ac1cc25c5c7d6977d77353b41f8ead4a6a/src/ReportGenerator.Core/Parser/CoberturaParser.cs#L89
We are not propagating that information: https://github.com/danielpalme/ReportGenerator/blob/e722fc50b9d64b3f5948dae007bfb10daaa78c8b/src/ReportGenerator.Core/Reporting/ReportGenerator.cs#L80

Attached sample cobertura xml (generated with official maven cobertura plugin)
[coverage.txt](https://github.com/danielpalme/ReportGenerator/files/2905470/coverage.txt)

**Comment by danielpalme** [comment]
The relevant code for determining the correct path can be found here:
https://github.com/danielpalme/ReportGenerator/blob/1f4fb6ac1cc25c5c7d6977d77353b41f8ead4a6a/src/ReportGenerator.Core/Parser/Preprocessing/CoberturaReportPreprocessor.cs#L62

In your case ReportGenerator evaluates the following paths:
- ```--source/org/jacoco/examples/maven/java/HelloWorld.java```  
- ```E:/Repo/example-java-maven/src/main/java/org/jacoco/examples/maven/java/HelloWorld.java```  

What's the correct **full path** on your system?

**Comment by danielpalme** [comment]
New release contains your fix / PR:
https://www.nuget.org/packages/ReportGenerator/4.0.14
