### ISSUE TITLE
Jacoco Html report generation doesn't use Source folder correctly

### ISSUE THREAD

**Issue by nigurr** [danielpalme/ReportGenerator#214]
Hi,

This is similar to issue https://github.com/danielpalme/ReportGenerator/issues/213
Sample Jacoco xml is attached from pure Java project.

We have SourceFileName in the report, however we don't have source folder (absolute path).
We should be searching recursively in given Source folder argument or default folder with file name.

[jacoco.txt](https://github.com/danielpalme/ReportGenerator/files/2905626/jacoco.txt)

**Comment by danielpalme** [comment]
When using JaCoCo, you **have to** supply the base directory via the `-sourcedirs:YOURBASEDIRECTORY` command line parameter.

Files will be searched at `YOURBASEDIRECTORY/org/jacoco/examples/maven/java/HelloWorld.java`

See:
https://github.com/danielpalme/ReportGenerator/blob/e722fc50b9d64b3f5948dae007bfb10daaa78c8b/src/ReportGenerator.Core/Parser/Preprocessing/JaCoCoReportPreprocessor.cs#L88

**Comment by danielpalme** [comment]
Does the parameter `-sourcedirs:E:/Repo/example-java-maven/src/main/java/` work for you?

**Comment by nigurr** [comment]
Yes this works for me. Can we support recursive pattern like we support for report xml (a\*\*.xml)

**Comment by danielpalme** [comment]
The root directory should be enough. The JaCoCo files contains the relative path and the file name.
What would the benefit of "recursive pattern" be?

**Comment by nigurr** [comment]
in typical pipeline scenario, we must supply exact path. It would be good to just pass `Default source folder (Source)` and if there are some nested paths like `Source\MyApp\src\main\java\abc\abc.java', it just works.

Because if we change `App` directory name (MyApp), we need to change the configuration everywhere. ideally it would be simply (Source\**\) would be simple as we have for summary file

**Comment by nigurr** [comment]
@danielpalme Will you accept this enhancement if we contribute?

**Comment by danielpalme** [comment]
I'm not sure yet, since I still think that the path should be supplied to _ReportGenerator_.
But let's have a look.
