### ISSUE TITLE
ReportGenerator fails "Value was either too large or too small for an Int32." with not enough debug information

### ISSUE THREAD

**Issue by baubakg** [danielpalme/ReportGenerator#216]
Hi There,

I have been try report generator, and it seems like a great product. However I am seeing that for one of my cobertura files I am getting the error:

```
 Error during reading report '/Users/gandomi/Documents/Development/gitRepositories/gcovrFull_ToTo.xml' (Size: 27MB): Multiple errors
Value was either too large or too small for an Int32.
Value was either too large or too small for an Int32.
```

I end up with no results. I have two issues with this:

1. I am not getting enough information as to where exactly this Value error occurs
2. That it fails :)

**Comment by danielpalme** [comment]
Can you please share the file?
You can send it by email: danielpalme82@gmail.com

**Comment by danielpalme** [comment]
New release should fix your problem:
https://www.nuget.org/packages/ReportGenerator/4.0.14

Give it a try and please let me know if it works for you.

**Comment by baubakg** [comment]
Thanks, will try. I will send you my file.

**Comment by baubakg** [comment]
Thanks Daniel,

This works much better :) Ok I don't know about the log but the regeort generation works wonderfully now
