### ISSUE TITLE
Coverage (from OpenCover) not interpreted correctly

### ISSUE THREAD

**Issue by calimero1000582** [danielpalme/ReportGenerator#217]
Closing brace considered as not tested
![image](https://user-images.githubusercontent.com/3637661/53602083-b4b09b80-3b7b-11e9-97ad-743734eb7fee.png)

There is 8 space before the closing brace

In OpenCover.xml, for this file, I have
```xml
<SequencePoint vc="0" uspid="11514" ordinal="8" offset="317" sl="502" sc="9" el="502" ec="10" bec="0" bev="0" fileid="1003" />
```

**Comment by danielpalme** [comment]
The attribute `vc="0"` indicates that the line has been executed 0 times.
Therefore I think the red indication is correct.

**Comment by calimero1000582** [comment]
Ok, I found an old issue in OpenCover about this (reported in 2014), so I will close this one
