### ISSUE TITLE
Crap Score sometimes display trailing zeros

### ISSUE THREAD

**Issue by calimero1000582** [danielpalme/ReportGenerator#218]
Just a strange behavior that display trailing zeros for crap score. Sequence Coverage is not 100% due issue #217 

![image](https://user-images.githubusercontent.com/3637661/53602322-6bad1700-3b7c-11e9-82ba-c7e66f9e3788.png)

**Comment by danielpalme** [comment]
I will investigate this.

https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs#L698

**Comment by danielpalme** [comment]
I'm not able to reproduce. Can you share your OpenCover file?
You can send it by email: danielpalme82@gmail.com

**Comment by calimero1000582** [comment]
Sent the file by email

**Comment by danielpalme** [comment]
New release is available:
https://www.nuget.org/packages/ReportGenerator/4.0.15
