### ISSUE TITLE
Generated Cobertura output is invalid according to DTD

### ISSUE THREAD

**Issue by SteveGilham** [danielpalme/ReportGenerator#219]
Generate cobertura output from e.g. OpenCover input.  The file begins
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
```

Pass it as input to this simple validation program
[Program.cs](https://github.com/danielpalme/ReportGenerator/files/2927419/Program.cs.txt)

See each `method` element report
```
The required attribute 'complexity' is missing.
The element 'method' has invalid child element 'line'. List of possible elements expected: 'lines'.
```

The file at the SourceForge URL is the same as the current development copy in [the Cobertura GitHub repo](https://github.com/cobertura/cobertura/blob/master/cobertura/src/site/htdocs/xml/coverage-04.dtd)

**Comment by SteveGilham** [comment]
Reading the [Cobertura source code](https://github.com/cobertura/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/reporting/xml/XMLReport.java#L226) confirms that yes, Cobertura does hew to the DTD definition.

**Comment by danielpalme** [comment]
New release is available:
https://www.nuget.org/packages/ReportGenerator/4.0.15
