### ISSUE TITLE
Downgrade Risk HotSpot section

### ISSUE THREAD

**Issue by nigurr** [danielpalme/ReportGenerator#220]
Hi,

Currently Report Generator does generate `Risk Hotspots`. However this is available for limited code coverage tools.
Can we move this section below Coverage table so that UI becomes consistent with all formats and also highlight the most important function (Coverage)

![image](https://user-images.githubusercontent.com/15208679/53871497-60496800-4022-11e9-9ab6-03cfa4043290.png)

**Comment by danielpalme** [comment]
I'm not sure yet. If the `Risk Hotspots` are moved down, they might easily get overseen.
The coverage table is typically pretty long whereas the hotspots table is limited in its default length.
