### ISSUE TITLE
Support for .NET Core 3 (dotnet-reportgenerator-globaltool)

### ISSUE THREAD

**Issue by Djohnnie** [danielpalme/ReportGenerator#221]
Is it possible to create a version of dotnet-reportgenerator-globaltool that supports the .NET Core 3 SDK?
I would like to use the report generator in an Azure Pipelines build using the .NET Core 3 SDK and I get an error that .NET Core 2.1 SDK could not be found.

**Comment by danielpalme** [comment]
This is already tracked in #205.
The necessary changes are also already made in branch [netcoreapp30](https://github.com/danielpalme/ReportGenerator/tree/netcoreapp30).

Release will be made when .NET Core is finally released.

Until then you can try this pre-release (a little bit outdated):
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.0.11-netcore3-p2-01

**Comment by Djohnnie** [comment]
Thank you for your response and looking forward to the final release of .NET Core 3.
For now I have forked your repo to create a custom globaltool to use in my Azure Pipelines build.
