### ISSUE TITLE
Sorting does not work as expected

### ISSUE THREAD

**Issue by stannynuytkens** [danielpalme/ReportGenerator#229]
1. Group by assembly
2. Sort any column

It's not working. Only if you expand everything and even then the sorting is behaving strangely..?

**Comment by danielpalme** [comment]
Intended behavior:
- The order of the assemblies/namespaces does not change change
- Only the order of the classes in a assemblies/namespace is changed based on the sorting column.

I just verified that behavior and it works for me.
Can you provide a concrete example where it does not work?

**Comment by stannynuytkens** [comment]
Ok, it's the intended behaviour that's bugging me.

![image](https://user-images.githubusercontent.com/1488543/57126604-d69de880-6d8d-11e9-913c-7eb7c48f9f1f.png)

![image](https://user-images.githubusercontent.com/1488543/57126615-e0275080-6d8d-11e9-9b63-a0fc3fbb82c9.png)

Nothing changes when changing sort... If you provide grouping in the grid, at least sort that grouping accordingly. (assembly total > class)  🤷‍♂️

**Comment by danielpalme** [comment]
Can you please share the report with me by email?
danielpalme82@gmail.com

Then I can have a look at your files. It seems like a bug.

**Comment by stannynuytkens** [comment]
Sorry, I can't share the report (and code) with you.
The **HtmlInline** report is generated from multiple (vstest) `coverage.xml` files.

**Comment by stannynuytkens** [comment]
Actually, this is what Azure DevOps (VSTS) generates using this tool when I publish the the coverage results.

**Comment by danielpalme** [comment]
If you cant's share your report, can you try to reproduce the issue with this coverage report:
[Sample.zip](https://github.com/danielpalme/ReportGenerator/files/3141235/Sample.zip)

What steps do I have to do, to get the behavior?

**Comment by stannynuytkens** [comment]
Same behaviour with your sample?

Steps I do:
- Open index.html in Chrom
- Collapse all
- Change sorting (either column)

Expected: 
- _ReportGenerator.DotnetCorePluginLoader_ to be on top when sorting Line Coverage desc

**Comment by danielpalme** [comment]
New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.1.5
