### ISSUE TITLE
Using ReportGenerator in AzurePipelines experiences

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#231]
Hi Daniel,

We are from the Azure DevOps team at Microsoft and are working on the code coverage reporting experiences in Azure Pipelines. 
We [recently](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#cobertura-code-coverage-report-updates) improved Cobertura based code coverage HTML reporting experience in Azure Pipelines by using ReportGenerator. We are investing in better code coverage reporting experiences for both CI builds (coverage status for a repo) and PR validation (diff coverage for changes being brought in), for a wide variety of languages and popular coverage formats. For this, we are exploring using ReportGenerator as it already supports most of the popular formats, is cross-plat, extensible and popular in open source community.
A quick Skype/Teams call would be great for us to connect.
I wasn't able to find your E-mail id. Can you reach me at siddhap AT microsoft DOT com, so we can take this forward.

/CC:  @smalpani-msft, @PBoraMSFT

**Comment by danielpalme** [comment]
Hi Siddhartha,

I've just sent you an email.

**Comment by acesiddhu** [comment]
Thanks Daniel. I have got your mail. Will take it from there.

**Comment by MrLuje** [comment]
Hi, I'm interested in having coverage diff in Azure Devops PRs
I found this [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops) but I'm building a C# app with Docker so, running build & test inside docker and extracting/publishing the coverage in the pipeline.

I'm using both PublishTestResults@2 & PublishCodeCoverageResults@1 to publish test results & coverage (coverage are merged using ReportGenerator).

I'm getting full coverage but I can't find any way to get diff coverage. 
Is there any guidance about how to achieve this ? @acesiddhu
