### ISSUE TITLE
Report generated for cobertura xml missing some classes 

### ISSUE THREAD

**Issue by liliankasem** [danielpalme/ReportGenerator#235]
Hi,

Generating the report from a cobertura.xml file ends up with some classes missing, but using opencover works fine.

**opencover report:**
<img width="1080" alt="opencover" src="https://user-images.githubusercontent.com/2198905/57184063-8b0d3c80-6e6a-11e9-9319-bbf10842ab2f.png">

**cobertura report:**
<img width="1088" alt="cobertura" src="https://user-images.githubusercontent.com/2198905/57184066-8f395a00-6e6a-11e9-8e3a-37bfe035b5d2.png">

The commands I used:

`dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=\"[xunit*]*\"`

`dotnet reportgenerator -reports:./coverage.cobertura.xml -reporttypes:HTML -targetdir:./report/cobertura`

Copies of the reports:
https://likasem.blob.core.windows.net/issues/coverage.cobertura.xml
https://likasem.blob.core.windows.net/issues/coverage.opencover.xml

**Comment by danielpalme** [comment]
Thanks for the great issue (with sample files attached).

I fixed that behavior. The next release will contain the change.

**Comment by danielpalme** [comment]
New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.1.5
https://www.nuget.org/packages/dotnet-reportgenerator-cli/4.1.5
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.1.5
