### ISSUE TITLE
Possible branch coverage rounding problem

### ISSUE THREAD

**Issue by seesharper** [danielpalme/ReportGenerator#236]
Hi @danielpalme and thanks for all your effort into making this a great tool. 

I have an issue though 😀 I have an OpenCover xml file that states that the overall branch coverage is 99.7%, but when the report is generated it says that the branch coverage is 100%.
Attaching the file in this issue. 

[coverage.opencover.xml.zip](https://github.com/danielpalme/ReportGenerator/files/3148222/coverage.opencover.xml.zip)

Here is a screenshot of the generated summary 

![image](https://user-images.githubusercontent.com/1034073/57230134-f0eaf700-7017-11e9-9c55-85e33f0cfb0c.png)

Any ideas?

**Comment by danielpalme** [comment]
Hi @seesharper 

OpenCover counts a little bit different here.
The "problem" seems to be caused by this class:
```xml
<Class>
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="4" visitedBranchPoints="3" sequenceCoverage="100" branchCoverage="75" maxCyclomaticComplexity="4" minCyclomaticComplexity="4" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="0" />
  <FullName>DbReader.DbReaderOptions/&lt;&gt;c__DisplayClass11_0</FullName>
  <Methods />
</Class>
```

The attributes `numBranchPoints="4"` and `visitedBranchPoints="3"` indicate a 75% coverage and one uncovered branch.
ReportGenerator only count the `<BranchPoint />` elements, and the class above does not contain any `<BranchPoint />`.
Therefore the difference.

**Comment by seesharper** [comment]
Yeah, I found it by looking at the raw xml file, but it is a little bit unfortunate that it did not show up in the report. The method being reported contains a lambda that combines two other lambdas. Maybe that is why this is a corner case though. But what you are saying is that this is by design? 

https://github.com/seesharper/DbReader/blob/3a920f8dec754725d2daf72ab27f0573d1c17407/src/DbReader/DbReaderOptions.cs#L75

**Comment by danielpalme** [comment]
I can only speak for ReportGenerator:
My goal here is, to create a consistent report.
If you sum up the branches in a file/class the number should match "Total branches".
Otherwise I would get a lot of questions why numbers do not match :-)

**Comment by seesharper** [comment]
Perfectly understandable. I think this is sort of an edge case anyway. Thanks for your quick response 👍
