### ISSUE TITLE
Not able to install ReportGenerator.Core Nuget package

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#237]
I am not able to install ReportGenerator.core nuget package (Latest version). This is the error i get

`Unable to resolve dependency 'SixLabors.ImageSharp.Drawing'. Source(s) used: 'nuget.org', 'CliFallbackFolder', 'Package source', 'Microsoft Visual Studio Offline Packages'.`

Is this dependency needed for ReportGenerator.core?

**Comment by danielpalme** [comment]
Yes that dependency is currently needed.

I'm able to install the package on my machine (I tried with a .NET 4.7 and a .NET Core project).
Perhaps a networking issue?

The package is available on Nuget:
https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta0004

**Comment by acesiddhu** [comment]
i installed this package directly and then installed Reportgenerator.core it worked. closing the issue
