### ISSUE TITLE
Missing a link back to the summary

### ISSUE THREAD

**Issue by stannynuytkens** [danielpalme/ReportGenerator#239]
This would be helpful on Azure DevOps because the only way to return to the report summary page is by refreshing the entire page. If this is added I won't expect it to be on Azure DevOps anytime soon because they're still on version `4.0.15.0`.

On a side note, Microsoft stripped the report from any javascript.. 
Understandable but annoying certainly when sorting got [improved](https://github.com/danielpalme/ReportGenerator/commit/f9078e8ed4c926c77395513461c6e2e077a65ccb).

**Comment by danielpalme** [comment]
I already created a PR to update the Azure DevOps task.

Regarding the link to the summary page:
Good idea. Will add this in the next release.

**Comment by stannynuytkens** [comment]
Link to the PR? 😉

**Comment by danielpalme** [comment]
New release should be available soon:
https://www.nuget.org/packages/ReportGenerator/4.1.6

**Comment by danielpalme** [comment]
The new symbol is not rendered correctly in Azure DevOps:
![Devops](https://user-images.githubusercontent.com/859606/58309212-e6946f80-7e03-11e9-8efe-6c9f09453631.png)

See: https://github.com/Microsoft/azure-pipelines-tasks/issues/9150
