### ISSUE TITLE
Seems filters don't work

### ISSUE THREAD

**Issue by nilfdev** [danielpalme/ReportGenerator#240]
I am configuring azure CI pipeline. 
and I've added following steps:

- test
- report generator
- publish code coverage 

but in the generated report I see all the files assemblies (including xunit) because filter seems doesn't work. 
also I changed report type to Dark scheme, but not changes in the report:

the list of filers is following: 
![image](https://user-images.githubusercontent.com/15476934/57526457-bfcb3900-732d-11e9-8e23-966af17bd70c.png)

but the result still contains 
![image](https://user-images.githubusercontent.com/15476934/57526498-d4a7cc80-732d-11e9-873d-ecd60c47afce.png)

looks like no parameters applied from the configuration section, or I do something wrong

**Comment by danielpalme** [comment]
You are not doing anything wrong.

The problem is:
The generated HTML is ignored and regenerated by the 'Publish code coverage' task.
Microsoft changed that recently:
https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#cobertura-code-coverage-report-updates

**Comment by nilfdev** [comment]
> You are not doing anything wrong.
> 
> The problem is:
> The generated HTML is ignored and regenerated by the 'Publish code coverage' task.
> Microsoft changed that recently:
> https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#cobertura-code-coverage-report-updates

does it mean that Microsoft ignoring all the filters, removed all the styles (according to the security reasons) but NOT add the filtering functionality by themselves? 
means there is no workaround to apply filtering during publishing code coverage results?

**Comment by danielpalme** [comment]
Correct.

Workaround:
Publish the report generated by 'ReportGenerator' as a separate artifact and ignore the coverage results from Azure DevOps.

**Comment by nilfdev** [comment]
Microsoft as usually makes the life easier. 
thank you for quick reply and great tool!

**Comment by danielpalme** [comment]
I just found out, that you can set an environment variable to prevent regenerating the report:
```
disable.coverage.autogenerate: 'true'
```
