### ISSUE TITLE
[Risk Hotspots] [Feature Request] Option to remove Risk Hotspots section (in appsettings.json)

### ISSUE THREAD

**Issue by nikosatwork** [danielpalme/ReportGenerator#242]
Hi Daniel,

Currently, if none of the CyclomaticComplexity, NPathComplexity and CrapScore are in the OpenCover data, the report generator will display an empty Risk Hotspots section.

Do you think it would make sense to add an option to hide the Risk Hotspots section? This will allow the ReportGenerator to be used purely as a Code Coverage report tool rather than needing to include Static Analysis aspects to it. Something like `settings:includeRiskHotspots=false`

Thank you, your time and effort to develop ReportGenerator are really appreciated

**Comment by danielpalme** [comment]
New release should be available soon:
https://www.nuget.org/packages/ReportGenerator/4.1.6

You can now use this setting:
```
riskHotspotsAnalysisThresholds:disableRiskHotspots=true
```

**Comment by nikosatwork** [comment]
Awesome! Thanks Daniel!

**Comment by nikosatwork** [comment]
Would it be possible for these settings to be made available in the `ReportConfiguration` too, so that they can be configured at runtime when calling `GenerateReport`? For example we would like to display the Risk Hotspots section when CyclomaticComplexity and/or NPathComplexity and/or CrapScore exist in the OpenCover data, and not display it when they are not. Thanks!

**Comment by danielpalme** [comment]
I made some changes:

1.  I moved the new option to the [Settings](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Settings.cs#L33) class
2. I added a new overload of the [GenerateReport](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Generator.cs#L74) method, which lets you pass in a `Settings ` class instance

Sample:
```csharp
IReportConfiguration reportConfiguration = ...;

new Generator().GenerateReport(
    reportConfiguration,
    new Settings() { DisableRiskHotspots = true },
    new RiskHotspotsAnalysisThresholds());
```

New release will be available within the next hour.

**Comment by nikosatwork** [comment]
Awesome! Thanks Daniel!
