### ISSUE TITLE
Expose SummaryResult constructor

### ISSUE THREAD

**Issue by karanjitsingh** [danielpalme/ReportGenerator#243]
[`internal SummaryResult(IReadOnlyCollection<Assembly> assemblies, string usedParser, bool supportsBranchCoverage, IReadOnlyCollection<string> sourceDirectories)`](https://github.com/danielpalme/ReportGenerator/blob/46bd5f5f9709d29401b3bef849c65f3e2d04c017/src/ReportGenerator.Core/Parser/Analysis/SummaryResult.cs#L19)

I'm trying to create an HTML report using the parsed result with `ReportGenerator.Core`. The class `HtmlReportBuilder` which takes `SummaryResult` as an argument whose constructor isn't exposed.

![image](https://user-images.githubusercontent.com/4632805/58073460-3be03f00-7bc0-11e9-87c4-b250240129a8.png)

**Comment by danielpalme** [comment]
I merged your PR with some changes/additions:

1. [SummaryResult](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/Analysis/SummaryResult.cs#L16) now has a new constructor which directly takes a [ParserResult](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/ParserResult.cs)
2. I did not make `HtmlRenderer` public.
Please use the [HtmlReportBuilder](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Reporting/Builders/HtmlReportBuilder.cs) to generate the HTML file(s).
`HtmlRenderer` gets changed quite often and you should not directly depend on it. 

New release will be available within the next hour.
