### ISSUE TITLE
[Risk Hotspots] [Feature Request] Hide Risk Hotspots section if there is nothing to display

### ISSUE THREAD

**Issue by nikosatwork** [danielpalme/ReportGenerator#249]
Hi Daniel,

really appreciate implementing https://github.com/danielpalme/ReportGenerator/issues/242

Related to that I was wondering, when `settings:disableRiskHotspots=false` (default), you could also check whether there is something to display (that pass the threasholds), and if not, to not display the section.

For me I think `settings:displayRiskHotspotsIfEmpty=false` would be more valuable than `settings:disableRiskHotspots=false`

Thanks!

**Comment by danielpalme** [comment]
Currently there are the following cases:
```
1. `disableRiskHotspots=true` => Report does not show any hint on hotspots
2. `disableRiskHotspots=false`
   a. Coverage file contains quality metrics 
      i. Any quality metric exceeded => Show table with hotspots
      ii. No quality metric exceeded => Show message: 'No risk hotspots found'
   b. Coverage file does not contain quality metrics => Report does not show any hint on hotspots
```

In my opinion these cases are enough to cover the most common use cases.
