### ISSUE TITLE
Back link symbol not rendered correctly on Firefox on macOS High Sierra

### ISSUE THREAD

**Issue by chrisj-unity** [danielpalme/ReportGenerator#250]
Hi Daniel,

A minor cosmetic problem, related to issue #239. On the latest version of the Report Generator (v4.1.8), the back link isn't being displayed correctly on Firefox 67.0 on macOS High Sierra as shown here:
<img width="109" alt="Screen Shot 2019-05-30 at 12 06 48" src="https://user-images.githubusercontent.com/39768533/58633106-6a0c0000-82df-11e9-8c10-b1ca38ec7292.png">

Thanks,
Chris.

**Comment by danielpalme** [comment]
Thanks for reporting. I'm now using a simple "<". That should work everywhere.
