### ISSUE TITLE
Metrics overview showes quite high percentages:

### ISSUE THREAD

**Issue by boldt** [danielpalme/ReportGenerator#252]
# My setup

* nUnit (3.12.0)
* coverlet.msbuild (2.6.1)
* ReportGenerator (4.1.8)

# Issue

The metrics overview showes quite high percentages:

![grafik](https://user-images.githubusercontent.com/750793/59027791-3d656480-885a-11e9-96e3-663553bbd94e.png)

Probably it is 91% abd 96%.

**Comment by danielpalme** [comment]
Can you please have a look at the coverage file generated by _coverlet_?
Especially at the `sequenceCoverage` and `branchCoverage` attributes of the corresponding methods from your screenshot?

**Comment by boldt** [comment]
Just ran again the tool chain. This is how it looks in the report:

![grafik](https://user-images.githubusercontent.com/750793/59258767-de786480-8c38-11e9-8787-e88fc1d59136.png)

This is how it looks in the `coverage.cobertura.xml`:

```xml
<method name="VariableChanged" signature="()" line-rate="1" branch-rate="0,9666">
```

**Comment by danielpalme** [comment]
The problem is, that I would expect `0.9666`. The `,` makes the difference.

There are several tools that generate _Cobertura_ files. _coverlet_ is the only one that uses `,`.

**Comment by boldt** [comment]
Okay, I reported the issue at ReportGenerator.
