### ISSUE TITLE
ReportGenerator.DotnetPluginLoader.dll is not packaged with ReportGenerator.Core

### ISSUE THREAD

**Issue by karanjitsingh** [danielpalme/ReportGenerator#253]
Trying to generate report with the new overloaded methods

![image](https://user-images.githubusercontent.com/4632805/59029296-837ef000-887b-11e9-8a5d-76a374a1586c.png)

This fails with the exception
```
Could not load file or assembly 'D:\azure-pipelines-coveragepublisher\packages\reportgenerator.core\4.1.10\lib\netstandard2.0\ReportGenerator.DotnetCorePluginLoader.dll'. The system cannot find the file specified.
```

Update: Also appsettings.json is also not a part of the package.

**Comment by danielpalme** [comment]
Please try this new release:
https://www.nuget.org/packages/ReportGenerator.Core/4.1.10.2
