### ISSUE TITLE
Performance issue while Parsing cobertura xml

### ISSUE THREAD

**Issue by acesiddhu** [danielpalme/ReportGenerator#255]
Hi @danielpalme 

We have this cobertura xml file which is around 55 MB. ReportGenerator.exe takes around 500 secs to parse this file. Any known issue wrt to large coverage files?

Here is a build logs where ReportGenerator tries to parse these files. cobertura xml is attached as part of coverage html folder in artifacts. https://dev.azure.com/dotnet/Rx.NET/_build/results?buildId=18353&view=results

**Comment by danielpalme** [comment]
Hi @acesiddhu ,

 I don't have permission to download the artifact.
Can you share in another way (e.g. OneDrive)?

I will investigate why it takes that long. Should be much faster.

**Comment by acesiddhu** [comment]
@danielpalme you can open the link in private and then download the Code Coverage Repo... folder. Not the Coverage Report XML folder. If this doesnt work i will upload to onedrive

**Comment by danielpalme** [comment]
Ok, that worked. I will have a look.

**Comment by danielpalme** [comment]
New release should be much faster: https://www.nuget.org/packages/ReportGenerator/4.2.1

**Comment by acesiddhu** [comment]
Thanks. it takes 50 seconds now.

**Comment by danielpalme** [comment]
Great, much better. And this is mainly caused by `System.Linq.AsyncEnumerable` which is very very long and has a lot of methods.
