### ISSUE TITLE
How to run dotnet report-generator dotnet core

### ISSUE THREAD

**Issue by HaroonSaid** [danielpalme/ReportGenerator#257]
I added 
```
<ItemGroup>
<DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.2.2" />
</ItemGroup>
```
when i execute the following command from the sln folder location
```
$ dotnet report-generator
```
I get the error:
No executable found matching command "dotnet-report-generator"

What's the correct way to execute the cli?

**Comment by danielpalme** [comment]
When you execute "dotnet reportgenerator" your working directory has to be the project's directory not the directory of the solution.

See #144
