### ISSUE TITLE
How to use a custom report name for the generated reports

### ISSUE THREAD

**Issue by farhad-taran-cko** [danielpalme/ReportGenerator#258]
I have the following which generates a report name Summary.txt:

`<Exec Command="dotnet reportgenerator -reports:$(CoverletResultsDir)Cobertura.xml -targetdir:$(SolutionDir) -reporttypes:TextSummary -verbosity:Verbose" WorkingDirectory="$(ProjectDir)" />`

but I would like this report to be generated with a name such as `.coverage.txt`

is there anyway to accomplish this?

**Comment by danielpalme** [comment]
The name is hard coded and can't be customized at the moment.
But you can rename the file afterwards.
