### ISSUE TITLE
Tooltip is cut off in the history graph page

### ISSUE THREAD

**Issue by riccardomerlin** [danielpalme/ReportGenerator#259]
The history graph page generated using `-reporttypes:HTMLChart` is cutting off the top of the tooltip when hover over the graph. See image below.
![cut-off tooltip](https://user-images.githubusercontent.com/13499635/60442289-a3060000-9c10-11e9-828f-4fc887da13f2.png)

I'm also embedding that page as an iframe and that scenario has the same result.

It would be nice to dynamically display the tooltip according to the space left in the page...

**Comment by danielpalme** [comment]
I will try to improve that within the next days.

**Comment by danielpalme** [comment]
Please try again with this release:
https://www.nuget.org/packages/ReportGenerator/4.2.3

**Comment by riccardomerlin** [comment]
Thanks, 4.2.3 fixes it!
