### ISSUE TITLE
Compare by tag

### ISSUE THREAD

**Issue by riccardomerlin** [danielpalme/ReportGenerator#260]
In the report summary the `Compare with` functionality is using date and time as reference for the specific historic results you want to compare.
Since we use the `tag` flag to mark coverage results coming from a specific build, it would be useful to have the possibility to compare 2 different tags, since date and time on its own is not very meaningful in our context.

It would be a great help if you could add this enhancement.

Thanks

**Comment by danielpalme** [comment]
Could you please test again with this release:
https://www.nuget.org/packages/ReportGenerator/4.2.4

**Comment by riccardomerlin** [comment]
Thanks for coming back to this so quickly!

It looks like the `Filter` underneath `Compare with` dropdown doesn't work anymore in v4.2.4.
I'm comparing 2 results where the latter has a decrease in branch coverage in only few classes and when I apply the filter on the comparison I still see entire list (not filtered). Same scenario is working fine in 4.2.3

![image](https://user-images.githubusercontent.com/13499635/60573453-9946de80-9d6f-11e9-8e3e-bf53ef89bd78.png)

**Comment by danielpalme** [comment]
I will have a look at this.

**Comment by danielpalme** [comment]
Could you please test again with this release:
https://www.nuget.org/packages/ReportGenerator/4.2.5

**Comment by riccardomerlin** [comment]
Thanks, it seems fixed in 4.2.5
