### ISSUE TITLE
Q.  Support for .Net core 2.2

### ISSUE THREAD

**Issue by prongcs** [danielpalme/ReportGenerator#267]
Hi, I tried installing this tool on my .net core 2.2 project. It gives an error "Package 'dotnet-reportgenerator-cli 4.2.9' has a package type 'DotnetCliTool' that is not supported by project".	

Seems like It doesnt have support for the framework 2.2 as of now. Are there any plans to enable the same?

Thanks much for the work already done.

**Comment by danielpalme** [comment]
If you want to use the CLI package, you have to manually modify your `*.csproj`file.
You'll have to add:
```xml
<ItemGroup>
<DotNetCliToolReference Include="dotnet-reportgenerator-cli" Version="4.2.9" />
</ItemGroup>
```

The different packages and how they are used is explained here:
https://github.com/danielpalme/ReportGenerator#install-the-package-matching-your-platform-and-needs
