### ISSUE TITLE
XML report contains very long filenames

### ISSUE THREAD

**Issue by JanDevOps** [danielpalme/ReportGenerator#268]
Hi,

We are facing the issue that the generated filenames in the XML report produced by ReportGenerator are very long. This results in errors during processing of the XML report further in our pipeline by third-party tools (Tiobe Tics).

The cause of the problems is the maximum path length restriction on Windows of 260 characters, see for details:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

In our case, the long filename produced by ReportGenerator (for some classes with very long namespaces) combined with the report location used by the third party processing tool exceeds this 260 characters limit.

To resolve this I was wondering if ReportGenerator can provide an option to influence/limit the generated filenames.
I see it now generates filenames according to pattern: `<namespace>_<fully qualified class name>`
Just having the fully qualified class name would be good enough for us and resolve our issue.

Thanks,
Jan

**Comment by danielpalme** [comment]
I will look into that within the next 1-2 weeks

**Comment by danielpalme** [comment]
New release should produce shorter filenames:
https://www.nuget.org/packages/ReportGenerator/4.2.11

**Comment by JanDevOps** [comment]
Hi Daniel,

This solves our problem, filenames are now well within Windows limits.
Thanks for your solution!

Thanks, Jan
