### ISSUE TITLE
File Globbing - Files Parsed Multiple Times?

### ISSUE THREAD

**Issue by abbotware** [danielpalme/ReportGenerator#271]
it seems that if a file matches multiple patterns, it is parsed multiple times?

`"-reports:$TestResultsPath/*win-x64*coverage.xml;$TestResultsPath/*coverage.xml"`  (see below for explanation)

I only have 4 files.. but the summary says 6 files:

`MultiReportParser (6x CoberturaParser)`

using 4.2.12.0

I can't tell if it parsed it twice(thus inflating the hit counts), or if it is just a bug and the 6x number is wrong.   

You may wonder why I have that command line argument like that.  Well it turns out that if I don't 'trick' the report generator into parsing the windows files first, it might use the linux files and it won't be able to find any source since the file system doesn't match.

My build pipeline is such that I have linux and windows machines running different suites of tests with coverage.  I ship the coverage output for final report (a windows machine) to be build using all the outputs.

**Comment by danielpalme** [comment]
Could you please try again with release [4.2.13](https://www.nuget.org/packages/ReportGenerator/4.2.13)

**Comment by abbotware** [comment]
Yes, the x6 became 4x now.

I saw your commit / changes (Admittedly I don't know the code base) but I did notice a List ->  HashSet.  If that drives the file processing order, will the behavior/order be different now since it is based on hash of the file names instead insert order? I am just wondering If I lucky that the hashes are in the order I need.

Also, I am curious If my approach of specifying the window files first as an 'anchor' is the correct way to merge files from different file systems?

**Comment by abbotware** [comment]
See the PR i opened - If I understand the code correctly, it should keep the files ordered and removed duplicates

**Comment by danielpalme** [comment]
> Also, I am curious If my approach of specifying the window files first as an 'anchor' is the correct way to merge files from different file systems?

Your approach is correct.

New release [4.2.14](https://www.nuget.org/packages/ReportGenerator/4.2.14) also prevents the order.
