### ISSUE TITLE
Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by alclonky** [danielpalme/ReportGenerator#273]
if a line has an hit count > int, the reportgeneration fails with:

Initiating parser for LCov
Error during reading report 'lcov.info' (Size: 50.7MB): Value was either too large or too small for an Int32.

can you change that to long?  https://github.com/danielpalme/ReportGenerator/blob/9a9a0cc7a2d359906f82e918f92bb21e70afd91c/src/ReportGenerator.Core/Parser/LCovParser.cs#L148

**Comment by danielpalme** [comment]
I will take a look.

**Comment by danielpalme** [comment]
Please try again with new release: https://www.nuget.org/packages/ReportGenerator/4.2.15

**Comment by alclonky** [comment]
works for me
thank you!
