### ISSUE TITLE
Provide a way to just display the results (do not calculate)

### ISSUE THREAD

**Issue by themperek** [danielpalme/ReportGenerator#274]
I would like to "misuses" ReportGenerator to also visualize functional coverage but in order to do this one would need a way to just display values from XML file. Calculation based on line numbers will not work here.

**Comment by danielpalme** [comment]
Can you elaborate on that?
**What** data do you want to visualize in **what** way?

**Comment by themperek** [comment]
It is coverage data (functional coverage[1] used in hardware design) but not line coverage. I can generate Cobertura xml file [2] and put coverage numbers so we can generate nice HTML reports with ReportGenerator (even if the naming, not really matches). But it seems like ReportGenerator always recalculates the values not only takes them from the file (this will not work in our case).

[1] http://www.asic-world.com/systemverilog/coverage1.html
[2] https://github.com/mciepluc/cocotb-coverage

**Comment by danielpalme** [comment]
Can you share one of the Cobertura files and a sample HTML report?
A screenshot/drawing with expected results would also be helpful.

danielpalme82@gmail.com

**Comment by danielpalme** [comment]
I'm closing this for now.
Feel free to reopen if you can supply further information.

**Comment by themperek** [comment]
Will provide the examples just are full of work at the moment.
