### ISSUE TITLE
Interactive InlineHtml in Azure devops pipeline

### ISSUE THREAD

**Issue by fs99erab** [danielpalme/ReportGenerator#275]
Hi,
I am using your Azure task to create code coverage in Azure devops pipeline.
Is it possible to make the html more interactive? i.e sorting on coverage or grouping on namespaces?

**Comment by danielpalme** [comment]
If you download the report files and open them in your browser, the report is active.
Unfortunately Azure DevOps blocks all JavaScript and the reports become static.

**Comment by fs99erab** [comment]
Ah, I see. Too bad...
Thanks for a create tool!

**Comment by fs99erab** [comment]
I can't seem to get the grouping by namespace to work.
Everything is grouped under - (a dash). Does it sound familiar?

**Comment by danielpalme** [comment]
No that doesn't sound familiar.
Can you please share your coverage file (Cobertura, OpenCover, etc)?

You can send it by email: danielpalme82@gmail.com
