### ISSUE TITLE
Allow browsing covered code more easily

### ISSUE THREAD

**Issue by dotnetjunkie** [danielpalme/ReportGenerator#28]
Hi Daniel,

We just switched to OpenCover and ReportGenerator with Simple Injector. A really nice combination and I love how nicely the coverage reports look.

What I'm missing though is a way to navigate really quickly through classes and jump directly to methods that are not (fully) covered. In a sense, what I'm missing who the old NCover v3 interface worked, as shown below:

![Old NCover interface](https://www.ncover.com/support/docs/v3/assets/nce_documentation_mainwindow.PNG)

The most important part that this UI has (what I'm missing with ReportGenerator) is that:

 - The left panel [5] of the screen has a list with 'elements' that can be clicked, and are shown in the right panel [7].
 - The left panel shows an hierarchical view of classes (with a coverage percentage) and per class its methods with their coverage.

I would really love to see a report type added that would mimic this behavior.

**Comment by danielpalme** [comment]
Hi Steven,

thanks for your suggestion. I will have a look at that.
But it will probably take a while, since I'm quite busy at the moment.

**Comment by danielpalme** [comment]
@dotnetjunkie 
The class view now contains a list of all methods and properties for a quick navigation

The new feature is available in this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.0-beta4

**Comment by dotnetjunkie** [comment]
It took some time for me to be able to try it out, but I have to say this is truly awesome. Thanks for all the hard work you're taking into this. Your work makes it much easier for me to improve Simple Injector.
