### ISSUE TITLE
ReportGenerator shows incorrect accent names in  coverage report

### ISSUE THREAD

**Issue by vagisha-nidhi** [danielpalme/ReportGenerator#281]
This is related to this issue: https://developercommunity.visualstudio.com/content/problem/717340/code-coverage-tab-doesnt-show-corrrect-accents-in.html
The html report generated by report generator does't show correct accent names if accents are present in class name.
I have generated the coverage report and the .coverage file reports correct class names. Adding some screenshots for the same.

![image](https://user-images.githubusercontent.com/13175100/64848693-70747c80-d62f-11e9-8cac-178c59898420.png)
![image](https://user-images.githubusercontent.com/13175100/64848730-82eeb600-d62f-11e9-9d49-8d8442c196c9.png)

However, the html report generated doesn't display correct data.

![image](https://user-images.githubusercontent.com/13175100/64848826-b598ae80-d62f-11e9-93bd-0a9ec59b0e5d.png)

**Comment by danielpalme** [comment]
Probably an encoding issue.
I just published a new release (version 4.2.20) which tries to detect the encoding.

Could you please try again?
