### ISSUE TITLE
Run dotnet reportgenerator in a solution with many test project files

### ISSUE THREAD

**Issue by RuiCostafrg** [danielpalme/ReportGenerator#282]
Hi, i want to know if it is possible to run the `dotnet reportgenerator` command in a solution that have more than one test projects.
For example, i am able to run the `dotnet test` at the solution directory however if i want the generate the report of all the test projects i need to go inside of the test project individually and generate all the reports one by one using the `dotnet reportgenerator` command. There is some way that i can do this at the solution level?
Thank you

**Comment by danielpalme** [comment]
I would suggest you generate one single report when all tests where executed.
I don't know which coverage tool you are using, but they all generate XML files.
So when your tests got executed you typically have one or more XML files.

Then the last thing to do, is to run ReportGenerator once and pass all the XML files.
Samples:
```
dotnet reportgenerator -reports:file1.xml;file2.xml -targetdir:coverage
dotnet reportgenerator -reports:file*.xml -targetdir:coverage
dotnet reportgenerator -reports:Test*/coverage.xml -targetdir:coverage
```
