### ISSUE TITLE
Suggestion: Logging => Verbosity: Verbose

### ISSUE THREAD

**Issue by ramonduraes** [danielpalme/ReportGenerator#283]
I would suggest showing the full path of where he is seeking the coberturafile.

**Arguments**
 -reports:**Reports/Output/coverage.cobertura.xml**
 -targetdir:Reports/Output
 -reporttypes:HTML;HTMLSummary
 -verbosity:Verbose

>>
I had a bug in path and it was very hard to find because I couldn't see the path that reportgenrator was actually using

**Comment by danielpalme** [comment]
I made some changes to the logging. In your case the output should look like this:

```
Arguments
-reports:Reports/Output/coverage.cobertura.xml
-targetdir:Reports/Output
-reporttypes:HTML;HTMLSummary
-verbosity:Verbose
Executable:C:\SomeDirectory\ReportGenerator.Core.dll
Working directory: C:\SomeDirectory
The report file 'Reports/Output/coverage.cobertura.xml' is invalid. File does not exist (Full path: 'C:\SomeDirectory\Reports\Output\coverage.cobertura.xml').
```

You can test with the following packages:
https://www.nuget.org/packages/ReportGenerator/4.3.0-rc3
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.3.0-rc3

If you are using the Azure DevOps task: I will publish the changes within the next days.
