### ISSUE TITLE
Convert .coverage to .lcov file

### ISSUE THREAD

**Issue by tapika** [danielpalme/ReportGenerator#285]
In Visual Studio code there exists extension called Coverage Gutters:
https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters

That extension is targeted to display code coverage information, based on .lcov file format.
(Target programming languages are: Java, Javascript and so on).

Meanwhile C++ is not supported there, even thus you could use vstest.console.exe from Visual studio to execute the test, and produce .coverage file.

To my best understanding ReportGenerator is already capable of parsing .coverage files, and it has also knowledge of lcov.info, since it's parsing them as well.

How complex would it be to perform conversion from .coverage to lcov.info ?

**Comment by danielpalme** [comment]
Genrerating _lcov.info_ files is pretty easy. The format is very simple.

_*.coverage_ files are currently not supported. You have to convert them to XML first. See:
https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools

Should I add support for _lcov.info_ as an output format?

**Comment by danielpalme** [comment]
I just added support for lcov output format.

You can try the following packages:
https://www.nuget.org/packages/ReportGenerator/4.3.0-rc4
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.3.0-rc4

Please use the following command line parameter:
-reporttypes:lcov

**Comment by tapika** [comment]
![image](https://user-images.githubusercontent.com/3228645/65883202-3b8e5680-e39f-11e9-8dbf-db136fe5986b.png)

Wow !  It does work. On left side - Visual studio, on right side - Visual Studio code.

Thanks, need to test it bit more.

**Comment by tapika** [comment]
Is still works on line by line basis, not by scope - but I think it's limitation of visual studio itself.

**Comment by tapika** [comment]
Microsoft has similar requirement:
https://developercommunity.visualstudio.com/idea/365850/support-lcov-file-format-for-code-coverage.html

But not sure when it will be available.

**Comment by danielpalme** [comment]
I'm closing this issue. Feel free to reopen if you need further changes.
