### ISSUE TITLE
v4.3.0 fails without .net core 3 installed

### ISSUE THREAD

**Issue by pmeijer** [danielpalme/ReportGenerator#286]
Was using ReportGenerator without a specified version and got this error this morning:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Fixating the version to the previous release, `#tool nuget:?package=ReportGenerator&version=4.2.20`,  fixes my problem and I suspect the error is related to #205 (although I haven't performed any deeper investigation).

Thanks!

**Comment by danielpalme** [comment]
The [package](https://www.nuget.org/packages/ReportGenerator/4.3.0) contains several versions:
```
tools\net47\ReportGenerator.exe
tools\netcoreapp2.0\ReportGenerator.dll
tools\netcoreapp2.1\ReportGenerator.dll
tools\netcoreapp3.0\ReportGenerator.dll
tools\netcoreapp3.0\ReportGenerator.exe
```

If you use `dotnet $(UserProfile)\.nuget\packages\reportgenerator\4.3.0\tools\netcoreapp2.0\ReportGenerator.dll` you should be able to use _ReportGenerator_ without .NET Core 3.0

**Comment by aaronasmith** [comment]
This caused my cake build scripts to start failing, but I guess that's my fault for not specifying a version.

**Comment by aaronasmith** [comment]
I don't think this is an issue with this repo.  It appears to be how cake selects the executable when executing the report generator.
