### ISSUE TITLE
MUnit Coverage Support in Report Generator

### ISSUE THREAD

**Issue by cdayne** [danielpalme/ReportGenerator#287]
I'm currently building a CI pipeline in Azure DevOps for a Mule project and code coverage is available from a plugin for Maven that outputs in JSON (see https://docs.mulesoft.com/munit/2.2/munit-coverage-report). Would it be possible to support this for conversion to Cobertura?

**Comment by danielpalme** [comment]
I guess that's not possible. The [sample report](https://docs.mulesoft.com/munit/2.2/munit-coverage-report) does not contain enough details (e.g. coverage status of each line) to gather enough information for conversion into Coberatura format.

**Comment by shinaly** [comment]
I'm facing the same issue. 
Can anyone suggest on the same please.
