### ISSUE TITLE
dotnet-reportgenerator-cli 4.3.0 fails without 2.1 SDK installed

### ISSUE THREAD

**Issue by seesharper** [danielpalme/ReportGenerator#288]
Hi Daniel and thanks for this great projects. 

Just wanted to let you know that the `dotnet-reportgenerator-cli` fails when you only have the 3.0 sdk installed. 

You can see the error here https://github.com/seesharper/LightInject.Microsoft.Hosting/commit/8db0375a0cfe5bf61523775344b0432f6525263d/checks?check_suite_id=247696092#step:5:68

This tool should maybe target `netcoreapp2.1` and `netcoreapp3.0` ?

https://github.com/danielpalme/ReportGenerator/blob/57b12cb92f245c0b085bf10f4e1054fda4d9854a/src/ReportGenerator.DotnetCliTool/ReportGenerator.DotnetCliTool.csproj#L5

Will you be accepting a PR ?

**Comment by danielpalme** [comment]
DotNetCliTool seem to be no longer supported:
https://github.com/dotnet/cli/issues/11111#issuecomment-482274805
https://github.com/dotnet/announcements/issues/107

But you can use the [global tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/) or the "regular" [Nuget package](https://www.nuget.org/packages/ReportGenerator).

**Comment by seesharper** [comment]
Ah, damn it. I forgot all about local tools being deprecated. 
Thanks for your quick response as always 👍

**Comment by seesharper** [comment]
@danielpalme I ended up using ReportGenerator.Core directly since this is executed from a C# script. 
Kudos for making it so simple to integrate. Great work!!!!
