### ISSUE TITLE
'Source directories'  parameter is not working

### ISSUE THREAD

**Issue by anshii03** [danielpalme/ReportGenerator#290]
'Source Directories' is not working while trying to generate report .

This is project repository : https://dev.azure.com/anagarw/abc/_git/coveragetest
After building code and generating cobertura.xml, we moved our source files to srcx folder.

Now when we try to generate report using report generator , it is not able to find source files.

![image](https://user-images.githubusercontent.com/9054199/67200168-aa038900-f420-11e9-8b9c-799c832d3f59.png)

Is there anything we can do?

**Comment by danielpalme** [comment]
The parameter `Source Directories` is not intended to fix invalid file paths.

Fixing the paths can be accomplished by preprocessing the coverage files with a Powershell script.

Example:
```powershell
(gc "cobertura.xml") | % { $_ -replace "E:\jesttest\src", "E:\jesttest\srcx" } | Out-File "cobertura.xml" -Encoding UTF8
```

**Comment by danielpalme** [comment]
Could you please try again with release 4.3.2 (should be available in a few minutes)?!

**Comment by anshii03** [comment]
Thanks @danielpalme . It worked.
