### ISSUE TITLE
ReportGenerator cannot parse numbers with exponent in Cobertura report

### ISSUE THREAD

**Issue by Galad** [danielpalme/ReportGenerator#291]
I have a Cobertura report that cannot be parsed by ReportGenerator. It returns the error

>  Error during reading report 'C:\Users\galad\Downloads\NunitCoverage (1)\NunitCoverage\Cobertura.xml' (Size: 117,9MB): Input string was not in a correct format.

I run it in debug and found that a number value contains an exponent: `branch-rate="8.48608282416836E-05"`

Changing the line https://github.com/danielpalme/ReportGenerator/blob/fce0a24b39e759fabb55851976194fe27964087c/src/ReportGenerator.Core/Parser/CoberturaParser.cs#L284

With 

     value = Math.Round(100 * decimal.Parse(branchRate.Value, NumberStyles.Number | NumberStyles.AllowExponent, CultureInfo.InvariantCulture), 2, MidpointRounding.AwayFromZero);

Fixes the issue.

**Comment by danielpalme** [comment]
Thanks for reporting. New release should be available within a few minutes.

**Comment by Galad** [comment]
So fast, I was going to submit a pull request :)
Thanks !
