### ISSUE TITLE
Report Generator does not show up as installed extension after import

### ISSUE THREAD

**Issue by dilandau2001** [danielpalme/ReportGenerator#293]
VSTS: Azure Devops Server On Premise, Update 1 RC2.
Task Version: It happened with 4.3.3 and also happening with 4.3.5

I have just installed report Generator task using Vsts market.

If I browse local extension I can see it is available:

![image](https://user-images.githubusercontent.com/12834469/68013054-294c5480-fc8c-11e9-83e2-531fb20649bd.png)

But then this extension does not show up in the settings extensions, neither installed or requested:

![image](https://user-images.githubusercontent.com/12834469/68013772-12a6fd00-fc8e-11e9-86b1-912e293004d2.png)

And also there is no task available at build definition to use it. 
I have wait 2 days but the task does not show up, neither after TFS servers restart.

Not sure what else to try or verify

**Comment by danielpalme** [comment]
I don't have a local _DevOps Server_ available.
In _Azure Devops_ the extensions shows up after installation:

![image](https://user-images.githubusercontent.com/859606/68018993-d037ed00-fc9a-11e9-8209-8faeb33307d4.png)

When I setup a new pipeline, the extension is selectable:
![image](https://user-images.githubusercontent.com/859606/68018856-79321800-fc9a-11e9-835d-8e7d50028b50.png)

**Comment by dilandau2001** [comment]
Is there anything I can review, debug, check?
Or any other place where to request help from?

**Comment by dilandau2001** [comment]
Sorry I forgot an additional step to "install" it in a specific project. 
You can close this.
