### ISSUE TITLE
Bug in conversion from format Cobertura to Html for partial classes

### ISSUE THREAD

**Issue by lifemanship** [danielpalme/ReportGenerator#294]
There is issue when we convert `Cobertura` XML to `HTML`
When we generate report for partial classes Generator merges all coverage to the first part of partial classes.

**Comment by danielpalme** [comment]
That's the intended behavior.
Coverage is grouped by class and not by file.
Therefore a partial class is handled as a single element and shows all corresponding files.

**Comment by lifemanship** [comment]
I prepared simple test solution which will show difference between code coverage in html format after conversion from `Cobertura` and `OpenCover` formats.
[TestCoveragePartialClasses.zip](https://github.com/danielpalme/ReportGenerator/files/3809936/TestCoveragePartialClasses.zip)

The Coverage.zip contains: 
[Coverage.zip](https://github.com/danielpalme/ReportGenerator/files/3810024/Coverage.zip)

- UnitTests.xml\Cobertura.UnitTests.TestCoveragePartialClasses.results.xml - coverage created by dotnet with options `dotnet test TestCoveragePartialClasses.sln --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura`

- UnitTests.xml\OpenCover.UnitTests.TestCoveragePartialClasses.results.xml - coverage created by dotnet with options `dotnet test TestCoveragePartialClasses.sln --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover`

 - folder cobertura.html - report converted from `Cobertura.UnitTests.TestCoveragePartialClasses.results.xml` by ReportGenerator.exe with option `-reporttypes:Html`

 - folder opencover.html -report converted from `OpenCover.UnitTests.TestCoveragePartialClasses.results.xml` by ReportGenerator.exe with option `-reporttypes:Html` 

As you can see the `Html` report converted from `OpenCover.UnitTests.TestCoveragePartialClasses.results.xml` contains valid coverage
![image](https://user-images.githubusercontent.com/6093708/68225184-17a6dc00-0001-11ea-94cc-bf93ddda48b5.png)

While the `Html` report converted from `Cobertura.UnitTests.TestCoveragePartialClasses.results.xml` contains merged coverage(which is invalid):
![image](https://user-images.githubusercontent.com/6093708/68225495-913eca00-0001-11ea-8225-d4d799b65618.png)

**Comment by danielpalme** [comment]
Thanks for providing a minimal sample. Now I have understood the problem.

It's already fixed. A new release (4.3.6) should be available within the next 30 minutes.
