### ISSUE TITLE
cannot install into a v3.0 app

### ISSUE THREAD

**Issue by aday12345** [danielpalme/ReportGenerator#295]
I tried to install dotnet-reportgenerator-cli but get the following error:

- Package 'dotnet-reportgenerator-cli 4.3.6' has a package type 'DotnetCliTool' that is not 
  supported by project

I then tried to install dotnet-reportgenerator-globaltool and got these errors:

- Package dotnet-reportgenerator-globaltool 4.3.6 is not compatible with netcoreapp3.0 
  (.NETCoreApp,Version=v3.0). Package dotnet-reportgenerator-globaltool 4.3.6 supports:
           - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
          - netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any	

- Package 'dotnet-reportgenerator-globaltool 4.3.6' has a package type 'DotnetTool' that is not 
  supported by project 			
 
- Invalid project-package combination for dotnet-reportgenerator-globaltool 4.3.6. 
  DotnetToolReference project style can only contain references of the DotnetTool type

**Comment by danielpalme** [comment]
`DotnetCliTool`s are no longer supported in .NET Core 3.0.
So using the global tool is a good choice.

Installation:
```bat
dotnet tool install -g dotnet-reportgenerator-globaltool
```

Execution:
```bat
reportgenerator [options]
```

What's the output when you execute ` dotnet --info`?

**Comment by aday12345** [comment]
it is kind of strange but when I trued to install via PMC is looks to have installed it and if I try to install it again it says that it is installed.

but the nuget package manager does not show it as installed and if i try to install it from there I get the 3 errors mentioned above.

PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.13 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

**Comment by danielpalme** [comment]
Global tools are not managed by PMC.

You have to use the commands on the command line (see my first comment)

**Comment by aday12345** [comment]
ok, i got it, thanks
now I just need to get jenkins to run it.

Thanks for your help
