### ISSUE TITLE
Odd coverage reporting of compiler generated code with respect to class lexical scope

### ISSUE THREAD

**Issue by SteveGilham** [danielpalme/ReportGenerator#297]
I just spotted this unusual looking behaviour and wanted to at least get it on the record, even if the result is a "not worth fixing".

This coverage file [coverage.opencover.xml.zip](https://github.com/danielpalme/ReportGenerator/files/3893796/coverage.opencover.xml.zip) contains a class `AltCover.StaticFilter` that has a compiler generated member.  When an HTML report is generated, some of the code associated with a lexically separate class (but actually belonging to a third, system generated, type) is shown in the HTML report here [AltCover_StaticFilter.zip](https://github.com/danielpalme/ReportGenerator/files/3893804/AltCover_StaticFilter.zip).

I assume that the autogenerated types `<StartupCode$AltCover>.$Filter/get_Apply@48` and  `<StartupCode$AltCover>.$Filter/get_Apply@49-1` have been assigned to the lexically nearest type with some code location, rather than being exposed in all their weirdness to the unsuspecting consumer; but in this case, the end result does appear rather counter-intuitive.

**Comment by danielpalme** [comment]
I've tried to find a solution to fix this special case.
There is no good way to determine that the found class is not correct for the compiler generated class. Matching the name would work here, but would break other cases in my test suite.

I'm closing this for now.
