### ISSUE TITLE
Merged Reports from Linux / WIndows don't show 100% coverage

### ISSUE THREAD

**Issue by abbotware** [danielpalme/ReportGenerator#299]
When merging reports run on windows and linux the file paths are rooted differently so the report is wrong... however, I manually adjust the input files by changing the file paths in the input xmls so they will line up and match.

- the main report says 100% code / 50% branch - but the drill down says 100% for both
- the branch covered icon has the green / red indicator meaning that a branch was not covered

I use coverlet to produce reports in cobtura and this is related:
https://github.com/tonerdo/coverlet/issues/649

**Update:** I can't seem to reproduce the line coverage mismatch - I suspect my reports were bad, but now the only issue is with branch coverage

**Comment by danielpalme** [comment]
Can you please share your coverage xml files?
You can send them by email: danielpalme82@gmail.com

**Comment by abbotware** [comment]
I sent you the input files and mentioned a small subset were the issue is easily visible.   I think the branches are being counted twice and that is why the numbers are off.

**Comment by danielpalme** [comment]
Will have look within the next days.

**Comment by abbotware** [comment]
based on your analysis - I think this is not an issue
