### ISSUE TITLE
GitlabCI CodeQuality format support

### ISSUE THREAD

**Issue by jfaixo** [danielpalme/ReportGenerator#301]
It would be nice to have a supported output format for the [GitlabCI CodeQuality format](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool).

**Comment by danielpalme** [comment]
ReportGenerator is about _code coverage_ not so much about _code quality_.
I'm not sure how ReportGenerator should tell anything about coding issues.
