### ISSUE TITLE
settings:cachingDuringOfRemoteFilesInMinutes

### ISSUE THREAD

**Issue by aschlicht** [danielpalme/ReportGenerator#302]
I think there is a typo in the setting named `cachingDuringOfRemoteFilesInMinutes`. I think `During` should be `Duration`. I searched all issues and didn't see this mentioned anywhere else. If you agree, maybe change to `Duration` and support `During` for backward compatibility?

**Comment by danielpalme** [comment]
You are right.
I've fixed the spelling in v4.3.9.
The old setting is still working for backward compatibility.
