### ISSUE TITLE
Support JSONSummary output

### ISSUE THREAD

**Issue by rosenbjerg** [danielpalme/ReportGenerator#304]
Exactly the same as XMLSummary, but as JSON

**Comment by danielpalme** [comment]
Will add this in the next release.

**Comment by rosenbjerg** [comment]
Great to hear :)

**Comment by danielpalme** [comment]
Release [v4.4.0](https://www.nuget.org/packages/ReportGenerator/4.4.0) contains the new output format _JSONSummary_

**Comment by rosenbjerg** [comment]
Cool, thanks 👍
