### ISSUE TITLE
Passing command-line arguments to plugin

### ISSUE THREAD

**Issue by pantosha** [danielpalme/ReportGenerator#305]
I'm writing a plugin for ReportGenerator. What is the recommended way to pass custom command-line arguments to the plugin?

Just for information. I want to reimplement [BitBucket code coverage plugin](https://bitbucket.org/atlassian/bitbucket-code-coverage/src/master/code-coverage-maven-plugin/) in C#.

**Comment by danielpalme** [comment]
You can access the command line arguments with the following method:
```csharp
string[] args = Environment.GetCommandLineArgs()
```

Let me know when you need further help.  

Maybe your plugin is useful for other users as well? If that's the case I would consider adding it to _ReportGenerator_.

**Comment by pantosha** [comment]
Thank you for your answer! I will try to use your proposal.

> Maybe your plugin is useful for other users as well? If that's the case I would consider adding it to ReportGenerator.

I will be happy. The plugin is installed on 144 instances.
![image](https://user-images.githubusercontent.com/1799798/71484078-9bb85b80-281b-11ea-92fa-db3287ba8284.png)
https://marketplace.atlassian.com/apps/1218271/code-coverage-for-bitbucket-server
