### ISSUE TITLE
Command line arguments dumped to console at warning and error verbosity levels

### ISSUE THREAD

**Issue by sigmunau** [danielpalme/ReportGenerator#307]
When using -verbosity:Error I only expect to get any output if something goes wrong, but reportgenerator still outputs a list of all received arguments. I would not expecct that sort of output at any level lower than Verbose

**Comment by danielpalme** [comment]
You are right. Those messages are only hidden with with verbosity _Off_.  
But they are pretty helpful (for me) if anything goes wrong and users are able to evaluate those settings without executing again with changed verbosity level.

**Comment by ViktorHofer** [comment]
I agree with @sigmunau here. Logging CLI invocations shouldn't be part of the various tools but of the CLI engine, ie cmd or bash.

**Comment by danielpalme** [comment]
Fixed in release [4.4.6](https://www.nuget.org/packages/ReportGenerator/4.4.6)
