### ISSUE TITLE
0 of 2 branches covered despite unit tests covering the two scenarios

### ISSUE THREAD

**Issue by Jericho** [danielpalme/ReportGenerator#308]
I use OpenCover version 4.7.922 to generate `coverage.xml` and I use ReportGenerator version 4.4.0 to convert the XML file into a HTML report but something seems odd in the generated report. 

Here's an extension method I wrote to illustrate the situation:
```csharp
public static string Foo(this string target)
{
    if (target == null) throw new ArgumentNullException(nameof(target));
    return "Hello World!";
}
```
As you can see, either an exception is thrown when the `target` parameter is null or a string value is returned when the parameter is not null. I wrote the following two unit tests to validate these two scenarios:

```csharp
public class StringExtensionsTests
{
    public class Foo
    {
        [Fact]
        public void Throws_if_target_is_null()
        {
            var target = (string)null;
            Should.Throw<ArgumentNullException>(() => target.Foo());
        }

        [Fact]
        public void Returns_expected_string_if_target_is_not_null()
        {
            var target = "foo";
            var expected = "Hello World!";

            var result = target.Foo();

            result.ShouldBe(expected);
        }
    }
}
```

Here's what OpenCover generates:
```xml
<Method visited="true" cyclomaticComplexity="2" nPathComplexity="2" sequenceCoverage="100" branchCoverage="100" crapScore="2" isConstructor="false" isStatic="true" isGetter="false" isSetter="false">
  <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="3" visitedBranchPoints="3" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
  <MetadataToken>100663297</MetadataToken>
  <Name>System.String Picton.StringExtensions::Foo(System.String)</Name>
  <FileRef uid="5" />
  <SequencePoints>
    <SequencePoint vc="2" uspid="11" ordinal="0" offset="0" sl="14" sc="4" el="14" ec="23" bec="2" bev="2" fileid="5" />
    <SequencePoint vc="1" uspid="12" ordinal="1" offset="3" sl="14" sc="24" el="14" ec="72" bec="0" bev="0" fileid="5" />
    <SequencePoint vc="1" uspid="13" ordinal="2" offset="14" sl="15" sc="4" el="15" ec="26" bec="0" bev="0" fileid="5" />
  </SequencePoints>
  <BranchPoints>
    <BranchPoint vc="1" uspid="14" ordinal="0" offset="1" sl="14" path="0" offsetend="3" fileid="5" />
    <BranchPoint vc="1" uspid="15" ordinal="1" offset="1" sl="14" path="1" offsetend="14" fileid="5" />
  </BranchPoints>
  <MethodPoint xsi:type="SequencePoint" vc="2" uspid="11" ordinal="0" offset="0" sl="14" sc="4" el="14" ec="23" bec="2" bev="2" fileid="5" />
</Method>
```

And here's a screenshot of the HTML report:
![image](https://user-images.githubusercontent.com/112710/72088482-3dd64a00-32d8-11ea-907d-20f2ea7655fe.png)

As you can see, the report said that there were 3 "visits" (which is odd since I only wrote 2 unit tests), and also it reports that 0 of the 2 branches are covered despite the fact that my unit tests are intended to cover the two scenarios.

I'm confused by these oddities. Can someone help me understand what's going on? By the way, I am not sure if I should have asked this question in the OpenCover repo.

I have also attached the whole [coverage.xml](https://github.com/danielpalme/ReportGenerator/files/4041743/coverage.xml.txt) file in case it can help make sense of this situation.

**Comment by danielpalme** [comment]
This looks really strange to me. The code and the coverage file do not match.
The `<BranchPoint />` elements point to line 14 in your file (attribute `sl="14"`), but the `if` statement is in line 16.

I guess you are passing the wrong coverage.xml file to _ReportGenerator_. Did you have an old version of the class `StringExtensions` where the if statement was in line 14?

When I generate the report it shows full branch coverage for line 14:
![image](https://user-images.githubusercontent.com/859606/72097024-ba3e4c80-331b-11ea-9f0d-55f185996918.png)

**Comment by Jericho** [comment]
ok, good point. Based on your feedback, I created a new empty project, created a new .net core project and a new xunit project, copied and pasted the code of my `Foo` extension method and the two unit tests and got the following result:

![image](https://user-images.githubusercontent.com/112710/72104283-1479e600-32f9-11ea-9c81-5dccf2c4a21d.png)

Good news is: it was able to recognize that I have tests covering all scenarios (it still reports 3 visits despite the fact that I only have 2 unit tests).

One thing just struck me: my original library multi-targets `net461`, `net472` and `netstandard2.0` and therefore my xunit project targets `net461`, `net472` and `netcoreapp3.1` in order to test my library code in all three frameworks. So I modified my new simplified project to also target the same three frameworks and as soon as I do that I observe the same problem:

![image](https://user-images.githubusercontent.com/112710/72104860-50fa1180-32fa-11ea-896b-2fc4e2fe6e65.png)

This leads me to conclude that the issue occurs when library project targets multiple frameworks and/or when the unit testing project targets multiple frameworks.

I uploaded my simplified project to GitHub in case it can help you reproduce. Please clone the following [repo](https://github.com/Jericho/WeirdCoverageRepro), and then from a Powershell prompt run `.\build --bootstrap` (one time only). From then on, you can execute `.\build -t coverage` to automatically clean previous artifacts, restore nuget packages, build, run unit tests, generate coverage xml, convert xml to html report and open the report in your default browser.

**Comment by danielpalme** [comment]
I don't know why OpenCover reports wrong branch coverage for net461 / net471.

ReportGenerator produces a correct report based on the coverage xml file.

I only can explain why you get 3 line visits:  
Tools like OpenCover don't track **line visits**, the track **statements visits / sequence points**.
Since you placed the  `if` statement and the `throw new ...` statements on the same line, those are added up to 3 line visits.

**Comment by Jericho** [comment]
Your explanation for the "3 visits" make sense. 

I will raise an issue in OpenCover's repo regarding the weird coverage report issue. Thanks for your help.
