### ISSUE TITLE
Converting OpenCover to Lcov missing branch coverage

### ISSUE THREAD

**Issue by Cjewett** [danielpalme/ReportGenerator#309]
When converting from OpenCover to Lcov the Lcov file is missing branch coverage. Also, the test name is only populated for the first file and ignored for the rest. 

Questions:
1.  Is there anything stopping Lcov from populating branch coverage if you're converting an OpenCover file which has branch coverage included?
2. Should we not be putting TN: at the beginning of every file for coverage? My knowledge on this subject comes from istanbul which populates it and leaves the value empty (like "TN:") and it's good because it lets the user know a new fragment or file for coverage has started.

**Comment by danielpalme** [comment]
Will have a look within the next days.

**Comment by danielpalme** [comment]
Regarding 1:
Latest release [4.4.1](https://www.nuget.org/packages/ReportGenerator/4.4.1) will also emit additional information, including branch coverage. The following elements are now available:

- FNDA
- FNF
- FNH
- BRDA
- BRF
- BRH

Regarding 2:
Every file starts with an `SF` element and end with `end_of_record`.
The `TN` element is intended for the overall test name and appears only once per file.
See: http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

**Comment by Cjewett** [comment]
@danielpalme  Thank you for adding this! 

Regarding 2: Understood. Not a huge deal so I'm okay to close this.
