### ISSUE TITLE
Shared folders in command line no loger working, since version 2.3.1.0.

### ISSUE THREAD

**Issue by marcelmunarolo** [danielpalme/ReportGenerator#31]
Dear Colleagues,

Since version 2.3.1.0, using shared folders in the command line (argument -reports), stoped to work.
Ex. ... "-reports:\\server\share\file.xml" ...
It works in versions 2.3.0.0 and below (tested since 2.1.8.0)

It would be great if we could have this feature working again.
Thanks and Cheers!
Marcel

**Comment by danielpalme** [comment]
I will look into this.

**Comment by danielpalme** [comment]
Could you please try again with new version 2.3.4.0:
https://www.nuget.org/packages/ReportGenerator/2.3.4

**Comment by marcelmunarolo** [comment]
Now, it works very well!
Thanks Daniel!
