### ISSUE TITLE
Unable to Fetch Remote Source on Windows

### ISSUE THREAD

**Issue by wsugarman** [danielpalme/ReportGenerator#310]
I am using Coverlet + SourceLink to generate cobertura code coverage reports for my .NET Standard project. The XML files are generated fine. They have classes like the following:

```xml
<class name="Foo.Bar" filename="https://raw.githubusercontent.com/wsugarman/Example/123456789ABCDEF/src/Example.Project/Foo/Bar.cs" ...>
    <!-- Code Coverage -->
</class>
```

However, when I go to generate my report with a command such as:
```bat
reportgenerator --reports:coverage.cobertura.xml -targetdir:reports -reporttypes:"Cobertura"
```

I see the below error:
> File 'https:\\\\raw.githubusercontent.com\\wsugarman\\Example\\123456789ABCDEF\\src\\Example.Project\\Foo\\Bar.cs' does not exist (any more).

It seems that all of the forward-slashes are converted to backslashes inappropriately, and the URL cannot be found! I took a look into the code to see what could be the problem, and I saw that in the [`CoberturaReportPreprocessor`](https://github.com/danielpalme/ReportGenerator/blob/b4cf5320acde4672978592627fa98805bb7f23b8/src/ReportGenerator.Core/Parser/Preprocessing/CoberturaReportPreprocessor.cs#L68), the `filename` attributes have their slashes normalized to [`Path.DirectorySeparatorChar`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=netframework-4.7). This prevents [CachingFileReader](https://github.com/danielpalme/ReportGenerator/blob/b4cf5320acde4672978592627fa98805bb7f23b8/src/ReportGenerator.Core/Parser/FileReading/CachingFileReader.cs#L55) from detecting that the file is remote.

Am I perhaps missing something when using SourceLink? Otherwise, I'd be happy to try my hand at a fix.

**Comment by danielpalme** [comment]
Correct. The preprocessor should ignore files that start with "http://" or "https://".
If you like, you can create a PR.

**Comment by danielpalme** [comment]
New release [4.4.2](https://www.nuget.org/packages/ReportGenerator/4.4.2) will fix this issue (should be available within a few minutes).

**Comment by wsugarman** [comment]
Oh! That’s great news! You beat me to it haha. I’ll give the new version a shot.

**Comment by wsugarman** [comment]
Looks like it's all good. Thank you for fixing it so quickly!
