### ISSUE TITLE
Lcov parser issue on real C++ projects

### ISSUE THREAD

**Issue by borisovandrey** [danielpalme/ReportGenerator#311]
If the C++ project is large it is possible that some logic is placed header files and this files are used from different source files.
As a result the coverage.info (lcov output) contains multiple "SN" entrances for the same header files.
Lcov parser doesn't recognize this situation and creates duplicates of the same class (file name) in assembly. 
This leads to two effects:
1. The html report contains duplicated entrances for such header files
2. History throws exception because of the key duplication.

The proposed changes could be:

                    var @class = new Class(fileName, assembly);

                    this.ProcessClass(@class, fileName, lines, ref i);

                    var exClass = assembly.Classes.FistOrDefault( cl => cl.Name == fileName );
                    if(exClass != nulptr)
                    {
                        exClass.Merge(@class);
                    }
                    else
                    {
                        assembly.AddClass(@class);
                    }                    

At  private void ProcessAssembly(Assembly assembly, string[] lines)

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
I will fix this within the next days.

**Comment by danielpalme** [comment]
New release [4.4.3](https://www.nuget.org/packages/ReportGenerator/4.4.3) fixes this issue.
