### ISSUE TITLE
Badge Modifications

### ISSUE THREAD

**Issue by RichieRunner** [danielpalme/ReportGenerator#312]
Can we extend the badge generation functionality to generate different some different stylings? I'm looking for something more simple like what [shields.io](https://shields.io/category/coverage) has.

**Comment by danielpalme** [comment]
I will consider adding some more badges.

**Comment by RichieRunner** [comment]
Thanks for the consideration. On a slightly related note, how come there isn't a generated badge for 'method'? I only see one for line and branch, but none for method

![image](https://user-images.githubusercontent.com/20289967/72654994-fb031a80-3946-11ea-8d3b-4fa5967aebb1.png)

**Comment by danielpalme** [comment]
Method coverage is currently not evaluated by ReportGenerator.

Release [4.4.4](https://www.nuget.org/packages/ReportGenerator/4.4.4) now contains additional badges in Shields IO style.

The following badges are now available:
- badge_shieldsio_branchcoverage_blue.svg
- badge_shieldsio_branchcoverage_brightgreen.svg
- badge_shieldsio_branchcoverage_green.svg
- badge_shieldsio_branchcoverage_lightgrey.svg
- badge_shieldsio_branchcoverage_orange.svg
- badge_shieldsio_branchcoverage_red.svg
- badge_shieldsio_branchcoverage_yellow.svg
- badge_shieldsio_branchcoverage_yellowgreen.svg
- badge_shieldsio_linecoverage_blue.svg
- badge_shieldsio_linecoverage_brightgreen.svg
- badge_shieldsio_linecoverage_green.svg
- badge_shieldsio_linecoverage_lightgrey.svg
- badge_shieldsio_linecoverage_orange.svg
- badge_shieldsio_linecoverage_red.svg
- badge_shieldsio_linecoverage_yellow.svg
- badge_shieldsio_linecoverage_yellowgreen.svg

See sample reports:
https://danielpalme.github.io/ReportGenerator/resources/SampleReports.zip
