### ISSUE TITLE
Running ReportGenerator global tool on Gitlab runner is broken - v 4.4.4

### ISSUE THREAD

**Issue by vraravam** [danielpalme/ReportGenerator#313]
I'm setting up a dotnetcore 3.1.1 codebase, and trying to incorporate the reportgenerator globaltool as part of the CI process. 
<img width="1061" alt="Screenshot 2020-01-20 at 4 05 06 PM" src="https://user-images.githubusercontent.com/69629/72719879-bc679d00-3b9e-11ea-9456-d84ad9afa1da.png">

But, even though the same shell script works on my local (mac os catalina), the command fails on CI. The command that I am running is:
```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/ && ./tools/reportgenerator '-reports:./api.test/TestResults/Coverage/coverage.cobertura.xml' '-targetdir:./api.test/TestResults/Coverage/Reports' -reportTypes:Html
```
(This is the content of the `test.sh` shell script)

**Comment by danielpalme** [comment]
I just tried it myself on Ubuntu.
First I installed the global tool:
```
dotnet tool install dotnet-reportgenerator-globaltool --tool-path ./tools
```

Then I was able to execute it:
```
./tools/reportgenerator ...
```

Is `reportgenerator` available in your `tools` directory?

**Comment by vraravam** [comment]
Yes - I have installed it in the `tools` directory, and committed it into the git repo as well (though I suspect that is unnecessary since I am also trying to install the tool as part of the CI process itself).

**Comment by danielpalme** [comment]
The error message "Exec format error" confuses me.
I will try to setup a Gitlab agent myself and try to reproduce this issue within the next days.

**Comment by jdodds** [comment]
This is an error that happens when you try to run a binary compiled for one architecture on another one, or when you try to run a 64bit executable on a 32bit system. 

This could be happening if the reportgenerator binary was committed, if so removing it and installing it as part of the CI process should fix it unless you're on a 32bit system and there are only 64bit binaries available.

**Comment by danielpalme** [comment]
@jdodds 
The error message "Exec format error" points in that direction.
But: The global is not compiled for a specific architecture. It should work everywhere.

**Comment by danielpalme** [comment]
I have not found enough time to setup an environment to reproduce the issue.
Is this still a problem?

**Comment by danielpalme** [comment]
First guess: Running `ReportGenerator.exe` will only work on Windows not on your Linux build agent.

Could you please try:

```
dotnet packages/reportgenerator/4.5.3/tools/netcoreapp3.0/ReportGenerator.dll -reports:"coverage-results/coverage.opencover.xml" -targetdir:"coverage-report" -reporttypes:HtmlSummary
```

**Comment by williammcainsh** [comment]
Same result.

**Comment by danielpalme** [comment]
I have to setup a Linux build agent myself. Which Linux OS are you using?
32 or 64 bit?

**Comment by williammcainsh** [comment]
I don't have direct access to the vm's, Is this any use?
Linux version 3.10.0-1062.18.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) )

**Comment by danielpalme** [comment]
I tried to reproduce this issue but it worked in my environment. I tried two setups:
- Ubuntu with `shell` executor
- Ubuntu with `docker` executor

I created the following setups:

## Ubuntu with `shell` executor
1. Installed Ubuntu 19.10 with latest updates
2. Installed .NET Core SDK 3.1 (see https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-1910)
3. Installed Gitlab Agent as a service (see https://docs.gitlab.com/runner/install/linux-manually.html)
4. Registered Gitlab Agent as `shell` executor (see https://docs.gitlab.com/runner/register/index.html#gnulinux)

### My `.gitlab-ci.yml`
```yaml
stages:
  - build

build_job:
  stage: build
  script:
    - dotnet tool restore
    - dotnet reportgenerator -reports:OpenCover.xml -targetdir:out
```

Full content of my repository: [shell.zip](https://github.com/danielpalme/ReportGenerator/files/4529945/shell.zip)


## Ubuntu with `docker` executor
1. Installed Ubuntu 19.10 with latest updates
2. Installed Docker (see https://docs.docker.com/engine/install/ubuntu/)
3. Installed Gitlab Agent as a service (see https://docs.gitlab.com/runner/install/linux-manually.html)
4. Registered Gitlab Agent as `docker` executor (see https://docs.gitlab.com/runner/register/index.html#gnulinux)

### My `.gitlab-ci.yml`
```yaml
image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build

build_job:
  stage: build
  script:
    - dotnet tool restore
    - dotnet reportgenerator -reports:OpenCover.xml -targetdir:out
```

Full content of my repository: [docker.zip](https://github.com/danielpalme/ReportGenerator/files/4529973/docker.zip)

**Comment by danielpalme** [comment]
Can anyone provide a complete list of steps, that are required to reproduce the issue (with or without Gitlab)?

E.g. 
- Install Ubuntu / CentOS / SuSe / etc (A link to the corresponding ISO would be perfect)
- Install global tool: `dotnet tool install dotnet-reportgenerator-globaltool --tool-path ./tools`
- Execute global tool: `./tools/reportgenerator ...`

**Comment by danielpalme** [comment]
I'm closing this issue for now. Please reopen if you can provide instructions how to reproduce the error.
