### ISSUE TITLE
Missing summary information for one or more source files in HTML report

### ISSUE THREAD

**Issue by johndaintree** [danielpalme/ReportGenerator#316]
The command line:

reportgenerator -reports:../coverage/lcov.info -targetdir:../coverage 

doesn't generate a summary line for the first file  listed in the lcov.info file (which is attached). Moving the relevant part of the file (that between SF: and end_of_record) to the end of the file, results in a different file being omitted. 

No .htm file is created for the missing source, nor is an entry created for it in index.htm.

[lcov.info.txt](https://github.com/danielpalme/ReportGenerator/files/4127922/lcov.info.txt)

**Comment by danielpalme** [comment]
I will fix this within the next days.

**Comment by johndaintree** [comment]
Very cool, Thank you.

**Comment by danielpalme** [comment]
Fixed in release [4.4.6](https://www.nuget.org/packages/ReportGenerator/4.4.6)
