### ISSUE TITLE
GitHub Actions Sample?

### ISSUE THREAD

**Issue by ardalis** [danielpalme/ReportGenerator#318]
Any plans to show how to get this working with GitHub Actions in your wiki Integrations section?

**Comment by danielpalme** [comment]
Good idea.
I have not yet tried to work with GitHub Actions.

Do you have any information?

**Comment by ardalis** [comment]
Not yet. Started looking for examples, found none, added this issue. :)

**Comment by danielpalme** [comment]
I created a sample project here: https://github.com/danielpalme/coveragesample
The relevant workflow is in this file: https://github.com/actions-rs/grcov/blob/master/.github/workflows/ci.yml

I use the following steps:
- Install .NET Core
- Install / Restore ReportGenerator as a global tool
- Run tests with code coverage
- Execute ReportGenerator
- Publish report as an artifact

I'm considering publishing a Marketplace tool for GitHub

**Comment by danielpalme** [comment]
I just published a Marketplace action:
https://github.com/marketplace/actions/reportgenerator

Usage in the workflow of the sample project from above:
https://github.com/danielpalme/coveragesample/blob/github-action/.github/workflows/ci.yml

**Comment by danielpalme** [comment]
Wiki is also up to date:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#github-actions
