### ISSUE TITLE
Question about sequenceCoverage, Line coverage and branchCoverage, branch coverage differences

### ISSUE THREAD

**Issue by draftsteve** [danielpalme/ReportGenerator#32]
Hey Daniel,

I'm reviewing a report from an OpenCover run and I'm wondering where some of the numbers come from. For example, I have one sequenceCoverage value in the OpenCover xml that's 47.17 and the Line coverage value in the ReportGenerator output is 41.6. I am assuming sequenceCoverage is Line coverage in the report. 

In the same class there's a branchCoverage value in the OpenCover xml of 52.94 and Branch coverage value in the ReportGenerator output is 60. 

The numbers are close, but not equal. I'm wondering how the numbers in ReportGenerator are calculated. Any chance you could shed a little light? Or point me to the class that does the math and I can figure it out?

ReportGenerator version: 2.3.2.0

Kind regards,
Steve

**Comment by ddur** [comment]
AFAIK and remember, when branch coverage is improved, original branch coverage calculated for method is left unchanged for legacy reasons. I believe correct values comes from ReportGenerator. 
Take look at your &lt;BranchPoints&gt; in report

**Comment by danielpalme** [comment]
This wiki page explains some metrics of ReportGenerator: https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details

I don't know the details of how OpenCover calculates its metrics, so I can't explain any differences.
But: _Line coverage_ is not the same as _Sequence coverage_. One sequence point can span several lines of code. So there might be a (little) difference.

**Comment by draftsteve** [comment]
@danielpalme Thank you. I'll go over these. 

@ddur I'm having trouble parsing what you're saying. What do I look for with the BranchPoints in the OpenCover output?

**Comment by ddur** [comment]
@draftsteve 
I mean, % of branch coverage should be number of visited &lt;branch point&gt;'s divided by number of all &lt;branch point&gt;'s, multiplied by 100

**Comment by danielpalme** [comment]
@ddur:
Coverage percentage totals are not averaged. For each level (assembly, class, file), the values are exact numbers are calculated.

**Comment by ddur** [comment]
@danielpalme Sorry, I said "probably" cause I'm not sure.
So you accumulate visited/unvisited numbers of &lt;SequencePoint&gt;'s & &lt;BranchPoint&gt;'s for each level up and then compute?

**Comment by danielpalme** [comment]
> So you accumulate visited/unvisited numbers of <SequencePoint>'s & <BranchPoint>'s for each level up and then compute?

Yes.
