### ISSUE TITLE
Teamcity Code Coverage Branch Statistics Reported as Block Statistics 

### ISSUE THREAD

**Issue by tmulkern** [danielpalme/ReportGenerator#320]
Branches stats should be reported with a PostFix of 'R' according to this https://www.jetbrains.com/help/teamcity/custom-chart.html#Default-Statistics-Values-Provided-by-TeamCity

Fix in this PR
https://github.com/danielpalme/ReportGenerator/pull/319

**Comment by danielpalme** [comment]
Thanks! Will release a new version within the next 1-2 days.

**Comment by danielpalme** [comment]
New release will be available in a few minutes:
https://www.nuget.org/packages/ReportGenerator/4.4.7
