### ISSUE TITLE
Miss-match between testrunner's coverage console output & generated HTML report

### ISSUE THREAD

**Issue by stoyandimov** [danielpalme/ReportGenerator#321]
I'm running report generator against a opencover report.

The console output:
```
+------------------------------+--------+--------+--------+
| Module                       | Line   | Branch | Method |
+------------------------------+--------+--------+--------+
| Unic.Services.AudioConverter | 59.25% | 64.7%  | 51.45% |
+------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 59.25% | 64.7%  | 51.45% |
+---------+--------+--------+--------+
| Average | 59.25% | 64.7%  | 51.45% |
+---------+--------+--------+--------+
```
## Expected behavior
ReportGenerator HTML report showing `Unic.Services.AudioConverter`:
* Line coverage: 59.2* %
* Branch coverage: 64.7* %

## Actual behavior
ReportGenerator HTML report shows `Unic.Services.AudioConverter`:
* Line coverage: 59.2 % (as expected)
* **Branch coverage: 68.2 % (not as expected)**

### Screenshots
Here is the script that runs the tests and generates the reports:
![image](https://user-images.githubusercontent.com/1770309/74139071-028aac00-4bf3-11ea-9197-e6ef96c94b1c.png)

Here is the console output.
![image](https://user-images.githubusercontent.com/1770309/74139213-44b3ed80-4bf3-11ea-9a8a-f727c4198a60.png)

Here is the generated report.
![image](https://user-images.githubusercontent.com/1770309/74138907-b3447b80-4bf2-11ea-9f03-d4b8bfdae11b.png)

Please, let me know if you need further information.

**Comment by danielpalme** [comment]
_ReportGenerator_ counts branches in the following way:

For each line: Get number of branches from XML
For each file file: Sum of all lines
For each class: Sum of all files
For each assembly: Sum of all classes
Total: Sum of all assemblies

Only "real" branches (<BranchPoint> in OpenCover XML) are taken into account.
OpenCover counts differently here, it counts one extra branch per method.

See also:
https://github.com/danielpalme/ReportGenerator/issues/236
https://github.com/danielpalme/ReportGenerator/issues/191

**Comment by stoyandimov** [comment]
Thanks for the explanation!
