### ISSUE TITLE
Support for Atlassian Bamboo (NCoverReportBuilder or CloverReportBuilder format)

### ISSUE THREAD

**Issue by GrayPockets** [danielpalme/ReportGenerator#323]
The Atlassian Bamboo build system only supports importing code coverage via NCover or Clover formats: https://confluence.atlassian.com/bamboo/using-bamboo-with-clover-289277349.html

**Comment by danielpalme** [comment]
I will try to add Clover support within the next 1-2 weeks.

XSD schema is available here:
https://bitbucket.org/atlassian/clover/src/default/etc/schema/clover.xsd

**Comment by GrayPockets** [comment]
That's amazing! I figured I'd make a pull request myself, but it's been a long time since I started digging into XML schemas. Would likely take me much longer.

**Comment by danielpalme** [comment]
I added support in ReportGenerator 4.5.0.
Please use `-reporttypes:Clover` to generate a _Clover.xml_ file

**Comment by GrayPockets** [comment]
Worked like a charm! Was able to integrate it into Bamboo history and charting.
