### ISSUE TITLE
Branch coverage dropped 20%

### ISSUE THREAD

**Issue by lostchopstik** [danielpalme/ReportGenerator#325]
Hello,

I've been using the report generator for a few months now without any major hiccups until just recently. Something has changed on the branch coverage generation and I can't make any sense of how to resolve it. My branch coverage has dropped from ~80% to ~60% without nearly that many changes being made to the code. 

An example is this:
![image](https://user-images.githubusercontent.com/3332512/75805653-154a5980-5d37-11ea-90dd-0bdf03acd4ad.png)

The message shows 2/4 branch coverage, but it is on the method opening bracket which makes no sense at all. Can anyone tell me how to address this because this appears to be where I have lost the big percentage.

The tests for the code shown above are as follows:
``` c#

[Fact]
public async Task Delete_OkRequest_ReturnsJson()
{
	// Arrange
	_mockBlogService.Setup( s => s.Tags.GetByID( It.IsAny<int>() ) )
		.ReturnsAsync( new Tag() );

	_mockBlogService.Setup( s => s.Tags.Delete( It.IsAny<int>() ) )
		.ReturnsAsync( HttpResponseHelper.GetHttpResponse( null, System.Net.HttpStatusCode.OK ) );

	// Act / Assert
	var result = Assert.IsType<JsonResult>( await _controller.Delete( new TagViewModel() ) );
}

[Fact]
public async Task Delete_BadRequest_ReturnsJson()
{
	// Arrange
	_mockBlogService.Setup( s => s.Tags.GetByID( It.IsAny<int>() ) )
		.ReturnsAsync( new Tag() );

	_mockBlogService.Setup( s => s.Tags.Delete( It.IsAny<int>() ) )
		.ReturnsAsync( HttpResponseHelper.GetHttpResponse( null, System.Net.HttpStatusCode.BadRequest ) );

	// Act / Assert
	var result = Assert.IsType<JsonResult>( await _controller.Delete( new TagViewModel() ) );
}

[Fact]
public async Task Delete_ErrorOnAPI_ReturnsJson()
{
	// Arrange
	_mockBlogService.Setup( s => s.Tags.GetByID( It.IsAny<int>() ) )
		.ThrowsAsync( new System.Exception() );

	// Act / Assert
	var result = Assert.IsType<JsonResult>( await _controller.Delete( new TagViewModel() ) );
}
```

Granted these are not thorough as far as checking the results, but they should still be hitting all branches.

Here are shots of the overall coverage drop:
BEFORE
![image](https://user-images.githubusercontent.com/3332512/75806278-38293d80-5d38-11ea-9d79-c9acf1fd8ea4.png)

AFTER
![image](https://user-images.githubusercontent.com/3332512/75806293-3d868800-5d38-11ea-9d92-32c5b8e520e6.png)

Thank you for any assistance.

**Comment by danielpalme** [comment]
Which coverage tool are you using? Coverlet or something else?
Can you share the generated XML file that you pass to ReportGenerator? You can send it by email: danielpalme82@gmail.com

**Comment by lostchopstik** [comment]
I'm using coverlet and outputting as opencover, the same result when outputting cobertura. Sending the XML your way.

**Comment by tfadler** [comment]
I think we are seeing the same issue (on the same day).  

Seems to be not displaying branch coverage correctly for async/await methods anymore.  

I recently update packages on a repo.  It is a .net framework 4.7.2 application using opencover.

Whatever caused this happened AFTER ReportGenerator 4.2.10.  Not sure exactly what version after but that may help.  Updating to latest drops my branch coverage.  

We are using opencover 4.7.922 now.  

Please let me know what I can do to help.  If needed I could try to make a sample repo when/if I have time.  

Thank you any help!

**Comment by danielpalme** [comment]
@lostchopstik 
Thanks for sending the XML file.

if you look at line 5742 you can see the relevant branches of your class `TagsController`
```xml
<BranchPoints>
  <BranchPoint vc="3" uspid="93" ordinal="0" path="0" offset="18" offsetend="22" sl="93" fileid="27" />
  <BranchPoint vc="3" uspid="93" ordinal="2" path="0" offset="24" offsetend="35" sl="93" fileid="27" />
  <BranchPoint vc="0" uspid="93" ordinal="1" path="1" offset="18" offsetend="122" sl="93" fileid="27" />
  <BranchPoint vc="0" uspid="93" ordinal="3" path="1" offset="24" offsetend="270" sl="93" fileid="27" />
  <BranchPoint vc="1" uspid="100" ordinal="4" path="0" offset="346" offsetend="348" sl="100" fileid="27" />
  <BranchPoint vc="1" uspid="100" ordinal="5" path="1" offset="346" offsetend="372" sl="100" fileid="27" />
</BranchPoints>
```

Line 93 contains 4 branches.  
2 of them are covered and 2 others are not executed .
Attribute `sl` contains the line number, attribute `vc` indicates the number of executions

That means that the HTML report shows exactly the branch information from the OpenCover file.  
The question is why this line contains 4 branches.

@MarcoRossignoli: Any idea why coverlet generates this unexpected result?

**Comment by MarcoRossignoli** [comment]
Depends on versions(before and after) it's possible a difference in coverage result between version because for instance when we remove some compiler generated branches the average could drop...but not too much I would say, @lostchopstik can you open an issue on coverlet with before/after or with a repro?
Seem very similar to https://github.com/tonerdo/coverlet/issues/729

**Comment by lostchopstik** [comment]
@MarcoRossignoli sure thing, I'll see if I can make a simple repro on a new project, otherwise, I'll try to provide as much detail as I can with what I have now.

**Comment by danielpalme** [comment]
I'm closing this issue since _ReportGenerator_ parses the coverage file correctly.  
The coverage file itself seems to be incorrect.
