### ISSUE TITLE
Allow custom report heading

### ISSUE THREAD

**Issue by hannahchan** [danielpalme/ReportGenerator#327]
Hi,

This is more of a feature request. I currently use ReportGenerator to generate 3 different coverage reports for an ASP.NET Core project. I generate coverage reports for Unit Tests, Integrations Tests and a Combine report. It would be nice when viewing the reports to know which report I am looking at by simply looking at a big heading in the report.

I was wondering if it was possible to include a parameter you could pass into ReportGenerate to set a custom heading and to show it on the report.

**Comment by danielpalme** [comment]
I will consider this in the next release.

**Comment by danielpalme** [comment]
New release is available here:
https://www.nuget.org/packages/ReportGenerator/4.5.1

**Comment by hannahchan** [comment]
Awesome! I didn't expect this so fast. I just tried it out and it looks good so far. Thanks heaps.
