### ISSUE TITLE
Merging Source Files

### ISSUE THREAD

**Issue by isc30** [danielpalme/ReportGenerator#328]
Hi, I'm trying to merge 2 test suite runs over the same source code (js).

I get 2 folders, each with some relevant sources and the `info.lcov` for them.
When merging both reports using multiple source folders, it detects the same file as different sources (but they are the same).

Is there any easy way of merging these?
Thanks

**Comment by isc30** [comment]
Attaching screenshot for clarity:
![image](https://user-images.githubusercontent.com/10807051/75878089-56b33580-5e19-11ea-889e-ac4bd0523194.png)

**Comment by danielpalme** [comment]
`lcov` is a very basic format. It only contains file names.  
It does not include any additional information (assemblies/packages/modules).

ReportGenerator does not analyze the file's content or hash for equality. It just uses the full path, and that's different here.

Possible workarounds:
- Preprocessing of  the `lcov` files, to apply a common base directory
- Use a different format than `lcov`. I don't know which tool you are using to generate the `lcov` files. But maybe this tool also supports `Cobertura` format?! Or maybe you can use a different tool that support Cobertura (Example: https://istanbul.js.org/docs/advanced/alternative-reporters/)?!

**Comment by isc30** [comment]
Cobertura fixed the issue, but I like the idea of preprocessing the files so the path matches.
Do you think its worth having a flag to check the file hash too? I guess I'm not the only one trying to merge 2 test runs with 2 completely isolated output but with the same source code

**Comment by danielpalme** [comment]
I try to avoid adding command line arguments whenever possible. It makes maintenance (for me) and setup (for all users) more complicated.

**Comment by isc30** [comment]
Agreed, thanks!
