### ISSUE TITLE
Branch coverage dropped with opencover report

### ISSUE THREAD

**Issue by tfadler** [danielpalme/ReportGenerator#329]
This is with a .net framework 4.7.2 application.  

Opencover 4.7.922

When going from reportgenerator 4.2.10 to latest (4.5.0), I see a drop in branch coverage.  Mostly around async and await...though you can see it on my if too.

I can provide the coverage report XML if needed.

On earlier version
![image](https://user-images.githubusercontent.com/42788888/75925251-ff6b9000-5e2d-11ea-84cd-91bdc9105157.png)

On current version
![image](https://user-images.githubusercontent.com/42788888/75925205-e8c53900-5e2d-11ea-84d4-ddea6f742537.png)

**Comment by danielpalme** [comment]
The XML will would be helpful: danielpalme82@gmail.com

**Comment by tfadler** [comment]
Sent.  Thank you sir!

**Comment by danielpalme** [comment]
if you look at line 36055 you can see the relevant branches of your class `Session`

```xml
<BranchPoint vc="0" uspid="6265" ordinal="8" offset="263" sl="87" path="0" offsetend="265" fileid="573" />
<BranchPoint vc="0" uspid="6266" ordinal="9" offset="263" sl="87" path="1" offsetend="333" fileid="573" />
<BranchPoint vc="0" uspid="6267" ordinal="10" offset="376" sl="88" path="0" offsetend="378" fileid="573" />
<BranchPoint vc="0" uspid="6268" ordinal="11" offset="376" sl="88" path="1" offsetend="448" fileid="573" />
<BranchPoint vc="0" uspid="6269" ordinal="12" offset="503" sl="89" path="0" offsetend="505" fileid="573" />
<BranchPoint vc="0" uspid="6270" ordinal="13" offset="503" sl="89" path="1" offsetend="528" fileid="573" />
```

All lines from 87 to 89 contain 2 branches.  
0 of them are covered/executed.
Attribute `sl` contains the line number, attribute `vc` indicates the number of executions

That means that the HTML report shows exactly the branch information from the OpenCover file.  
The question is why is none the branches marked as covered/executed?!
All of the lines are executed, so at least some branches should be covered as well.

**Comment by danielpalme** [comment]
See also:
https://github.com/OpenCover/opencover/issues/931
https://github.com/OpenCover/opencover/issues/933

**Comment by danielpalme** [comment]
I'm closing this issue since ReportGenerator parses the coverage file correctly.  
The coverage file itself seems to be not correct.
