### ISSUE TITLE
The JSONSummary report type creates invalid JSON

### ISSUE THREAD

**Issue by lotsofish** [danielpalme/ReportGenerator#331]
I am using ReportGenerator to combine an lcov coverage file (from Chutzpah) and an open cover coverage file (from OpenCover.)

My lcov file looks like this:
```
SF:D:\source\myapp\myscript.js
DA:2,1
DA:6,3
DA:7,3
DA:9,2
DA:10,2
DA:13,1
DA:16,3
DA:17,3
end_of_record
```
The "SF:" value is used as the assembly name in the resulting JSONSummary file. (Relevant properties below.)
```
{ 
  "coverage" : {
    "assemblies": [
      { "name": "D:\source\myapp\myscript.js" }
    ]
  }
}
```
The JSON is invalid because the backslash characters are not escaped. Name should be `"D:\\source\\myapp\\myscript.js"`.

**Comment by danielpalme** [comment]
Will fix this soon.

**Comment by danielpalme** [comment]
New release 4.5.2 should be available in a couple of minutes.
