### ISSUE TITLE
startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by WorldVM** [danielpalme/ReportGenerator#333]
Hello, everybody,
i have a small problem every time i want to create a html file i get the following error: 

2020-03-16T09:02:58:  Error during reading report 'E:\Workspace\Build01\jenkins\workspace\mybuild\coverage.xml' (Size: 62,7MB): startIndex cannot be larger than length of string.
Parameter name: startIndex

I have already created the coverage.xml file with opencover. Now I tried to create a html report with the following command: 

 ReportGenerator.exe \"-reports:coverage.xml" \"-targetdir:CodeCoverageHTMLReport\"

i also get a html file in the directory only if i open it with firefox it says : No assemblies have been covered.

**Comment by danielpalme** [comment]
Can you please share your `coverage.xml` file.
You can send it by email: danielpalme82@gmail.com

**Comment by danielpalme** [comment]
Any update? Can you please share your Opencover file?

**Comment by WorldVM** [comment]
I select the false .xml file sorry. Please close the ticket Sir.
