### ISSUE TITLE
Add dotCover support

### ISSUE THREAD

**Issue by Sam13** [danielpalme/ReportGenerator#34]
Maybe consider adding support for dotCover XML files?
https://www.nuget.org/packages/JetBrains.dotCover.CommandLineTools/

**Comment by danielpalme** [comment]
Thanks for your suggestion.
I will see what I can do.

**Comment by Sam13** [comment]
Great, thanks. According https://www.jetbrains.com/dotcover/help/dotCover__Console_Runner_Commands.html#analyse it can generate XML reports and other formats (see ReportType) parameter

**Comment by danielpalme** [comment]
I just added support for dotcover.
It would be great if you you test this beta: https://www.nuget.org/packages/ReportGenerator/2.4.0-beta1

**Comment by Sam13** [comment]
Thanks, I'll test it asap...

**Comment by danielpalme** [comment]
Did you already test the beta release?

**Comment by JohnnyMLH** [comment]
Hi Daniel,

no, not yet.
I hope to get it done until the end of the week.

Best regards,
Joao




Von:    Daniel Palme <notifications@github.com>
An:     danielpalme/ReportGenerator <ReportGenerator@noreply.github.com>
Datum:  13.01.2016 22:04
Betreff:        Re: [ReportGenerator] Add dotCover support (#34)



Did you already test the beta release?
?
Reply to this email directly or view it on GitHub.

------------------------------------------------------------------------------------------------
ServiceXpert Gesellschaft für Service-Informationssysteme mbH
Tempowerkring 3, D - 21079 Hamburg
Sitz der Gesellschaft / Registered office: Hamburg
Registergericht / Commercial register: Hamburg, HRB 135022
Geschäftsführer / Board of Directors:
Dipl.-Wirt.-Ing. Ferdinand Stocker
------------------------------------------------------------------------------------------------

**Comment by Sam13** [comment]
Will test at the beginning of next week, sorry for the delay...

**Comment by Sam13** [comment]
A first test creating a summary XML from multiple dotCover detailed XML reports worked, will do more detailed tests the next days...

**Comment by Sam13** [comment]
Generating a HTML report from dotCover detailed XML files works as well...

**Comment by danielpalme** [comment]
Great. Branch coverage is not available in dotCover. Therefore branchcoverage=""
