### ISSUE TITLE
Support "-p:x=y" to be ignored from command line arguments

### ISSUE THREAD

**Issue by CodeTherapist** [danielpalme/ReportGenerator#341]
When using the MsBuild task, the generator ignores all command line arguments starting with "-property:" ([Generator.cs](https://github.com/danielpalme/ReportGenerator/blob/9938cb5b35c04c82a71b72dee88f69456e1e4106/src/ReportGenerator.Core/Generator.cs#L267)) but not the short form of it, like "-p:".

**Comment by danielpalme** [comment]
Next release will contain a [fix](https://github.com/danielpalme/ReportGenerator/blob/74b58ba5cda75556f30f57d0a267e966700204cb/src/ReportGenerator.Core/Generator.cs#L269).
See also #279

**Comment by CodeTherapist** [comment]
Thanks @danielpalme for your fast answer and for the fix.
