### ISSUE TITLE
Document usage as .NET Core local tool

### ISSUE THREAD

**Issue by older** [danielpalme/ReportGenerator#346]
Since .NET Core 3.0 [local tools are supported by .NET Core](https://docs.microsoft.com/dotnet/core/tools/global-tools#install-a-local-tool). I tested it and it seem to be working. I used the following in `dotnet-tools.json`:

```javascript
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-reportgenerator-globaltool": {
      "version": "4.5.8",
      "commands": [
        "reportgenerator"
      ]
    }
  }
}
```
Package name `dotnet-reportgenerator-globaltool` is a bit unfortunate because it contains word "global", but I can live with that ;)

**Comment by danielpalme** [comment]
There are several options to install a global tool:

 - **Global**
    ```
    dotnet tool install -g dotnet-reportgenerator-globaltool
    ```

 - **Global - In custom directory**
    ```
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tool
    ```

 - **Local**
    ```
    dotnet new tool-manifest
    dotnet tool install dotnet-reportgenerator-globaltool
    ```

I will add the last option (your setup) to the documentation, which is listed at several places:
 - https://github.com/danielpalme/ReportGenerator#install-the-package-matching-your-platform-and-needs
 - https://danielpalme.github.io/ReportGenerator/usage.html
 - https://www.nuget.org/packages/dotnet-reportgenerator-globaltool
