### ISSUE TITLE
Color Method Links to Match their Coverage Percent

### ISSUE THREAD

**Issue by aschlicht** [danielpalme/ReportGenerator#348]
@danielpalme What do you think about coloring the method links to match their coverage percent? I'm referring to the method / property links on the right side of an html page that shows the source code and highlights which lines are covered or not. I think users could more quickly navigate to uncovered or partially covered methods if they are color coded. The method name could be colored and / or the icon next to the function / method name could be color coded.

I don't know which input types support function coverage information. I do know gcov supports covered line % in a function because I use gcov with the ceedling unit tests. We recently added support to call report generator from ceedling.

I experimented with changing a few report generator source files and it appears to work well. These changes set the method name color, not the icon color. Not sure if the way I made the changes goes along with your design, so I sent the .cs source files in a zip file instead of a pull request.

Consider an enable / disable command line option similar to those found here, if you think some people may like this change while others dislike it:
https://github.com/danielpalme/ReportGenerator/wiki/Settings

[ColorCodeMethodNames.zip](https://github.com/danielpalme/ReportGenerator/files/4659635/ColorCodeMethodNames.zip)

**Comment by danielpalme** [comment]
I will have a look at this within the next days.

**Comment by aschlicht** [comment]
Thank you for looking at this enhancement request already. You have a more generic way of calculating method / property coverage, which is great! I pulled your 4.6.0 branch and so far I see either 0% or 100% for gcov. I think it is because of this line from GCovParser.cs. The first and last line number are equal, so there can only be either 0 or 1 covered lines of code.

```cs
codeElements.Add(new CodeElement(name, CodeElementType.Method, maxiumLineNumber + 1, maxiumLineNumber + 1));

I'm not sure of a great way to determine when a function ends from gcov files. Could update the previous function's last line when encountering the next "function" text or end-of-file. The .gcov file does have the "blocks executed" percentage already calculated and in the file. Could use that value. You know your report generator tool well and maybe you already have a better idea.
```

**Comment by danielpalme** [comment]
I'm still working on it.
Gcov is pretty limited. The regular expression is not perfect, because you get the _block coverage_ and not the _line coverage_.
ReportGenerator is all about _line coverage_ and _block coverage_ is similar but not the same.
This might result in discussions like "The coverage does not match...".

**Comment by aschlicht** [comment]
I believe it's not ready yet. If you thought it was, you would have published a release. I was interested in your approach, so I took a look, tested it, and gave some feedback. I think it looks great. Thank you for working on this feature.

I didn't know about the line coverage and block coverage difference. You are correct. People would log issues saying the coverage does not match.

**Comment by danielpalme** [comment]
If you like you can try my changes again. It now works for all input formats.

Instead of the block coverage I'm detecting the first and last line of each method.
This has some limitations for _gcov_ since _gcov_ does don't contain a status for each line.
But it should be good enough in most situation.

**Comment by aschlicht** [comment]
I tried only with gcov through ceedling and your latest changes are working well. I like having a way to quickly navigate to the source code needing additional unit tests. Thank you for making these changes.

Maybe it's my eyes, but to me it appears the red part of the coverage percent indicator is slightly offset toward the left when compared to the green part. Do you see that as well?

![image](https://user-images.githubusercontent.com/16124508/82736353-5d4d9c80-9ce6-11ea-8662-d0ff8bf605a4.png)

**Comment by sungam3r** [comment]
I see that too.

**Comment by danielpalme** [comment]
I see it too. But it disappears when I zoom in.
It's a straight line implemented as simple CSS border with gradient (see https://github.com/danielpalme/ReportGenerator/blob/v4.6.0/src/ReportGenerator.Core/Reporting/Builders/Rendering/resources/custom.css#L63)

**Comment by danielpalme** [comment]
I published a new release which includes the new feature:
https://www.nuget.org/packages/ReportGenerator/4.6.0
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.6.0

**Comment by aschlicht** [comment]
@danielpalme Thank you!
