### ISSUE TITLE
Ability to maintain query string parameters per page.

### ISSUE THREAD

**Issue by dvbarnes** [danielpalme/ReportGenerator#349]
Hey all,

We host our html reports in azure blob storage and use a SAS token to expose the reports. One pain point we have is the token doesn’t persist from page to page, making us need to copy the SAS token click the link to the specific class then paste the SAS token back in the url. It’s be awesome if we had a setting that persisted the query string param from link to link.

**Comment by danielpalme** [comment]
Good idea. Will add support for this within the next days.

**Comment by danielpalme** [comment]
Which report type are you using?
One of the "inline" types: _HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark_
or the _Html_ type?

**Comment by danielpalme** [comment]
I published a new release which includes the new feature:
https://www.nuget.org/packages/ReportGenerator/4.6.0
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.6.0

You don't have to change any settings. It should work out of the box.
If you open `index.html` with a query string, the query string will be applied to all internal links.

JavaScript needs to be enabled to support this.

**Comment by dvbarnes** [comment]
@danielpalme thanks for this super helpful. One question I have, is this something that's persisted in the azure devops package?

**Comment by danielpalme** [comment]
I'm not sure if I understand your question correctly.
The [azure devops extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator) also contains the changes.

Does this answer your question?!

**Comment by dvbarnes** [comment]
That does answer my question. Thank you.

**Comment by danielpalme** [comment]
Starting with release 5.5.9 you'll have to use `settings:settings:applyQueryStringToAllLinks=true` as a command line parameter in order to apply the query string to all links.
