### ISSUE TITLE
Possible bug when converting nested private classes in C# from OpenCover to Lcov format

### ISSUE THREAD

**Issue by Cjewett** [danielpalme/ReportGenerator#353]
I'm not sure if this is a bug or not. In C# if you have two classes in the same file the OpenCover.xml to Lcov conversion will list the file twice. One for each class seen in that file which I feel is an intuitive way to display the information.

However, if you have one class that is nested within another class then the OpenCover.xml to Lcov conversion outputs all of the data under the parent class. That seems a little bit weird because you run into issues where the same function name can appear twice for a single record. 

Is this expected behavior? Nested private classes are a bit ugly in my opinion so it's something we (company I work for) need to look at, but I feel like nested private classes should display the information similar to how two non-nested classes existing within the same file looks like. Two records for that file but one for each class, so there are no duplicate functions.

https://gist.github.com/Cjewett/4d511990c35ed2ba990459c927eaac7a

**Comment by danielpalme** [comment]
No this does not mess up the results.

You have to take the line(s) of the methods into account.

The first `Add` method start in line 6 (see `FN:6,Add(System.Int32,System.Int32)`).
The second `Add` method start in line 52 (see `FN:52,Add(System.Int32,System.Int32)`).

**Comment by Cjewett** [comment]
I'm not understanding how that let's you map FNDA execution counts to the function in FN. The FNDA does not provide a line number. It provides function name and execution count, and the only information in FNDA that corresponds to FN is the function name. The line number won't help you determine which FN the FNDA maps to.

I noticed in the ReportGenerator Lcov reports the function and execution count is also included in the DA section. I feel like that is incorrect based on the documentation and experience using Istanbul and Coverlet. Why have FNDA at all if DA includes the function information too? 

My experience with Istanbul and Coverlet which both have Lcov output is that function information is not included in the DA section, and the DA section is restricted to line executions only. Similarly the branch information is not included in the DA section either.

**Comment by danielpalme** [comment]
> I'm not understanding how that lets you map FNDA execution counts to the function in FN. The FNDA does not provide a line number. It provides function name and execution count, and the only information in FNDA that corresponds to FN is the function name. The line number won't help you determine which FN the FNDA maps to.

The FN and FNDA section contains the same elements, in the same order.
The elements are ordered by line number, so the result is deterministic.

> I noticed in the ReportGenerator Lcov reports the function and execution count is also included in the DA section. I feel like that is incorrect based on the documentation and experience using Istanbul and Coverlet. Why have FNDA at all if DA includes the function information too?

I'm not sure if coverlet and Istanbul are a good reference here.
I'm using the "official" documentation http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php for my implementation.

Just out of curiosity:
For what reason do you need the _lcov_ format at all? Formats like _OpenCover_ or _cobertura_ contain much detailed information.

**Comment by Cjewett** [comment]
Existing tools within the company have a pipeline for Lcov built out already. OpenCover file sizes are also much larger for us (20x+). I haven't looked at Cobertura much. 

I can look to see if we can alter our tools to assume the FN and FNDA sections always display information in the same order. Seems weird to me since the documentation states there is a list of FN, then a list of FNDA, but it does not say the order in which information is displayed in those lists must be mapped to each other. Where entry #1 in FN must map to entry #1 in FNDA, entry #2 in FN must map to entry #2 in FNDA, etc.

**Comment by danielpalme** [comment]
I'm closing this issue now. Feel free to reopen if you have further questions.
