### ISSUE TITLE
Absolute filenames when merging multiple Cobertura

### ISSUE THREAD

**Issue by t-knapp** [danielpalme/ReportGenerator#356]
Hello,

I'm facing thw problem that `filename` attributes of `class` elements will be absolute when merging multiple Cobertura styled reports to one single Cobertura styled report.

Both source reports have slightly different `source` paths. They are based in the same directory but the `source` of one of them is part of the `source` of the other one (sub-folder structure)

**Source report A**
```
[...]
<sources>
  <source>D:\Code\Discovery\Discovery.Client\</source>
</sources>
[...]
```

**Source report B**
```
[...]
<sources>
  <source>D:\Code\Discovery\</source>
</sources>
[...]
```

In both source reports, the filename attribute is relative based on the source directory.
In the merged report, both sources are present, but all filename attribute values are absolute.

Is it possible to find the "deepest" common source folder of the input reports and calculate relative filename attribute?

Kind regards,
Tobias

**Comment by danielpalme** [comment]
ReportGenerator supports several [input formats](https://github.com/danielpalme/ReportGenerator#supported-input-and-output-file-formats), some of them use relative paths, some use absolute paths.
To provide a consistent result, ReportGenerator uses absolute paths everywhere.
Finding the "deepest common source folder" is not as easy as it may seem.
Your case is pretty simple, but several different base folder could also exist.

In your case a small powershell script can "fix" the problem.

```powershell
(gc "cobertura.xml") | % { $_ -replace "D:\Code\Discovery\", "" } | Out-File "cobertura.xml" -Encoding UTF8
```

**Comment by t-knapp** [comment]
Thanks for clarification.
