### ISSUE TITLE
Code Coverage On Linux

### ISSUE THREAD

**Issue by manishi2V** [danielpalme/ReportGenerator#357]
Hello Folks,

I am not able to get report generator utility on Linux machine. Please let me know how can I generate an HTML report in Linux machine. 
I am following this [Article ](https://dzone.com/articles/code-coverage-reports-for-aspnet-core) to generate test case report of my dotnet core project but didn't found a way to get this utility on Linux machine.

**Comment by danielpalme** [comment]
The [dotnet-reportgenerator-cli](https://www.nuget.org/packages/dotnet-reportgenerator-cli) is deprecated and won't work properly with .NET Core 3.x.
I would recommend that you try the [dotnet-reportgenerator-globaltool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool).

On the command line it should like this:
```
dotnet tool install -g dotnet-reportgenerator-globaltool
reportgenerator [options]
```
