### ISSUE TITLE
Blocked script execution

### ISSUE THREAD

**Issue by GaTechThomas** [danielpalme/ReportGenerator#358]
We're using the Report Generator Azure DevOps add-in with report types set to "HtmlInline_AzurePipelines;Cobertura". The historical chart functionality isn't working beyond the initial history chart, and we're seeing the following error in the browser console:

`Blocked script execution in 'https://dev.azure.com/.../_apis/test/CodeCoverage/browse/.../Code%20Coverage%20Report_49600/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
`

From what I've read, I gather that this error should not be occurring. Have I misunderstood? Can the error be avoided?

**Comment by danielpalme** [comment]
The error can not be avoided. Azure DevOps blocks all dynamic content including JavaScript by applying strict [CSP rules](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

**Comment by GaTechThomas** [comment]
Would it be possible for the Report Generator ADO extension to make the scripts available from within ADO so that the origin is the same?

**Comment by danielpalme** [comment]
The typical setup is:
- Generate report with _ReportGenerator_
- Publish report with _PublishBuildArtifacts_

If you use this setup there's nothing I can do about. The "Code Coverage" tab is controlled by ADO and the content is restricted by CSP rules.

What you can do:
Download the "Code Coverage Report_xx" artifact which get published automatically and view the report on you local machine.

**Comment by GaTechThomas** [comment]
Thank you again for the info. ReportGenerator is fantastic. Unfortunately the download requirement is troublesome for the needs at hand. I understand that the limitation is out of your control. We'll just have to work around it somehow.

**Comment by danielpalme** [comment]
One thing you could do:
Create a Azure Blob Storage and publish the coverage report to a blob container.
Create a SAS token to allow access.
Open `index.html` in your browser and set a bookmark.
