### ISSUE TITLE
Branch Coverage count seems to be a factor 2 to high

### ISSUE THREAD

**Issue by ibforever** [danielpalme/ReportGenerator#36]
I have made a very simple method that I run a coverage test using OpenCover. I can only think of two possible branches but the report says thet there are 4.

Am I wrong, or is it a bug in the ReportGenerator og is it a bug in OpenCover?

I have attached the OpenCover result and the ReportGenerator report for the method

[CoverageConsoleApplication_Fun.zip](https://github.com/danielpalme/ReportGenerator/files/112170/CoverageConsoleApplication_Fun.zip)

**Comment by danielpalme** [comment]
Seem to be an issue in ReportGenerator. I will have a look soon.

**Comment by danielpalme** [comment]
I have fixed this in release 2.4.1
Another possibility is to use the _-mergebyhash_ comand line parameter for _OpenCover_
