### ISSUE TITLE
Support flame graphs

### ISSUE THREAD

**Issue by peteroupc** [danielpalme/ReportGenerator#361]
Support flame graphs described at https://github.com/BrendanGregg/FlameGraph .

I have found flame graphs very useful when [profiling Java code](https://github.com/jvm-profiling-tools/async-profiler), and I would find them equally useful when profiling .NET code.  Thus, flame graphs should be supported for any report format that supports call stacks.

**Comment by danielpalme** [comment]
Looks nice.
But you already mentioned "any report format that supports call stacks".

None of the [supported formats](https://github.com/danielpalme/ReportGenerator#supported-input-and-output-file-formats) supports call stacks.
