### ISSUE TITLE
Problems using dark themes with VSCode with the generated report

### ISSUE THREAD

**Issue by ByteDecoder** [danielpalme/ReportGenerator#365]
I am experienced a weird behavior using dark themes in VSCode. Is hard to read the report output inside the editor. Is there a workaround to fix this by not moving to a lighter theme? 

![reporter_dark_themes](https://user-images.githubusercontent.com/11826115/88985413-ced13a80-d295-11ea-8daa-19ac9f2d18d8.png)

**Comment by danielpalme** [comment]
Are you using a plugin to show the HTML page in VSCode?

**Comment by ByteDecoder** [comment]
Hi, I am using the Coverage Gutters plugin and using the option to show the coverage report inside VSCode. 

I am using the report tool with the next arguments:
`reportgenerator "-reports:coverage/lcov.info" "-reporttypes:HTMLInline;Badges" "-targetdir:coverage/report"`

I notice if I change the VSCode themes to lighter colors, the report output result colors became easier to distinguish.

**Comment by danielpalme** [comment]
Will look into it.

**Comment by ByteDecoder** [comment]
Thanks

**Comment by danielpalme** [comment]
Release 4.6.3 of ReportGenerator fixes this issue (should be available within a few minutes).

By the way: If you prefer a dark theme for your report, try the `"-reporttypes:HtmlInline_AzurePipelines_Dark;Badges"` instead of `"-reporttypes:HTMLInline;Badges"`

**Comment by ByteDecoder** [comment]
The enhancement is working now with Coverage Gutters with VSCode dark themes. Should I close the issue, or you will be doing that?  

Thanks
