### ISSUE TITLE
[Feature request] Filtering the whole directory

### ISSUE THREAD

**Issue by maisreymom** [danielpalme/ReportGenerator#366]
"-filefilters -*Test.java" kind of works but that would be more useful if there is an option to generate the report for everything under src/main only without including anything under src/test. 
e.g. If we have utility classes under src/test that doesn't have the name *Test.java or if we have a class in src/main that is *Test.java

Thanks

**Comment by danielpalme** [comment]
Have you tried `-assemblyfilters`?
E.g. `assemblyfilters:-test*`

**Comment by maisreymom** [comment]
@danielpalme I tried that, and seem like it doesn't work.

**Comment by danielpalme** [comment]
Please have a look at the generated report. You have to identify the namespaces you want to exclude.
Then modify the `-assemblyfilters:-test*` accordingly

**Comment by EugenDueck** [comment]
@danielpalme 

It seems for clover, the value in `<package name="` maps to assembly. However in Java, the package name of the test class is in general the same as that of the tested class, for reasons of visibility ("package-private"). So you cannot distinguish test code from production code using assemblyfilter.

If you look at a `clover.xml` file for a simple project, it will look like this:
```xml
<coverage>
  <project name="my-project 1.0" timestamp="1596157313247">
    ... 
  </project>
  <testproject name="my-project 1.0" timestamp="1596157313247">
    ...
  <testproject>
</coverage>
```

ReportGenerator treats both identically:

```csharp
var projectElement = new XElement(
    "project",
    new XAttribute("timestamp", timeStamp));

rootElement.Add(projectElement);

var testProjectElement = new XElement(
    "testproject",
    new XAttribute("timestamp", timeStamp));

rootElement.Add(testProjectElement);
```

Wouldn't clover users in general be happy if you just ignored the `<testproject>` element altogether? Who needs a coverage report for the test code - which will in general be 100% or close to 100%, thus skewing the result?

**Comment by danielpalme** [comment]
> Wouldn't clover users in general be happy if you just ignored the `<testproject>` element altogether? Who needs a coverage report that includes test code - which will in general be 100% or close to 100%, thus skewing the overall coverage result?

I don't think so. [Coverlet](https://github.com/coverlet-coverage/coverlet) did the same and now test assemblies are included in the results. Some users want that as well.

**Comment by EugenDueck** [comment]
The test code being part of the report does not bother me, but the 100% test coverage skewing a 50% production code coverage towards 70% or so does. And I'd be surprised if any user wants the coverage % figure to include coverage from test code.

Be that as it may - could we perhaps get a flag to control that?

**Comment by danielpalme** [comment]
Release 4.6.3 of ReportGenerator (should be available within a few minutes) add a new [flag](https://github.com/danielpalme/ReportGenerator/wiki/Settings) to control that behavior.

Add `settings:excludeTestProjects=true` to your command line parameters. And everything in a `testproject` node will be ignored.

**Comment by EugenDueck** [comment]
Thanks!

I'm using this from AzDO. Your version 4.6.3 has been automatically updated, and I tried this.
```yaml
- task: reportgenerator@4
  displayName: 'convert clover report -> cobertura'
  inputs:
    reports: '$(Build.SourcesDirectory)/target/site/clover/clover.xml'
    excludeTestProjects: true
    targetdir: '$(Build.SourcesDirectory)/CoverageResults'
```
However, the parameter does not seem to get recognized - and tests in fact did not get excluded:
```
Starting: convert clover report -> cobertura
==============================================================================
Task         : ReportGenerator
Description  : ReportGenerator converts coverage reports generated by OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov or lcov into human readable reports in various formats.
Version      : 4.6.3
Author       : Palmmedia
Help         : [More Information](https://github.com/danielpalme/ReportGenerator)
==============================================================================
/usr/bin/dotnet /home/vsts/work/_tasks/reportgenerator_be803a55-9253-4895-a525-be570d86f161/4.6.3/tools/netcoreapp2.1/ReportGenerator.dll
 -reports:/home/vsts/work/1/s/target/site/clover/clover.xml
 -targetdir:/home/vsts/work/1/s/CoverageResults
 -reporttypes:HtmlInline_AzurePipelines;Cobertura
 -sourcedirs:
 -historydir:
 -plugins:
 -assemblyfilters:+*
 -classfilters:+*
 -filefilters:+*
 -verbosity:Info
 -title: -tag:20200802.1_#448
```
A quick grep for "filefilters" vs "excludetest" shows the latter is not present in the following files that contain the former. Perhaps that's the reason.

- ./src/ReportGenerator.Core/ReportConfiguration.cs
- ./src/ReportGenerator.Core/ReportConfigurationBuilder.cs
- ./src/ReportGenerator.Core/Reporting/Builders/MhtmlReportBuilder.cs
- ./src/ReportGenerator.Core/Reporting/IReportConfiguration.cs
- ./src/ReportGenerator.Core/Help.cs
- ./src/ReportGenerator.Core/Properties/Help.Designer.cs
- ./src/ReportGenerator.MSBuild/ReportGenerator.cs
- ./src/ReportGenerator.Console/MSBuild/ReportGenerator.cs

**Comment by danielpalme** [comment]
You are right, i'll have to update the Azure DevOps extension to support those settings.

**Comment by danielpalme** [comment]
The following should work with version 4.6.4:
```yaml
- task: reportgenerator@4
  displayName: 'convert clover report -> cobertura'
  inputs:
    reports: '$(Build.SourcesDirectory)/target/site/clover/clover.xml'
    targetdir: '$(Build.SourcesDirectory)/CoverageResults'
    customSettings: 'settings:excludeTestProjects=true'
```

**Comment by EugenDueck** [comment]
This works! Thanks a lot!
