### ISSUE TITLE
Cobertura report shows NaN for all complexities

### ISSUE THREAD

**Issue by briangardner** [danielpalme/ReportGenerator#367]
**Expected Behavior**
Creating the Cobertura report type should include Cycolmatic Complexity, and highlight Risk Hotspots.

**Observed Behavior**

- Step 1: Run `dotnet test --collect:"XPlat Code Coverage" --settings .\coverlet.runsettings.xml` on a .Net Core 3.0 project
  - coverlet.runsettings.xml:
  ```
  <?xml version="1.0" encoding="utf-8" ?>
  <RunSettings>
    <DataCollectionRunSettings>
      <DataCollectors>
        <DataCollector friendlyName="XPlat code coverage">
          <Configuration>
            <Format>cobertura</Format>
            <Exclude>[*.Tests]*</Exclude>
            <IncludeTestAssembly>false</IncludeTestAssembly>
          </Configuration>
        </DataCollector>
      </DataCollectors>
    </DataCollectionRunSettings>
  </RunSettings>
  ```
- Step 2: run `reportgenerator "-reports:*\TestResults\*\*.xml" "-targetdir:coveragereport" -reporttypes:""HTMLInline_AzurePipelines;Cobertura"` on a .Net Core 3.0 project, 

The HTML Report shows cyclomatic complexity numbers, and risk hotspots as expected.  The Cobertura.xml file has `complexity="NaN"` for every package, class, and method.  And since all complexities are `NaN`, no Risk Hotspots show.

**Comment by eddynaka** [comment]
@danielpalme , I was looking at this and every place in `CoberturaReportBuilder` that prints complexity is pointing to `NaN`. Is it on purpose? Can i create a PR adding the logic to fill that value?

**Comment by danielpalme** [comment]
It's not as easy as it may seem.
ReportGenerators supports several [input formats](https://github.com/danielpalme/ReportGenerator#supported-input-and-output-file-formats). Not every format contains the complexity metric.
ReportGenerator currently only tracks the metrics for each method (if available).
So adding this to the [method elements](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Reporting/Builders/CoberturaReportBuilder.cs#L96) should be doable.

All the other elements require quite a lot of work.
You'll have to take into account, that information is not available in all formats and that you have to support merging of results as well.

**Comment by eddynaka** [comment]
I will try some stuff and we can check if that will work. At least, for my case, I had the values in the xml.
________________________________

**Comment by eddynaka** [comment]
@danielpalme , i opened the PR https://github.com/danielpalme/ReportGenerator/pull/369. Right now, with this changes i already added the complexity to:
- method
- file

And, trying to figure out how to add to package / root.

**Comment by danielpalme** [comment]
Will test this in several scenarios. But make take a while, since I'm on vacation.

**Comment by danielpalme** [comment]
Merged this into [develop branch](https://github.com/danielpalme/ReportGenerator/tree/develop).
Next release will contain your changes.
