### ISSUE TITLE
[Question] How report generator works with multi-target framework

### ISSUE THREAD

**Issue by eddynaka** [danielpalme/ReportGenerator#368]
Hi,

imagine that I have a project that targets 3 different frameworks: net452, net461, netstandard2.0.

Some tests are conditional:
- for net452, i have 10 tests
- for net461, i have 9 tests
- for netstandard2.0, i have 15 tests

When I use dotnet test to generate the output, it generates 3 files, one for each framework. Then, i use reportgeenerator tool to merge.

What will happen with the data? Is it going to merge de results as well?

**Comment by danielpalme** [comment]
Yes.

Assemblies with same name are merged, Classes within an assembly with the same name are merged.
Coverage of each line is summed up.

You can simply try by generating the report for one coverage file. The do the same for two/three files and you will see the difference in the numbers.
