### ISSUE TITLE
Coverage History dashboard

### ISSUE THREAD

**Issue by rvignesh89** [danielpalme/ReportGenerator#37]
Hi Daniel,

We've been using ReportGenerator for a while now. Only recently we noticed that it can also generate the history trends which is a very useful feature. But we wanted a way to be able to see the trends for many projects in a dashboard view in Jenkins to get an overall picture. 

I was thinking of creating a custom view and embedding the coverage report as an iframe. But the trends chart is using svg and I'm not able to take that out alone from the whole html.

I'm thinking the trends chart alone can be exported out, something like the badges so that it can be plugged in anywhere. Do you have any plans for this?

**Comment by danielpalme** [comment]
Hi,

I have two or three solutions for you. You can 
1) Create a custom report which generates a **HTML** file containing only the chart
2) Create a custom report which generates a **PNG** file showing the chart

If you want to do so, download my sample custom reports:
http://danielpalme.github.io/ReportGenerator/resources/CustomReportTypes.zip
Compile the project and put the DLL next to _ReportGenerator.exe_
Then you can use the following reporttypes when calling ReportGenerator.exe: _PngChart, HtmlChart_

If you want to customize the chart or report, you can adjust the plugin code.

Please see also this issue:
https://github.com/danielpalme/ReportGenerator/issues/21

See here for an introduction for writing custom reports:
https://github.com/danielpalme/ReportGenerator/wiki/Custom-reports

Hope this helps

**Comment by rvignesh89** [comment]
Thanks for your quick response! Looks like it is just what I want. Let me give it a try and get back to you soon.

**Comment by rvignesh89** [comment]
Hi,

I tried it and it does work exactly like I wanted it to. The only concern I have is that when we upgrade ReportGenerator in the future I have to remember to place this dll next to the exe again. Is there a way to integrate this into the default package itself? 

Other than this, the feature works just as I'd like to! Thanks for that.

**Comment by danielpalme** [comment]
I'm thinking about integrating some of these report types into the default set.

**Comment by rvignesh89** [comment]
Great, I'd +1 that feature for sure! If you need my help, I can also look into a give you a pull request if you want. But I'm guessing that is not a big task.

**Comment by danielpalme** [comment]
Just released ReportGenerator 2.4.2 with new report types.
