### ISSUE TITLE
Metrics in metrics table may be listed in the wrong column when combining coverage reports of different types

### ISSUE THREAD

**Issue by egraff** [danielpalme/ReportGenerator#371]
In my setup, I have some test projects that are multi-targeted against  both .NET Framework and .NET Core / .NET Standard. When running tests for .NET Framework, I'm using OpenCover for code coverage, wheres for .NET Core and .NET Standard, I'm using coverlet, which generates code coverage reports in the cobertura format.

When feeding both OpenCover and cobertura reports for the _same_ project into ReportGenerator (the parser is listed as `MultiReportParser (Nx CoberturaParser, Mx OpenCoverParser)`, the metrics shown for the cobertura report ends up in the wrong columns, as shown in the image below:

![image](https://user-images.githubusercontent.com/5569523/89518895-db94e780-d7db-11ea-8c30-103b57e15294.png)

I'm guessing because only the OpenCover report has metrics for the "NPath complexity", the sequence coverage and branch coverage of the cobertura results are shifted one column too far to the left. The expected result would be that the rows from the cobertura report either are filled with blank columns for the missing metrics, or the columns were reordered to prevent this.

I.e. it should have looked something like this:

![image](https://user-images.githubusercontent.com/5569523/89519832-4561c100-d7dd-11ea-9b7f-565e9b3aacf1.png)

For completeness, here is a snippet of the generated HTML (I've removed the `title` attrs):

```html
<tbody>
<tr><td><a href="#file0_line19" class="navigatetohash">.ctor(...)</a></td><td>2</td><td>2</td><td>100%</td><td>66.67%</td><td>2</td></tr>
<tr><td><a href="#file0_line19" class="navigatetohash">.ctor(...)</a></td><td>2</td><td>100%</td><td>50%</td></tr>
<tr><td><a href="#file0_line28" class="navigatetohash">.ctor()</a></td><td>1</td><td>0</td><td>100%</td><td>100%</td><td>1</td></tr>
<tr><td><a href="#file0_line28" class="navigatetohash">.ctor()</a></td><td>1</td><td>100%</td><td>100%</td></tr>
...
```

**Comment by danielpalme** [comment]
Thanks for reporting this issue.

I will fix this end of august.

**Comment by danielpalme** [comment]
I finally added two additional columns in release 4.6.5:
https://www.nuget.org/packages/ReportGenerator/4.6.5
