### ISSUE TITLE
Document how to remove Sponsor and Star buttons from report

### ISSUE THREAD

**Issue by jstallm** [danielpalme/ReportGenerator#372]
Its not clear in the documentation how to remove the 2 HTML elements (Sponsor and Star buttons) in the summary of the results. I am considering using this for a large fortune 500 company and really dont want engineers to get distracted when looking at the results of code coverage. Is it possible to remove these elements?

**Comment by danielpalme** [comment]
There is no option to remove those buttons.

Reason:
_ReportGenerator_ is used by many companies and developers (over 15.000.000 downloads). But only very few a willing to support open source projects like _ReportGenerator_.
Therefore I added those buttons to make it more obvious (without annoying banners or popups).

I'm willing to add an option to remove the buttons if you [become a sponsor](https://github.com/sponsors/danielpalme).

**Comment by jstallm** [comment]
Sorry @danielpalme , I am not willing to ask the enterprise to sponser at this point in time. But thank you for the quick reply.

**Comment by raspe88** [comment]
May I suggest to make it more clear, what to sponsor or star on the first glance. Maybe just by writing a string in front of the buttons: "This report has been generated using [ReportGenerator](https://github.com/danielpalme/ReportGenerator)".

At least within Azure DevOps, the two grey buttons that just contain the strings "Sponsor" and "Star" feel strange and may cause confusion. When hovering over e.g. "Star" and not looking at the exact link, it feels strange to read "Star on GitHub" within Azure DevOps when you do not even have a bridge to GitHub.

**Comment by Happypig375** [comment]
Can't you just do a simple file replace for this? It's not hard - you only need to modify index.htm and index.html.

**Comment by jstallm** [comment]
You can totally close this. I think I received a good satisfactory response on this. I appreciate it.
