### ISSUE TITLE
Different targetdirs for different reporttypes

### ISSUE THREAD

**Issue by pantosha** [danielpalme/ReportGenerator#379]
We use three report types for different purposes.
It will be nice to store result files in different folders to simplify the following processing, e.g. archiving.
A possible workaround is run reportgenerator several times, but it takes three times as long

Separate target dirs can be implemented with a pattern: `-targetdir:abc/{reporttype}/`
or additionals to report types: `-reporttypes:HtmlSummary,subpath=summary;Html,subpath=html`

**Comment by danielpalme** [comment]
Next release 4.6.6 will support the following setting / command line argument: settings:createSubdirectoryForAllReportTypes=true

See https://github.com/danielpalme/ReportGenerator/wiki/Settings

**Comment by pantosha** [comment]
It works! Thank you!

(Settings wiki page doesn't describe that command-line switch should start with `--`)

**Comment by danielpalme** [comment]
There are several options to pass parameters:
https://docs.microsoft.com/de-de/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#command-line-arguments
