### ISSUE TITLE
Do not save the generated Cobertura XML file with a UTF-8 BOM

### ISSUE THREAD

**Issue by ahsonkhan** [danielpalme/ReportGenerator#380]
Came across this when trying to make sure all files in our repo (including build artifacts) are ASCII-only:
https://github.com/Azure/azure-sdk-for-c/issues/1201
https://github.com/Azure/azure-sdk-for-c/pull/1199

```text
Validating that ./build/Cobertura.xml file only contains ASCII bytes...
1:﻿<?xml version="1.0" encoding="utf-8"?>
```

cc @danielpalme

**Comment by danielpalme** [comment]
Release 4.6.6 contains your PR.

**Comment by ahsonkhan** [comment]
Sweet!

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/danielpalme/ReportGenerator/pull/381
