### ISSUE TITLE
Add a filter for namespaces

### ISSUE THREAD

**Issue by manfred-brands** [danielpalme/ReportGenerator#385]
**Describe the bug**
Our assembly has internal  .NUnit classes in the same assembly as the actual code.
To get proper code coverage reports I would like to exclude `*.NUnit.*` classes as they skew the metrics.
I tried this with a `-classfilters:-*.NUnit.*` argument but this didn't work.

Debugging the issue, I found that the class filter is called with `ClassName` and not `FullName`
I misinterpreted that class name does not include namespace.
I managed to sort of get what I needed by using `-classfilters:-*Fixture`, but that doesn't catch all test classes.

To not break existing functionality, can we add an `-namespacefilters` argument?

I don't mind contributing this functionality myself.

**Comment by danielpalme** [comment]
It's more work to add this feature as you might expect:
- Add new filter to all [parsers ](https://github.com/danielpalme/ReportGenerator/tree/master/src/ReportGenerator.Core/Parser)for all coverage formats
- Update [help ](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Help.cs)inside of ReportGenerator
- Update[ Azure Devops task](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator)
- Update [Github Action](https://github.com/marketplace/actions/reportgenerator)
- Update [documentation](https://github.com/danielpalme/ReportGenerator/blob/master/README.md)
- Update [usage guide](https://danielpalme.github.io/ReportGenerator/usage.html)

**Comment by manfred-brands** [comment]
Thanks for pointing out all area. I will give it a go.

**Comment by manfred-brands** [comment]
I have implemented this for the `DynamicCodeCoverageParser` and updated all files, except the Azure Task/Github Action.

Whilst checking the other parsers, I noticed that all other parsers pass the full class name to the classfilter.

E.g. `DotCoverParser` combines them explicitly:
    Select(c => c.Parent.Attribute("Name").Value + "." + c.Attribute("Name").Value)
So does the `VisualStudioParser`:
    return c.Parent.Parent.Element("NamespaceName").Value + "." + fullname;

The `LCovParser` and `GCovParser` actually pass the fileName + *extension* to the class filter:
   string className = fileName.Substring(fileName.LastIndexOf(Path.DirectorySeparatorChar) + 1);

The `JaCoCoParser` passes items like `"test/AbstractClass_SampleImpl1"`. This might need stripping the `"test/"` prefix, but I don't know the format.

Only the `DynamicCodeCoverageParser` seems to explicitly separate them into a local `ClassWithNamespace` class.
This was added as part of issue #275.

So how do you want me to go on from here?
* Use the full name in the class filter for `DynamicCodeCoverageParser` to match the others?
* Split the full name in all other parsers into Namespace and ClassName and use two filters?

I have pushed up my work so far as a draft pull request https://github.com/danielpalme/ReportGenerator/pull/387

**Comment by danielpalme** [comment]
I would suggest, that `DynamicCodeCoverageParser` should match the behavior of the other parsers.
But let me review the different parsers and the changes of #275 before we continue.

**Comment by danielpalme** [comment]
I reviewed the code and the problem is, that the namespace is not considered in the filter.

By changing `.Where(c => this.ClassFilter.IsElementIncludedInReport(c.ClassName))` to `.Where(c => this.ClassFilter.IsElementIncludedInReport(c.FullName))` filtering by namespace should be fully supported as in the other parsers.

I guess adding a separate `namespace` filter is obsolete. But thanks for your effort!

**Comment by danielpalme** [comment]
Release 4.6.7 includes the fix.

**Comment by manfred-brands** [comment]
> I guess adding a separate `namespace` filter is obsolete. But thanks for your effort!
It is obsolete, but was a good exercise going through the code structure.

I only had suggested it based upon the one parser I was using and I didn't want to break that functionality, not realising that it was the only parser behaving that way. Maybe you can update the documentation to say that the class filter works on the full class name including namespace.

You probably want to fix the broken parsers:
> The `LCovParser` and `GCovParser` actually pass the fileName + _extension_ to the class filter:
> 
> ```cs
>    string className = fileName.Substring(fileName.LastIndexOf(Path.DirectorySeparatorChar) + 1);
> ```

Use `string className = Path.GetFileNameWithoutExtension(fileName);` instead.

**Comment by manfred-brands** [comment]
> Release 4.6.7 includes the fix.

Works properly with my original filter: `-*.NUnit.*`
