### ISSUE TITLE
Add a .editorconfig file

### ISSUE THREAD

**Issue by manfred-brands** [danielpalme/ReportGenerator#386]
**Make it easier for collaborators**
The current coding style inside ReportGenerator should be described in a .editorconfig file.
As it differs from my VS settings, I get warnings about the use of the 'this.' prefix.

To allow collaboration, I suggest that @danielpalme exports his VS settings
 (Tools->Options->Text Editor->C#->Code Style->Generate .editorconfig file from settings)

This ensures that collaborations from other developers use the same style.

**Comment by danielpalme** [comment]
See also: https://github.com/danielpalme/ReportGenerator/pull/383#issuecomment-688729315
