### ISSUE TITLE
Suggestion: Add Option To Disable PNG Badges

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [danielpalme/ReportGenerator#389]
When running in a Linux CI environment (like GitHub), the badges creation errors as Arial does not exist; it would be great if we could have an option to disable PNG badges so that the CI build doesn't fail as we cannot install other fonts.

**Comment by danielpalme** [comment]
The build / ReportGenerator should not fail.
A warning is printed but all SVG badges or other reports will be generated.

Does the build really fail?

**Comment by SamuelJohnsonMedia** [comment]
Ugh, I am so sorry ... I was looking and testing the wrong file and it was failing earlier on on something else. Sorry to waste your time; and thanks for the great project 👍
