### ISSUE TITLE
Is it possible to show coverage data in files instead of class?

### ISSUE THREAD

**Issue by kyocwn** [danielpalme/ReportGenerator#39]
Hi daniel,

Your tool is really cool. And I have created several code coverage reports using your open source tool. However, I am wondering whether it is possible to show the coverage information in terms of cpp files instead of class.

I am using VS2012 dynamic coverage file to generate the report. Sometimes I would feel more easier if you could list the coverage information for several classes defined in the same cpp file altogether. Now I could only see the coverage information for a specific class in a cpp file. All other classes are grayed out.

**Comment by danielpalme** [comment]
Theoretically it would to possible to change from "by class" view to a "by file" view. But this would require to change the entire code base.
It is best practice to only have one class per file (at least for C#, http://stackoverflow.com/questions/2434990/one-class-per-file-rule-in-net).
If you don't violate that rule, then "by file" or "by class" doesn't really matter.
