### ISSUE TITLE
assemblyfilters not working

### ISSUE THREAD

**Issue by steeve49** [danielpalme/ReportGenerator#394]
I'm currently trying to exlude a sub namespace from coverage using assemblyfilters but it doesn't work.
The issue is related to this one : https://github.com/danielpalme/ReportGenerator/issues/84

Testing libraries : 
- CoverletCollector 1.3.0
- Coverlet.MsBuild 2.9.0
- ReportGenerator 4.7.1
- XUnit 2.4.1

As you can see, I've checked that argument is passed to command line and all is ok (i've changed the root namespace name for confidentiality).

`##[debug]   C:\AgentsVSTS\agentJ\_work\_tasks\reportgenerator_be803a55-9253-4895-a525-be570d86f161\4.7.1\tools\netcoreapp2.1\ReportGenerator.dll

##[debug]   -reports:C:\AgentsVSTS\agentJ\_work\20\s/TestResults/Coverage/coverage.net461.json

##[debug]   -targetdir:C:\AgentsVSTS\agentJ\_work\20\s/CodeCoverage

##[debug]   -reporttypes:Cobertura;Badges;HtmlInline_AzurePipelines_Dark;HtmlChart

##[debug]   -sourcedirs:

##[debug]   -historydir:

##[debug]   -plugins:

##[debug]   -assemblyfilters:-xunit*;-RootNS.Common.Library.Clients.*

##[debug]   -classfilters:+*

##[debug]   -filefilters:+*

##[debug]   -verbosity:Info

##[debug]   -title:

##[debug]   -tag:20201020.10_#11409`

As you can see, my coverage still use the sub namespace :

![image](https://user-images.githubusercontent.com/61324521/96564217-2b575b00-12c3-11eb-8095-36a72e154649.png)

**Comment by danielpalme** [comment]
Please try a classfilter. The settings should look like:
```
-assemblyfilters:-xunit*
-classfilters:-RootNS.Common.Library.Clients.*
```

**Comment by steeve49** [comment]
Ok, just found why it wasn't working...

I'm using your reportgenerator (which is a great tool, thanks for all !) into a yaml pipeline in azure devops.
But, I didn't knew that there is an autogenerate option to disable to get the hand on the way the report is generated.

adding disable.coverage.autogenerate: 'true' into my pipeline template solved the issue and let me act on parameters...
Thanks
