### ISSUE TITLE
Combining Cobertura reports with relative filenames results in Cobertura report with absolute filenames

### ISSUE THREAD

**Issue by dennisverheijen** [danielpalme/ReportGenerator#395]
**Situation**
We use ReportGenerator to generate a single merged Cobertura report from a collection of individual Cobertura reports. The merged report is then published into Jenkins, to be used in the Cobertura plugin. 
The individual source reports have a relative path in the class\filename attribute, but the merged report has an absolute path in that same attribute.

**Background**
The Jenkins Cobertura plugin only displays the annotated source when the "class\filename" attribute has a *relative* path, relative to one of the absolute paths in `<sources><source>`. When the class\filename attribute has an *absolute* path, Jenkins can't locate the file and doesn't display it.

I expect that ReportGenerator retains the 'relativeness' of the filenames in the merged report.

Sample snippet of one of the input reports:
```
<coverage line-rate="0.0416" branch-rate="1" version="1.9" timestamp="1603393280" lines-covered="1" lines-valid="24" branches-covered="0" branches-valid="0">
  <sources>
    <source>D:\Jenkins\workspace\bla\src\</source>
  </sources>
  <packages>
    <package name="Bla.Messages" line-rate="0" branch-rate="1" complexity="2">
      <classes>
        <class name="Bla.Messages.UserLoggedInEvent" filename="Bla.Messages\UserLoggedInEvent.cs" line-rate="0" branch-rate="1" complexity="2">
```

Actual merged output report (snippet):
```
<coverage line-rate="0.17587939698492464" branch-rate="0.1111111111111111" lines-covered="35" lines-valid="199" branches-covered="6" branches-valid="54" complexity="89" version="0" timestamp="1603403717">
  <sources>
    <source>D:\Jenkins\workspace\bla\src\Bla.Utilities\</source>
    <source>D:\Jenkins\workspace\bla\src\</source>
    <source>D:\</source>
  </sources>
  <packages>
    <package name="Bla.Messages" line-rate="0" branch-rate="1" complexity="2">
      <classes>
        <class name="Bla.Messages.UserLoggedInEvent" filename="D:\Jenkins\workspace\bla\src\Bla.Messages\UserLoggedInEvent.cs" line-rate="0" branch-rate="1" complexity="2">
```
Notice that the filename attribute for the same file now has an absolute path.

Expected merged output report (snippet):
```
<coverage line-rate="0.17587939698492464" branch-rate="0.1111111111111111" lines-covered="35" lines-valid="199" branches-covered="6" branches-valid="54" complexity="89" version="0" timestamp="1603403717">
  <sources>
    <source>D:\Jenkins\workspace\bla\src\Bla.Utilities\</source>
    <source>D:\Jenkins\workspace\bla\src\</source>
    <source>D:\</source>
  </sources>
  <packages>
    <package name="Bla.Messages" line-rate="0" branch-rate="1" complexity="2">
      <classes>
        <class name="Bla.Messages.UserLoggedInEvent" filename="Bla.Messages\UserLoggedInEvent.cs" line-rate="0" branch-rate="1" complexity="2">
```

Using ReportGenerator 4.7.1 on Windows

**Comment by danielpalme** [comment]
That's not easy to fix.
See #356 and #238.

Maybe a litte Powershell script can convert the absolute path to relative paths afterwards?!

**Comment by dennisverheijen** [comment]
Ah, had not found those tickets yet. Thanks, this makes sense. I'll do a separate conversion.

**Comment by jhavlicek-profinit** [comment]
@danielpalme How about skipping automatic detection and having an extra parameter for the tool for expected root path to use for relative paths? In most cases, multiple test projects are in a same subdirectory.

It seems rather common situation and gitlab won't visualize code coverage in changes tab of merge request. It was rather hard to find the root cause and later find out that the merging tool doesn't support reasonable. Replacing attribute values through string replace is not ideal.
