### ISSUE TITLE
Visual Studio Extension

### ISSUE THREAD

**Issue by FortuneN** [danielpalme/ReportGenerator#396]
Hello,

I have been working on a Visual Studio extension (Fine Code Coverage) that is powered by Coverlet, OpenCover and ReportGenerator.
The goal of the extension is to visualize coverage output inside VS while you code and run tests.
It is free and open source.

[View in Github](https://github.com/FortuneN/FineCodeCoverage)
[View in Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage)

I would like to thank you for ReportGenerator which is a vital part of the Fine Code Coverage extension.
Also, i would also like to (shamefully) request a listing on your repo/blog/... for the benefit of ReportGenerator users who are interested in a Visual Studio extension that utilizes ReportGenerator.

I ask because i myself was using your Azure DevOps pipeline extension long before i knew i could run it as a CLI on my desktop.
I hope my efforts amplify yours for Visual Studio users.

I eagerly await any terms, conditions, suggestions or feedback that you may have for me.

Regards

**Comment by danielpalme** [comment]
Thanks for sharing!

I will add this to my README within the next days.

There are some other extensions with similar functionality, which might be interesting:

https://github.com/the-dext/RunCoverletReport

https://github.com/axodox/AxoCover
https://marketplace.visualstudio.com/items?itemName=axodox1.AxoCover

**Comment by FortuneN** [comment]
Thank you

**Comment by danielpalme** [comment]
Done:
https://github.com/danielpalme/ReportGenerator#visual-studio-extensions

**Comment by FortuneN** [comment]
Again; thank you, thank you, thank you
