### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator#397]
Hi @danielpalme.

Any plans/ETA for allowing the tool to work with .NET 5?
My use case will be not having to install .NET Core 3.1.x when using the [GitHub Action](https://github.com/marketplace/actions/reportgenerator).

Thanks!

**Comment by danielpalme** [comment]
Hi @eduherminio ,

yes I will add support for .NET 5 within the next days.
I want it so be ready once .NET 5 is finally released.

**Comment by danielpalme** [comment]
I made the necessary code changes to support .NET 5.

The publishing of all packages is done via Azure DevOps.
I hope the Azure DevOps build agents get MSBuild 16.8 soon, since it's required for .NET 5.
As soon as it gets available, I will publish the packages.

**Comment by danielpalme** [comment]
Azure DevOps is still missing MSBuild 16.8.
I decided to update ReportGenerator manually. Could you please try release 4.8.0:

- https://www.nuget.org/packages/ReportGenerator/4.8.0
- https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.8.0
- https://www.nuget.org/packages/ReportGenerator.Core/4.8.0
- https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator
- https://github.com/marketplace/actions/reportgenerator

**Comment by eduherminio** [comment]
I tried the Azure DevOps extension and it's still not working for me.
* [Commit](https://github.com/eduherminio/SheepTools/commit/dd060955ff37ae7eaa3f946b113a5a5b1413f647).
* [Empty report](https://dev.azure.com/eduherminio/SheepTools/_build/results?buildId=715&view=codecoverage-tab)
* [Previous commit report](https://dev.azure.com/eduherminio/SheepTools/_build/results?buildId=679&view=codecoverage-tab)

I checked that I have v4.8.0 recently installed in my organization, so it's the new version.
Do I have to wait for any specific coverlet versions?

**Comment by eduherminio** [comment]
GH Action, AzureDevOps app and dotnet global tool v4.8.0 tested and working as expected 👍
