### ISSUE TITLE
Wrong line coverage color and percentage in 'Methods/Properties' right container

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator#399]
**Describe the bug**

* All methods should appear as green in the `Methods/Properties` part.
* When hovering over them, a 100% coverage message should appear (it says 0% in the ones that appear as red).

![image](https://user-images.githubusercontent.com/11148519/98881928-6e07ef80-248b-11eb-875a-cd77456f69dd.png)

**To Reproduce**

Relevant files:
*  Original [coverage.cobertura.xml](https://github.com/danielpalme/ReportGenerator/files/5527612/coverage.cobertura.log) file (change extension to xml)
* Relevant page of the generated [`HtmlInline_AzurePipelines_Dark` report](https://github.com/danielpalme/ReportGenerator/files/5527618/SheepTools.XUnit_Asssert.log) (change extension to html)

It can be reproduced in [this workflow](https://github.com/eduherminio/SheepTools/actions?query=workflow%3ACI), and the full report can be downloaded from the latest master runs (such as [this one](https://github.com/eduherminio/SheepTools/actions/runs/358762406)).

---

It seems kind of a subtle bug, since it doesn't affect the actual covered/uncovered/coverable numbers or line coverage %, just that `Methods/Properties` part of the report; and I've only detected it in the described scenario. I guess it doesn't hurt to report it, though 😃

**Comment by danielpalme** [comment]
Thanks reporting this issue and the great sample repo.

The next release will contain a fix for this issue.

**Comment by eduherminio** [comment]
Awesome, thanks for the quick fix!

**Comment by danielpalme** [comment]
Release 4.8.1 is now available.
