### ISSUE TITLE
Coverable vs. Uncoverable lines

### ISSUE THREAD

**Issue by mmitche** [danielpalme/ReportGenerator#4]
This is a general question, rather than a direct bug report.

Basically I used the VS perf cmd tools to generate coverage data for a native executable, then converted that into xml using the built in visual studio APIs (wrote a quick custom tool to just save xml from the loaded coverage file).

I'm seeing some level of inconsistency in the report though.  It appears that there are times when ReportGenerator lists sections of code as not coverable when the code was simply clearly not covered.  I think this stems from the input xml though.  When reading methods from the input xml, does ReportGenerator assume that all methods not listed in the input are "not coverable"?

**Comment by danielpalme** [comment]
Methods that are not listed in the XML are listed as "not coverable".
I guess that your XML is not complete.

If you like, you can provide the XML and I will have a look.

There may be some other inconsistencies, but I don't think that a problem for you.
See here for an explanation:
http://reportgenerator.codeplex.com/discussions/549025#PostDetailsCell_1257465

**Comment by mmitche** [comment]
Thanks for the info.  I think it's the VS coverage exporter that's not correctly marking all the lines.  It's missing functions here and there.
