### ISSUE TITLE
Misleading coverage while using {get;set}

### ISSUE THREAD

**Issue by thomasmanalil** [danielpalme/ReportGenerator#407]
Report generator tool displays 100% line coverage even though Visual Studio coverage shows gaps. This happens when Setter is not covered for a property.

**To Reproduce**
Create a model class that has a property 
public string Field1 {get;set}
let the test case cover only get. and not set.
Run visual studio code coverage and convert it to html using reportgenerator tool. 
Visual studio coverage will highlight set is not covered, but html report shows 100% line coverage. 
**Setup**
ReportGenerator: 4.8.4.0
Visual Studio 2019 Enterprise

**Comment by danielpalme** [comment]
The problem here is, that the XML report does not contain enough details to track coverage of get/set individually.
It only contains information line by line.
ReportGenerator counts the visits per line and since the line is visited, it is marked green.
I guess there's now way to improve that.

**Comment by thomasmanalil** [comment]
ok. I thought that could be the reason. But somehow visual studio is able to detect it though.
