### ISSUE TITLE
Not generating the Reports on build server

### ISSUE THREAD

**Issue by nagtilaklaxman** [danielpalme/ReportGenerator#409]
![image](https://user-images.githubusercontent.com/16507190/110245035-beb0d480-7fb5-11eb-9092-6dc1376d613b.png)

ReportGenerator giving an exec format error on the build server.
I have used the Cake build file 
![image](https://user-images.githubusercontent.com/16507190/110245126-16e7d680-7fb6-11eb-9761-3408a4d1ddac.png)

It works fine on local windows system

**Comment by danielpalme** [comment]
Hard to tell with so few details.

Which Nuget package of ReportGenerator are you using?
Which DLL / EXE are you actually executing?

If you use the e.g. `net5.0\ReportGenerator.exe` make sure that the runtime is installed.

**Comment by nagtilaklaxman** [comment]
@danielpalme 
I am using cake build and GitLab pipeline to run where it is failing

![image](https://user-images.githubusercontent.com/16507190/110270387-cc984100-8019-11eb-88b0-bb32f7723cde.png)

Below is the yml of gitlab
![image](https://user-images.githubusercontent.com/16507190/110270522-213bbc00-801a-11eb-9b68-e9bd373ecc4e.png)

**Comment by danielpalme** [comment]
The package https://www.nuget.org/packages/ReportGenerator you are using, contains several versions:

```
netcoreapp2.0\ReportGenerator.dll

netcoreapp2.1\ReportGenerator.dll

netcoreapp3.0\ReportGenerator.dll
netcoreapp3.0\ReportGenerator.exe

net5.0\ReportGenerator.dll
net5.0\ReportGenerator.exe

net47\ReportGenerator.exe
```

Which versions does get executed by cake? In your scenario (Docker, .NET 5), I would suggest:

```
dotnet net5.0/ReportGenerator.dll -reporttypes:Html -targetdir:coveragereport -reports:YOUR_COVERAGE_FILE
```

**Comment by nagtilaklaxman** [comment]
@danielpalme 
I am using ReportGenerator 4.7.922
![image](https://user-images.githubusercontent.com/16507190/110295015-b5bb1400-8044-11eb-94bd-a079356042a0.png)

**Comment by danielpalme** [comment]
And which executable / DLL in the tools folder (see my list above)?

**Comment by nagtilaklaxman** [comment]
![image](https://user-images.githubusercontent.com/16507190/110298545-d1281e00-8048-11eb-8619-3733a5a06fa4.png)

**Comment by danielpalme** [comment]
Probably the same issue as #313

I tried to reproduce this issue last year. I documented my steps here:
https://github.com/danielpalme/ReportGenerator/issues/313#issuecomment-619091354

Result: I was not able to reproduce the issue.

Perhaps you can setup a minimum sample project (or use [mine](https://github.com/danielpalme/ReportGenerator/files/4529973/docker.zip) from last year).

**Comment by nagtilaklaxman** [comment]
@danielpalme 

I have created a sample project for you.. Can you check the below project?
https://gitlab.com/nagtilaklaxman/cicddemo/-/tree/master

**Comment by danielpalme** [comment]
Thanks for the sample repo! Will have a look as soon as possible.

**Comment by danielpalme** [comment]
Just wanted to setup an agent, but now your sample project is gone.
Can you share it again?

**Comment by nagtilaklaxman** [comment]
Sorry for the inconvenience. 
I have updated the link. Can you check it 
https://gitlab.com/myself56/cicddemo/-/tree/master

**Comment by danielpalme** [comment]
Your link seems to be broken or only available when you are logged in.

**Comment by nagtilaklaxman** [comment]
@danielpalme 
Now you should be able to access it.
Let me know if you still can't access the link.

**Comment by danielpalme** [comment]
Thanks. I'm able to reproduce the problem.
Will try to figure out what's wrong within the next days.

**Comment by danielpalme** [comment]
I was able to resolve your issue.

If you use the following "Report-Generation" task definition, it works:
```cake
Task("Report-Generation")
  .IsDependentOn("Test")
  .Does(()=>
  {
              var reportSettings = new ProcessArgumentBuilder();
              reportSettings.Append($"-targetdir:" + reportsDirectory);
              reportSettings.Append($"-reports:" + coverageFilePath);

              var toolpath = Context.Tools.Resolve("net5.0/ReportGenerator.dll");
              Information($"Tool Path : {toolpath.ToString()}");

              DotNetCoreExecute(toolpath, reportSettings);
  });
```

You can't execute `ReportGenerator.dll` directly. Instead you have to execute `dotnet ReportGenerator.dll ...`.

Another option might be, to use the global tool: https://www.nuget.org/packages/dotnet-reportgenerator-globaltool

**Comment by nagtilaklaxman** [comment]
@danielpalme 
Thanks ...
But it should work with ReportGenerator in all OS

**Comment by danielpalme** [comment]
ReportGenerator does work on all OS. There's no limitation as it is a .NET Core application which is platform independent.  
But you have to execute it correctly.

**Comment by nagtilaklaxman** [comment]
@danielpalme 
Thanks for the help.
Any way to execute the following code in each OS.
It is very easy to use rather than focusing on commands to execute.
It works perfectly on windows.
```
Task("Report-Generation")
  .IsDependentOn("Test")
  .Does(()=>
  {
         
             var reportSettings = new ReportGeneratorSettings
            {
                ArgumentCustomization = args => args.Append($"-reportTypes:Html")
            };
          
            ReportGenerator(coverageFilePath, reportsDirectory, reportSettings);
  });

**Comment by danielpalme** [comment]
I'm not familiar with _Cake_.
I guess the command `ReportGenerator(...)` works on Windows, because the directory contains an executable (net5.0\ReportGenerator.exe).

On Linux though you can't run an executable.

If you use `DotNetCoreExecute(toolpath, reportSettings);` it works on all operating systems, since this command results in `dotnet ReportGenerator.dll ...`
