### ISSUE TITLE
Differences with OpenCover.xml

### ISSUE THREAD

**Issue by labilbe** [danielpalme/ReportGenerator#41]
Hi,

Is there a way to display OpenCover sequence points data in ReportGenerator?
Please see this [discussion](https://github.com/OpenCover/opencover/issues/558) for more information about the problem I'm facing.

Thanks!

**Comment by danielpalme** [comment]
That's not possible. _ReportGenerator_ maps sequence points to the corresponding line(s).
Additionally it shows information about covered branches.

If you want to get a high coverage, do the following:
1. Reduce number of uncovered lines
2. If all (important) lines are covered, make sure that all (important) branches are covered.

**Comment by labilbe** [comment]
Got it! Thanks!
