### ISSUE TITLE
Colors to bright after running the reportgenerator

### ISSUE THREAD

**Issue by ByteDecoder** [danielpalme/ReportGenerator#411]
**Describe the bug**
After running the reportgenerator in the command line, always output the text with bright colors. Will be nice if there is a way to lower the contrast to be more friendly with the eyes. 

**To Reproduce**
dotnet reportgenerator "-reports:../coverage/lcov.info" "-reporttypes:HTMLInline;Badges" "-targetdir:../coverage/report"

![colors to bright](https://user-images.githubusercontent.com/11826115/112566760-3304b980-8da5-11eb-8c43-96a9e5c8b7f5.png)

**Comment by danielpalme** [comment]
I'm just using `ConsoleColor.White`.  
If I would use gray or similar, somebody would complain, that the contrast is not high enough.

So I guess I won't change the color.
