### ISSUE TITLE
Cobertura.xml line coverage and Report Generator html file line coverage are different

### ISSUE THREAD

**Issue by Dhruv-1982** [danielpalme/ReportGenerator#413]
Hi

I am using open cover to run unit tests and Code coverage. Using opencovertocobertura converter for converting it to cobertura.xml file and Report generator for generating Html report. But i found line coverage are different in Cobertura.xml and Reportgenerator generated html file. Below are the screenshots of the two files

![CodeCoverage Report](https://user-images.githubusercontent.com/73667626/114404247-26fd6200-9bc3-11eb-94a4-9fec850dad27.JPG)
![Cobertura report](https://user-images.githubusercontent.com/73667626/114404637-822f5480-9bc3-11eb-8df8-3c87c10fa356.JPG)
![Reportgenerator html](https://user-images.githubusercontent.com/73667626/114404658-85c2db80-9bc3-11eb-87c0-d6fcbb6b52d8.JPG)

**Comment by danielpalme** [comment]
I would recommend to not use [OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter) any more.

Instead you can use ReportGenerator to generate both files, use `-reportTypes:Html;Coberatura` to generate HTML and Coberatura reports. The numbers should be consistent if you do so.
