### ISSUE TITLE
Command line parsing

### ISSUE THREAD

**Issue by Keboo** [danielpalme/ReportGenerator#417]
Hi,

First, thank you for this great tool. I was using the [global tool](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool). However, I was disappointed to find that the command line argument parsing was a bit un-usual (requiring arguments to be quoted). I was wondering if there would be any interest in a PR where the command line parsing was updated to use [SystemCommandLine](https://github.com/dotnet/command-line-api). This would provide the following benefits:
- Arguments would no loner be required to be quoted (unless there were spaces in the name/value)
- Built in support for things like `--version` and context specific `--help`
- [Tab completion support](https://github.com/dotnet/command-line-api/blob/main/docs/Features-overview.md#Suggestions)

If this is something that would be considered I am happy to provide a PR for evaluation.

**Comment by danielpalme** [comment]
You don't have to quote command line arguments if they don't contain spaces. It should work without. I only use quotes if a value contains any spaces.  
The `System.CommandLine` package look promising. Migrating the current parameter handling to another library may be more difficult than you may expect. Over time several issues regarding parameter handling, validation support for DotNetConfig were implemented. By changing the implementation you may easily break some behavior).

**Comment by rcollette** [comment]
For me this fails:
```bash
reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:reports/coverage" -reporttypes:Latex;HtmlSummary
```
with the message "HtmlSummary: command not found"

but this works:
```bash
reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:reports/coverage" "-reporttypes:Latex;HtmlSummary"
```

**Comment by danielpalme** [comment]
@rcollette 
Thanks for your example. Now I'm able to reproduce the problem.
The problem is the semicolon in the last parameter.

This is not related to _ReportGenerator_. It's caused by _Powershell_. You have to use quotes or you can escape the semicolon with `;

See also: https://stackoverflow.com/questions/10131021/make-powershell-ignore-semicolon

**Comment by rcollette** [comment]
Is powershell embedded?   I'm on a Mac.

**Comment by danielpalme** [comment]
I'm on Windows. I guess the shell on macOS has the same "problem" as Powershell.
With the Windows CMD it works without quotes.
