### ISSUE TITLE
Report fails when using partial C# classes

### ISSUE THREAD

**Issue by gregveres** [danielpalme/ReportGenerator#42]
Hi, 

Great tool. Thank you for providing it. 

When developing ASP.Net MVC apps, I have been using a pattern for my viewmodels where I have the main viewmodel class in ControllerViewmodel.cs for a given Controller . Then when I need a specific viewmodel for a particular action of the controller, I use a partial class as an extension and put the new viewmodel class with this extension in ControllerViewmodel_action.cs. This works really well for organizing the code, but what I have found is that the generated coverage report claims that the portion of ControllerViewmodel found in ControllerViewmodel_action.cs is not covered. 

I am also using OpenCover.UI to see the coverage in the GUI of VS. That tool properly shows that the partial class of ControllerViewmodel that is found in ControllerViewmodel_action is covered properly. So this must be a problem with the report generation rather than a problem with OpenCover. 

Here is a sample of the C# code that represents what I am doing:

In ControllerViewmodel.cs:

```
public partial class ControllerViewmodel {
    public int X { get; set; }
    public ControllerViewmodel {
          X = 1;
    }
}
```

Then in ControllerViewmodel_action.cs

```
public class ControllerViewmodel_action {
    public int X {get; set; }
    public int Y {get; set; }
}

public partial class ControllerViewmodel {
     public ControllerViewmodel_action getY () {
           var returnVM = new ControllerViewmodel_action();
           returnVM.X = X;
           returnVM.Y = 2 * X;
     }
}

```

I then have unit tests that will test the code in ControllerViewmodel_Action.cs 100%. When I run OpenCover in OpenCover.UI, it correctly shows me that all the code in ControllerViewmodel_Action.cs is covered. But when I run the OpenCover on the same code and generate the report with ReportGenerator, the only lines of code that are shown as being cover are those of the ControllerViewmodel_action class. The getY function is shown as not being covered. 

Thanks
Greg

**Comment by danielpalme** [comment]
Do you have a sample project which you can share?

**Comment by gregveres** [comment]
I created a project using the code from the issue. I am using VS2015 Update 1. I think if you unzip the attached file, it should have everything to run and see the issue. I installed OpenCover and ReportGenerator using nuget and the batch file to run them refers to their location in the project. 

Now that I have a very small example, I can see that the summary screen reports 100% coverage in both classes, but when I drill into the ControllerViewmodel_action.cs file, I see no coverage indicated on the ControllerViewmodel method that is in that file. 

Thanks for looking at this
Greg


[ReportGeneratorProblem.zip](https://github.com/danielpalme/ReportGenerator/files/172786/ReportGeneratorProblem.zip)

**Comment by gregveres** [comment]
I created a project using the code from the issue. I am using VS2015 Update 1. I think if you unzip the attached file, it should have everything to run and see the issue. I installed OpenCover and ReportGenerator using nuget and the batch file to run them refers to their location in the project. 

Now that I have a very small example, I can see that the summary screen reports 100% coverage in both classes, but when I drill into the ControllerViewmodel_action.cs file, I see no coverage indicated on the ControllerViewmodel method that is in that file. 

Thanks for looking at this
 Greg
[ReportGeneratorProblem.zip](https://github.com/danielpalme/ReportGenerator/files/172790/ReportGeneratorProblem.zip)

**Comment by danielpalme** [comment]
It should work if you remove the "-skipautoprops" when executing OpenCover.
If you use this option, you are telling OpenCover to exclude auto properties. Therefore also ReportGenerator ignores auto properties.

**Comment by gregveres** [comment]
Hi Daniel

I don't think this has anything to do with -skipautoprops. Here is another version of the project but this time I didn't use autoprops. I created my own accessor methods. Notice that the unit test calls ControllerViewmodel::getActionViewmodel() but the report doesn't say that it does. 

Here is the new copy of the project that doesn't use autoprops. And I removed the -skipautoprops flag from the OpenCover command line. It still didn't show those lines covered. (the attached project still has the -skipautoprops flag, but after I zipped it up, I did a run without the flag and there was no difference)


[ReportGeneratorProblem.zip](https://github.com/danielpalme/ReportGenerator/files/172917/ReportGeneratorProblem.zip)

**Comment by gregveres** [comment]
I see that OpenCover has noted that getActionViewmodel was called:

```
-<Method branchCoverage="100" sequenceCoverage="100" isSetter="false" isGetter="false" isStatic="false" isConstructor="false" nPathComplexity="0" cyclomaticComplexity="1" visited="true">

<Summary numMethods="1" visitedMethods="1" numClasses="0" visitedClasses="0" minCyclomaticComplexity="1" maxCyclomaticComplexity="1" branchCoverage="100" sequenceCoverage="100" visitedBranchPoints="1" numBranchPoints="1" visitedSequencePoints="4" numSequencePoints="4"/>

<MetadataToken>100663300</MetadataToken>

<Name>ReportGeneratorProblem.ViewModels.ControllerViewmodel_action ReportGeneratorProblem.ViewModels.ControllerViewmodel::getActionViewmodel(System.Int32)</Name>

<FileRef uid="3"/>


-<SequencePoints>

<SequencePoint fileid="3" bev="0" bec="0" ec="10" el="12" sc="9" sl="12" offset="0" ordinal="0" uspid="8" vc="1"/>

<SequencePoint fileid="3" bev="0" bec="0" ec="60" el="13" sc="13" sl="13" offset="1" ordinal="1" uspid="9" vc="1"/>

<SequencePoint fileid="3" bev="0" bec="0" ec="24" el="15" sc="13" sl="15" offset="14" ordinal="2" uspid="10" vc="1"/>

<SequencePoint fileid="3" bev="0" bec="0" ec="10" el="16" sc="9" sl="16" offset="18" ordinal="3" uspid="11" vc="1"/>

</SequencePoints>

<BranchPoints/>

<MethodPoint fileid="3" bev="0" bec="0" ec="10" el="12" sc="9" sl="12" offset="0" ordinal="0" uspid="8" vc="1" xsi:type="SequencePoint"/>

</Method>
```

but I also see from the XML code that it isn't telling you which file those methods are in. I assume you have some logic to try to find which file a method is in. It appears that heuristic isn't working in the presence of partial classes.

**Comment by danielpalme** [comment]
Please have a look at both files (ReportGeneratorProblem_ControllerViewmodel.htm and ReportGeneratorProblem_ControllerViewmodel_action.htm).
Each of them contains the content of the file _ControllerViewmodel_action.cs_.
If you look at ReportGeneratorProblem_ControllerViewmodel.htm, you will see that the method _getActionViewmodel_ is correctly covered.
In ReportGeneratorProblem_ControllerViewmodel_action.htm it is not marked as covered. This is due to the fact, that this method belongs to the partial class _ControllerViewmodel_.
Each HTML file shows the coverage for exactly **ONE** class. If other classes are defined in the same file(s), then they get ignored.

I also switched back to auto properties. This works too, if "-skipautoprops" is not used.
The report is correct, but you have to make sure, that you look at the correct class.
[Report_AutoProperties.zip](https://github.com/danielpalme/ReportGenerator/files/174703/Report_AutoProperties.zip)

**Comment by gregveres** [comment]
Ah I see how that works. Sorry for the confusion, I expected each report to be based on file, not class. But now that I now it is based on class, this makes complete sense. 

Thank you for pointing that out and sorry for thinking it was a bug. 
Greg
