### ISSUE TITLE
Output in OpenCover format

### ISSUE THREAD

**Issue by ardalis** [danielpalme/ReportGenerator#420]
I'm trying to use NDepend support for code coverage analysis. NDepend wants its input in OpenCover format (or NCrunch, DotCover, or NCover):
https://www.ndepend.com/docs/code-coverage#OpenCoverFile

ReportGenerator currently supports OpenCover as an input type, but not as an output type:

![image](https://user-images.githubusercontent.com/782127/115893372-18fedb00-a426-11eb-80f7-a0382193b60c.png)

You even have a dedicated tool to go that direction:
https://github.com/danielpalme/OpenCoverToCoberturaConverter

Do you have support for going the other direction, from Cobertura to OpenCover (or simply from ReportGenerator to OpenCover)?

And if not, any suggestions? Thanks!

**Comment by danielpalme** [comment]
I have to verify if all information that is expected in an OpenCover file is actually available.
Will have a look if this within the next days.

**Comment by danielpalme** [comment]
I just took a closer look at the _OpenCover_ format. It contains much more details than e.g. a Cobertura file.
I can't produce this XML format based on the information that is available. Too many attributes would not be available.

In my opinion it would make much more sense to add support for `Cobertura` files to NDepend.

Another option: If you are using [coverlet](https://github.com/coverlet-coverage/coverlet/) you can also generate coverage reports in OpenCover format.
Downside: You can't merge several files into one.
