### ISSUE TITLE
Multiple code coverage reports merged, published showing no data in Azure DevOps pipeline

### ISSUE THREAD

**Issue by msrinivascharan** [danielpalme/ReportGenerator#421]
Hi Team… 

I am using ReportGenerator task in my Azure DevOps to merge Cobertura based code coverage reports into one, end up with empty reports in pipeline CodeCoverage tab.

Below is my pipeline with three jobs.

Job1 – uses Windows agent pool1, builds java- (clean compile, test, cobertura:cobertura ), if build success, saves test reports, code coverage reports (only xml) to Azure pipeline artifacts.

Job2 – uses Windows agent pool2, builds .NET core- (restore, test, coverlet reports in Cobertura format), if build success, saves test reports, code coverage reports (only xml) to Azure pipeline artifacts.

Job3 - uses Windows agent pool3, downloads test and multiple coverage reports uploaded from previous jobs, merges all Cobertura reports into one using ReportGenerator. Publish code coverage reports.

But, if I go and see the Code Coverage report tab pipeline, assemblies, classes, files, package names data is there but no coverage data, when I click on a particular package class name it’s empty and showing “ ’/some relative path/ abc.java’ does not exist (any more)”.
Please suggest.

**Comment by msrinivascharan** [comment]
Hi Team.. I tried copying source code also from job1 agent to job3 agent, it's working now. I can see complete report. 

Is there any other option, to avoid copying huge amount of a multimodule project code between jobs ? please suggest.

Thank you.

**Comment by danielpalme** [comment]
Great that you were able to find a solution.
ReportGenerator needs the source code in order to create a complete report.  
There is no way to avoid that.

**Comment by msrinivascharan** [comment]
Thanks for the confirmation @danielpalme .
