### ISSUE TITLE
Support for extended glob pattern

### ISSUE THREAD

**Issue by lamLeX** [danielpalme/ReportGenerator#422]
**Describe the bug**
Although globing is supported here https://github.com/danielpalme/ReportGenerator/issues/161
Reportgenerator does not support extended pattern such as `[Tt]est?(s)`.  The pattern is expected to match `test`, `tests`, `Test`, `Tests` but it doesn't match any of those

**Comment by danielpalme** [comment]
Just use `*est*` and it should match all expected names.
