### ISSUE TITLE
FR: default value of grouping specified at generation time

### ISSUE THREAD

**Issue by gregveres** [danielpalme/ReportGenerator#43]
HI

I don't see a way to set the default value of the grouping slider on the html report. It would be very useful to have the grouping slider start all the way to the right as that is my preferred method of looking at the report. 

I would be happy to specify this on the report generation command line.

Thanks
Greg

**Comment by danielpalme** [comment]
I'm sorry, but that's a very specific requirement.
You should use a [custom report](https://github.com/danielpalme/ReportGenerator/wiki/Custom-reports).

This would be the easiest way to solve your problem:


```
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;
using Palmmedia.ReportGenerator.Parser.Analysis;
using Palmmedia.ReportGenerator.Properties;
using Palmmedia.ReportGenerator.Reporting;
using Palmmedia.ReportGenerator.Reporting.Rendering;

namespace MyCompany.CustomReportTypes
{
    [System.ComponentModel.Composition.Export(typeof(IReportBuilder))]
    public class CustomHtmlReportBuilder : HtmlReportBuilder
    {
        public override void CreateSummaryReport(SummaryResult summaryResult)
        {
            base.CreateSummaryReport(summaryResult);

            string javascriptPath = Path.Combine(this.TargetDirectory, "combined.js");

            string content = File.ReadAllText(javascriptPath)
                .Replace("grouping: '0',", "grouping: this.getGroupingMaximum(this.props.assemblies),");

            File.WriteAllText(javascriptPath, content);
        }
    }
}
```

**Comment by gregveres** [comment]
Thank you I will give this a try.

**Comment by gregveres** [comment]
thanks for the suggestion on this. It doesn't work. I can see that it properly sets the initial value of the grouping variable in the js. And the page does come up with that value as the value for grouping. But the initialization of the page doesn't respect the variable so the result is that I have to switch the grouping to something else, the come back to the max value. 

I am going to look through the code to see if I can fix the issue where the page init doesn't respect the initial grouping value.

**Comment by gregveres** [comment]
Found the problem. The function needs to be changed in two locations:
        return {
            grouping: this.getGroupingMaximum(this.props.assemblies),
            groupingMaximum: this.getGroupingMaximum(this.props.assemblies),
            filter: '',
            sortby: 'name',
            sortorder: 'asc',
            assemblies: this.getAssemblies(this.props.assemblies, '0', '', 'name', 'asc')
};

The call to getAssemblies needs to have the '0' changed to "this.getGroupingMaximum(this.props.assemblies)" as well. 

Recording this here incase it helps somebody else in the futrue. 

Greg

**Comment by gregveres** [comment]
The final solution that I went with is working great with this code for a plugin:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;
using Palmmedia.ReportGenerator.Parser.Analysis;
using Palmmedia.ReportGenerator.Properties;
using Palmmedia.ReportGenerator.Reporting;
using Palmmedia.ReportGenerator.Reporting.Rendering;

namespace MyCompany.CustomReportTypes
{
    [System.ComponentModel.Composition.Export(typeof(IReportBuilder))]
    public class ComponentExpandedReportBuilder : HtmlReportBuilder
    {
        public override void CreateSummaryReport(SummaryResult summaryResult)
        {
            base.CreateSummaryReport(summaryResult);

            string javascriptPath = Path.Combine(this.TargetDirectory, "combined.js");

            string content = File.ReadAllText(javascriptPath)
                .Replace("getInitialState: function () {", "getInitialState: function () { var maxGroup = this.getGroupingMaximum(this.props.assemblies);")
                .Replace("grouping: '0',", "grouping: maxGroup,")
                .Replace("groupingMaximum: this.getGroupingMaximum(this.props.assemblies)", "groupingMaximum: maxGroup")
                .Replace("assemblies: this.getAssemblies(this.props.assemblies, '0', '', 'name', 'asc')",
                "assemblies: this.getAssemblies(this.props.assemblies, maxGroup, '', 'name', 'asc')");

            File.WriteAllText(javascriptPath, content);
        }
    }
}
```
