### ISSUE TITLE
Feature request: add limit on persistent coverage information

### ISSUE THREAD

**Issue by adriangodong** [danielpalme/ReportGenerator#44]
We're running OpenCover and ReportGenerator on each PR and the amount of data is growing to a point it takes a minute plus to parse historical coverage info supplied via -historydir argument.

I propose a set of new arguments that limits how may items are loaded:
`-historymax:<maximum items to read>`
`-prunehistory:<true|false>` -- if true, limit file count in `historydir` to `historymax`, keep newest

I can write the code change and PR back to this repository but would love to get some information on whether this makes sense or any alternative approach that I should write instead.

**Comment by danielpalme** [comment]
Thanks for your suggestion. Definitely a good idea.

I try to avoid too many command line parameters. 
Perhaps a fixed maximum of historic files is a better idea.

Can you tell me how many historical coverage files you have in your system and how long does it take to parse them all?

**Comment by adriangodong** [comment]
I've trimmed down the files to 100 and it took 24 seconds to parse. Relevant sample log:
`22:24:52 Reading historic reports`
`22:25:17 Initializing report builders for report types: Html, PNGChart`

Maximum 50 files sounds like a reasonable balance between history and load time.

**Comment by danielpalme** [comment]
It now limited to 100 files by default. If you want to adjust the limit, you can do this in _ReportGenerator.exe.config_.

**Comment by jatouma** [comment]
I have not been able to increase the 100 files limit. I have tried changing the value in the config file to 300, but my history report still shows 100 only. Does ReportGenerator not support increasing that maximum value? From skimming through the code, seems like this should work.
