### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by HaroonSaid** [danielpalme/ReportGenerator#440]
In a typical project folder, we have lots of test projects,  I want to get a report of all coverage reports into a single report

The command to create the coverage file is 
```
test-int: 
	@dotnet test ${SLN} \
	--collect:"XPlat Code Coverage" \
	--logger:"xunit;LogFileName=TestResults.xml" \
	--logger:"console;verbosity=detailed" \
	--logger:"trx;LogFileName=TestResults.trx" \
	-- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover \
	-- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude=[xunit.*]* 
```
This creates files in `tests/unit/**/TestResults/uuid/coverage.opencover.xml` 

How can I create a report for all of code coverage files?

**Comment by danielpalme** [comment]
The following comand should work for you:

```
ReportGenerator.exe -reports:tests/unit/**/TestResults/*/coverage.opencover.xml -reporttypes:Html -targetdir:coveragereport
```

**Comment by HaroonSaid** [comment]
Thanks - is there a linux version? 
All of our code is dotnet core running on linux

**Comment by danielpalme** [comment]
Yes. You can use the global tool:
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool
