### ISSUE TITLE
Enhancement: Please add Method Coverage to the report

### ISSUE THREAD

**Issue by dberry-rcs** [danielpalme/ReportGenerator#441]
Please add method coverage to the report.

dotnet test shows it when it generates the cobertura file. It would be nice to have this in report generator as well.

Calculating coverage result...
  Generating report '.\bin\test-results\coverage.cobertura.xml'

+----------------------------------+--------+--------+--------+
| Module                           | Line   | Branch | Method |
+----------------------------------+--------+--------+--------+
| RCS.Libs.LoggingMessageInspector | 95.46% | 92.85% | 97.22% |
+----------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 95.46% | 92.85% | 97.22% |
+---------+--------+--------+--------+
| Average | 95.46% | 92.85% | 97.22% |
+---------+--------+--------+--------+

**Comment by dberry-rcs** [comment]
I am using the markdown summary so I do not get the coverage graphs. I would like to see it as additional columns. Are both the coverable and total lines columns necessary? Personally, I am not interested in lines that are not coverable. I could see one totals column with the coverables number, or just covered and uncovered.

**Comment by danielpalme** [comment]
Great. With MarkdownSummary there is no problem.
Here is a sample report:

# Summary
|||
|:---|:---|
| Generated on: | 21.09.2021 - 22:06:40 |
| Parser: | OpenCoverParser |
| Assemblies: | 1 |
| Classes: | 18 |
| Files: | 15 |
| Covered lines: | 131 |
| Uncovered lines: | 63 |
| Coverable lines: | 194 |
| Total lines: | 508 |
| Line coverage: | 67.5% (131 of 194) |
| Covered branches: | 5 |
| Total branches: | 8 |
| Branch coverage: | 62.5% (5 of 8) |
| Covered methods: | 35 |
| Total methods: | 55 |
| Method coverage: | 63.6% (35 of 55) |

|**Name**|**Covered**|**Uncovered**|**Coverable**|**Total**|**Line coverage**|**Covered**|**Total**|**Branch coverage**|**Covered**|**Total**|**Method coverage**|
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
|**Test**|**131**|**63**|**194**|**665**|**67.5%**|**5**|**8**|**62.5%**|**35**|**55**|**63.6%**|
|Test.AbstractClass|4|0|4|54|100%|0|0||1|1|100%|
|Test.AbstractClass_SampleImpl1|4|4|8|54|50%|0|0||1|3|33.3%|
|Test.AbstractClass_SampleImpl2|4|4|8|54|50%|0|0||1|3|33.3%|
|Test.AbstractGenericClass`2|0|3|3|49|0%|0|0||0|1|0%|
|Test.AnalyzerTestClass|0|11|11|48|0%|0|0||0|5|0%|
|Test.AsyncClass|4|0|4|15|100%|0|0||1|1|100%|
|Test.ClassWithExcludes|8|0|8|22|100%|0|0||6|6|100%|
|Test.CodeContract_Contract|0|4|4|16|0%|0|0||0|1|0%|
|Test.CodeContract_Target|7|0|7|18|100%|2|2|100%|1|1|100%|
|Test.CoverageExcludeAttribute|0|0|0|0||0|0||0|0||
|Test.GenericClass`2|8|0|8|49|100%|0|0||2|2|100%|
|Test.PartialClass|12|10|22|53|54.5%|1|2|50%|3|6|50%|
|Test.PartialClassWithAutoProperties|2|1|3|18|66.6%|0|0||4|5|80%|
|Test.Program|41|3|44|84|93.1%|0|0||6|6|100%|
|Test.SomeClass|1|0|1|8|100%|0|0||2|2|100%|
|Test.SomeModel|0|0|0|0||0|0||0|0||
|Test.TestClass|12|9|21|38|57.1%|1|2|50%|1|2|50%|
|Test.TestClass2|24|14|38|85|63.1%|1|2|50%|6|10|60%|

**Comment by danielpalme** [comment]
Release 4.8.13 is now available, you could give it a try.
