### ISSUE TITLE
Reportgenerator skips particular project coverage when converting to Cobertura and Sonar formats

### ISSUE THREAD

**Issue by Sergey1209** [danielpalme/ReportGenerator#444]
Strangely noticed, that for my solution with 100+ projects, one of them is skipped by Reporgenerator.

I convert the raw report generated by dotCover into 3 formats: Cobertura, SonarQube and HtmlInline_AzurePipelines.

Interesting fact, that coverage for this project do exist in HTML report, but both Cobertura and SonarQube don't show it up. The rest projects are being exported correctly (from the first glance) to all aforementioned formats.

**Comment by danielpalme** [comment]
Some more details would be helpful. Can you share your coverage files and the name of the missing project? You can also send the coverage files privately by email (reportgenerator@palmmedia.de).

**Comment by Sergey1209** [comment]
Sure, will send them out once i get fresh version of them

**Comment by danielpalme** [comment]
Any update on this?

**Comment by danielpalme** [comment]
Thanks for the feedback!
