### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by RoadTrain** [danielpalme/ReportGenerator#445]
Hello! Thanks for the great library.

I've been using it in my application for a while via nuget package `ReportGenerator.Core`, and now I wonder how to set up logging in a way that internal library logs are not printed to console, but instead redirected to the application-level logger (I'm using Serilog).

Is there a way to configure that? From what I see from source code, class loggers are resolved once, and are stored in static fields, which will prevent runtime reconfiguration.

Am I missing something?

**Comment by danielpalme** [comment]
That's correct. The logger is currently not configurable.

**Comment by RoadTrain** [comment]
@danielpalme Would you welcome contributions to make it configurable? Maybe you already have a vision of how it should be done?

**Comment by danielpalme** [comment]
Sorry, my initial reply was wrong or at least not complete.

You can implement a custom [Logger](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Logging/ILogger.cs) and custom [LoggerFactory](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Logging/ILoggerFactory.cs).

Then you can register your custom factory:
```csharp
LoggerFactory.Configure(new MyCustomLoggerFactory());
```

That way you should be able to write a custom adapter to your logging system.

**Comment by danielpalme** [comment]
Sure, that should be no problem.

**Comment by danielpalme** [comment]
I created a draft here: #446 
What do you think?
