### ISSUE TITLE
Shut down after the launch

### ISSUE THREAD

**Issue by Yefimov** [danielpalme/ReportGenerator#45]
I cloned ReportGenerator from this repository, then compiled it on my VisualStudio 2015 and ReportGenerator just shuting down after the launch.
![image](https://cloud.githubusercontent.com/assets/16087064/14410215/75aa85d2-ff32-11e5-9005-1b02d502c602.png)

> ReportGenerator 2.4.4.0
> Copyright c Palmmedia 2015
> 
> Parameters:
>     ["]-reports:<report>[;<report>][;<report>]["]
>     ["]-targetdir:<target directory>["]
>     [["]-reporttypes:<...>[;<...>]["]]"
>     [["]-sourcedirs:<directory>[;<directory>][;<directory>]["]]
>     [["]-historydir:<history directory>["]]
>     [["]-assemblyfilters:<(+|-)filter>[;<(+|-)filter>][;<(+|-)filter>]["]]
>     [["]-classfilters:<(+|-)filter>[;<(+|-)filter>][;<(+|-)filter>]["]]
>     [["]-verbosity:<Verbose|Info|Error>["]]
> 
> Explanations:
>     Reports: The coverage reports that should be parsed (separated by semicolon). Wildcards are allowed.
>     Target directory: The directory where the generated report should be saved.
>     Reporttypes: The output formats and scope (separated by semicolon).
>                  Values:
>     Source directories: Optional directories which contain the corresponding source code (separated by semicolon).
>                         The source files are used if coverage report contains classes without path information.
>     History directory: Optional directory for storing persistent coverage information.
>                        Can be used in future reports to show coverage evolution.
>     Assembly Filters: Optional list of assemblies that should be included or excluded in the report.
>     Class Filters:    Optional list of classes that should be included or excluded in the report.
>                       Exclusion filters take precedence over inclusion filters. Wildcards are allowed.
>     Verbosity: The verbosity level of the log messages.
>                Values: Verbose, Info, Error
> 
> Default values:
>    -reporttypes:Html
>    -assemblyfilters:+*
>    -classfilters:+*
>    -verbosity:Verbose
> 
> Examples:
>    "-reports:coverage.xml" "-targetdir:C:\report"
>    "-reports:target\*\*.xml" "-targetdir:C:\report" -reporttypes:Latex;HtmlSummary
>    "-reports:coverage1.xml;coverage2.xml" "-targetdir:report"
>    "-reports:coverage.xml" "-targetdir:C:\report" -reporttypes:Latex "-sourcedirs:C:\MyProject"
>    "-reports:coverage.xml" "-targetdir:C:\report" "-sourcedirs:C:\MyProject1;C:\MyProject2" "-assemblyfilters:+Included;-Excluded.*"
> Press any key to continue . . .

**Comment by danielpalme** [comment]
Well you should have a look at the printed help.
The parameter "-reports" and "-tagetdir" are required.

**Comment by Yefimov** [comment]
@danielpalme, i don't know where i have to write this parameters. In console? It just shuting down.

**Comment by danielpalme** [comment]
Yes of course. Do you know what this tool is doing?
Example:
ReportGenerator.exe "-reports:coverage.xml" "-targetdir:C:\report"
