### ISSUE TITLE
Is ReportGenerator working with .coveragexml file?

### ISSUE THREAD

**Issue by RachelXGanon** [danielpalme/ReportGenerator#451]
I'm having .coverage file as an output of code coverage tool in visual studio 2019.
I want to  use the` danielpalme/ReportGenerator` action.
I can only convert my .coverage to a .coveragexml file.
Can I use the` danielpalme/ReportGenerator` action with .coveragexml file?
thank you.

**Comment by danielpalme** [comment]
Yes, the _.coveragexml_ format is supported. 
The conversion of _.coverage_ to _.coveragexml_ is explained [here](https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools#codecoverageexe)

**Comment by RachelXGanon** [comment]
Thank you

**Comment by RachelXGanon** [comment]
what is `DynamicCodeCoverage`
in the command %UserProfile%\.nuget\packages\microsoft.codecoverage\XYZ\build\netstandard1.0\CodeCoverage\CodeCoverage.exe analyze /output`:DynamicCodeCoverage.coveragexml DynamicCodeCoverage.coverage`

**Comment by danielpalme** [comment]
The name of your input/output file.

**Comment by RachelXGanon** [comment]
code coverage crating folder with a random guid.
how do you get the path of the .coverage file? 
the cmd:
`"CodeCoverage.exe" analyze /output:DynamicCodeCoverage.coveragexml DynamicCodeCoverage.coverage
`thank you.

**Comment by danielpalme** [comment]
A little Powershell script should do the job:

```ps1
$directory = (Get-ChildItem -Path TODO/TestResults -Force | Select-Object -First 1).Name
"CodeCoverage.exe" analyze /output:$dircectory/DynamicCodeCoverage.coveragexml DynamicCodeCoverage.coverage thank you.
```

**Comment by RachelXGanon** [comment]
hi, thanks for your quick responds.
I'm using `Developer PowerShell for vs 2019` to run all commands,
Include that one `$directory = (Get-ChildItem -Path TODO/TestResults -Force | Select-Object -First 1).Name`.
But I don't success to run the cmd: 
`"CodeCoverage.exe" analyze /output:$dircectory/DynamicCodeCoverage.coveragexml DynamicCodeCoverage.coverage`
**CodeCoverage.exe : The term 'CodeCoverage.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program.**
How do you run the commands?
Thank you.

**Comment by danielpalme** [comment]
You need to prefix the exe:
```
.\CodeCoverage.exe ....
```

**Comment by RachelXGanon** [comment]
Right.
Thank you.
