### ISSUE TITLE
Coverage does not recognize that code will not return from a method

### ISSUE THREAD

**Issue by Saborion** [danielpalme/ReportGenerator#452]
Line coverage does not report correctly when there is a branch and the code inside the branch block statement will not get pass the last method in the block, even though the last method is marked with the `[DoesNotReturn()]` attribute.
``` csharp
// SUT
public static string CreateName(bool isError)
{
    if (isError)
    {
        ThrowException(); // This methods is marked with the [DoesNotReturn()] attribute and throws.
    } // This line is reported as not being covered.

    return "SomeName";
}

[DoesNotReturn()]
private static void ThrowException() => throw new InvalidOperationException("...");

// ---------------------------
// Unit tests
[Fact]
public void CreateName_IsErrorIsFalse_ReturnsName()
{
    var reportGeneratorIssue = new ReportGeneratorIssue();
    var name = reportGeneratorIssue.CreateName(isError: false);
    Assert.Equal("SomeName", name);
}

[Fact]
public void CreateName_IsErrorIsTrue_Throws()
{
    // Arrange
    var reportGeneratorIssue = new ReportGeneratorIssue();

    // Act
    var exception = Record.Exception(() => reportGeneratorIssue.CreateName(isError: true));

    // Assert
    Assert.NotNull(exception);
    Assert.IsType<InvalidOperationException>(exception);
    Assert.Equal("...", exception.Message);
}
```
The above code results in the following coverage report:
![image](https://user-images.githubusercontent.com/16595068/135721984-12e2324a-d9df-4333-9222-177be127f8b0.png)

If the code inside `ThrowException();` is instead inlined (remaining the same logically):
``` csharp
public static string CreateName(bool isError)
{
    if (isError)
    {
        throw new InvalidOperationException("...");
    } // This line is now being reported as covered.

    return "SomeName";
}
```
As can be seen in the following coverage report:
![image](https://user-images.githubusercontent.com/16595068/135722086-1e78af06-b679-4618-b7eb-bd3d23cdd929.png)

Even though I rely more on branch coverage than line coverage, I evaluate them both when looking at the coverage report. The above issue is sad and unfortunate, since we, for readability or [DRY reasons](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), occasionally use a helper method similar to the one in the examples above. I was hoping this issue was because of the report generator not having had time to take the nullable warning attributes into account, but those attributes have been around for a while now.

**Comment by danielpalme** [comment]
What coverage tool are you using (Coverlet, OpenCover, etc)?

ReportGenerator only evaluates the coverage file produces by your coverage tool.
It does not analyze the actual source code.
If the coverage file marks one line as covered/uncovered, ReportGenerator does the same.

Perhaps you should open an issue for your coverage tool.

**Comment by Saborion** [comment]
Oh, I see. My apologies. I will try different coverage tools and see if the issue can be solved that way. If so I'll inform the appropriate tool developers about the issue as well.

Thanks for a quick reply. Feel free to close the (non-)issue.
