### ISSUE TITLE
INQUIRY: Could this tool write a "Privacy or Data Protection Policy"?

### ISSUE THREAD

**Issue by mcallaghan-geotab** [danielpalme/ReportGenerator#456]
Hi!

We have a question regarding data protection and privacy policy for this tool.

From legal licensing perspective, this tool uses Apache2.0 license (https://github.com/danielpalme/ReportGenerator/blob/master/LICENSE.txt) which lends itself for the user to understand under what constraints (or not) a user or company can utilize and distribute this tool. :heavy_check_mark: 

However from a "data protection" perspective (privacy / security of data), short of conducting a code audit directly, it is unclear if the tool may or may not "gather and retain and share" data about usage or analysis. From a technical perspective the tool operates on an `lcov` coverage report format file and generates local files, so it seems intuitively that pre and post data remain secure/local.

Would it be possible to create a short "Privacy or Data Protection Policy" to demonstrate the technical underpinnings of the tool to confirm for legal/security that data remains local to the system that is utilizing the tool?

**Comment by danielpalme** [comment]
_ReportGenerator_ is completely free and does not gather any user data.
No statistics, telemetry or other tracking data is collected. The tool operates strictly locally.

Your inquiry seem to originate from a corporate background.  
How about your company supporting the project via a GitHub sponsorship or via Paypal and I'll add a Privacy Policy?
