### ISSUE TITLE
Support for Source Generator

### ISSUE THREAD

**Issue by latop2604** [danielpalme/ReportGenerator#457]
**Describe the bug**
Hello, 

I use altcover (global tool) to generate code coverage for an .Net5.0 app. And use the result as open cover format to generate report with [Report-Generator](https://github.com/danielpalme/ReportGenerator).

The line coverage is ok. But report generator is unable to find related file. (Understandable as source generated file are in memory only by default.

I don't know if it's in altcover scope or in report generator. Or both. 

And btw, thx for your great work on this tool.

**To Reproduce**

- Add a source generator to your app
- Add some test on the generated code
- Run coverage tool (here is altcover) in opencover format
- Generate html report from the coverage file

![image](https://user-images.githubusercontent.com/2058133/138094394-c125b6f2-cd5b-48f2-a2d0-247af2f326ea.png)

**Comment by latop2604** [comment]
When adding the property `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` in the csproj file. The generated file is available but in `Obj` directory. Maybe some path lookup fallback can be an option ?

![image](https://user-images.githubusercontent.com/2058133/138153761-d03c6022-feca-4bbc-8f62-d962412f65cb.png)

**Comment by danielpalme** [comment]
And what path does the altcover file contain, when you add the <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles> option?
Does it point to the obj directory?

**Comment by latop2604** [comment]
Ah, cool. I will try this. Thank

**Comment by latop2604** [comment]
It worked 🎉

Only a chunk of the path was missing and does not depend on the project the generator is installed. So this bash command for all project at once. It still a ack but not so much. We can live with it.

```bash
- sed -i "s/Marketplace.Common.Generators\//obj\/Debug\/net5.0\/generated\/Marketplace.Common.Generators\//g" *.opencover.xml
```

Thank you the the help.

I let you close this issue if you think it should.

**Comment by danielpalme** [comment]
Great that it is working for you!

**Comment by SteveGilham** [comment]
In the next release, AltCover will include embedded source in the reports it emits, which can be used to mitigate this issue.  The source is represented as UTF8 string -> bytes -> deflate compression -> Base64 encoded string.

For OpenCover format, there is an `altcover.embed` attribute added to the `File` element; for NCover classic, `altcover.file` elements are added after the `method` records in a `module`, with attributes `document` and `embed`; and for the extended coverlet JSON format, as a type `«AltCover.embed»` with an empty method with name being the embedded text.

Samples follow -- 
[AltCoverEmbeddingSamples.zip](https://github.com/danielpalme/ReportGenerator/files/7446142/AltCoverEmbeddingSamples.zip)

**Comment by SteveGilham** [comment]
> And what path does the altcover file contain, when you add the EmitCompilerGeneratedFiles=true option? Does it point to the obj directory?

For the record, AltCover, like other coverage tools, relies on the information provided in the debug symbols for source paths.  If this is an embellishment of the reality, the issue lies with the compiler that puts that information into the debug database.  Fortunately the compiler does embed the source by default, which would be used for e.g. debug step-into, hence the change alluded to above.

**Comment by danielpalme** [comment]
And the next version of ReportGenerator will support embedded source files for OpenCover.
I will probably release end of next week (after .NET 6 is published).

**Comment by SteveGilham** [comment]
We're both waiting on .net 6, then.  I suspect there will be a lot of similar upgrade versions dropping all week.

**Comment by SteveGilham** [comment]
After some delays e.g. [Windows Defender being over-enthusiastic](https://github.com/pester/Pester/issues/2104), feature released as part of [AltCover v8.2.828](https://www.nuget.org/packages/altcover/8.2.828)

**Comment by danielpalme** [comment]
ReportGenerator has been updated too:
https://www.nuget.org/packages/ReportGenerator/5.0.0

**Comment by terryaney** [comment]
Doesn't seem to be working for me in .NET 7 for `LoggerMessageGenerator\LoggerMessage.g.cs` files?

![image](https://github.com/danielpalme/ReportGenerator/assets/6237247/c1854771-28b6-4122-98be-5c1b37fefd2e)

![image](https://github.com/danielpalme/ReportGenerator/assets/6237247/6a745af2-d886-4aa6-a85d-088a5e68d421)

**Comment by danielpalme** [comment]
@terryaney 
_ReportGenerator_ only supports embedded source files for _OpenCover_ coverage files.

Your Coberatura files probably contains the file paths that (no longer) exist on disk. E.g. `C:\BTR\Camelot\Api\Api\src\Microsoft.Extensions.Logging.Generators\Microsoft. xtensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs`

**Comment by terryaney** [comment]
Thanks.  Note, in my dotnet test, I used `"/p:ExcludeByFile=**/LoggerMessage.g.cs",` in tasks.json and it worked.  However, `"/p:ExcludeByAttribute=GeneratedCodeAttribute",` did not work.  I thought it would given this:

```
namespace KAT.Camelot.Api.DataLocker.Features
{
    partial class BaseFileEndpoint<TRequest, TResponse>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "7.0.9.7226")]
        private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.String, global::System.String, global::System.Exception?> __LogWarningUnauthorizedAccessCallback =
            global::Microsoft.Extensions.Logging.LoggerMessage.Define<global::System.String, global::System.String>(global::Microsoft.Extensions.Logging.LogLevel.Warning, new global::Microsoft.Extensions.Logging.EventId(1, nameof(LogWarningUnauthorizedAccess)), "Camelot DataLocker Unauthorized access by {user}: {message}", new global::Microsoft.Extensions.Logging.LogDefineOptions() { SkipEnabledCheck = true }); 

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "7.0.9.7226")]
        static partial void LogWarningUnauthorizedAccess(global::Microsoft.Extensions.Logging.ILogger logger, global::System.String user, global::System.String message)
        {
            if (logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Warning))
            {
                __LogWarningUnauthorizedAccessCallback(logger, user, message, null);
            }
        }
    }
}
```
