### ISSUE TITLE
Error during reading report cobertura.xml (Size: 619.6KB): Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mirkof** [danielpalme/ReportGenerator#458]
Hi @danielpalme, thank you for the unification of all reporting tools :)

**Describe the bug**
We're running our Scala services in Azure Pipelines, and for some reason, our cobertura.xml is not read properly. 

**To Reproduce**
The output:
```
2021-10-13T11:16:19: Arguments
2021-10-13T11:16:19:  -reports:/home/vsts/work/1/s/**/cobertura.xml
2021-10-13T11:16:19:  -targetdir:/home/vsts/work/_temp/cchtml
2021-10-13T11:16:19:  -reporttypes:HtmlInline_AzurePipelines
2021-10-13T11:16:19:  -sourcedirs:/home/vsts/work/1/s/src/main/scala
2021-10-13T11:16:20: Error during reading report '/home/vsts/work/1/s/target/scala-2.12/coverage-report/cobertura.xml' (Size: 619.6KB): Object reference not set to an instance of an object.
2021-10-13T11:16:20: Writing report file '/home/vsts/work/_temp/cchtml/index.html'
2021-10-13T11:16:20: Report generation took 0.2 seconds
```

This is part of our pipeline:

```
  - task: Bash@3
    target: sbt
    displayName: Test
    inputs:
      targetType: 'inline'
      script: |
        sbt coverage test coverageReport coverageOff

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: '$(System.DefaultWorkingDirectory)/**/TEST-*.xml'
      testRunTitle: Publish test results

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage
    target: host
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/cobertura.xml
      pathToSources: $(Build.SourcesDirectory)/src/main/scala
      failIfCoverageEmpty: true
```

Unfortunately, I can't send the testing report due to sensitive information. 

The easiest thing to test would probably be to run a [sample project](https://github.com/scoverage/sbt-scoverage-samples)

If you need anything from my side, please let me know.

**Comment by danielpalme** [comment]
Does the [sample project](https://github.com/scoverage/sbt-scoverage-samples) show the same issue?

If yes, it would be great if you can run the tests of the sample project and share the cobertura file.
I currently too busy to setup the sample project myself.

If no, it would be great if you could share the cobertura file of your project.
You can send it by email (reportgenerator@palmmedia.de). The file will be treated confidentially and deleted after investigating your issue.

Probably the cobertura is used some special formatting or is missing some attributes.
