### ISSUE TITLE
Minor : use Math.Round instead of Math.Truncate in calculation SummaryResult.CoverageQuota

### ISSUE THREAD

**Issue by JorisSpriet** [danielpalme/ReportGenerator#46]
Probably nitpicking...
We added a check on our build server : a build is refused if coverage goes down - we look at the reported coverage in the summary in percent
We got remark the coverage was "wrong" - turns out this was the reason.
Needless to say it probably would have been solved faster/better by adding tests...

**Comment by danielpalme** [comment]
This is the reason for this behavior:
http://reportgenerator.codeplex.com/workitem/9065

> When coverage is higher than 99.95%, ReportGenerator rounds this up to 100%.
>  
> We have an automated build for a subsection of our code base which is set to fail if coverage falls below 100%. We use the output from ReportGenerator to determine this figure.
>  
> Because ReportGenerator rounds this figure up, this allows the coverage to be slowly eroded over time without anyone noticing before the figure drops to <99.95%.
>  
> I suggest that ReportGenerator is changed to round down to the last significant figure instead of rounding to the nearest last significant figure.
