### ISSUE TITLE
Node 6 execution handler warning in Azure Devops Task

### ISSUE THREAD

**Issue by asears** [danielpalme/ReportGenerator#464]
Getting this warning running the Azure Devops Extension.

See https://github.com/microsoft/azure-pipelines-tasks/issues/15493

```shell
Task         : ReportGenerator
Description  : ReportGenerator converts coverage reports generated by coverlet, OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov or lcov into human readable reports in various formats.
Version      : 4.8.13
Author       : Palmmedia
Help         : [More Information](https://github.com/danielpalme/ReportGenerator)
==============================================================================
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```

snippet of the relevant settings from the pipeline

```yaml
- task: reportgenerator@4
    reporttypes: "Cobertura;HtmlInline_AzurePipelines"
```

**Comment by danielpalme** [comment]
Thanks. Will have a look within the next days.

**Comment by danielpalme** [comment]
It was pretty easy to fix.

Please upgrade to version 5:

```yaml
- task: reportgenerator@5
...
```

**Comment by asears** [comment]
Worked great, thanks for the quick response and a great tool.

**Comment by andreujuanc** [comment]
Hi @danielpalme 
The readme on the visual studio marketplace is not updated: https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator
And it shows v4. 

cheers

**Comment by danielpalme** [comment]
Thanks for the hint.

I fixed it here:
https://github.com/danielpalme/ReportGenerator/blob/master/src/AzureDevopsTask/README.md

Next release will also update the market place.
