### ISSUE TITLE
Mismatch between Visual studio code coverage report and ReportGenerator code coverage report

### ISSUE THREAD

**Issue by msrinivascharan** [danielpalme/ReportGenerator#465]
There is a difference when Visual studio code coverage report compared with report generator. There are total 60 line in my “Abc.cs” file.

Abc.cs file code coverage report (.coverage) in visual studio 2019

       1] Covered lines -> 23
       2] Not covered lines -> 1
       3] Covered lines % -> 92.00 
       4] Covered blocks -> 29
      5] Not Covered blocks -> 2
       6] Covered blocks % -> 93.55

Abc.cs file code coverage report in ReportGenerator

       1] Covered lines -> 24
       2] Not covered lines -> 1
       3] Covered lines % -> 96.00 
       4] Covered blocks -> 18
      5] Not Covered blocks -> 2
       6] Covered blocks % -> Not available

What is the difference between line and block ? Why line numbers and block numbers are different for the same file in these two reports ?

Please provide some clarity. Thanks in advance.

**Comment by danielpalme** [comment]
One line could contain several blocks and one block could also span several lines.

See also:
https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details

**Comment by msrinivascharan** [comment]
> One line could contain several blocks and one block could also span several lines.
> 
> See also: https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details

Hi @danielpalme thank for the clarity provided.

**Comment by msrinivascharan** [comment]
> One line could contain several blocks and one block could also span several lines.
> 
> See also: https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details

Please help me to understand the difference in covered line numbers (23 in .coverage and 24 in Reportgenerator). Similarly, uncovered lines different in two reports.

Assembly1 .coverage        -> Covered, uncovered lines 230 - 361
Assembly1 .ReportGenrtr -> Covered, uncovered lines 238 - 360

Assembly2 .coverage        -> Covered, uncovered lines 19 - 403
Assembly2 .ReportGenrtr -> Covered, uncovered lines 19 - 386

Assembly3.coverage        -> Covered, uncovered lines 19 - 4104
Assembly3 .ReportGenrtr -> Covered, uncovered lines 7 - 4093

**Comment by danielpalme** [comment]
Can you share the XML coverage file that you are passing to _ReportGenerator_?

Without that file I can't tell any details.
In generell _ReportGenerator_ analyzes this XML file assembly by assembly, class by class, line by line.

**Comment by msrinivascharan** [comment]
Hi @danielpalme Thank you for your inputs. at this point, i cannot share the XML coverage file.

Please help me to understand below point from calculation details wiki page.

"Metrics are always displayed as they are provided in the coverage file. ReportGenerator does not (re-)calculate those values itself. This may result in inconsistent values if you merge several coverage files. In this case the minimum/maximum value is used."

**Comment by danielpalme** [comment]
Each class report shows a metrics table. The values in that table are not calculated by ReportGenerator.
Now if you merge several coverage files, the result can become incorrect in that table.
E.g. branch coverage may show too low values, since this value is not recalculated after merging the results. It's just read from the coverage file as is.

**Comment by msrinivascharan** [comment]
Hi @danielpalme thank for the clarity provided.
