### ISSUE TITLE
CoberturaParser: support detailed method signature

### ISSUE THREAD

**Issue by RoadTrain** [danielpalme/ReportGenerator#466]
Hi!

We've been using the `Core` library for parsing Cobertura coverages with great results so far.
There's one behavior that seems strange though.

For example, the coverage contains the following class:
```XML
        <class name="UnitTestExt.MoqExt.Setups.Setups`1" filename="UnitTestExt\MoqExt\Setups\Setups.cs" line-rate="0" branch-rate="1" complexity="1">
          <methods>
            <method name=".ctor" signature="(System.Collections.Generic.IReadOnlyCollection`1&lt;UnitTestExt.MoqExt.Setups.IMockSetup`1&lt;TMocksRoot&gt;&gt;)" line-rate="0" branch-rate="1" complexity="1">
              <lines>
                <line number="15" hits="0" branch="False" />
                <line number="17" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="15" hits="0" branch="False" />
            <line number="17" hits="0" branch="False" />
          </lines>
        </class>
```
Which after parsing translates to a `CodeElement` with `Name` of `.ctor(...)`.
So basically we lose method signature information, which prevents us from correctly mapping covered methods between different coverages, especially if there are many overloads of `.ctor(...)` which all have the same name when parsed.

As I see from the sources, method's full name [is parsed](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/CoberturaParser.cs#L341), but then [shortened](https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Core/Parser/CoberturaParser.cs#L349), and full name is not stored in the resulting `CodeElement` object.

So my questions are: 
1. Is this a deliberate design decision?
2. If not, can it be changed to preserve method signature info?
3. If it is deliberate, can we have an additional property on `CodeElement` which will contain the full method name?

Thanks!

**Comment by RoadTrain** [comment]
I've drafted a patch for (3): https://github.com/RoadTrain/ReportGenerator/commit/5413b655e08fca02d1b1967de037e12677093196

**Comment by danielpalme** [comment]
Will have a look at your questions and your patch within the next days!

**Comment by danielpalme** [comment]
I removed the method name shorting completely (see 32364a574de983a52584f641ee47843161003bb9).
Now the `Name` property of the `CodeElement` always contains the full name.
There is no reason to shorten the name.

The next release will contain the change.

**Comment by RoadTrain** [comment]
Awesome, thanks!
