### ISSUE TITLE
Node 6 execution handler will be deprecated soon

### ISSUE THREAD

**Issue by 4szt4l** [danielpalme/ReportGenerator#468]
I have got this warning message recently on Azure DevOps:

`##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
`

Are there any plans to migrate to Node 10?

**Comment by danielpalme** [comment]
Please upgrade to version 5:

```yaml
- task: reportgenerator@5
...
```

See also: https://github.com/danielpalme/ReportGenerator/issues/464
