### ISSUE TITLE
Sonarqube ignoring files / folders not working

### ISSUE THREAD

**Issue by nholdsworth94** [danielpalme/ReportGenerator#469]
**Describe the bug**
I'm using jenkins to scan on sonarqube, and I've got the code coverage working using your tool, but I can't for the life of me work out how to exclude a file / folder successfully.

I'm using dotnet-reportgenerator-globaltool as we use .Net Core 3.1

**To Reproduce**
This is my main command:
`reportgenerator "-reports:*/TestResults/*/coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"`

I've tried the following with no success:

` -assemblyfilters:-*DevonMicroservice\\.Application\\.Configuration*`
`-assemblyfilters:-*DevonMicroservice.Application.Configuration*` 
`-assemblyfilters:-DevonMicroservice.Application.Configuration*` 
`-filefilters:-*DependencyInjectionConfiguration.cs`
`-filefilters:-*ConfigReader.cs `

I have also tried wrapping them in quotes which hasn't worked either

I have files such as:
`DevonMicroservice.Application.Configuration/ConfigurationManager.cs`

I'd like to ignore any files underneath the folder: "DevonMicroservice.Application.Configuration" and others, but if I can get one working it should be rather simple (I hope) to fix

Any help would be greatly appreciated!

**Comment by danielpalme** [comment]
I guess it has to do with the path format in your cobertura file.

Can you share one of your cobertura files? Then I could give concrete advise.
You can send it by email: reportgenerator@palmmedia.de

**Comment by nholdsworth94** [comment]
[coverage.cobertura.xml.zip](https://github.com/danielpalme/ReportGenerator/files/7717839/coverage.cobertura.xml.zip)
File attached - had to zip as I couldn't upload an XML
Thank you for quick reply, and sorry for slow response - but I had finished work for the day

**Comment by danielpalme** [comment]
Thanks for the sample file.

For me the following filters are working:
```
-filefilters:-*DevonMicroservice.Application.Configuration*
-classfilters:-*DevonMicroservice.Application.Configuration*
```

You can choose which one you would like to use.
Does this work for you?

**Comment by nholdsworth94** [comment]
Working as expected locally, just pushing up to bitbucket / jenkins / sonarqube

**Comment by nholdsworth94** [comment]
![image](https://user-images.githubusercontent.com/69724935/146163208-dcb505fa-534b-4651-bb69-e2162f6a8771.png)
Although the coverage has increased slightly, and the number of lines to cover also, I'm still seeing the files in sonarqube with lines to test
For reference, this is the full command in the jenkinsfile
![image](https://user-images.githubusercontent.com/69724935/146163389-09f0b471-d9cc-4943-a21c-9c108d562471.png)

**Comment by danielpalme** [comment]
On my system the `SonarQube.xml` looks like this:

Without filters:
```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage version="1">
  <file path="C:\Obfuscated\DevonMicroservice.Application.Configuration\ConfigurationManager.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.Configuration\DatabaseConfiguration.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.Configuration\Startup\DependencyInjectionConfiguration.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\ConfigReader.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\CorsConfig.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\IdpConfig.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Controllers\AdminClientController.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\LambdaEntryPoint.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\LocalEntryPoint.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Startup.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Configuration\BusinessCommonConfiguration.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\ClientCrudDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\ClientDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\IdDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Service\AdminClientService.cs" />
</coverage>
```

With filter:
```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage version="1">
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\ConfigReader.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\CorsConfig.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Config\IdpConfig.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Controllers\AdminClientController.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\LambdaEntryPoint.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\LocalEntryPoint.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Application.WebAPI\Startup.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Configuration\BusinessCommonConfiguration.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\ClientCrudDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\ClientDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Dto\IdDto.cs" />
  <file path="C:\Obfuscated\DevonMicroservice.Business.Common\Service\AdminClientService.cs" />
</coverage>
```

So the first 3 files are filtered and not present in the `SonarQube.xml`.

**Comment by nholdsworth94** [comment]
Yes I experience the same locally
Must be a sonarqube issue
Appreciate your quick and detailed support massively

**Comment by nholdsworth94** [comment]
Sorry Daniel, one more thing if I may... how do I pass multiple filefilters?

**Comment by danielpalme** [comment]
```
"-filefilters:-*DevonMicroservice.Application.Configuration*;-SomeOtherFilter*"
```

**Comment by nholdsworth94** [comment]
Thanks, in the end I have gone for the approach of "include" rather than "exclude"
I have got the coverage up, but I'm still experiencing sonarqube behaving oddly, but I don't think this is your tool, as that is working exactly as expected locally.
Thank you again :)
