### ISSUE TITLE
Multiple classes per file report

### ISSUE THREAD

**Issue by brewsoftware** [danielpalme/ReportGenerator#47]
Hi,
   I've just noticed that the reporting doesn't appear to work when there are multiple Classes per file. Is there something that I'm missing or is this a known limitation. Looking at the Coverage.xml input there is no reference to the file in which the given class was hosted so it might be a problem with opencover?

**Comment by danielpalme** [comment]
Multiple classes in a single file should not cause any problems for ReportGenerator.
If you could provide the OpenCover file and the name of the class(es), I could have a closer look at your problem.

**Comment by brewsoftware** [comment]
I will have to put together a clean test and send it through... I will see if I can run up a unit test and a PR...

**Comment by brewsoftware** [comment]
Ah ok, I will have have another look at this tomorrow when I get back to work. Running a smaller test project it appears as though the report is generated per class instead of per file. Both coverage metrics appear but in separate report files.  

I'm assuming that this is "By design" so let me confirm tomorrow and we can close this out. Otherwise is there a way of merging coverage stats for multiple classes (Single file) into a single report file?

If not I might look at a custom report generator.

Cheers,
Jason

**Comment by danielpalme** [comment]
Yes the report is generated by class not by file.
Merging several classes into a single report file is not supported.

It is also best practice to place each class in a separate file, then it makes no difference.

**Comment by brewsoftware** [comment]
Hey, thanks. No problem. This is a non issue...
