### ISSUE TITLE
Package name with same last word results in single Html file

### ISSUE THREAD

**Issue by jpreese** [danielpalme/ReportGenerator#470]
I have two packages that end in the same word, for example `my/package/name` and `some/other/name`.

When generating a report in `Html` mode, a single `name__.html` file is generated.

This causes the navigation in the UI to always go to the single page (whichever wins) rather than have them be distinct.

Is there some way to make the generated filenames more verbose? is there another recommended solution?

Thanks!

**Comment by danielpalme** [comment]
Hi John,
thanks for reporting this issue.
Will have a look next week

**Comment by danielpalme** [comment]
Can you please share a sample coverage file?
If you like, you can send it by email: reportgenerator@palmmedia.de

**Comment by jpreese** [comment]
Sent! ❤️

**Comment by danielpalme** [comment]
Thanks for your sample file.

I fixed this issue and published a new release. Please try version 5.0.2

**Comment by jpreese** [comment]
Looks like it worked, I see the numerical identifier on the `.html` files now for duplicates. Thanks a ton!
