### ISSUE TITLE
Missing icons when viewing reports in Azure Devops

### ISSUE THREAD

**Issue by xantari** [danielpalme/ReportGenerator#471]
**Describe the bug**
This is a simple one. The icon's do not show up when viewing the generated Cobotura report in Azure DevOps.

This occurs with both the V4 and V5 ReportGenerator tasks in Azure Devops (we are using the cloud hosted version).

![image](https://user-images.githubusercontent.com/6610039/146933408-1c3891fb-fe2a-4bfb-9f17-cf61e0f083b6.png)

**Comment by sungam3r** [comment]
This question has already been asked earlier. This is due to security restrictions.

**Comment by xantari** [comment]
Ohh, something Microsoft blocks? I’ll close case

**Comment by danielpalme** [comment]
@sungam3r is right. The icons are blocked.
See also: https://github.com/danielpalme/ReportGenerator/issues/358
