### ISSUE TITLE
Query: any way to benchmark the privacy, security and performance benchmark

### ISSUE THREAD

**Issue by p00j4** [danielpalme/ReportGenerator#476]
Apologies Daniel for using issues for asking a query. First of all, thanks a bunch, actually a zillion for building and keeping it open. 
This is such an useful extension. 
I really like to have it on my company's azure instance. However since my company is quiet large and hence this instance has many many and many code repositories and so the extensions on it. My request to get approval on adding this extension has to go through some checks to ensure I'm not breaking anything existing as well as not causing any performance issue. 
Seeking your help in having some data pointers that I can use to showcase that 
1. it's secure
2. doesn't breach privacy
3. doesn't hamper performance 
4. won't affect any code repo. Only pipeline that consumes it will see it's benefits. Rest all existing pipelines will still keep behaving the same way as they did so far. i.e. it doesn't cause any integration issues.

**Comment by danielpalme** [comment]
Thanks for using _ReportGenerator_.

Here my answers regarding your questions:

1. Nobody can give a 100% guarantee. I'll do my best to keep everything up to date and to answer issues as fast as possible. As _ReportGenerator_ operates only locally, I would say that the overall risk is very low.
2. _ReportGenerator_ is completely free and does not gather any user data.
No statistics, telemetry or other tracking data is collected. The tool operates strictly locally.
3. _ReportGenerator_ does not affect the performance of the software under test. If you use _ReportGenerator_  in your pipeline, it will take some time to generate the coverage report. But in generell it should be quite fast. Is it fast enough for your use case? I don't know. Just give it a try.
4. It does not modify your code and won't affect your code repos.

How about your company supporting the project via a GitHub sponsorship or via Paypal?

**Comment by p00j4** [comment]
Thanks Daniel, appreciate your swift response. And yes, I would love to get this enrolled in my org's support Open OSS policy to get funded even periodic (I got to hear that we have such provision, i'm trying to get to the person who approves and get the policy application info) 
However before that, I'm yet to use it and showcase the power. Still facing friction in getting it in as ADO task, because of some painful history in the past (because of some other ADO 3rd party task), our security team is being extremely protective to not let any ADO task inside, thar ain't developed by team/person within my org.  sigh!
I'm trying to get there. I shall keep you posted with the application link, as I get luck to get it in.
