### ISSUE TITLE
Reported branch coverage for OpenCover is miscounted

### ISSUE THREAD

**Issue by less0** [danielpalme/ReportGenerator#48]
Each method is an implicit branch, but branches are only counted on expllicit branch points. This leads to an incorrect estimate of the branch coverage. Think of a class containing the following methods

```
void A()
{
  if(...)
  {
    //do something
  }
  //do something else
}

void B()
{
  //do something
}
```

A is called in a way that both branches are taken, B is never executed. ReportGenerator would report 2/2 branches covered, since it only counts the explicit branches (the if), whereas the summary in the OpenCover result.xml would state 3/4 branches covered, since we'll have to add 1 branch for each of the methods. Both the OpenCover class summary and the OpenCover method summary report the correct values.

**Comment by danielpalme** [comment]
You are right ReportGenerator only takes explicit branch points into account.
ReportGenerator works on a "per line" basis. That mean's it does not "know" about the methods in a file.
OpenCover also provides information on method level. Both approaches are "correct".
