### ISSUE TITLE
JsonSummary contains Byte Order Mark (BOM)

### ISSUE THREAD

**Issue by Chris-D-Turk** [danielpalme/ReportGenerator#481]
**Describe the bug**
The JsonSummary-Report contains a Byte Order Mark (BOM).
This is invalid JSON according to https://datatracker.ietf.org/doc/html/rfc8259#section-8.1

> Implementations MUST NOT add a byte order mark (U+FEFF) to the
   beginning...

**Why am I reporting this?**
I'm trying to parse the JsonSummary using the Jenkins Step [readJSON](https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#readjson-read-json-from-files-in-the-workspace), which fails because of the BOM :cry:

**Possible Fix**
https://github.com/danielpalme/ReportGenerator/blob/main/src/ReportGenerator.Core/Reporting/Builders/JsonSummaryReportBuilder.cs

change
`using (var reportTextWriter = new StreamWriter(new FileStream(targetPath, FileMode.Create), Encoding.UTF8))`
to
`using (var reportTextWriter = new StreamWriter(new FileStream(targetPath, FileMode.Create), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)))`

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
I will have a look within the next days.

**Comment by danielpalme** [comment]
Fixed in release 5.0.3
