### ISSUE TITLE
Shadow in the picture remains at 100%

### ISSUE THREAD

**Issue by suleymanozev** [danielpalme/ReportGenerator#482]
**Describe the bug**
Badge report builder is working incorrectly.

* wrong image
![badge_shieldsio_linecoverage_blue](https://user-images.githubusercontent.com/20399264/151665380-272835b4-ae25-40af-a499-28dcc96854ad.svg)

The shadow in the picture remains at 100%.
@danielpalme

**Comment by danielpalme** [comment]
Thanks for your PR!
