### ISSUE TITLE
Total Line issue

### ISSUE THREAD

**Issue by maxwelltan83** [danielpalme/ReportGenerator#49]
Hi Daniel,
               I had been using report generator to generate my opencover result, but I am getting some uncertainty about the number of total line, it since when merge multiple opencover result will double or triple the total line, in this case in correct total line & coverage percentage is incorrect.

So I had some doubt about it, not sure what is your suggestion, many thanks for the help

Best Regards,
                       Maxwell

**Comment by danielpalme** [comment]
@maxwelltan83 
Sorry for the late reply. Somehow I missed this issue.

Can you provide a more detailed sample?
