### ISSUE TITLE
ReportGenerator task does not work on the project for .NET Framework .

### ISSUE THREAD

**Issue by norainu98** [danielpalme/ReportGenerator#494]
**Describe the bug**

'..\..\tools\net47\ReportGenerator.MSBuild.dll' is set as 'ReportGeneratorAssembly' in a build\netstandard2.0\ReportGenerator.props.
However, above file does not exist in tools\net47 folder of the nupkg of v5.0.4.
As result,  when target is .NET Framework. ReportGenerator command in the msbuild file does not wok.

**To Reproduce**

1. Set a reference of ReportGenerator v5.0.4 into the msbuild project file with TargetFrameworks is net47 or net48.
2. Set 'ReportGenerator' as msbuild task.
3. Run msbuild and even if 'ReportGenerator' is called but it's not work because ReportGenerator.MSBuild.dll for .NET Framework does not exist.

**Comment by danielpalme** [comment]
You are right, this file is missing in the packages.
I guess there was a temporal problem with the GitHub action building the project.
The files got missing in v5 and now seem to be back again (without any changes in the build pipeline).

I plan to publish v5.1 within the next days, which will fix the problem.

**Comment by danielpalme** [comment]
I just released v5.1. Does this work for you?

**Comment by danielpalme** [comment]
It took some time, but I figured it out.
New version 5.1.2 should finally work again.

**Comment by norainu98** [comment]
I confirmed to work 5.1.2 on my environment.
It worked by both net48 and net6.
Thanks!
