### ISSUE TITLE
Feature Request: Show Cobertura Generation Date

### ISSUE THREAD

**Issue by princefishthrower** [danielpalme/ReportGenerator#497]
While I really like that the report itself shows when it was generated, I don't see any reference to the timestamp of the coverage.cobertura.xml file that was used for the actual generation. I ran into an issue thinking I was looking at a "new" report, but really in the background, I was using the same coverage report from weeks ago. Really confusing if you don't look into the folder and data of where your Cobertura files live.

I suggest simply a new key-value pair in the summary area of the report that provides this info (maybe even as the second one right under "generated on", for example:

"coverage.cobertura.xml generated on:" "3/9/2022 - 7:42:51 PM"

What do you think of this feature? Would have saved me a large amount of time spent head-scratching.

**Comment by danielpalme** [comment]
Good idea!
I will consider this for the next release.
I have to think about some edge cases:

- ReportGenerator supports several input formats, not all of them contain a date. If that's the case, no date will be displayed in the report
- You can pass several coverage files and ReportGenerator merges them. The files can have different dates. My idea is to display the minimum / maximum dates in the report.

What do you think?

**Comment by princefishthrower** [comment]
@danielpalme - this would be awesome! And thanks so much for the fast reply! Both points seem to make a lot of sense to me.

One question about this merging functionality, I didn't even realize this was possible - does it show any sort of chart of improvement (or degradation) of coverage over time? Like a chart? Or how does this merge work exactly? Is there a link to the documentation for this?

Thanks again!

**Comment by danielpalme** [comment]
There are two concepts:
- **Merging**: This means you pass several coverage files via the `-reports:...` command line parameter. ReportGenerator will then parse all of your coverage files and merge them together to get a single coverage report
- **History**: If you use the `-historydir:...` command line parameter, ReportGenerator will collect historic coverage information and you will get:
  - A history chart on the summary page and every class page
  - An option to compare coverage results on the summary page

![image](https://user-images.githubusercontent.com/859606/157605479-0c32cde5-d3be-4ade-96cf-62e164b410f4.png)

**Comment by princefishthrower** [comment]
Hey, incredible work! I'll update my vesion and check it out very soon!
