### ISSUE TITLE
Integration with CruiseControl.NET

### ISSUE THREAD

**Issue by qujck** [danielpalme/ReportGenerator#5]
Hi,

Nice product BTW :-)

I have integrated xUnit, OpenCover and ReportGenerator into CruiseControl.NET and the coverage report is being displayed successfully by using [this](http://www.palmmedia.de/Blog/2012/9/27/cruisecontrol-net-integration-of-coverage-reports) guide

The coverage report works within the dashboard

> http://localhost/ccnet/server/local/project/x/build/log20150305102701Lbuild.65.xml/coverageReport.aspx

in its own window

> http://localhost/ccnet/server/local/project/x/build/log20150305102701Lbuild.65.xml/RetrieveBuildFile.aspx?file=coveragereport\index.htm

But in both instances I am unable to view the individual detail files for each of the classes

> http://localhost/ccnet/server/local/project/x/build/log20150305102701Lbuild.65.xml/x.y.z_DebugTraceCommandHandler_1.htm

I get a yellow screen of death

> Unknown object name : x.y.z_debugtracecommandhandler_1
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> Exception Details: System.ApplicationException: Unknown object name : x.y.z_debugtracecommandhandler_1
> 
> Source Error:
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> Stack Trace:
> 
> 
> [ApplicationException: Unknown object name : x.y.z_debugtracecommandhandler_1]
>    Objection.ObjectionStore.GetByName(String name) +344
>    ThoughtWorks.CruiseControl.WebDashboard.MVC.Cruise.CruiseActionFactory.CreateHandler(String actionName) +191
>    ThoughtWorks.CruiseControl.WebDashboard.MVC.Cruise.CruiseActionFactory.Create(IRequest request) +40
>    ThoughtWorks.CruiseControl.WebDashboard.MVC.RequestController.Do() +128
>    ThoughtWorks.CruiseControl.WebDashboard.MVC.ASPNET.HttpHandler.ProcessRequest(HttpContext context) +594
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +599
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +171

It looks to me like I need to get `/RetrieveBuildFile.aspx?file=coveragereport\` into the url to change this

> http://localhost/ccnet/server/local/project/x/build/log20150305102701Lbuild.65.xml/x.y.z_DebugTraceCommandHandler_1.htm

into this

> http://localhost/ccnet/server/local/project/x/build/log20150305102701Lbuild.65.xml/RetrieveBuildFile.aspx?file=coveragereport\x.y.z_DebugTraceCommandHandler_1.htm

Can you help?

**Comment by danielpalme** [comment]
Hi Peter,

the problem is that CruiseControl replaces all links with it's custom URLs.
That works fine for static files. But if JavaScript is enabled, the summary report is rendered dynamically.
The URLs created in JavaScript are not rewritten and therefore don't work.

The download on my [blog](http://www.palmmedia.de/Blog/2012/9/27/cruisecontrol-net-integration-of-coverage-reports) includes a file named _tools/RemoveScriptsFromReport.ps1_.
If you run this file after ReportGenerator the JavaScript is removed and you should be able to use the static report with working links.

This is the Powershell script:
```
param (
    [string]$file
 )
 
((Get-Content "$file") -join "`n").Replace("<script", "<!-- script").Replace("</script>", "</script -->") | Set-Content "$file"
```

This is really annoying, but I don't think that there is anything that ReportGenerator can do about.

I use [TeamCity](https://www.jetbrains.com/teamcity/) for CI, that works much better.
It's very easy to setup and to configure (much easier than CruiseControl) and it is free.

**Comment by qujck** [comment]
I did try to get the script to work before raising the issue

I had to run [`Set-ExecutionPolicy RemoteSigned`](http://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system)

Which got me to this

> C:\CCNet\OpenCover>PowerShell RemoveScriptsFromReport.ps1 C:\CCNet\BuildArtifacts\x\65\coveragereport\index.html
> The term 'RemoveScriptsFromReport.ps1' is not recognized as the name of a cmdle
> t, function, script file, or operable program. Check the spelling of the name,
> or if a path was included, verify that the path is correct and try again.
> At line:1 char:28
> + RemoveScriptsFromReport.ps1 <<<<  C:\CCNet\BuildArtifacts\x\65\coveragerepo
> rt\index.html
>     + CategoryInfo          : ObjectNotFound: (RemoveScriptsFromReport.ps1:Str
>    ing) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by danielpalme** [comment]
You probably need to prefix the path to the script with ".\"
See http://stackoverflow.com/questions/762927/powershell-ps1-file-is-not-recognized-as-a-cmdlet-function-operable-program

**Comment by qujck** [comment]
Yup, that fixed it. Thanks!

**Comment by qujck** [comment]
My first choice was TeamCity. I spent quite some time getting it set up but lost the will to live trying to configure it to use the NTLM proxy server to connect to Nuget.
