### ISSUE TITLE
Need help to create history from VS 2013 coverage files

### ISSUE THREAD

**Issue by gurufordy** [danielpalme/ReportGenerator#50]
Hi,

Firstly this is great so thanks!

I need help though. I've got a Visual Studio coverage file that I want to share in pretty HTML with others and am using your tool to do that. The bit that would be freaking awesome is a nice history with graphic to show progress (or decline!), but it's not doing anything for me.

So I run the below in a batch file:

.\tools\ReportGenerator.exe ^
-reports:"2016-06-14 16_02_40.coveragexml" ^
-targetdir:".\report" ^
-reporttypes:"Html" ^
-historydir=".\report\history"

And I get is the statistical table HTML page with no history folder :(

Any help?

**Comment by danielpalme** [comment]
Your batch file seems to be correct.
If you execute ReportGenerator for the first time the directory "report\history" should get created.

The chart in the report should look similar to this:
![image](https://cloud.githubusercontent.com/assets/859606/16055721/be0f7be8-3272-11e6-9c17-c87879465a3e.png)

Make sure that JavaScript is enabled. Otherwise you won't see the chart.
Never delete the historydir, otherwise you will loose the coverage information from older generated reports.

**Comment by gurufordy** [comment]
Hi Daniel,

It's really weird as I can't see anything about history in my report (screenie below). Tried in Chrome and IE 11 with no difference. Even with JS off I'd expect to see the title? index.htm in Notepad also has no mention of the word history.

![image](https://cloud.githubusercontent.com/assets/5593892/16070896/3f98a8da-32d0-11e6-8680-a86240e2aa69.png)

**Comment by danielpalme** [comment]
Is it possible that you send me your coveragexml file?
danielpalme82@gmail.com

**Comment by gurufordy** [comment]
Hi Daniel,

Just sent the email!

**Comment by danielpalme** [comment]
Thanks, I will look into it tomorrow.

**Comment by danielpalme** [comment]
I looked at your batch file again...
This line is wrong: 
-historydir**=**".\report\history"

You should use:
.\tools\ReportGenerator.exe ^
"-reports:2016-06-14 16_02_40.coveragexml" ^
"-targetdir:.\report" ^
"-reporttypes:Html" ^
"-historydir:.\report\history"

When executed with the above script, you will get:
![coverage](https://cloud.githubusercontent.com/assets/859606/16142868/5b089180-3469-11e6-8a23-4a498d40ccb9.png)

**Comment by gurufordy** [comment]
Oh dear lol. You're right it works perfectly now.

Really sorry that's something I should've spotted :(
