### ISSUE TITLE
Unexpected behavior while merging multiple overlapping Cobertura files

### ISSUE THREAD

**Issue by dennisdoomen** [danielpalme/ReportGenerator#504]
**Describe the bug**
We've been trying to analyze why our AZDO builds report such a low coverage value, even though our IDE confirms our coverage is quite high for certain classes. Our build runs `dotnet test` on four separate test projects and then merges the resulting Cobertura files into one. The final step is that it builds an HTML representation to be rendered in AZDO. For the record, we are _not_ using the built-in AZDO task for that.

We've observed three different scenarios:
1. When our AZDO pipeline merges the four files into a new Cobertura` file using RG 4.6.1 and _then_ renders it to `HtmlInline_AzurePipelines` using that same RG version, line coverage is 55.9% and branch coverage is 34.4%
2. When I download those four files and then use RG 5.1.3 to render those 4 directly to an HTML page, I end up with a line coverage of 71% and branch coverage of 42%
3. When I first try to merge those four files using RG 5.1.3 to a Cobertura file and _then_ render it to HTML, I end up with no coverage (N/A).

What's important is that the four test projects contain various integration tests that cover the same code. For example, the `UserService` class is supposed to reach 97%.

I'm at loss here. Is something wrong with the Cobertura files that `dotnet test` and `coverlet.msbuild` 3.1.2 produces? 

Oh, and one more note. When producing the merged files we get warnings that the `.cs` files don't exist (anymore). Can that cause the problems?

I've send the four files by email named to this issue.

**Comment by dennisdoomen** [comment]
Never mind for now, It seems the missing C# files were the que.

**Comment by danielpalme** [comment]
Great that you found the reason.
Let me know if you need further help.
