### ISSUE TITLE
ReportGenerator for Mono

### ISSUE THREAD

**Issue by bgurmendi** [danielpalme/ReportGenerator#51]
I'm using ReportGenerator on Mono with monos coverage tooling.

I can prepare a pull request if it is ok for you to add dependency to Mono.Cecil.

**Comment by danielpalme** [comment]
I don't understand yet what I could expect from your offered pull request.
What new features would this PR add to ReportGenerator?

ReportGenerator should already work with Mono. I tested this a while ago and it already worked for me.

**Comment by bgurmendi** [comment]
ReportGenerator will be compatible with Mono coverage, so it could make reposts for Linux/iOS enviroment or for Xamaring.

**Comment by danielpalme** [comment]
Sounds good. Just go ahead!

**Comment by bgurmendi** [comment]
OK!!! :+1:

**Comment by danielpalme** [comment]
@bgurmendi 
Any updates on this issue?

**Comment by danielpalme** [comment]
I will close this issue since I got no feedback. Please reopen if required.

**Comment by bgurmendi** [comment]
I will open it when is ready

2016-10-26 22:36 GMT+02:00 Daniel Palme <notifications@github.com>:

**Comment by danielpalme** [comment]
Great. If you like, we can split the work.

I have two test projects:
https://github.com/danielpalme/ReportGenerator/tree/master/ReportGenerator.Testprojects/CSharp/Project
https://github.com/danielpalme/ReportGenerator/tree/master/ReportGenerator.Testprojects/FSharp/Project

If you could compile them and execute them with _monocov_ and send me the resulting XML files, I can do the implementation of the parser.
That way we can move faster. You probably already have _monocov_ working and I have implemented a couple of parsers and I know what I have to pay attention for.

**Comment by bgurmendi** [comment]
The XML generated by monocov is not enought for code coverage we need to
read the pdb (debug info) for correct file and line number identification.
I have a working dirty solution that we use on every day work.

Perhabs I can give you a dirty solution explained and you can clean up.


2016-10-27 21:32 GMT+02:00 Daniel Palme <notifications@github.com>:

**Comment by danielpalme** [comment]
That would be an option, I will have a look if I can help out.
