### ISSUE TITLE
riskhotspot class filter should be case insensitive

### ISSUE THREAD

**Issue by tonyhallett** [danielpalme/ReportGenerator#517]
**Describe the bug**
https://github.com/danielpalme/ReportGenerator/blob/dc395da3825e07700c1a16defd89e0c00434d2fd/src/AngularComponents/src/app/components/riskhotspots/riskhotspots.component.ts#L161

```
if (this.settings.filter !== "" && allRiskHotspots[i].class.toLowerCase().indexOf(this.settings.filter) === -1) {
```

should this be
```
if (this.settings.filter !== "" && allRiskHotspots[i].class.toLowerCase().indexOf(this.settings.filter.toLowerCase()) === -1) {
```

**Comment by danielpalme** [comment]
Thanks for reporting this.
I have changed the behavior according to your suggestion.
