### ISSUE TITLE
Generated Report has different numbers than the visual studio coverage file

### ISSUE THREAD

**Issue by mdaher** [danielpalme/ReportGenerator#518]
I am attaching the visual studio coverage numbers. Also I am attaching the report generated by ReportGenerator
The numbers are different although I am using the right file.

![visualstudio coverage](https://user-images.githubusercontent.com/5772349/168124508-baf43d80-cd2a-455f-b05c-06fbeb59dbc6.PNG)

![reportgenerator](https://user-images.githubusercontent.com/5772349/168124515-c2b26310-051b-4cdc-8f0d-0d009f1467b5.PNG)

**Visual studio report shows 46.85%
ReportGenerator report shows 49.6%**

1- I exported the coverage file from visual studio to a location on my drive and named it 'csharpselenium.coveragexml'
2- I ran the following command
dotnet ReportGenerator.dll 
"-reports:C:\WorkInProgress\TestCoverage\csharpselenium.coveragexml" 
"-targetdir:C:\WorkInProgress\TestCoverage\TestCoverageReport"
-reporttypes:Html;

**Comment by danielpalme** [comment]
The big difference here is: _Visual Studio coverage_ is about "Blocks". ReportGenerator is about "Lines".

A block can span several line, a line can also contain several blocks.
_ReportGenerator_ maps this information to the lines of your file.
Therefore there the results can differ.

See also:
https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details
