### ISSUE TITLE
Is wiki disabled for editing intentionally?

### ISSUE THREAD

**Issue by MNF** [danielpalme/ReportGenerator#52]
Is wiki disabled for editing intentionally?
I want  to add the info  about different **ReportTypes** to FAQ:
**HtmlSummary** creates a single HTML file  summary.htm(without links). 
**Html** creates the index.htm that has summary (with links) and detailed reports for each class.

**Comment by danielpalme** [comment]
Thanks for your input. I added the above information to the FAQ.
