### ISSUE TITLE
Installing ReportGenerator as global tooling doesn't work as expected

### ISSUE THREAD

**Issue by NicolasDorier** [danielpalme/ReportGenerator#523]
On windows, I ran this
```bash
dotnet tool install -g dotnet-reportgenerator-globaltool
```

Then

```bash
dotnet reportgenerator
```

**Actual:**

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-reportgenerator does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Expected:**

The reportgenerator should be usable.

**Workaround:**

Add `%USERPROFILE%\.dotnet\tools` to the PATH, then you can invoke with

```
reportgenerator.exe
```

**What is going wrong:**

It seems that running `dotnet reportgenerator` try to run `%USERPROFILE%\.dotnet\tools\dotnet-reportgenerator.exe`.
However, the tool actually installed is `%USERPROFILE%\.dotnet\tools\reportgenerator.exe`.

The `dotnet-` prefix seems to be missing for `dotnet reportgenerator` to work as expected.

![image](https://user-images.githubusercontent.com/3020646/169195491-7c819b3d-9005-4e8a-bae7-6b4aecf309f3.png)

dotnet version 6.0.202 on windows.

**Comment by danielpalme** [comment]
If you install the global too, you don't have to use "dotnet".

Just use: 
```
reportgenerator ...
```

**Comment by AndresGMD** [comment]
Hi in my case doesn't work

dotnet tool remove --global dotnet-reportgenerator-globaltool

reportgenerator : The term 'reportgenerator' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ reportgenerator
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (reportgenerator:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

![image](https://github.com/danielpalme/ReportGenerator/assets/90065355/571850a4-57a0-487f-8e89-3ab8e0373628)

Thanks in advance.

**Comment by danielpalme** [comment]
@AndresGMD 
The commands are:

**Uninstall**:
```
dotnet tool uninstall --global dotnet-reportgenerator-globaltool
```

**Install**:
```
dotnet tool install --global dotnet-reportgenerator-globaltool
```

In your command you have used "remove". That's not correct.

**Comment by danielpalme** [comment]
@AndresGMD 
I just looked at your screenshot.

Your setup seems to be "broken".
There's a warning regarding a PATH issue. I guess you have to fix that first.
