### ISSUE TITLE
Syntax error in GitLab integration documentation

### ISSUE THREAD

**Issue by spl-sotax** [danielpalme/ReportGenerator#529]
**Describe the bug**
The coverage regex in https://github.com/danielpalme/ReportGenerator/wiki/Integration#gitlab does not escape single quotes correctly. According to https://yaml.org/spec/1.2.2/#single-quoted-style single quotes have to escaped with two consecutive single quotes (`''`), not with a backslash.
The LINT feature of GitLab reports the following error:
`(<unknown>): did not find expected key while parsing a block mapping at line 37 column 3`
The correct line for the GitLab-YAML is
```
  coverage: '/##teamcity\[buildStatisticValue key=''CodeCoverageS'' value=''(\d+\.?\d*)''\]/'
```

**To Reproduce**
* Create a project on a GitLab instance.
* Add a .gitlab-ci.yml
* Copy the code sample from  https://github.com/danielpalme/ReportGenerator/wiki/Integration#gitlab to your .gitlab-ci.yml
* Use the LINT feature to check the syntax of the file

**Comment by danielpalme** [comment]
Thanks! I fixed the documentation.
