### ISSUE TITLE
Mention 3rd party support in Wiki

### ISSUE THREAD

**Issue by stevepeak** [danielpalme/ReportGenerator#53]
[Codecov](https://codecov.io) now supports coverage reports produced by Visual Studio. It would be great to mention this in the [Wiki here](https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools). Let me know if I can help provide any additional information to help out, I work at for Codecov 😄

Examples:
https://codecov.io/gh/hebinhuang/Mobius/tree/e27aa20a52a1fb15966dd38f66f5e60ca45cfb97
https://codecov.io/gh/hebinhuang/Mobius/tree/98316fdb40bc0aa9f664174d7a820025fb1f08b2

Thank you 👍

**Comment by danielpalme** [comment]
@stevepeak 
I don't understand why the wiki of ReportGenerator should mention your (commercial) tool.
ReportGenerator is able to parse the output of the Visual Studio tools.
If Codecov is able to do so too, that's great. But I don't think that this valuable information in the ReportGenerator wiki?!

**Comment by stevepeak** [comment]
I understand. Just thought I should mention the support for ReportGenerator output in Codecov somewhere in the project. But I understand not listing commercial tools. Thank you for reviewing 👍
