### ISSUE TITLE
Error when creating History File

### ISSUE THREAD

**Issue by maxl-13** [danielpalme/ReportGenerator#530]
Hi!

I want to create the History graph. I put the xml reports in a folder (Does I need the output from the reportgenerator??). But i am getting this error message. Someone has any idea how i have to structure the files to fix this?

2022-06-10T07:15:58: Error during reading historic report 'covrep/2022-05-27_20-56-49_CoverageHistory.xml': Object reference not set to an instance of an object.

Thanks!

**Comment by danielpalme** [comment]
Can you please share the content of your history file `2022-05-27_20-56-49_CoverageHistory.xml`?
You can also send it by email: reportgenerator@palmmedia.de

**Comment by maxl-13** [comment]
The content is the last Summary.xml

<?xml version="1.0" encoding="utf-8"?>
<CoverageReport scope="Summary">
  <Summary>
    <Generatedon>06/10/2022 - 07:15:59</Generatedon>
    <Parser>MultiReport (2x Cobertura)</Parser>
    <Assemblies>1</Assemblies>
    <Classes>1</Classes>
    <Files>1</Files>
    <Coveredlines>10</Coveredlines>
    <Uncoveredlines>19</Uncoveredlines>
    <Coverablelines>29</Coverablelines>
    <Totallines>89</Totallines>
    <Linecoverage>34.4</Linecoverage>
    <Coveredbranches>4</Coveredbranches>
    <Totalbranches>6</Totalbranches>
    <Branchcoverage>66.6</Branchcoverage>
    <Coveredmethods>6</Coveredmethods>
    <Totalmethods>7</Totalmethods>
    <Methodcoverage>85.7</Methodcoverage>
    <Title>IntegrationTest</Title>
    <Tag>6.1.30</Tag>
  </Summary>
  <Coverage>
    <Assembly name="ClassLibrary1" classes="1" coverage="34.4" coveredlines="10" coverablelines="29" totallines="89" branchcoverage="66.6" coveredbranches="4" totalbranches="6" coveredmethods="6" totalmethods="7" methodcoverage="85.7">
      <Class name="ClassLibrary1.Class1" coverage="34.4" coveredlines="10" coverablelines="29" totallines="89" branchcoverage="66.6" coveredbranches="4" totalbranches="6" coveredmethods="6" totalmethods="7" methodcoverage="85.7" />
    </Assembly>
  </Coverage>
</CoverageReport>

**Comment by danielpalme** [comment]
It seems like you have manually copied the XML file to the history directory.
That's not how it works. There is no manual effort required.
Please delete the file and just execute _ReportGenerator_ with the `historydir:covrep` parameter.

Every time you execute _ReportGenerator_ it will generate a new XML file in that directory.
If you specify `-reporttypes:Html`, you will see charts in your report.

**Comment by maxl-13** [comment]
Ok thank you, thats is what i am searching for :)
