### ISSUE TITLE
single HTML file causes browser "out of memory"

### ISSUE THREAD

**Issue by gfim** [danielpalme/ReportGenerator#537]
ReportGenerator creates HTML output as a large single file (as well as some ancillary files). Opening this file in a some web browsers causes an "Out of memory" error.

Specifically...

Running our C++ unit tests under CppCoverage (https://github.com/atlaste/CPPCoverage) produces a Cobertura XML file that is about 14Mb. ReportGenerator takes that XML and produces its results in a file that is 284Mb in size. Opening that file in a browser causes the process size to expand to 13Gb. In Edge and Chrome, this causes the browser to fail with an error message "Out of memory". In Firefox, it succeeds, but takes a very long time to open (more than a minute).

It would be much better if the detailed HTML output was contained in a number of smaller files - one per source code file.

**Comment by danielpalme** [comment]
I will come back to you after my vacation.
But a file size of 284MB seems rely large.

In general ReportGenerator produces a summary file (index.html) and one additional file per class.

**Comment by gfim** [comment]
Thanks for the reply, Daniel.

Attached is a directory listing of the output from ReportGenerator.
[unit_tests.coverage.dir.txt](https://github.com/danielpalme/ReportGenerator/files/9304352/unit_tests.coverage.dir.txt)
As you can see, there are a few small HTML, SVG, CSS, and JS files. And then there is the one huge HTML file Program.exe_C_.html. The name of this file comes from the Cobertura input file to ReportGenerator where the one and only "<package>" entry is "Program.exe". I'm not sure where the "C" part comes from - maybe the "<source>" entry is "c:".

I also tried an older version of ReportGenerator 4.8.13 - but the results were the same (after applying the patch that is the fix for #536).

I tried one of your test input files Cobertura_Istanbul.xml and that does produce multiple output files. I'll investigate what's different between it and my input file.

Enjoy your holiday!

**Comment by gfim** [comment]
Ok, a bit of investigation later...

If you go back to the chunk of XML that I attached to #536, you can see that the `<class>` entries produced by CppCover have a full pathname to the source file in the "name" field. That's seems to be what causes it to create the one big file. When I remove the path and just leave the file name (e.g. "radiocallactivity.h"), it does produce separate HTML files. However, making that simple change isn't the correct things to do as that's **not** the class name. Looks like the problem is with CppCover, not ReportGenerator. I'll investigate further.

**Comment by danielpalme** [comment]
The file name should not be an issue.
In general you will open _index.html_ in your browser and navigate to the individual files from there.

But why is the coverage file so big? Is the file `radiocallactivity.h` that long?

**Comment by gfim** [comment]
Maybe the file name shouldn't be an issue, but it is. The radiocallactivity.h source file is quite small. When it has a full path name in the input XML file, it is not output as a separate HTML file. When it is just a simple file name (without the path), it is output as radiocallactivty.html.

I'm giving up on CppCover - its output is just wrong. I'm trying OpenCppCoverage instead. Firstly, it can output HTML directly. Secondly, the Cobertura file it produces works much better with ReportGenerator than CppCover's one does. Its (big) downside is that it takes about 10 times as long to run - over 90 minutes for our unit tests.

So, thanks Daniel. I wouldn't worry about this big HTML file problem any more.

**Comment by gfim** [comment]
ReportGenerator output looks good when using OpenCppCoverage - a separate HTML file for each source file. So, you can close this issue as "not a bug" (not in ReportGenerator, anyway).
