### ISSUE TITLE
Conversions from Jacoco code coverage are either empty or not complete

### ISSUE THREAD

**Issue by djthornton1212** [danielpalme/ReportGenerator#539]
**Describe the bug**
Note that I've attempted this on a Mac/.Net Docker Image/GitHub Actions. None work for me.

Conversions from Jacoco code coverage are either empty or not complete. The Cobertura has some information but is woefully incomplete. Where as the lcov report only has 1 line consisting of `TN:`. Not sure if I'm missing an input or not. 

**To Reproduce**
The following input helps to reproduce your issue:
1. Console output of ReportGenerator

> reportgenerator "-reports:target/site/jacoco-both/jacoco.xml" "-targetdir:converted-coverage" "-reporttypes:Cobertura;lcov" "-sourcedirs:src/main/java/" -title:Code-Coverage-Converter
> 2022-08-15T16:31:32: Arguments
> 2022-08-15T16:31:32:  -reports:target/site/jacoco-both/jacoco.xml
> 2022-08-15T16:31:32:  -targetdir:converted-coverage
> 2022-08-15T16:31:32:  -reporttypes:Cobertura;lcov
> 2022-08-15T16:31:32:  -sourcedirs:src/main/java/
> 2022-08-15T16:31:32:  -title:Code-Coverage-Converter
> 2022-08-15T16:31:32:  -verbosity:verbose
> 2022-08-15T16:31:32: Executable: /root/.dotnet/tools/.store/dotnet-reportgenerator-globaltool/5.1.9/dotnet-reportgenerator-globaltool/5.1.9/tools/net6.0/any/ReportGenerator.Core.dll
> 2022-08-15T16:31:32: Working directory: /workfir
> 2022-08-15T16:31:32: Settings
> 2022-08-15T16:31:32:  { "NumberOfReportsParsedInParallel": 1, "NumberOfReportsMergedInParallel": 1, "MaximumNumberOfHistoricCoverageFiles": 100, "RenderPngFallBackImagesForHistoryCharts": false, "CachingDurationOfRemoteFilesInMinutes": 10080, "DisableRiskHotspots": false, "ExcludeTestProjects": false, "CreateSubdirectoryForAllReportTypes": false, "CustomHeadersForRemoteFiles": "", "DefaultAssemblyName": "Default" }
> 2022-08-15T16:31:32:  { "MetricThresholdForCyclomaticComplexity": 30, "MetricThresholdForCrapScore": 15, "MetricThresholdForNPathComplexity": 200 }
> 2022-08-15T16:31:32: Loading report '/workfir/target/site/jacoco-both/jacoco.xml' 1/1 in memory
> 2022-08-15T16:31:32: Preprocessing report
> 2022-08-15T16:31:32: Initiating parser for JaCoCo
> 2022-08-15T16:31:32: Current Assembly: com/example/javamavenjunithelloworld
> 2022-08-15T16:31:32: Finished parsing '/workfir/target/site/jacoco-both/jacoco.xml' 1/1
> 2022-08-15T16:31:32: Parsing of 1 files completed
> 2022-08-15T16:31:32: Starting merging result 1
> 2022-08-15T16:31:32: Finished merging result 1
> 2022-08-15T16:31:32: Coverage report parsing took 0.1 seconds
> 2022-08-15T16:31:32: Initializing report builders for report types: Cobertura, lcov
> 2022-08-15T16:31:32: Analyzing 2 classes
> 2022-08-15T16:31:32: Creating report 1/2 (Assembly: javamavenjunithelloworld, Class: com/example/javamavenjunithelloworld/Hello)
> 2022-08-15T16:31:32: Creating report 2/2 (Assembly: javamavenjunithelloworld, Class: com/example/javamavenjunithelloworld/HelloApp)
> 2022-08-15T16:31:32: Creating summary
> 2022-08-15T16:31:32: Writing report file 'converted-coverage/Cobertura.xml'
> 2022-08-15T16:31:32: Writing report file 'converted-coverage/lcov.info'
> 2022-08-15T16:31:32: Report generation took 0.1 seconds

2. If the issue is related to a specific coverage file which gets parsed by ReportGenerator, you can share the file:
Input: [jacoco-both.xml.zip](https://github.com/danielpalme/ReportGenerator/files/9338456/jacoco.xml.zip)
Output: [converted-coverage.zip](https://github.com/danielpalme/ReportGenerator/files/9338460/converted-coverage.zip)

*Note that I've also attempted this with the single Jacoco report (Not `-both`) as the one attached is the combined. I get the same result. I've been able to successfully generate a cobertura report w/ cover2cover.py which give me confidence that it isn't the coverage report itself.*

**Operating System**
macOS Monterey w/ `.Net 6.0.400`
ReportGenerator: `5.1.9`

I've also used  `mcr.microsoft.com/dotnet/sdk:6.0` w/ no success.
dotnet-reportgenerator-globaltool: `5.1.9`

**Comment by danielpalme** [comment]
Thanks for reporting this issue.
I will look into it within the next 2 weeks.

**Comment by danielpalme** [comment]
Which JaCoCo version are you using?
I guess it's 0.7.x or older.

If you upgrade to a current version (0.8.8 is the current release), it should work.
Older versions of JaCoCo don't contain the `sourcefilename` attribute.

See 
https://github.com/danielpalme/ReportGenerator/blob/main/src/Testprojects/Java/Reports/JaCoCo0.7.7.xml#L6
and
https://github.com/danielpalme/ReportGenerator/blob/main/src/Testprojects/Java/Reports/JaCoCo0.8.3.xml#L6

**Comment by djthornton1212** [comment]
You're absolutely right. I'm using v0.8.1. Moving to v0.8.8 fixed it.

Thank you!

Did I miss that in the docs somewhere?

**Comment by danielpalme** [comment]
No, it's not mentioned in the docs.
But I will add a hint.
