### ISSUE TITLE
Feature Request: Self contained exeutable

### ISSUE THREAD

**Issue by rcollette** [danielpalme/ReportGenerator#549]
I'm a big fan, having used this in my .NET projects.

I am wondering if any thought has been given to creating a self contained executable.  The reports generated by this tool are really quite nice.  However, one tends to get sneers when dotnet is required to generate the report when the source is another language/platform.   Publishing as a self executable for install with apk, apt-get, etc. could broaden the audience for this tool.

**Comment by danielpalme** [comment]
Thanks for your suggestion.
As far as I know, that would mean I would have to create executables for all permutations of operating systems and plattforms:
- Windows, macOS, Linux
- x64, x86, ARM

I'm not sure if I want to spend my time on this and keep maintaining it in the future.

**Comment by danielpalme** [comment]
I'm closing this for now. I guess the effort is too high for maintaining this.
