### ISSUE TITLE
How to enable Branch Coverage

### ISSUE THREAD

**Issue by decentshakti** [danielpalme/ReportGenerator#55]
Is there any option to enable Branch Coverage in report generator ?
See the snapshot we have blank in place of branch coverage.
![capture](https://cloud.githubusercontent.com/assets/8180193/17053591/642f371e-5020-11e6-9d7b-2a622b18fd06.JPG)

**Comment by danielpalme** [comment]
Branch coverage is only supported for [OpenCover](https://github.com/OpenCover/opencover).

**Comment by SiddhiKK** [comment]
Hello Daniel,

I have recently started using reportgenerator with Visual Studio coverage files and the results generated are really very good. I understand that the Branch coverage is currently only supported for OpenCover but I would like to know is there some way I can all together just not display it as it doesn't quite look good in the report that its just blank. I don't actually require it anyway.
Also just a suggestion it would be great if it was possible to adjust the width of the columns in the report.
Any help would be appreciated.Thanks

**Comment by danielpalme** [comment]
@SiddhiKK:
I will see what I can do. 
But I think these a minor issues. An empty column does not really affect the usefulness of the report.

**Comment by decentshakti** [comment]
Hey, add this css in your index file to hide "branch coverage". We have done the same. :)

th:nth-child(n + 8), td:nth-child(n + 8), col:nth-child(n + 8), thead th:nth-child(7)
{
	display:none;
}

**Comment by decentshakti** [comment]
You can also add this to "report.css", if it doesn't affect other html pages.

**Comment by danielpalme** [comment]
@decentshakti:
Sorry but it's not that easy. I have to make that conditional, depending on whether branch coverage is available or not.

**Comment by decentshakti** [comment]
Yeah daniel its just a workaround to hide "branch coverage" column, if it is empty. The case when someone has generated coverage from VS. 
For you a check is definitely required.

**Comment by SiddhiKK** [comment]
@danielpalme Thanks for replying back. yes its a minor issue otherwise the tool works beautifully, I just wanted to know whether there was some workaround that you can suggest.
Hey, any inputs on whether it's possible to make the columns widths adjustable, as my file names are quite long just wanted to know if something can be done? It isn't a problem just a question.

@decentshakti Thank you for the suggestion will try that tomorrow and let you know how it goes.

**Comment by danielpalme** [comment]
@all:
Please have a look at the beta:
https://www.nuget.org/packages/ReportGenerator/2.4.6-beta8

Branch coverage should now only be visible for OpenCover.

@SiddhiKK:
Column width are currently not adjustable.

**Comment by SiddhiKK** [comment]
@danielpalme 
Thank you so much for the quick response and helping me with the requirement. I appreciate that you fixed it so quickly.The report looks perfect now.

**Comment by bhavnajoshi1989** [comment]
Hi I am facing same issue, open cover is giving all the reports like class coverage ,branch coverage but when i am using report generator then nothing is coming for branch coverage.  its same as screen shot attached with this issue, please share solution ASAP.
