### ISSUE TITLE
Feature Request: Support using sub-folders in the TargetDir for each generated report type.

### ISSUE THREAD

**Issue by bhehe** [danielpalme/ReportGenerator#551]
I'm new to ReportGenerator and just getting acquainted with it, and in my initial exploration I was using more than 1 report type; I started off with using the **Cobertura report** (_for a summary/merged xml file_) along with the **Html report** and that worked but I was surprised to see the Cobertura file was dropped in the same TargetDirectory co-mingled with the Html report's files. 

As I continued to experiment to see what each report type generated, trying the other Html variants in addition to the 1st two, it seems like that wouldn't be possible as the files would get overwritten when 2 or more report types leverage the same name (i.e., index.html).

To address that, it would be nice if the TargetDirectory served as a root path but then each report type included would be dropped into a sub-folder named accordingly.  Obviously, this would be a change in behavior/breaking change so it would need some type of 'opt-in' model perhaps.  Another potential way to provide this without it being a breaking change or requiring any additional flag/opt-in would be to allow the TargetDir to be tokenized - i.e.  ".\MyTargetDir\$(ReportType)\" which would then allow existing tooling like Nuke Builds & it's fluent helper interface for ReportGenerator to take advantage of the support without those additional parties needing to make changes to accommodate the new behavior.

I know that I could run ReportGenerator multiple times with a different TargetDirectory for each report type I want but that seems inefficient as it would be parsing/analyzing the coverage input files each time and I'd rather avoid that approach.

If there's a way to achieve this currently, I'd be interested if someone could point me to the relevant documentation. I'll continue to look around more in the interim but so far, I've not found anything that suggests this is currently possible.

**Comment by danielpalme** [comment]
Please add this command line parameter: `settings:createSubdirectoryForAllReportTypes=true`

See also: https://github.com/danielpalme/ReportGenerator/wiki/Settings#other-settings

**Comment by bhehe** [comment]
Thanks so much for considering this request **and** turning it around so quickly! I'll have to see if I can make Nuke pass this additional new setting; I was hoping that the tokenization approach wouldn't require a new setting/opt-in model since I would assume nobody would be using $(ReportType) as part of an actual output path. 

I'll report back if that's a barrier, I think there's a way to pass along other undefined settings in the Nuke tools' fluent helper/wrappers for ReportGenerator.
