### ISSUE TITLE
Method Coverage available as Non-Pro User

### ISSUE THREAD

**Issue by Nefarion** [danielpalme/ReportGenerator#552]
**Describe the bug**
Method Coverage should be a pro-only feature, but is visible in "History" graph
![image](https://user-images.githubusercontent.com/542084/195635761-56dc99cb-3080-4c68-8ae1-6cc3c0f70616.png)

I am running ReportGenerator 5.1.10.0 like so:
```
reportgenerator.exe 
-reports:<some *.cobertura.xml>
-targetdir:<snip> 
-reporttypes:Html;TextSummary 
-historydir:<snip> 
-assemblyfilters:-*.Views;-*.Tests;-*.Migrations 
-tag:2022.39.3231-vc6149712
```

**Comment by danielpalme** [comment]
Thanks for letting me know!
