### ISSUE TITLE
Request to add XML documentation to ReportGenerator.Core NuGet package

### ISSUE THREAD

**Issue by MarcelVersteeg** [danielpalme/ReportGenerator#553]
In our project we create documentation from our source code using SandCastle Help File Builder. In this project we also have a ReportGenerator plugin, that references the ReportGenerator.Core.

However, when generating the documentation of this plugin, we get missing documentation warnings of inherited methods of interfaces and classes defined in the ReportGenerator.Core.dll. This could easily be solved if the XML documentation file (ReportGenerator.Core.xml) would also be part of this NuGet package.

**Comment by danielpalme** [comment]
I will have a look at this within the next days.

**Comment by danielpalme** [comment]
I added the XML documentation file to the Nuget package.

The next release will contain the change.

**Comment by MarcelVersteeg** [comment]
Thank you

**Comment by danielpalme** [comment]
Release 5.1.11 is now available.
