### ISSUE TITLE
Support for .NET 7

### ISSUE THREAD

**Issue by venugopala-reddy** [danielpalme/ReportGenerator#557]
We are using report generator we are upgrading our projects to .NET 7. I see the support for .NET 7 is not yet available for report generator. May I know when is the support for the same is available?

**Comment by danielpalme** [comment]
Once .NET 7 is released this month, I will upgrade as well.
I already started with the necessary changes here: https://github.com/danielpalme/ReportGenerator/tree/net7

**Comment by danielpalme** [comment]
Release 5.1.11 is now available. It support .NET 7.
