### ISSUE TITLE
Azure Devops Report Generator excludes classes which name include '<' '>' chars

### ISSUE THREAD

**Issue by fmontoyap** [danielpalme/ReportGenerator#558]
Report Generator excludes classes which name include '<' '>' chars used in c# for generic types.

Example: class InlineViewModel&lt;T&gt; is not included in report. 
Xml of Cobertura was:

&lt;class line-rate="0" branch-rate="1" complexity="4" name="InlineViewModel\&lt;T\&gt;" filename="D:\a\1\s\src\***\InlineViewModel.cs"&gt;

**Comment by danielpalme** [comment]
This was fixed with version 5.1.4.
Are you using an older version?

**Comment by fmontoyap** [comment]
I'm using Azure Devops Task 'Publish code coverage results' version 1.200.0
I don't know the version of ReportGenerator that it uses internally.

________________________________
De: Daniel Palme ***@***.***>
Enviado: martes, 8 de noviembre de 2022 20:01
Para: danielpalme/ReportGenerator ***@***.***>
Cc: Francisco Montoya Pelayo ***@***.***>; Author ***@***.***>
Asunto: Re: [danielpalme/ReportGenerator] Azure Devops Report Generator excludes classes which name include '<' '>' chars (Issue #558)





Este mensaje proviene de un REMITENTE EXTERNO. Ten PRECAUCIÓN, en especial con los links y los adjuntos y no envíes información sin validar el emisor.


This was fixed with version 5.1.4.
Are you using an older version?

**Comment by danielpalme** [comment]
The "Publish code coverage results" task uses an old version of ReportGenerator internally.

I would recommend to use the [ReportGenerator extension](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator).

Then you publish the report by using the "Publish code coverage results" task
Make sure to set the environment variable `disable.coverage.autogenerate: 'true'` to avoid regenerating the report.

Here you find the full documentation:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#azure-devops-extension

**Comment by sj-net** [comment]
A temporary workaround https://github.com/microsoft/azure-pipelines-tasks/issues/15160#issuecomment-1437747630
