### ISSUE TITLE
MoveNext() instead of method name in metrics report

### ISSUE THREAD

**Issue by Jericho** [danielpalme/ReportGenerator#56]
For some reason, I sometimes see "MoveNext()" in the Metrics report. Any idea why?

![image](https://cloud.githubusercontent.com/assets/112710/17595961/efe60974-5fb4-11e6-9486-494734d89784.png)

**Comment by danielpalme** [comment]
Your class probably contains some LINQ queries. This could lead to some MoveNext() calls.
If you could provide the corresponding class and the coverage report generated by OpenCover, I could have a closer look.

**Comment by Jericho** [comment]
Here's the [class](https://github.com/Jericho/Picton/blob/master/src/Picton.452/Extensions/CloudBlobExtensions.cs)

and see the attached [coverage report](https://github.com/danielpalme/ReportGenerator/files/417301/coverage.zip)

Thanks for looking into it.

**Comment by danielpalme** [comment]
When your class gets compiled, some nested classes are generated by the compiler (e.g. Picton.Extensions.CloudBlobExtensions/&lt;TryAcquireLeaseAsync&gt;d__0).
Those classes contain a _MoveNext()_ method.
It probably makes sense to exclude those methods from the report.

I will see what I can do within the next days.

**Comment by danielpalme** [comment]
Please try again with new beta:
https://www.nuget.org/packages/ReportGenerator/2.4.6-beta1

**Comment by Jericho** [comment]
2.4.6-beta1 is a little better: 2 additional method names are displayed in the metrics but there still 6 methods identified as "MoveNext()". By the way, do you think the issue is related to the fact that these methods are 'async'?

![image](https://cloud.githubusercontent.com/assets/112710/17673429/aadb6736-62e6-11e6-8415-04f981d2c54a.png)

**Comment by danielpalme** [comment]
It's definitely related to the fact, that those methods are async.
With your  [coverage report](https://github.com/danielpalme/ReportGenerator/files/417301/coverage.zip) I get the following result:
![image](https://cloud.githubusercontent.com/assets/859606/17676142/64b0039c-632d-11e6-8b8d-6609b6274e75.png)

Can you upload the latest coverage report xml? Then I can check with the same file that you used.

**Comment by Jericho** [comment]
Here's the latest xml (I also included the generated report in case that might be useful).

[CodeCoverageReport.zip](https://github.com/danielpalme/ReportGenerator/files/418796/CodeCoverageReport.zip)

**Comment by danielpalme** [comment]
Thanks for your data. I believe you are still using the old version of ReportGenerator?!
I created a new project in VS, downloaded the latest beta from ReportGenerator with Nuget and created the report and it no more contains MoveNext() method names.

Could you verify again, that you are really executing the new beta?

**Comment by Jericho** [comment]
To be on the safe side, I deleted al nuget packages from my `packages` folder and re-built my solution. 

![image](https://cloud.githubusercontent.com/assets/112710/17677479/9244d056-62f8-11e6-8cbf-118364c44841.png)

As you can see, the beta report generator was downloaded. Here is the resulting dat and report:
[CodeCoverageReport.zip](https://github.com/danielpalme/ReportGenerator/files/418837/CodeCoverageReport.zip)

**Comment by Jericho** [comment]
One quick observation: I see the following footer in index.htm: `Generated by: ReportGenerator 2.4.5.0<br />8/15/2016 - 2:55:23 PM` despite the fact that I used 2.4.6-beta1

**Comment by danielpalme** [comment]
I forgot to update the version in this beta release. So it's still 2.4.5.0.
But very strange that we get different results from the same coverage xml.

**Comment by danielpalme** [comment]
I just published beta2.
The only change is an updated version which is also used in the footer of the report.

**Comment by Jericho** [comment]
Something just occurred to me: I use CakeBuild to compile my code, run unit tests, run opencover and run report generator. Cake stores nugget packages in a separate `tools` folder (as opposed to my solution's `packages` folder). That's probably why 2.4.5 is used. Let me see how I can force Cake to use beta1.

**Comment by Jericho** [comment]
Victory! I was able to force Cake to use report generator 2.4.6-beta2 and here is the result:

![image](https://cloud.githubusercontent.com/assets/112710/17678125/7e3f6cc6-62fb-11e6-84e9-fa2a825240d3.png)

**Comment by Jericho** [comment]
The new footer: 
![image](https://cloud.githubusercontent.com/assets/112710/17678163/983ae9ca-62fb-11e6-86ed-f18ebc82f92b.png)
