### ISSUE TITLE
Help installing the tool

### ISSUE THREAD

**Issue by mundodisco8** [danielpalme/ReportGenerator#563]
Hi,

Sorry, I might be too dumb, but I'm unable to install Report Generator.

I created a Windows 11 Sandbox and only installed .NET Core on it (version 7.0.0, the recommended version to install today) to make sure that I am in the cleanest environment possible. 

I open a powershell session and this is the output I get

```
PS C:\Users\WDAGUtilityAccount> dotnet add package ReportGenerator --version 5.1.12
Could not find any project in `C:\Users\WDAGUtilityAccount\`.
```

I managed to install _something_ following [this advice](https://github.com/danielpalme/ReportGenerator/issues/425#issuecomment-843954620), and indeed I can run `reportgenerator.exe` but when I try to use it (with gcovr in Ceedling, one of the tools of the Unity Testing Framework), it complains that `ReportCoverage.dll` doesn't exists, and indeed there is no presence of such file in my computer.

What am I missing?

**Comment by danielpalme** [comment]
The command `dotnet add package ReportGenerator --version 5.1.12` will only work if the directory `C:\Users\WDAGUtilityAccount` contains a *.csproj file. This seems not to be the case.

I would recommend the following command: 
```
dotnet tool install -g dotnet-reportgenerator-globaltool
```

This will install _ReportGenerator_ as a global tool.

You can execute it everywhere with `reportgenerator [options]`

**Comment by mundodisco8** [comment]
Thanks for your help!

This is what I got when I entered your command
```
dotnet tool install -g dotnet-reportgenerator-globaltool
C:\Users\joel.santos\AppData\Local\Temp\f1332e7e-eee0-42c0-ae38-addca268942b\restore.csproj : error NU1100: Unable to r
esolve 'dotnet-reportgenerator-globaltool (>= 0.0.0)' for 'net7.0'.
C:\Users\joel.santos\AppData\Local\Temp\f1332e7e-eee0-42c0-ae38-addca268942b\restore.csproj : error NU1100: Unable to r
esolve 'dotnet-reportgenerator-globaltool (>= 0.0.0)' for 'net7.0/any'.
The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

I did some research about the error code last week, but I guess I was tired and couldn't solve it. Today, with a fresher mind, I found [this page](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100). I noticed [solution 2](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100#solution-2), and tried running `dotnet nuget list source`

```
dotnet nuget list source
No sources found.
```

Solution 2  says "Alternatively, you can create a configuration file using [dotnet new nugetconfig](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new). We recommend that you create this file at the repository level.". I tried that:

```
dotnet nuget list source
Registered Sources:
  1.  nuget [Enabled]
      https://api.nuget.org/v3/index.json

dotnet tool install -g dotnet-reportgenerator-globaltool
You can invoke the tool using the following command: reportgenerator
Tool 'dotnet-reportgenerator-globaltool' (version '5.1.12') was successfully installed.
```

And that did the trick! So it was a problem with that NuGet thingy. Sorry, it's the first time I install something with this dotnet thingy.

**Comment by danielpalme** [comment]
Great that you figured it out!
