### ISSUE TITLE
Unable to get the "group" element name when parsing the JaCoCo file

### ISSUE THREAD

**Issue by Oliverfk** [danielpalme/ReportGenerator#572]
**Describe the bug**
I am using ReportGenerator Nuget version 5.1.9 in .Net 6.0. Here's how I use it to parse the JaCoCo reports: 
```
  var filter = new DefaultFilter(new string[] { });
  CoverageReportParser parser = new CoverageReportParser(
      numberOfReportsParsedInParallel: 1,
      numberOfReportsMergedInParallel: 1,
      sourceDirectories: Array.Empty<string>(),
      assemblyFilter: filter,
      fileFilter: filter,
      classFilter: filter);

  var parserResult = parser.ParseFiles(JaCoCoFiles);
```

JaCoCo report has an element property called "group". The hierarchy of the elements starts with "group" -> "package" -> "class", etc. However, I cannot find the "group" information in the `parserResult`. The `parserResult.Assemblies` property only reflects the information under "package" element, yet I would also like to see the "group" element information.

**To Reproduce**
I am attaching the JaCoCo file [jacoco.txt](https://github.com/danielpalme/ReportGenerator/files/10223457/jacoco.txt) (github does not allow me to upload `.xml` format, attaching the `.txt` instead). In my example, the JaCoCo has 10 `<group name="">...<group>` element blocks, yet the `parserResult` does not contain any "group" element information. See the screenshots: 
![image](https://user-images.githubusercontent.com/25905012/207485075-601e9106-6040-43df-bdf5-ce4d57f71164.png)
![image](https://user-images.githubusercontent.com/25905012/207485299-038e81b0-c27f-4a35-8446-980e9cceda85.png)

I wonder if it is possible to have the group elements included in the `Assemblies` property, or make a new property called `Groups` for JaCoCo? 

It's more like a bug then a feature request to me, so I created a bug report. Thank you.

**Comment by danielpalme** [comment]
_ReportGenerator_ support a lot of different [input formats](https://github.com/danielpalme/ReportGenerator#supported-input-and-output-file-formats).
The different parsers create a common format to abstract away the differences between the different input formats.
This is intentionally to be able:
- to combine different formats into a single output report
- to have a single intermediate format which simplifies the further processing

That also means that not every detail is available in the intermediate format.
This format is good enough to generate the reports.
I understand that it may not fit your needs, but I won't introduce another hierarchy element here.

**Comment by Oliverfk** [comment]
Thanks for the answer. Fair enough.
