### ISSUE TITLE
Azure DevOps Services Sign In during report generation

### ISSUE THREAD

**Issue by lKoTl** [danielpalme/ReportGenerator#574]
Hi,

We started seeing next picture when the coverage is generated.

1. When there is no branch coverage for the classes the it generates the report and ends up with HTML page to sign in into DevOps when viewing the line coverage.
![image](https://user-images.githubusercontent.com/11078910/207861841-0353cf1c-5fb3-4530-9486-bf6455318b0d.png)

2. When there is a branch coverage during report generation it hits 500 error
![image](https://user-images.githubusercontent.com/11078910/207862194-87102bfa-d3f5-453b-83ca-1ee614d53ef6.png)

When navigating manually to the file view as a logged in user (via browser) the file is reachable.

Is there anything that could be configured / changed to make it work?

**Comment by danielpalme** [comment]
Please have a look at my comment here:
https://github.com/danielpalme/ReportGenerator/issues/501#issuecomment-1073008102

This comment describes how you can create a "Personal access token" and pass the token to ReportGenerator.

**Comment by lKoTl** [comment]
Great, that solves it.
Went with System Access token instead Personal, didn't want to personalize the pipelines.

`customSettings: 'settings:customHeadersForRemoteFiles=Authorization=Bearer $(System.AccessToken)'`
