### ISSUE TITLE
Feature Request: Title Parameter for other output file types

### ISSUE THREAD

**Issue by LordSaitamaa** [danielpalme/ReportGenerator#575]
Hey,

first of all thanks for the great work with this report generator.

But may it possible to add the title functionality for other files like Markdown ?

Currently only Html and Latex supports the use of the title parameter (which is not described in the readme).
It would be pretty awesome to use custom titles for any other file types :)

**Comment by danielpalme** [comment]
Thanks for the suggestion.

I made the necessary chnages to display the title on Markdown and text reports.

**Comment by danielpalme** [comment]
Release 5.1.13 has been published.
