### ISSUE TITLE
C# code clipped

### ISSUE THREAD

**Issue by Jericho** [danielpalme/ReportGenerator#58]
Report generator seems to clip my code if a line is longer than a certain number of characters as you can see in this example:

![image](https://cloud.githubusercontent.com/assets/112710/17708168/698e67b0-63a9-11e6-8c48-406b0034a3a8.png)

**Comment by Jericho** [comment]
Here are a few more examples:

![image](https://cloud.githubusercontent.com/assets/112710/17708263/e185b5b6-63a9-11e6-9321-1c8e00846ef3.png)

![image](https://cloud.githubusercontent.com/assets/112710/17708304/0a432b1e-63aa-11e6-8e7e-42c3418d0e6f.png)

![image](https://cloud.githubusercontent.com/assets/112710/17708327/20196354-63aa-11e6-95d4-ff6677abdc06.png)

**Comment by danielpalme** [comment]
Correct, lines are limited to 120 characters.
