### ISSUE TITLE
Files with 0 lines show up as red in output report

### ISSUE THREAD

**Issue by h2oboi89** [danielpalme/ReportGenerator#582]
Possibly filter / mark files with no coverable lines as green?

Example:
![image](https://user-images.githubusercontent.com/5531999/212236211-dc190d4b-2a39-49b5-89c6-730b47e67b2f.png)

**Comment by danielpalme** [comment]
Which version of ReportGenerator are you using?

Classes with no coverable lines should show up in grey:
![image](https://user-images.githubusercontent.com/859606/212465191-0f416ea8-255f-4756-870e-02b528d41d25.png)

Can you share the generated coverage report with me?
You can sent it privately by email: reportgenerator@palmmedia.de

**Comment by danielpalme** [comment]
I'm closing this for now. Let me know if you can provide any details.

**Comment by h2oboi89** [comment]
Sorry for delay. Sent email.

**Comment by danielpalme** [comment]
Thanks for providing the files.
I have fixed this in release 5.1.17.

**Comment by h2oboi89** [comment]
Sieht gut aus, Danke!
