### ISSUE TITLE
Missing styling, icons etc in Azure DevOps

### ISSUE THREAD

**Issue by aramB** [danielpalme/ReportGenerator#592]
I just installed ReportGenerator extension and configured it in my Azure DevOps. But it seems like that the summary/code coverage report is missing some styling and functionalities when I compare it with e.g. this example: https://reportgenerator.io/resources/reports/HtmlInline_AzurePipelines/index.html

With functionalities I mean e.g. the grouping function and the diagrams.
With styling I mean the colors and so on.

From the example:
![image](https://user-images.githubusercontent.com/21197578/220866956-a060e109-12af-429e-83d7-e5f97bb9a7ca.png)
![image](https://user-images.githubusercontent.com/21197578/220867061-a5ee6314-b953-455f-a651-2d10a663835b.png)

From my Azure DevOps:
![image](https://user-images.githubusercontent.com/21197578/220867476-5c68a414-62eb-4b5b-ba7e-9b2d83e53d08.png)
![image](https://user-images.githubusercontent.com/21197578/220867263-9da3d9ff-3fdd-4c27-9022-90a1e2b3b310.png)

What am I missing?

Thanks in advance!

**Comment by danielpalme** [comment]
Yes that's an limitation of Azure DevOps.
 Azure DevOps has very strict CSP-rules and blocks Javascript and some CSS rules.

If you download the corresponding artifact and open the report locally, you should have the full experience.

**Comment by aramB** [comment]
Ok, so does it mean that we can't have the full experience in Azure DevOps? Only locally? 😞

**Comment by danielpalme** [comment]
Yes.

**Comment by aramB** [comment]
Ok, thanks for quick reply!
