### ISSUE TITLE
Report colors do not match Azure DevOps theme

### ISSUE THREAD

**Issue by bramborman** [danielpalme/ReportGenerator#594]
[The wiki](https://github.com/danielpalme/ReportGenerator/wiki/Output-formats#html) says:

> _- **HtmlInline_AzurePipelines**: Same as HtmlInline but with an adaptive light/dark theme matching the look and feel of Azure Pipelines._

My Windows 10, browser (Edge) and Azure DevOps themes are all set to be dark, but the report is light when displayed in the Azure Pipelines UI, anyway:

![azdo](https://user-images.githubusercontent.com/20975774/221614454-c1e4fbf5-d5ab-41ea-a6b7-af1f7dd75a95.png)

I'm using the extension v5.1.18 in Azure DevOps Services (cloud) and this really is the file generated by this version. When I download it from the artifacts, the dark/light colors work fine. I've been looking into that and it seems that Azure DevOps cleans the HTML file of some tags and also CSS, resulting in this behavior when displayed in the Pipelines UI. I don't know if there's a way to fix this on your side, so at least the documentation here should be updated.

**Comment by danielpalme** [comment]
The problem here is that Azure DevOps blocks JavaScript and some CSS rules (see #592).
There is nothing I can do about it.

If you download the report, everything works fine and your local dark theme is picked up.
