### ISSUE TITLE
Red-green colorblind accessibility issue with coverage report

### ISSUE THREAD

**Issue by kristinnbragi** [danielpalme/ReportGenerator#595]
I was going over code coverage results with a developer who has colour blindness and discovered that the tool is not accessible for red green colour blindness. Line highlights are especially hard to differentiate due to the desaturated colour. A natural fix would be to include symbols as a supplement.
<img width="1394" alt="Screenshot 2023-03-03 at 14 50 02" src="https://user-images.githubusercontent.com/36210215/222738048-f620f57e-be65-427b-8138-898e82d8c63f.png">

**Comment by danielpalme** [comment]
I totally understand that this is an issue.

- Do you have a concrete idea for  "include symbols as a supplement"?
- Would a different color scheme be more helpful (e.g. blue/yellow instead of green/red). What would be good colors?

**Comment by kristinnbragi** [comment]
> Do you have a concrete idea for "include symbols as a supplement"?
Not really, although a simple + or - would work, it might also be misleading. Another tool, [Bullseye](https://www.bullseye.com/), uses these icons for example:
<img width="87" alt="Screenshot 2023-03-06 at 15 48 43" src="https://user-images.githubusercontent.com/36210215/223144753-6da18438-f79e-4de6-b84b-e24c9a305dec.png">

> Would a different color scheme be more helpful (e.g. blue/yellow instead of green/red). What would be good colors?
Definitely! I don't know what colors would make sense that would support all types of color blindness. Ultimately, the best solution would be to offer the user to choose their own color scheme

**Comment by danielpalme** [comment]
I added a new report type `Html_BlueRed` in version 5.1.19
To use it, add the following command line parameter when executing _ReportGenerator_: `-reporttypes:Html_BlueRed`

Here you can find a sample report:
https://reportgenerator.io/resources/reports/Html_BlueRed/index.html

Hope this helps!

**Comment by vzhik54** [comment]
> I added a new report type `Html_BlueRed` in version 5.1.19 To use it, add the following command line parameter when executing _ReportGenerator_: `-reporttypes:Html_BlueRed`
> 
> Here you can find a sample report: https://reportgenerator.io/resources/reports/Html_BlueRed/index.html
> 
> Hope this helps!
Hello.
Could you please clarify what type of reports I can use for summary report to resolve the same trouble?

**Comment by danielpalme** [comment]
> Hello. Could you please clarify what type of reports I can use for summary report to resolve the same trouble?

There no separate Blue_Red summary report yet.
But I can add this in the next release.

**Comment by danielpalme** [comment]
@vzhik54 
I just created a sample report: https://reportgenerator.io/resources/reports/Html_BlueRed_Summary/summary.html

Does this work for you?

The next release will contain the new report type `Html_BlueRed_Summary`.

**Comment by vzhik54** [comment]
@danielpalme 
Yes, this report type work for me. Thanks :-)

**Comment by danielpalme** [comment]
Release 5.1.26 is now available. It contains the new report type.
