### ISSUE TITLE
Wrong number for branchcoverage after reportgenerator for cobertura.xml

### ISSUE THREAD

**Issue by mklpanasiuk** [danielpalme/ReportGenerator#597]
**Describe the bug**
Wrong number for branchcoverage after reportgenerator for cobertura.xml

**To Reproduce**
1. Run: reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:./" "-reporttypes:JsonSummary;Html;Badges"
2. Open Summary.json or Index.html and check branch coverage, compare with results in coverage.cobertura.xml
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/53987913/225904180-93fc00d5-7700-4886-8001-6b2da7969334.png">

NOTE: the original file coverage.cobertura.xml has been sent to your email adress

**Comment by danielpalme** [comment]
I will have a look as soon as possible.

**Comment by mklpanasiuk** [comment]
Thank you for the reply!
