### ISSUE TITLE
Reference to js map

### ISSUE THREAD

**Issue by tomap** [danielpalme/ReportGenerator#6]
Hi,

In ReportGenerator.Reporting/Rendering/resources/chartist.min.js
there is a reference to chartist.min.js.map
(last line: //# sourceMappingURL=chartist.min.js.map )
This reference will cause an error message in Chrome debugger.
It's a minor issue :)

Thanks,

Thomas P.

**Comment by danielpalme** [comment]
As you said that's only a warning of the Chrome debugger. I don't think it's helpful to include that file.
Since I combine the Javascript sources into one file, the map would probably not match.

**Comment by tomap** [comment]
I wasn't suggesting to include the map but rather to remove the reference.
But indeed, it's a minor issue :)

**Comment by danielpalme** [comment]
Fixed with release v.2.1.2.0.
