### ISSUE TITLE
MultiReportParser dilutes Assembly and Class coverage if the same code files are analyzed from different source paths

### ISSUE THREAD

**Issue by kwhickey** [danielpalme/ReportGenerator#60]
I have the same source code (from the same Git revision) re-compiled into different DLL instances as part of parallel unit test execution in a fanned-out CI pipeline (in Jenkins) . 

It's not the same project being analyzed multiple times with OpenCover, but rather a common/shared project that is a transitive dependency of each of the unique projects being analyzed.

After all parallel tasks are done performing unit/integration tests, the ReportGenerator is run on each of the .xml OpenCover output files - up to about 14 files. The MultiReportParser accumulates the results of each OpenCoverParser pass on each file. In doing so, it checks file equality during the merge of repeated assemblies, and -- because each parallel task acts on its own Git repository and working directory, stored in different folders (but all checked-out to the same revision) -- the files are found to not be the "equal".

_This difference in `CodeFile` equality somehow causes the `coverablelines` and `totallines` metrics for the class(es) within the files to be additive when merged together, while the `coveredlines` stays the same. **This ends up diluting the coverage % to a much smaller amount than it ought to be**._ 

If the shared DLL is present in 2, 4, more of those targeted projects, and so is present as a Module in 2,4,+ OpenCover output .xml files, it will double/quadruple/etc. the coverable lines. 

Note: It's the Jenkins workspace directory that causes the file paths to be diferent, e.g.
- `c:\Jenkins\workspace\my_jenkins_proj\src\Fully\Qualified\Assembly\ThenClassName.cs`
- `c:\Jenkins\workspace\my_jenkins_proj@2\src\Fully\Qualified\Assembly\ThenClassName.cs`
- `c:\Jenkins\workspace\my_jenkins_proj@4\src\Fully\Qualified\Assembly\ThenClassName.cs`
- `c:\Jenkins\workspace\my_jenkins_proj@5\src\Fully\Qualified\Assembly\ThenClassName.cs`

Are there any mechanisms in ReportGenerator (or perhaps OpenCover) to hint that these are the _same_ assemblies-under-test made up of the exact same source code?

I would suggest that ReportGenerator use the `hash` value of OpenCover modules, but since each DLL is compiled anew in each Jenkins node/workspace, the hashes of the DLLs wouldn't match (timestamps or guids embedded during compile).
- Maybe the assembly guid attribute in `AssemblyInfo.cs` could be exposed by OpenCover and used by ReportGenerator?
- Maybe ReportGenerator does a hash of each file as a better equality comparison?
- Or, maybe I have to post-process the OpenCover output to chop out the unique Jenkins workspace folder names to ensure all file paths are the same, despite emerging from different Git working dirs?
- The `sourcedirs` parameter could help, but I understand it to be ignored if a file path is present. Maybe have a flag that ignores embedded paths and uses only `sourcedirs`?

**Comment by kveretennicov** [comment]
@kwhickey, FWIW, that's what I ended up with - post-processing OpenCover .xmls to normalize the noise differences in source file paths. Also due to Jenkins workspace differences.

**Comment by danielpalme** [comment]
@kwhickey:
You have a quite unusual scenario, since you built the same project several times.
As @kveretennicov mentioned, I would also suggest that you add a post-processing step to unify the paths in the OpenCover files.

I will think about the problem. Perhaps I can find a solution in ReportGenerator that does not break other person's workflows.

**Comment by kwhickey** [comment]
@danielpalme, I don't think it's too unusual. Trying to gain efficiencies by parallelizing work that can be divided up is a good goal in CI pipelines. And keeping each task atomic by providing it its own source code (pinned to a specific revision) decouples any dependencies so that task could be scaled out to execute on any node/executor/agent.

Note that I'm not _directly_ building the same project multiple times. I am _directly_ building a _**different**_ project during each parallel task (and then running unit tests by-way of OpenCover on that project's DLL), but, many of those different projects have dependencies on the _same_ shared or common projects - so _they_ are **indirectly** (re)built as transitive dependencies. While testing, OpenCover is gathering coverage metrics on those shared projects since they're often in the execution path of testing the main project-under-test's code.

In Jenkins 2.0 pipeline syntax, what I ended up doing was using a `bat` call to `powershell.exe` to realign source paths in OpenCover output .xml files to the current workspace that was accumulating the Coverage Report. Snippet below:
```groovy
// Post-process the coverage output to change all source-file-paths to align to the working source dir on this node
// This is a workaround to ReportGenerator issue #60: https://github.com/danielpalme/ReportGenerator/issues/60
// NOTE: This leans on some conventions of Jenkins, like the workspace names all being the same except for the number following an '@' symbol, and there not being more than ONE '@' in the path. Adjust if that changes.
def coverageFilePath = 'the\\relativePath\\to\\OutputCoverage.xml' // get it however you're managing these files
def workspaceNum = "${pwd()}".split('@')[1]
// Run 3 PowerShell commands chained together to read the xml, update file paths, and write it back
bat "powershell.exe -ExecutionPolicy ByPass -NonInteractive -Command \"\$xml = [xml](Get-Content '${coverageFilePath}'); \$xml.SelectNodes('//File/@fullPath') | %% { \$_.'#text' = \$_.'#text' -replace '@\\d+','@${workspaceNum}' }; \$xml.Save('${coverageFilePath}'); exit \$LastExitCode\""
```

So this works, but there is kindof a performance penalty since some of these coverage files could be 10s of MB big depending on the size of the project, and that uses of memory and time to read in and write back.

**Comment by danielpalme** [comment]
Could you please test again with this beta release:
https://www.nuget.org/packages/ReportGenerator/2.4.6-beta5

I changed the implementation of the _CodeFile_ class in this release. Now only the name of the file is used for comparison instead of the full path.

**Comment by danielpalme** [comment]
@kwhickey:
Did you have time to retest with the latest beta?

**Comment by kwhickey** [comment]
@danielpalme 
I just tried it, and it didn't seem to work. It looks like the few DLLs that had reported lower-than-they-should (diluted) coverage were again diluted. So, without transforming the coverage output files to all have the same path, it seems to still be treating things as an additive coverage target (adding coverable lines and total lines from each distinct file path).

How do you get _just_ the file _name_? Is that an attribute in the coverage file? From the opencover .xml files, I only see `<File uid="1" fullPath="D:\The\Full\Path\to\Class.cs" />` , under `<Module ...><Files>` elements.

If just chopping it off the end of the path, that may be risky if the same file/class name is used under different namespaces.

**Comment by danielpalme** [comment]
@kwhickey:
Sorry, I did not tested carefully enough.
Please try again with:
https://www.nuget.org/packages/ReportGenerator/2.4.6-beta6

I'm chopping it off the end of the path. But that should not be a problem. 
First the name of the assembly has to match, then the name of the class and only then the name of the file is compared.
The only conflict I can image is  if you define a partial class in several directories and use the same file name in every directory. But that should really be an edge case.

**Comment by kwhickey** [comment]
@danielpalme 
That appears to have done the trick! The coverage levels came at where we were expecting them. Thank you!
How long do you anticipate it may be before this goes from beta to a stable release?

**Comment by danielpalme** [comment]
@kwhickey:
I'm not sure when a new "stable" release will be available. I still have some minor topics that I want to get into the next version.
But "beta" does not mean buggy. You can use the beta release without any worries.
It does not have any known bugs, but some features may get added into the next stable release.
