### ISSUE TITLE
HtmlSummary doesn't work with Azure Pipelines

### ISSUE THREAD

**Issue by MisinformedDNA** [danielpalme/ReportGenerator#602]
**Describe the bug**
Because of the size of our repo, when code coverage files are generated with `HtmlInline_AzurePipelines`, we run out of space on our hosted agent.

> Error during rendering report for class 'DataModule.DataSetTableAdapters.SomeTableAdapter' (Report type: 'HtmlInline_AzurePipelines'): There is not enough space on the disk. : 'D:\a\1\s\coveragereport\DataModule_SomeTableAdapter.html'

HtmlSummary seemed like a good solution, but it generates a summary.html file, which is not picked up by the Azure Pipeline UI:

![image](https://user-images.githubusercontent.com/1784452/230637467-58fe84ce-00b3-4729-b052-6450e78b570e.png)

Some options:

1. Copy `summary.html` to `index.html`.
2. Add a parameter to name the summary file.
3. Add a new report `HtmlSummary_AzurePipelines`.
4. I add a rename task right afterward.

**Comment by danielpalme** [comment]
I would suggest that you go with option 4.
Your scenario seem to be really rare.

Regarding the other options:

> 1. Copy `summary.html` to `index.html`.

This could cause problem if you generate other formats as well.

> 2. Add a parameter to name the summary file.

Definitely "no". I try to keep the number of parameters as low as possible.
Nobody likes to read the documentation for 100 parameters.

> 3. Add a new report `HtmlSummary_AzurePipelines`.

The behavior would then be different from the other summary reports.

**Comment by marcinsku** [comment]
I have a very similar case where, due to the number of classes, generating the report takes a few minutes. However, generating the HtmlSummary takes only a few seconds.

Option 4 does not work when we simultaneously use publishCodeCoverageResults: true.

Option 2 or 3 would be very useful.

**Comment by danielpalme** [comment]
@marcinsku 
I will have a look within the next days.

**Comment by danielpalme** [comment]
@marcinsku 
_HtmlSummary_ and _Html_BlueRed_Summary_ report types now also create an index.html file.
This file will be displayed in Azure DevOps if you use the `publishCodeCoverageResults: true` option.

I will publish a new release within the next days.

**Comment by marcinsku** [comment]
That's great! Thank you for the quick response.

**Comment by danielpalme** [comment]
New release 5.3.7 is now available.
