### ISSUE TITLE
Code coverage report caching deleted files

### ISSUE THREAD

**Issue by dyapp1435** [danielpalme/ReportGenerator#605]
**Describe the bug**
It seems that ReportGenerator is caching deleted files when run in an Azure DevOps CI pipeline. Jest correctly outputs the current list of files, but the generated Cobertura report contains a file that was deleted months ago.

**What I've tried**
- Enabling "clean: true" in the Azure pipeline
- Setting the git fetch depth to 1
- Adding 'settings:maximumNumberOfHistoricCoverageFiles=0' to the ReportGenerator customSettings attribute

**To Reproduce**
The following input helps to reproduce your issue:
1. Console output of ReportGenerator

```
/usr/bin/dotnet /home/vsts/work/_tasks/reportgenerator_be803a55-9253-4895-a525-be570d86f161/5.1.20/tools/netcoreapp3.1/ReportGenerator.dll -reports:**/*cobertura*.xml -targetdir:/home/vsts/work/1/coveragereport -reporttypes:HtmlInline_AzurePipelines;Cobertura -sourcedirs: -historydir: -plugins: -assemblyfilters:+* -classfilters:+* -filefilters:+* -verbosity:Info -title: -tag:20230510.3_#14228 -license: settings:maximumNumberOfHistoricCoverageFiles=0

2023-05-10T15:32:05: File '/home/vsts/work/1/s/__FILE_PATH__/__FILE_NAME__.ts' does not exist (any more).

2023-05-10T15:32:05: Writing report file '/home/vsts/work/1/coveragereport/Cobertura.xml'

2023-05-10T15:32:05: Writing report file '/home/vsts/work/1/coveragereport/index.html'

2023-05-10T15:32:05: Report generation took 0.5 seconds

Finishing: Generate code coverage report
```

**Comment by danielpalme** [comment]
_ReportGenerator_ generates its results only based on the information available in the supplied coverages files (here: `-reports:**/*cobertura*.xml`).
One of theses files must contain the "deleted" file, otherwise it would not be available in the report.

One way to debug this further:

- Add a file artifact to your pipeline which contains all files matching `**/*cobertura*.xml`.
- Download this file after a build
- Search these files to determine whether one of them contains the  "deleted" file.

**Comment by dyapp1435** [comment]
Thanks for the quick response! Yeah, now that I'm looking, Cobertura is definitely generating an html report with the deleted file's name. Would this issue be better submitted to the Cobertura repo?

**Comment by danielpalme** [comment]
> Would this issue be better submitted to the Cobertura repo?

I think so, but first you should check if the file is really not available anywhere in your code base.

Every build in Azure Devops runs on a clean agent. Jest/Cobertura don't "remember" a deleted file. It must somehow still be present.

**Comment by dyapp1435** [comment]
I can confirm that it's definitely not present anywhere in our repository.

**Comment by danielpalme** [comment]
Could you please create an artifact of the coverage file supplied to _ReportGenerator_ in your Azure DevOps pipeline.

See my [comment ](https://github.com/danielpalme/ReportGenerator/issues/605#issuecomment-1542542869) above.

I'm pretty sure the file is listed in some of the Cobertura files.

**Comment by dyapp1435** [comment]
Sorry for the delay. It's definitely listed in the Cobertura files, I can see it here:
![cobertura-output-51623](https://github.com/danielpalme/ReportGenerator/assets/87770982/e27bcb0d-86d9-42ce-af6c-63c70f8fa77b)

Should this just go to the Cobertura GitHub board?

**Comment by danielpalme** [comment]
The highlighted file is an HTML file.
An XML file must also exist here (ReportGenerator parses the XML file).

But the result will be the same: The HTML/XML contains the name of the deleted file.
I have no idea how Cobertura comes up with this file. Perhaps the corresponding GitHub board can help.
