### ISSUE TITLE
Report Generation takes too many resources

### ISSUE THREAD

**Issue by OrgesKreka** [danielpalme/ReportGenerator#608]
My coverage.xml file ( I can share if you need it ) is 126MB it contains 12k+ classes and takes more or less 7 minutes to be generated.
But when I try to generate the report it takes more than 20 minutes ( I didn't let to finish ) and more than 10GB of memory.
Is there any way to generate a  simple MarkdownSummaryGithub because I use the GitHub action and I cannot use it this way.

Thanks

**Comment by danielpalme** [comment]
I would like to investigate this further next week.
Can you share your coverage xml file?

Can upload it to GoogleDrive/OneDrive/Dropbox and send me the link?
You can sent it confidentially by email: [reportgenerator@palmmedia.de](mailto:reportgenerator@palmmedia.de)

**Comment by danielpalme** [comment]
Thanks for your email. I will have a look next week.

**Comment by danielpalme** [comment]
Could you please try again with the new release 5.1.22?
I made some optimizations to significantly reduce the execution time.
On my laptop memory usage never exceeded 900 MB.
But let's see if this is still an issue with the new release.

**Comment by OrgesKreka** [comment]
@danielpalme Sorry for the late reply but I was on vacation.
I tried today with the new version and as you can see from the screenshot now it consumes around  7GB and takes more than 10minutes to finish ( I killed it after 10 minutes )
![image](https://github.com/danielpalme/ReportGenerator/assets/22299171/dd6eb58e-2917-484d-a1db-3ba6d5c5c099)

**Comment by danielpalme** [comment]
Thanks for testing again.

I just tested myself with your coverage file and can confirm that the memory usage is pretty high:
![image](https://github.com/danielpalme/ReportGenerator/assets/859606/e7b9b873-4d45-4093-a626-1191639bbb24)

But after 60 seconds the coverage file is processed.

I will investigate this within the next days.

**Comment by danielpalme** [comment]
Your codebase contains ~3000 classes that are named `*ArrayOf*`.

The corresponding files seem to be very long (~150000 lines of code).

If I remove these classes with this filter argument `-classfilters:-*ArrayOf*` the memory usage drops to 2.4GB and execution time is about 30 seconds.

![image](https://github.com/danielpalme/ReportGenerator/assets/859606/7d6ba30f-3b7c-4cb6-9cbc-9c8d84975ebc)

I guess that those large files are generated automatically by some tool. Maybe you can ignore them for your coverage report with the command line parameter: `-classfilters:-*ArrayOf*`
`

**Comment by OrgesKreka** [comment]
Thank you very much for the debug, yes you are right. I have some old wsdls that have created their Reference.cs and one of those was very large. Since I could not exclude the Reference.cs from the coverlet I excluded them during the report generation, but again now for me it takes around 9 minutes to be generated. Below you can see the result:
![image](https://github.com/danielpalme/ReportGenerator/assets/22299171/a4499037-dd72-46a8-8844-5bcc0bb0aa42)

Is there anything to do to decrease the generation time?

**Comment by danielpalme** [comment]
> Is there anything to do to decrease the generation time?

If you only want the MarkdownSummaryGithub report, you should not specify any other report types.

Your command line parameters should look like this:
`reportgenerator -reports:... -reporttypes:MarkdownSummaryGithub -classfilters:-*ArrayOf*`

On my machine this command takes about 30 seconds.
I don't know why it's that much slower on your machine.

Some potential issues:
- You added additional report types
- You don't use an SSD
- Some anti virus tool may slow down report generation

**Comment by OrgesKreka** [comment]
@danielpalme thank you very much for your help!
It looked like the issue was again related with the classes generated by the wsdl-s.
I excluded the assembly that contains those classes and now it takes around 30s to generate the report.
Wishing you all the best!
