### ISSUE TITLE
How to use Cobertura xml in Report generator

### ISSUE THREAD

**Issue by arpit-nagar** [danielpalme/ReportGenerator#61]
Hi @danielpalme,

Thanks for the nice tool. It shows very pretty coverage reports.
I have a cobertura coverage report (.xml file). 
Can I directly use this xml file in ReportGenerator or Is there any other way exists to convert cobertura xml to report generator?

**Comment by danielpalme** [comment]
The cobertura format is currently not supported.
But cobertura generates it's own HTML report, so do we really have to support in ReportGenerator? Till now, ReportGenerator is focused on .NET coverage tools.

**Comment by arpit-nagar** [comment]
We are using report generator in many of our .net applications. Now we started implementing some applications in nodejs. Report generator produce very pretty reports and we are now habitual of these reports. so just wanted to implement same experience in our nodejs application. 
We are not stucked on this request. It will be a plus if we can achieve this. 
If it not supported, you can close this issue.
Thanks for your quick response and support. 😄

**Comment by danielpalme** [comment]
I understand. Can you provide some sample cobertura files? Then I can have a look at them and see if I can support them in ReportGenerator.
You can upload them here or send by mail: danielpalme82@gmail.com

**Comment by arpit-nagar** [comment]
Thanks @danielpalme for looking into it.
I have sent you a mail.

**Comment by danielpalme** [comment]
I will look into it. But it could take a couple of days until I find time.

**Comment by danielpalme** [comment]
I already managed to add support for Cobertura.

It would be great if you could try this beta release:
https://www.nuget.org/packages/ReportGenerator/2.4.6-beta7

Let me know if you have any issues.
I will publish the corresponding source code on Github when I have added some more tests for Cobertura.

**Comment by arpit-nagar** [comment]
Thank @danielpalme,
You are awesome. It worked like a charm. 
Thanks for your quick support. Now we have same reports in C# and nodejs projects. 😂
