### ISSUE TITLE
Increase percentage accuracy in reports

### ISSUE THREAD

**Issue by pantosha** [danielpalme/ReportGenerator#612]
**Describe the bug**
In the current implementation, reports contain percentages rounded to tenths.
For projects with >100000 lines it's a too low resolution.
Is it possible to increase accuracy to hundreds/thousands?

**To Reproduce**
The following input helps to reproduce your issue:
1. Generate `Html` report
2. Open report:

Actual:
Line coverage, Branch coverage, Method coverage round to tenths

Expected:
Line coverage, Branch coverage, Method coverage round to thousands

**Comment by danielpalme** [comment]
Starting with version 5.1.24 you can now set the accuracy with a new setting

Just add the following command line parameter:
`settings:maximumDecimalPlacesForCoverageQuotas=3`
