### ISSUE TITLE
10 day trial period

### ISSUE THREAD

**Issue by behdad07** [danielpalme/ReportGenerator#613]
**Describe the bug**
Hi, I requested 10 days trial license request to try the pro library. I just received the license key but I don't know where to insert it. I tried to look around on the website but I did not see any relevant links. Can you please send me a link if it exists that explains how to activate the license key?

**To Reproduce**
The following input helps to reproduce your issue:
1. Console output of ReportGenerator
2. If the issue is related to a specific coverage file which gets parsed by ReportGenerator, you can share the file:
  - Publicly
  - By email: reportgenerator@palmmedia.de
Small files can be send as an attachment. Large files should can be shared via Dropbox, Google Drive, Onedrive.  
Shared files are treated confidentially and will be deleted after the issue is resolved.

**Comment by danielpalme** [comment]
@behdad07 
You can pass the license as a command line parameter:

`-license:YOURKEY`

**Comment by behdad07** [comment]
Thank you @danielpalme for your super quick response. Really appreciate it. I found the answer as soon as I posted the issue. I tried to delete it but it seems like it's not possible. Sorry for the inconvenience. 
Thank you again.

**Comment by danielpalme** [comment]
No worries. You're welcome.
