### ISSUE TITLE
LCov: branch hit count can overflow Int32. 

### ISSUE THREAD

**Issue by ericjulien** [danielpalme/ReportGenerator#619]
Getting the following error during report generation with lcov:
```
Error during reading report '/home/ejulien/lcov.info' (Size: 1.1MB): Value was either too large or too small for an Int32.
```

Branch hit count overflow protection seems to be missing [here](https://github.com/danielpalme/ReportGenerator/blob/255553e1328101cfc46c91d91da081d1df06b4b1/src/ReportGenerator.Core/Parser/LCovParser.cs#L153)

Ref to commit fixing similar issues https://github.com/danielpalme/ReportGenerator/commit/eae8dd7cc290dde57f3c7a99324012f62fa8d73b

**Comment by danielpalme** [comment]
Fixed in https://github.com/danielpalme/ReportGenerator/commit/ce32b7c0f26251ee13a147a383bae598a7b39cc8
