### ISSUE TITLE
Visual Studio .coveragexml: ReportGenerator ignores compiler-generated classes

### ISSUE THREAD

**Issue by RoadTrain** [danielpalme/ReportGenerator#625]
**Describe the bug**
Hi!
When class methods contain local functions, the .net compiler (roslyn-era) generates separate classes for them. These classes (and their methods) are ignored by ReportGenerator, while there can be a lot of logic in them. The main problem is that line and block coverages of these local functions is lost in the generated report. We have classes which mainly consist of local functions, and the coverage metrics are very off for them, compared to what Visual Studio shows.

I have found a very similar issue which was closed without resolution https://github.com/danielpalme/ReportGenerator/issues/120.

**To Reproduce**
I have attached a sample hand-crafted coveragexml where class `MyScenario` contains both a class method and two local functions and a resulting report. Line numbers are off but it doesn't matter because you can still see the main problem -- compiler-generated classes are ignored.
[vs_issue_sample.zip](https://github.com/danielpalme/ReportGenerator/files/12674126/vs_issue_sample.zip)

**Comment by RoadTrain** [comment]
After taking a quick glance at the code, I can see two things:
1. Currently there's a special case for compiler-generated iterator methods: https://github.com/danielpalme/ReportGenerator/blob/282bdbe7fc6ec88b5812a10a468195ce873798f3/src/ReportGenerator.Core/Parser/VisualStudioParser.cs#L333
2. Lambdas (and consequently local functions) are excluded (which dates back to the[ initial import in 2016](https://github.com/danielpalme/ReportGenerator/commit/1d641f24e1931c1d1e8b16b6afdcb901f975b98b#diff-846b0211c7127e57a159d293c47c9060cc6f9017c49de7357ddc341cbf0b441c)): https://github.com/danielpalme/ReportGenerator/blob/282bdbe7fc6ec88b5812a10a468195ce873798f3/src/ReportGenerator.Core/Parser/VisualStudioParser.cs#L245

Still,

**Comment by danielpalme** [comment]
I just found time to have a closer look. Sorry for the delay.

> The main problem is that line and block coverages of these local functions is lost in the generated report. We have classes which mainly consist of local functions, and the coverage metrics are very off for them, compared to what Visual Studio shows.

Compiler generated classes are not listed on the summary page, that's correct. But the relevant lines are processed within the corresponding parent class.
In your example the summary report only shows the classes `MyLogic` and `MyScenario`.
But if you look into the `MyScenario` report, you will see that all coverable lines are considered. Even the block with line 729-738, which belongs to a compiler generated class.

> 1. Currently there's a special case for compiler-generated iterator methods: 
Yes, but that's just a naming thing. The name `MoveNext` is not very helpful, instead the "correct" method name is retrieved.

> 2. Lambdas (and consequently local functions) are excluded
Yes, but only in the list of methods and their metrics. This does not affect the overall code coverage.

Does this help? I'm I missing something?

**Comment by RoadTrain** [comment]
The main issue we had is the 'Blocks covered' method metric which was incorrect (i.e. apparently not including compiler-generated local functions). It seems to me that the Lines metric is calculated correctly indeed.

**Comment by RoadTrain** [comment]
And what about properties? They are excluded from the report too, do they count towards line metrics like compiler-generated methods do? In theory, property getters/setters can (and often do) have some logic in them, so they should count towards line/block coverage metrics.

**Comment by RoadTrain** [comment]
We have been digging further, and now I'm not sure there's a problem with the library. Please put this on hold, I'll be back with a verdict shortly.

**Comment by RoadTrain** [comment]
So our current understanding is that including lambda/local functions in total metrics (as suggested by me) is incorrect because they are already included by Visual Studio coverage. So the premise of this bug report is false, sorry for that.

They only thing that we would like to have is the ability to "see" these functions, i.e. be able to extract their metadata with `ReportGenerator.Core` library to show them on our dashboard, without affecting metrics.

**Comment by danielpalme** [comment]
> They only thing that we would like to have is the ability to "see" these functions, i.e. be able to extract their metadata with `ReportGenerator.Core` library to show them on our dashboard, without affecting metrics.

I will see what I can do. Will come back to you as soon as possible.

**Comment by danielpalme** [comment]
I think I have found a solution.
To get this finished quickly: Would it be possible for you to run the tests in the attached project in Visual Studio and send me the _coveragexml_ file? 

[Project_DotNetCore.zip](https://github.com/danielpalme/ReportGenerator/files/12808925/Project_DotNetCore.zip)

If that's not possible I have to setup a Visual Studio Professional myself (currently using the Community edition).

**Comment by danielpalme** [comment]
Release 5.1.26 is now available. Could you please test if this works for you?

**Comment by RoadTrain** [comment]
Thanks! I will test it in the following days and come back.
