### ISSUE TITLE
coverlet-coverage give much higher Cyclomatic Complexity score for given Method then Visual Studio 2022 Code Metrics Results

### ISSUE THREAD

**Issue by wzaieddev** [danielpalme/ReportGenerator#635]
Hi,
I'm Trying to generate coverage report, and i get much higher Cyclomatic Complexity score  then Visual Studio 2022 Code Metrics Results
Method Cyclomatic Complexity score | coverage.cobertura.report   ==> 36
Method Cyclomatic Complexity score | Code Metrics Results   ==> 19

what is the most reliable value that could i adopt ?

PS: I don't know if it might be relevant or not,  with SonarQube i get 19, the same value as  Code Metrics Results   

Please find below some technical details:

NET 6
Xunit 
coverlet.collector =>  6.0.0
coverlet.msbuild  => 6.0.0
coverage report format => cobertura 
Attachment:
coverage.cobertura.report -> cobertura report
Method-SavePaymentNotifyAsync -> Method source code , method name: SavePaymentNotifyAsync
Code_Metrics_Results.PNG -> Visual studio screen

<img width="749" alt="Code_Metrics_Results" src="https://github.com/danielpalme/ReportGenerator/assets/47661547/d5ed94f6-28ff-43bf-9580-a24b4185e62a">

[coverage.cobertura.report.txt](https://github.com/danielpalme/ReportGenerator/files/13347944/coverage.cobertura.report.txt)

[Method-SavePaymentNotifyAsync.txt](https://github.com/danielpalme/ReportGenerator/files/13347946/Method-SavePaymentNotifyAsync.txt)

**Comment by danielpalme** [comment]
ReportGenerator does not calculate the metrics itself. It uses the raw values provided in the coverage file.

Here you see the value from the report generated by ReportGenerator:
![image](https://github.com/danielpalme/ReportGenerator/assets/859606/e8911fd8-05f3-4ac8-bdc7-fb69fb0ee5e8)

And this is the corresponding raw value from `[coverage.cobertura.report.txt] (line 8205)(https://github.com/danielpalme/ReportGenerator/files/13347944/coverage.cobertura.report.txt)`
![image](https://github.com/danielpalme/ReportGenerator/assets/859606/fc372cb5-36eb-4622-a062-c18ba55129d9)

I don't see a complexity value of 36 here. I guess you are referring to `CreditCardService` which also has a method `SavePaymentNotifyAsync()` with a complexity of 36. The same method in `OrdersService` has a complexity of 18 (see above).

**Comment by danielpalme** [comment]
Sorry, I don't know how coverlet calculates the metric exactly.

Cyclomatic Complexity is about number of execution paths in your code.
Your method contains several if/else statements. Each case is a different execution path.
Your code also contains serveral `??` operators. These are also if/else conditions.
