### ISSUE TITLE
Unknown report type 'Html'.

### ISSUE THREAD

**Issue by jmb-mage** [danielpalme/ReportGenerator#64]
Hi, I create a report from a different project using Visual Studio code coverage.  

In ReportGenerator project I build the project in Debug mode.

I renamed the report to "report.codecoverage" and copied it into the \bin\Debug\ folder of ReportGenerator to run it from the command line.

`ReportGenerator.exe "-reports:report.coveragexml" "-targetdir:.\"`

And I get an error:

`Unknown report type 'Html'.`

**Comment by danielpalme** [comment]
Please rebuild the solution to ensure that ReportGenerator.Reporting.dll is present in the \bin\Debug\ folder.

**Comment by jmb-mage** [comment]
Works!  Thanks.
