### ISSUE TITLE
Looking for documentations on how the extension manages data

### ISSUE THREAD

**Issue by fRanK45jPm** [danielpalme/ReportGenerator#644]
Hello, I am looking for any documentations on how the extension is managing Azure DevOps data?

**Comment by danielpalme** [comment]
Hi,
what do you mean with "Azure DevOps" data?
If you use _ReportGenerator_ on _Azure Devops_ or on your own machine, it operates strictly local on the build agent.
No data is transferred.

In detail:
-ReportGenerator reads the coverage file(s)
-It reads the corresponding code files
-It generates the desired report on the build agent

All this happens on the machine _ReportGenerator_ is executed on.
_ReportGenerator_ does not gather any user data. No statistics, telemetry or other tracking data is collected. The tool operates strictly locally.
