### ISSUE TITLE
Last(Latest) data point in History is multiplied by a factor of 2

### ISSUE THREAD

**Issue by SiddhiKK** [danielpalme/ReportGenerator#65]
Hello,

The latest data point in the history trend shows all the numbers multiplied by 2,which doesn't affect the percentage as all the numbers i.e. Covered,Uncovered,Coverable lines are multiplied by 2.
In summary it is correct but the numbers differ only in the box that appears when we move over the history chart.
![history](https://cloud.githubusercontent.com/assets/17789419/19031601/e808b7fa-8972-11e6-9b03-0eb2e3eaf9c7.png)
Thank you for any help.

**Comment by SiddhiKK** [comment]
Hello Daniel,

I was trying to include the badge in the html merged report and I have given reporttypes as HTML and Badges(separated by semicolon) and a file called 'badge_linecoverage.svg' does get created in the folder path.
I am able to  view the svg file individually but not in the Html report. Just wanted to know am I missing something, is it specific for any browser(I am using Chrome) or condition. Where do we exactly see the badge file in the Html report.
Thanks.

**Comment by danielpalme** [comment]
@SiddhiKK:
The SVG is generated but it is not embedded into the HTML report. Every report type is standalone. They don't reference each other.

**Comment by danielpalme** [comment]
@SiddhiKK:
Can you provide your code coverage files and the content of your historydir (I don't need the source code)?
I'm currently not able to reproduce the issue, that the latest data point in the history trend shows all the numbers multiplied by 2.
Email: danielpalme82@gmail.com

**Comment by danielpalme** [comment]
I'm unable to reproduce this issue.
If you are able to demonstrate the issue, please reopen.
