### ISSUE TITLE
Possibility to support diff coverage - Html report

### ISSUE THREAD

**Issue by tvbishan** [danielpalme/ReportGenerator#650]
Would it be feasible to count coverage for modifications made to the code (including those made or added) instead of the overall code?

Currently, I'm generating Html report and it shows the coverage gets measured for the entire codebase of the project. But, in the context of pull requests, I need to see if the specific lines of code that were added or changed are covered (diff coverage).

I am aware that TextDeltaSummary exists. But is there a way to see the Diff Coverage in the HTML report instead of the Full Coverage?

**Comment by danielpalme** [comment]
There is already an option in the summary page, that let's you filter classes where coverage has changed compared to a previous execution.
This feature requires that you are creating history files (you have to use the `-historydir:` parameter for that).

See sample report:
https://reportgenerator.io/resources/reports/Html/index.html

![image](https://github.com/danielpalme/ReportGenerator/assets/859606/ec820ba5-2f17-404e-b1d5-3d0e36b87e08)

I don't plan to create a report which shows the exact changes line by line between two executions.

**Comment by tvbishan** [comment]
Thank you. 

But this only changes the section below that dropdown. Top section (Summary) of the the report is not changing. Is there a way to change that section with selection of Compare with dropdown? 
![image](https://github.com/danielpalme/ReportGenerator/assets/12027448/8ef113a1-16b0-4c4e-bd73-c93821474696)

**Comment by danielpalme** [comment]
That's not supported at the moment.
