### ISSUE TITLE
Issue with -reporttypes field

### ISSUE THREAD

**Issue by roberAlb** [danielpalme/ReportGenerator#654]
I'm executing reportgenerator command from Azure DevOps pipeline like this 

reportgenerator -reports:$(Agent.WorkFolder)/_temp/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'HtmlInline_AzurePipelines;Cobertura' 

and I'm getting this error related to the report types while the report types used are in the list of supported ones

2024-02-26T16:06:28: Unknown report type ''HtmlInline_AzurePipelines'.
2024-02-26T16:06:28: Unknown report type 'Cobertura''.

Version of Report Generator: 5.2.2

.NET version: 8.0.200

**Comment by danielpalme** [comment]
Probably a problem with the `'`.

Please try this command:
`reportgenerator -reports:$(Agent.WorkFolder)/_temp/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines;Cobertura`
