### ISSUE TITLE
Wiki Edit

### ISSUE THREAD

**Issue by philipwolfe** [danielpalme/ReportGenerator#655]
Hi,

I couldn't find a way to do a PR on the Wiki.  On Getting Started at the bottom, shouldn't this:
`nyc --reporter=coberatura mocha` be 
`nyc --reporter=cobertura mocha`?

(maybe related and not worth another issue)
Could you provide an example of how to combine coverage with a test results report?  I am new to node.js and mocha and want to make sure I get the syntax right.  Is it:
`nyc --reporter=cobertura mocha \"test/**/*.tests.js\" --reporter mocha-junit-reporter`?  (assuming a folder named 'test' and test files named '*.tests.js')

**Comment by danielpalme** [comment]
> I couldn't find a way to do a PR on the Wiki. On Getting Started at the bottom, shouldn't this:

Thank you. I fixed the typo.

> Could you provide an example of how to combine coverage with a test results report? I am new to node.js and mocha and want to make sure I get the syntax right. Is it:

I'm sorry, but I'm not familiar with with the details of NodeJS.
