### ISSUE TITLE
Release notice confuses me.

### ISSUE THREAD

**Issue by Mertsch** [danielpalme/ReportGenerator#657]
**Describe the bug**
I find the notice `This release requires .NET 4.7 or .NET Core 6.x/7.x/8.x.` quite confusing. Maybe others feel the same
1. It gives me the impression that something has changed compared to the previous release, which not necessarily is the case.
2. The actual changes are more important and should be before the requirements.
3. If it has to stay I would suggest changing the text from
`This release requires .NET 4.7 or .NET Core 6.x/7.x/8.x.` to
`This release requires .NET Framework 4.7 or .NET 6.0/7.0/8.0.`
Removing the "x", as https://dotnet.microsoft.com/en-us/download only ever talks about .0 and there seems to be no plans of ever having a 8.1.

Thanks for listening ❤

**To Reproduce**
n/a

**Comment by danielpalme** [comment]
Changed it. Hope you are feeling better now :-)
