### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by silverbp** [danielpalme/ReportGenerator#66]
It would be awesome if we can get a chocolatey package for this!

You can actually replicate what they have here for opencover as it just pulls the zip file down from github releases:

https://github.com/OpenCover/opencover/tree/master/main/Opencover.Packages/chocolatey/opencover.portable

This makes it easy to put software on build machines as you can do..
choco install opencover.portable
choco install report-generator

**Comment by silverbp** [comment]
Actually you can just do this:

`choco install ReportGenerator -source https://www.nuget.org/api/v2`

then you have reportgenerator in your path.

**Comment by danielpalme** [comment]
I'm not sure if this is really an issue. OpenCover and ReportGenerator are normally used in Visual Studio projects and can be downloaded to a build server via Nuget as well.

I'm sure if we really need another source in this situation.
But I consider uploading the next release to chocolatey.

**Comment by danielpalme** [comment]
You can find the chocolatey package here:
https://chocolatey.org/packages/reportgenerator.portable/2.5.1.0
