### ISSUE TITLE
Allow to specify the root path

### ISSUE THREAD

**Issue by shargon** [danielpalme/ReportGenerator#660]
**Description**

It should be great if we are able to reduce the full path to a relative one, instead of see `/home/runner/work/MyProject.Core/Module/MyClass.cs` see `/Module/MyClass.cs` if we specify the root path.

**Comment by danielpalme** [comment]
Similar issues: #395, #356, #238

Does this answer help?
https://github.com/danielpalme/ReportGenerator/issues/356#issuecomment-649002083
