### ISSUE TITLE
Question: Is the format created by the CTC++ tool supported as input for report generator?

### ISSUE THREAD

**Issue by MTomBosch** [danielpalme/ReportGenerator#661]
Hello,
there is German software vendor Verifysoft that sells a codecoverage tool called CTC++.
Can the report generator also parse the XML files that are the output of this tool?

**Comment by danielpalme** [comment]
No that format is currently not supported.
Since you can't simply download CTC++, it not easy to implement.

**Comment by MTomBosch** [comment]
OK. Was expecting that ;)
Nevertheless thank you for the quick response.
