### ISSUE TITLE
Suggestion for new report type: MarkdownTableShortSummary

### ISSUE THREAD

**Issue by alexandrehtrb** [danielpalme/ReportGenerator#667]
Hello,

First, thanks for this tool.

I would like to propose a new report type, that makes a short Markdown table with just the global and analysed assemblies' coverages. It would be good for commenting in a pull request.

Level above or equal 80% makes green label, else, red. Something like this:

-----------

### Unit tests code coverage ![Line coverage](https://img.shields.io/badge/lines-92.7%25-080) ![Branch coverage](https://img.shields.io/badge/branches-72.2%25-800)

| Assembly | Line coverage | Branch coverage |
|---|---|---|
| **MySolution.Domain** | 94.4% | 82.4% 
| **MySolution.Application** | 74.7% | 81.3% |

-----------

```
### Unit tests code coverage ![Line coverage](https://img.shields.io/badge/lines-92.7%25-080) ![Branch coverage](https://img.shields.io/badge/branches-72.2%25-800)

| Assembly | Line coverage | Branch coverage |
|---|---|---|
| **MySolution.Domain** | 94.4% | 82.4% |
| **MySolution.Application** | 74.7% | 81.3% |
```

**Comment by danielpalme** [comment]
Will consider this in the next release!

**Comment by danielpalme** [comment]
Release 5.3.0 now contains a new report type 'MarkdownAssembliesSummary'
