### ISSUE TITLE
OpenCover report parsing

### ISSUE THREAD

**Issue by wahmedswl** [danielpalme/ReportGenerator#67]
Hi, i have generated report of opencover coverage but it seem to be missing a class in the final results.

```
SequelMed.Logging.__
```

Here is the results.xml file generated by opencover

[results.txt](https://github.com/danielpalme/ReportGenerator/files/523066/results.txt)

Thanks

**Comment by danielpalme** [comment]
"__" is a quite uncommon name for a class :-)

Currently classes that contain "__" are filtered out, since these classes are normally generated by the compiler.

But I will see if I can find a better way to filter those classes out.

**Comment by wahmedswl** [comment]
Hi, yeah its quiet un-common name but it is utility class and name is inspired from underscore.js but had to use double underscore as single was not working :-P

Thanks

**Comment by danielpalme** [comment]
It should work with this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.0-beta2
