### ISSUE TITLE
Azure pipeline failure due to dependency on NodeJS version 6

### ISSUE THREAD

**Issue by neildavisonwae** [danielpalme/ReportGenerator#670]
Today we are seeing an error before the Azure pipeline runs (Microsoft-hosted, 'windows-latest'):

> The pipeline is not valid. Job BuildAndTest: Step 'reportgenerator' references task 'reportgenerator' at version '5.3.0' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator.

I can't see a current workaround for this issue, is it possible to update the task to use a more recent version of NodeJS?

**Comment by danielpalme** [comment]
Will have a look in the evening.

**Comment by danielpalme** [comment]
I update the task definition to support Node 10, 16 and 20.
If you test again it should work without issues (may take 15-30 minutes until new version gets available in Azure DevOps).

**Comment by neildavisonwae** [comment]
That's great, the pipeline is running fine now. Thanks very much for the quick fix!
