### ISSUE TITLE
Docs/readmes: add info about `minimumCoverageThresholds`

### ISSUE THREAD

**Issue by alexandrehtrb** [danielpalme/ReportGenerator#671]
I was looking for this feature but couldn't find it in README nor the main website; only found in the wiki.

It would be good to document it in:

* ReportGenerator readme
* GitHub Action readme
* Main website -> usage

**Comment by danielpalme** [comment]
Documenting and maintaining all settings in all those locations could become tedious.

Instead I added the following text to all the locations you suggested:


> The more advanced settings are documented in the [wiki](https://github.com/danielpalme/ReportGenerator/wiki/Settings).

Thanks for your hint!
