### ISSUE TITLE
ReportGenerator 5.3.1 fails on self hosted azure devops agent running on Amazon Linux 2 arm64 instance (t4g) 

### ISSUE THREAD

**Issue by tscott-au** [danielpalme/ReportGenerator#672]
**Describe the bug**
ReportGenerator 5.3.1 fails due to missing node dependencies on self hosted azure devops agent running on Amazon Linux 2 arm64 instance (t4g).

**Workaround**
Lock the Azure devops task to reportgenerator@5.3.0 

**To Reproduce**
The following input helps to reproduce your issue:
1. Console output of ReportGenerator
Starting: ReportGenerator
==============================================================================
Task         : ReportGenerator
Description  : ReportGenerator converts coverage reports generated by coverlet, OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov, or lcov into human readable reports in various formats.
Version      : 5.3.1
Author       : Palmmedia
Help         : [More Information](https://github.com/danielpalme/ReportGenerator)
==============================================================================
/home/ec2-user/azure_devops_build_agent/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/azure_devops_build_agent/externals/node20/bin/node)
/home/ec2-user/azure_devops_build_agent/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/azure_devops_build_agent/externals/node20/bin/node)
##[error]Exit code 1 returned from process: file name '/home/ec2-user/azure_devops_build_agent/externals/node20/bin/node', arguments '"/home/ec2-user/azure_devops_build_agent/_work/_tasks/reportgenerator_be803a55-9253-4895-a525-be570d86f161/5.3.1/reportgenerator.js"'.
Finishing: ReportGenerator

**Comment by danielpalme** [comment]
I [removed](https://github.com/danielpalme/ReportGenerator/commit/5337051eb7f5992ac0dfe83ba0e7dd78617eb803) Node20 support.
Version 5.3.2 should be available within the next 15-30 minutes.

**Comment by tscott-au** [comment]
Amazing. Resolved.
 
I successfully tested it using the explicit task reference reportgenerator@5.3.2  

Thank you!
