### ISSUE TITLE
[Feature] Output as "MIME HTML"

### ISSUE THREAD

**Issue by ulrichb** [danielpalme/ReportGenerator#68]
Please add support for a new output format: "MHTML". This format first generates the same report as "HTML" but writes everything into a single `.mht` file (see https://en.wikipedia.org/wiki/MHTML, https://tools.ietf.org/html/rfc2557).

Use case: To be able to create a single, downloadable file as CI artifact (without zip-ing it). This file could be opened in a browser without the need to extract it.

**Comment by danielpalme** [comment]
I will see what I can do about this.

Useful links:
https://www.chilkatsoft.com
http://www.nullskull.com/articles/20040527.asp

**Comment by ulrichb** [comment]
The following link contains a sample which uses `System.Net.Mail`-classes. Unfortunately it uses internal APIs of the BCL (e.g. `System.Net.Mail.MailWriter`, see `MailMessageExtension`).

https://code.msdn.microsoft.com/windowsdesktop/Creating-a-MHTML-MIME-HTML-61cf5dd1/sourcecode?fileId=23825&pathId=696548704

**Comment by danielpalme** [comment]
Could you please test this beta:
https://www.nuget.org/packages/ReportGenerator/2.5.0-beta5

Please use the following parameter:
`-reporttypes:MHTML`

This should generate a file named _Summary.mht_ in the target directory.

**Comment by ulrichb** [comment]
@danielpalme Wow. Just [tested it](https://ci.appveyor.com/project/ulrichb/implicitnullability/build/3.1.0.345/artifacts). Works great!
