### ISSUE TITLE
Possible to have percentage and code coverage metrics in addition to the code coverage tabl in devops?

### ISSUE THREAD

**Issue by xantari** [danielpalme/ReportGenerator#683]
I've read the following:
https://github.com/danielpalme/ReportGenerator/wiki/Integration#attention

The only way I can get the report generator code coverage report to show is by unmarking the "Publish test results and code coverage" option on the .NET Core test step:

![image](https://github.com/user-attachments/assets/0d939e4a-4405-464b-98bb-ece89c993381)

Then my report generator setup is as follows:

![image](https://github.com/user-attachments/assets/2a80db17-ddbe-4a81-b70e-f1984fa46169)

![image](https://github.com/user-attachments/assets/f8f10a3e-eed8-4f6a-9972-7ab0033644cc)

When it is setup this way you get the report generator code coverage report, but then the summary area doesn't get populated:

![image](https://github.com/user-attachments/assets/31707fda-4d7c-4df1-8114-da1a33332d56)

Is there a way to have that summary area populate in addition to the Code Coverage tab?

**Comment by danielpalme** [comment]
I'm not aware of a way to achieve this.
