### ISSUE TITLE
coverage bars 1 pixel wide in 2.5.0

### ISSUE THREAD

**Issue by gregveres** [danielpalme/ReportGenerator#69]
Hi, 

I just upgraded to 2.5.0 and now the green/red coverage bars are showing 1 pixel wide. I am not specifying anything other than the path to the input and output. It is generating the default HTML report. 

I have very long function names. - they used to wrap in the previous version. I think what is happening is the table is squishing what it can, which is the bar columns because they have no fixed size and they have no header to force a fixed size. So they get squished to be content area size of 1 pixel. All I see is a vertical line. 

On an unrelated note, what is the report type badges that is mentioned on the front page of the github project? I tried it but it didn't seem to make a difference.

**Comment by danielpalme** [comment]
Hi @gregveres 
Can you please attach a screenshot?

Reagarding badges:
If you use `-reporttypes:Badges`, the target directory will contain some SVGs like this one:
https://github.com/danielpalme/ReportGenerator#badges

**Comment by gregveres** [comment]
Sure thing.
<img width="1290" alt="reportgenscreenshot" src="https://cloud.githubusercontent.com/assets/12899823/20146134/ff8057a6-a6a2-11e6-91f5-55d1fef47900.png">

**Comment by danielpalme** [comment]
Please try this new release:
https://www.nuget.org/packages/ReportGenerator/2.5.1

**Comment by gregveres** [comment]
Much better. Thank you for fixing it so quickly.
