### ISSUE TITLE
Report is not generating correctly for Partial class 

### ISSUE THREAD

**Issue by arvindmishra2000** [danielpalme/ReportGenerator#693]
**Describe the bug**
When we have partial class with bigger name , The summary is displayed in two rows and detailed html is pointing to 1 html file only 
**To Reproduce**
The following input helps to reproduce your issue:
1. Your partial Class Name should be more than 250 chars
2. When you generate the Assembly short name for detailed html, it is generating short name based on Class Name and for two summary rows short name is same and it is overriding the previous generated detailed html file.

**Comment by danielpalme** [comment]
Thanks for reporting this. I will have a look in the next days.

**Comment by danielpalme** [comment]
I currently not able to reproduce your problem.

Can you share a coverage file that helps me reproduce the issue?

You can send it privately via email: [reportgenerator@palmmedia.de](mailto:reportgenerator@palmmedia.de) or share it here.
