### ISSUE TITLE
dotnet-reportgenerator-globaltool version 5.3.11 fails to install

### ISSUE THREAD

**Issue by LucasOsborne** [danielpalme/ReportGenerator#698]
**Describe the bug**
Attempting to install version 5.3.11 via NuGet fails on both local machines and within pipelines. However, version 5.3.10 installs successfully without issues.

**To Reproduce**

**Steps to Reproduce**
Run nuget command `dotnet tool install -g dotnet-reportgenerator-globaltool`  (either on a local machine or in a CI/CD pipeline).
Installation fails with errors (see screenshots below).
Revert to version 5.3.10 `dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.3.10 `, which installs successfully.

**Expected Behavior**
Version 5.3.11 should install via NuGet without errors, similar to how version 5.3.10 functions.

**Actual Behavior**
Version 5.3.11 fails to install, producing the following console output error messages:
![image](https://github.com/user-attachments/assets/8dccc319-1ea7-4f95-b092-bac42517f416)

For reference, the installation of version 5.3.10 works without issues:
![image](https://github.com/user-attachments/assets/06c6fcbb-97a8-48ce-95e3-85037c2a4dde)

**Environment Details**
NuGet Version: 6.11.0.122
Project Type: (Local machine, CI/CD pipeline)
OS/Platform: Windows 11 and Linux
IDE/Build Environment: Visual Studio 2022

**Comment by danielpalme** [comment]
I can't reproduce.

Works locally on Windows and in Ubuntu (Azure DevOps) for me.

**Comment by LucasOsborne** [comment]
Maybe was an issue with NuGet sorry - just tested right now is back up and working

**Comment by danielpalme** [comment]
Perfect!
