### ISSUE TITLE
Crap score should be rounded to integers

### ISSUE THREAD

**Issue by t-b** [danielpalme/ReportGenerator#699]
We are using ReportGenerator Pro for a project [1]. The newly added crap score is interesting. I do think though that it should be rounded to integer for better readibility.

[1]: https://byte-physics.de/public-downloads/aistorage/transfer/report/coverage/

**Comment by danielpalme** [comment]
I made the necessary change in 2dd7e8c146d18d28e9d3c45001633bf88c4b06de.  
The next release will contain the new behavior.

**Comment by danielpalme** [comment]
Release 5.4.0 is now available!

**Comment by t-b** [comment]
@danielpalme Thanks. I'll give it a shot.
