### ISSUE TITLE
colour new function selector based on coverage

### ISSUE THREAD

**Issue by gregveres** [danielpalme/ReportGenerator#70]
hi @danielpalme 

Now that you have added the function navigator on the right hand side of a file view page, it would be great of the colour of the function was green if line and branch coverage was 100% and red if one or the other was not 100%. 

Thanks
Greg

**Comment by danielpalme** [comment]
@gregveres 
I expected that feature request :-)
I will probably add this in a future release. But this may take some time.

**Comment by danielpalme** [comment]
New beta with color indicator for test methods is available here:
https://www.nuget.org/packages/ReportGenerator/3.0.0-beta2
