### ISSUE TITLE
Does ReportGenerator Support "Source View"

### ISSUE THREAD

**Issue by bgyu** [danielpalme/ReportGenerator#703]
This is not bug report, more like a feature request.
In Visual Studio Enterprise, we can view the report in "Source View" or "Project View". From current observation, it looks like `ReportGenerator` only supports "Project View". The view tree is based on `assembly`, `namespace`, `class`, `functions`.

When I click a source file, I can only see the coverage report for global functions, no class member functions. If I want to see class member functions, I have to click a specific type.

Is it possible that to show the coverage report in a source tree view? When I expand sources in a tree, it shows me what the coverages of a source file, which includes both global functions and member functions.

**Comment by danielpalme** [comment]
I'm not sure if I understand your request correctly. I have never used the "Visual Studio Enterprise".

Currently ReportGenerator generates an overview/summary page which list all assemblies and classes.
Then you can select a class and get the full coverage information for that class including all the source lines.
Here's a sample report: https://reportgenerator.io/resources/reports/Html/index.html

What are you missing? Can you provide a screenshot?

**Comment by bgyu** [comment]
I mean when I click a source file, it should show me the coverage for all functions, including both global functions and class member functions. Now I can only see global functions if I click for example `Hello.cpp`. If I want to see coverage of member functions in `Hello.cpp`, I need to click class `Hello`.

What I want to see here is when I click `Hello.cpp`, I can see the coverage for file `Hello.cpp`.

This is VS Enterprise code coverage in `Project View`, which is similar to `ReportGenerator` in some way:
![image](https://github.com/user-attachments/assets/9ffe2bf2-e124-44a8-96fa-ebcf00068dc7)

This is in "Source View": (What I wish to have in `ReportGenerator`)
![image](https://github.com/user-attachments/assets/1c66bcfe-0d3d-40dc-8c75-24ed1d31a23c)

The "Source View" shows the source code tree, and the coverage of each source file and the coverage of its class, member functions and global functions.

**Comment by bgyu** [comment]
This example is more obvious:
### Project View
![image](https://github.com/user-attachments/assets/70ea3b69-d871-4917-8de4-608c188625d8)
It shows a tree structure similar to `ReportGenerator`:
![image](https://github.com/user-attachments/assets/5d71024c-2a0a-4ef5-bd75-f8fd3ec47e78)
Summary is similar. But when I click "MyHello.BasicTests.cpp":
I only see the coverage of `GlobalGreet`:
![image](https://github.com/user-attachments/assets/28eea99a-2d7c-44e6-b298-17eee2cc018c)
No coverage showed for class `Hello`. I need to click `MyHello.Hello` class to see it:
![image](https://github.com/user-attachments/assets/46dcd187-a1ac-4a50-b9bf-44944226414e)
In this case, I only see the coverage of member function `Greet`, no global function `GlobalGreet` showed here.

What I want to see if for both, like the following "Source View" in VS Enterprise.

### Source View
![image](https://github.com/user-attachments/assets/e4bc96ed-20e9-459e-9a8e-2fe3a0059c6b)

As you can see, the coverage of file `BasicTests.cpp` has global function `GlobalGreet` and a member function `Greet` of `Hello` class, both are showing in the same view. The coverage of `BasicTests.cpp` is for both global functions and member functions.

**Comment by danielpalme** [comment]
_ReportGenerator_ works on a class by class basis. What you suggest is more a file by file basis.
The current approach works fine for languages like C# or Java. In those languages most files contain exactly one class.

I see, that this does not work well in your case. But I probably won't change the behavior since this would be a breaking change for all other users and would also mean to rewrite the complete tool. I'm sorry.
