### ISSUE TITLE
`ReportGenerator.Core` nuspec has wrong dependency version for `DotNetConfig`

### ISSUE THREAD

**Issue by afscrome** [danielpalme/ReportGenerator#705]
I'm using `ReportGenerator.Core` in an application and am getting the error `Could not load file or assembly 'DotNetConfig, Version=1.2.0.0, Culture=neutral, PublicKeyToken=41dc05ca892b85e5'. The system cannot find the file specified.`

If you go to https://www.nuget.org/packages/ReportGenerator.Core, it lists the required version of `DotNetConfig` as `>= 1.0.6`, however the csproj lists it as 1.2.0 https://github.com/danielpalme/ReportGenerator/blob/24d447f1d3a2c78a10e1c8cfc0aeac0d4d9d0072/src/ReportGenerator.Core/ReportGenerator.Core.csproj#L85

Looks like dependency versions in the nuspec needs to be updated to match those used by the csproj - https://github.com/danielpalme/ReportGenerator/blob/24d447f1d3a2c78a10e1c8cfc0aeac0d4d9d0072/src/Deployment/nuget/ReportGenerator.Core.nuspec#L34

An alternative solution would be to use `dotnet pack` instead of a nuspec which should automatically infer all the versions etc. from the csproj.

**Comment by danielpalme** [comment]
Thank you. I have fixed the wrong version.
A new release will be published next week after .NET 9 has been released.

**Comment by afscrome** [comment]
Thank you very much.

**Comment by danielpalme** [comment]
Release 5.4.0 is now available!
