### ISSUE TITLE
Support for .NET 6 and 7 deprecated in minor version

### ISSUE THREAD

**Issue by delilahw** [danielpalme/ReportGenerator#706]
**Describe the bug**
Hey, it appears that support for .NET 6/7 was dropped in the latest minor version. Starting from [v5.4.0](https://github.com/danielpalme/ReportGenerator/releases/tag/v5.4.0), .NET 8/9 is required instead.

Should this change be a major version instead? Previous changes to .NET versioning requirements were published in major releases:
  - [v5.0.0](https://github.com/danielpalme/ReportGenerator/releases/tag/v5.0.0)
  - [v4.0.0.0](https://github.com/danielpalme/ReportGenerator/releases/tag/v4.0.0.0)

**To Reproduce**
Running the ReportGenerator on systems without the .NET 8 or .NET 9 Runtimes will fail. Example ADO output:
```
==============================================================================
Task         : ReportGenerator
Description  : ReportGenerator converts coverage reports generated by coverlet, OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov, or lcov into human readable reports in various formats.
Version      : 5.4.0
Author       : Palmmedia
Help         : [More Information](https://github.com/danielpalme/ReportGenerator)
==============================================================================
/usr/bin/dotnet /mnt/vss/_work/_tasks/reportgenerator_be803a55-9253-4895-a525-be570d86f161/5.4.0/tools/net8.0/ReportGenerator.dll
You must install or update .NET to run this application.

App: /mnt/vss/_work/_tasks/reportgenerator_be803a55-9253-4895-a525-be570d86f161/5.4.0/tools/net8.0/ReportGenerator.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  6.0.35 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  7.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64

##[error]The process '/usr/bin/dotnet' failed with exit code 150
```

**Comment by giovannimele** [comment]
Same issue here. Is there a way to force using version 5.3.11 to still be compatible with .net 6?

**Comment by Marc-fra76** [comment]
Same issue for us too. We have addded the `--version 5.3.11` option to the install task in our pipeline in order to continue using this tool.

The deprecated warning would have been more than appreciated for this change.

**Comment by mmonteiroc** [comment]
> Same issue for us too. We have addded the `--version 5.3.11` option to the install task in our pipeline in order to continue using this tool.
> 
> The deprecated warning would have been more than appreciated for this change.

@Marc-fra76 

In our side, we have a Powershell@2 task where we force a version 
`dotnet tool install -v:diag --local dotnet-reportgenerator-globaltool --version 5.3.4`

but then when we run the task `reportgenerator@5`, it seems to ignore this version


This breaking change should have been a new version of the task `reportgenerator@6` 😢

**Comment by erikbjoernestad** [comment]
@giovannimele 
We're were able to solve this by pinning the task to specific version. 

`- task: reportgenerator@5.3.1`

**Comment by giovannimele** [comment]
@erikbjoernestad thx! This solved our issue.

**Comment by danielpalme** [comment]
.NET 6 and 7 are no longer supported by Microsoft. You should upgrade to .NET 8 or 9 as soon as possible.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

The build agents provided by Microsoft already have .NET 9 installed. If you have a custom build agent you should consider updating it.

@delilahw 
Last year I dropped support for .NET 3.1 and .NET 5.0. Also in a minor release ([5.2.0](https://github.com/danielpalme/ReportGenerator/releases/tag/v5.2.0))

This year .NET 6 and 7 got dropped as they are out of support. This is also documented here: https://github.com/danielpalme/ReportGenerator/releases/tag/v5.4.0

As mentioned by @erikbjoernestad you can pin the previous release which supports .NET 6 and 7.

**Comment by rohitgupta-ipo** [comment]
Also It seems the latest version is not respecting -fileFilters argument altogether - we have started using latest tool with .net 8, but suddenly all our code converge percentage  is dropped as exclusions are not considered and excluded files are also included in calculating the code coverage - can this be fixed please @danielpalme

**Comment by danielpalme** [comment]
@rohitgupta-ipo 
This issue has already been fixed in version 5.4.1 (see: #707 ).

**Comment by ruskinb1** [comment]
@erikbjoernestad . we are using this as Azure devops Task. Is there any way to provide specific version ?

**Comment by danielpalme** [comment]
@ruskinb1 
This should work for you:
```
- task: reportgenerator@5.3.1
```

**Comment by delilahw** [comment]
@danielpalme Thank you for your response and your ongoing work on this project. We understand that dropping support for older .NET versions in a minor release has been the precedent (e.g. last year's [v5.2.0](https://github.com/danielpalme/ReportGenerator/releases/tag/v5.2.0)).

However, some consumers — like others on this thread — pin only the major version (`reportgenerator@5`) and use custom build agents. In this case, it can cause unexpected disruptions when breaking changes occur in a minor release.

To address this, @mmonteiroc and @Marc-fra76 had some good suggestions:
> This breaking change should have been a new version of the task reportgenerator@6 😢

> But I agree with you, a new version of the task or the use of the deprecated warning would have been a better way to handle this.

We really appreciate you considering this feedback! =)

**Comment by delilahw** [comment]
@danielpalme Thanks so much for taking it into consideration! We really appreciate it.
