### ISSUE TITLE
Does ReportGenerator merge the duplicate files or dlls ?

### ISSUE THREAD

**Issue by vinayakmsft** [danielpalme/ReportGenerator#711]
Hi @danielpalme 

I had 1 question related the logic behind ReportGenerator. Does the report generator merge the duplicate files or dlls while generating the code coverage report? If yes, can you please share me the code link to where it merges the files?

For example, please see this screenshot , there are duplicate dlls. 

![image](https://github.com/user-attachments/assets/01c433d7-d4a9-4dd1-b43b-e3d9940329ef)

**Comment by danielpalme** [comment]
@vinayakmsft 
If you pass several coverage files to ReportGenerator the results of all files are merged into one report.
Merging happens on several levels:

- Assemblies/Modules/DLLS: https://github.com/danielpalme/ReportGenerator/blob/main/src/ReportGenerator.Core/Parser/Analysis/Assembly.cs#L171
- Classes: https://github.com/danielpalme/ReportGenerator/blob/main/src/ReportGenerator.Core/Parser/Analysis/Class.cs#L271
- Files: https://github.com/danielpalme/ReportGenerator/blob/main/src/ReportGenerator.Core/Parser/Analysis/CodeFile.cs#L493

Based on your screenshot, I cannot tell whether you are passing a single or several coverage files to ReportGenerator.
But it does not really matter:
The class names are the same (e.g. `SourceViewLibrary.MathHelpers`), but they exist in different assemblies/Dlls: `SourceViewLibrary.dll` and `SourceViewLibrary.Tests.dll`, so nothing is merged here.

**Comment by vinayakmsft** [comment]
Got it, @danielpalme  , Also, is it possible to introduce sorting functionality for these columns like covered lines, total lines?

**Comment by danielpalme** [comment]
You can sort by all columns. See sample report here: https://reportgenerator.io/resources/reports/Html/index.html
