### ISSUE TITLE
Azure DevOps integration: Last published code coverage report wins or are all reports merged?

### ISSUE THREAD

**Issue by MTomBosch** [danielpalme/ReportGenerator#712]
Hello
we are using the report generator Azure DevOps extension to also publish the code coverage report in the Azure Pipelines pipeline.

In future we will publish the code coverage data (Cobertura) multiple times. Now I am wondering if the coverage data is somehow merged in the background or simply the last published code coverage data wins.

Thanks in advance for your answer.

**Comment by MTomBosch** [comment]
To add another related question: If I have all the Cobertura files I guess report generator can merge multiple Cobertura files in the background and create one report out of it.

**Comment by danielpalme** [comment]
If you publish several coverage reports, the last one will win.

But ReportGenerator is able to merge several coverage file into a single report.

**Comment by MTomBosch** [comment]
Ok. Thank you for the answer.
