### ISSUE TITLE
Suggestion - Method Coverage

### ISSUE THREAD

**Issue by tonyhallett** [danielpalme/ReportGenerator#717]
The Pro feature method coverage, does not provide statistics that I expect.

Perhaps you could add an entry in https://github.com/danielpalme/ReportGenerator/wiki/Calculation-details as the only mention of the definition that I could find was in your [comment](https://github.com/danielpalme/ReportGenerator/issues/345#issuecomment-626911791).  

Perhaps you could add a further entry as to whether a method is fully covered rather than a single line has been visited.
https://github.com/danielpalme/ReportGenerator/blob/537c17c126cefe4da5de2bb885cee520cdf43b70/src/ReportGenerator.Core/Parser/Analysis/CodeFile.cs#L256

**Comment by danielpalme** [comment]
I will take care of this as soon as possible.

**Comment by tonyhallett** [comment]
I still think that stats on method full coverage rather than a method having a single line of coverage would be useful

**Comment by danielpalme** [comment]
> I still think that stats on method full coverage rather than a method having a single line of coverage would be useful

Yes, I will consider this in a future release.

**Comment by danielpalme** [comment]
> > I still think that stats on method full coverage rather than a method having a single line of coverage would be useful
> 
> Yes, I will consider this in a future release.

Release 5.4.3 is now available with new feature "Full method coverage".
A sample report is available here: https://reportgenerator.io/resources/reports/Html/index.html
