### ISSUE TITLE
Support XML coverage format output by "mprof-report"

### ISSUE THREAD

**Issue by peteroupc** [danielpalme/ReportGenerator#74]
Report Generator should support the XML format output by the relatively new Mono report reader `mprof-report` (read more on [`mprof-report` and the Mono profiler](http://www.mono-project.com/docs/debug+profile/profile/profiler/)).  The following shows what the XML format looks like:

```
<?xml version="1.0"?>
<coverage version="0.3">
	<assembly name="Example" guid="..." filename="..." method-count="266" full="15" partial="0"/>
		<class name="Example.ExampleClass" method-count="8" full="2" partial="0"/>
	<assembly name="Example2" guid="..." filename="..." method-count="266" full="15" partial="0"/>
		<class name="Example2.ExampleClass2" method-count="8" full="2" partial="0"/>
	<method assembly="Example" class="Example.ExampleClass" name="ExampleMethod (string)" filename="..." token="100664465">
		<statement offset="0" counter="1" line="1" column="1"/>
		<statement offset="0" counter="1" line="7263" column="0"/>
	</method>
</coverage>

```

**Comment by danielpalme** [comment]
Hi @peteroupc 

I have two test projects:
https://github.com/danielpalme/ReportGenerator/tree/master/ReportGenerator.Testprojects/CSharp/Project
https://github.com/danielpalme/ReportGenerator/tree/master/ReportGenerator.Testprojects/FSharp/Project

If you could compile them and execute them with` mprof-report ` and send me the resulting XML files, I can do the implementation of the parser.

**Comment by peteroupc** [comment]
Attached is the XML output for the CSharp Test project. (I couldn't 
compile the FSharp Test project because it required 
System.Windows.Controls, which is apparently unavailable in Mono.)

The following commands will generate this XML:

    mono --debug --profile=log:output=report.dat,coverage,time=fast Test.exe
    mprof-report --coverage-out=report.xml report.dat

Where the form `filename="..."` appears in the XML output, I modified it 
by hand to show only the filename.  The original output showed the full 
file system path to the files concerned. The `--debug` option is 
necessary in order to show the file names of the C# source files.

**Comment by peteroupc** [comment]
Apparently, GitHub might not have accepted the XML attachment.  In case you didn't receive the XML, I try again by attaching the ZIP-compressed version of the XML file.

[report.zip](https://github.com/danielpalme/ReportGenerator/files/614605/report.zip)

**Comment by danielpalme** [comment]
Thanks for the report. I will have a look at it within the next 1-2 weeks.

**Comment by danielpalme** [comment]
One question regarding your sample report:
Some `<method />` elements have an empty `filename `attribute.
Did you accidentally delete the full filename or was it empty before?

**Comment by peteroupc** [comment]
The filename attribute was originally blank in those places.

--Peter

**Comment by danielpalme** [comment]
Please have a look at this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.2-beta2

I added support for _mprof-report_. The XML file generated by mbprof is very basic. It only contains lines in methods that have been executed at least once. So your line coverage results are probably not very accurate.

**Comment by peteroupc** [comment]
It works well for my purposes.  Thanks for supporting this XML format.
