### ISSUE TITLE
HTML reports should not require Internet connection

### ISSUE THREAD

**Issue by bjarneds** [danielpalme/ReportGenerator#75]
The HtmlRenderer inserts a reference to https://fonts.googleapis.com/css?family=Open+Sans in every file.
This makes offline use quite limited - when I open a report, there is a timeout ~20 secs, before anything is shown (both in IE and Chrome). It would be a big improvement if the reports didn't depend on external resources.

**Comment by danielpalme** [comment]
The external font is no longer in use. See this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.2-beta2
