### ISSUE TITLE
What is the difference between Total Lines and Coverable Lines?

### ISSUE THREAD

**Issue by dotnetdan** [danielpalme/ReportGenerator#77]
Hi,

I generated a report with the following summary - Total Lines is over 4 million, while coverable lines is just over 400,000.  What is the difference between these two metrics?

Summary

Generated on:	11/22/2016 - 6:11:30 PM
Parser:	MultiReportParser (7x VisualStudioParser)
Assemblies:	40
Classes:	11169
Files:	11225
Covered lines:	261911
Uncovered lines:	171324
**Coverable lines:	433235**
**Total lines:	4196050**
Line coverage:	60.4%

**Comment by danielpalme** [comment]
Total lines includes all lines in the source code (with comments, using directives etc).
Coverable lines only includes lines that could get executed. So only these lines are relevant.

**Comment by dotnetdan** [comment]
Ok, thanks!
