### ISSUE TITLE
System.IO.PathTooLongException

### ISSUE THREAD

**Issue by PavelAgejkin** [danielpalme/ReportGenerator#8]
Hi,
I'm using ReportGenerator 2.1.2.0
When I try generate report for my web site project I get exception **System.IO.PathTooLongException**
My web site project has karma tests and while installing npm modules I get really long paths, e.g. 
> C:\VSC\administration\CAT.Administration.Website\Angular\tests\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\lib\delayed_stream.js

Here is stacktrace https://gist.github.com/PavelAgejkin/d0d8977faf302c908dfc
P.s. I found similar issue: http://reportgenerator.codeplex.com/workitem/9671

**Comment by PavelAgejkin** [comment]
found solution: http://bcl.codeplex.com/wikipage?title=Long%20Path&referringTitle=Documentation
from this package: https://www.nuget.org/packages/Microsoft.Experimental.IO/
Just use Microsoft.Experimental.IO.LongPathDirectory instead System.IO.Directory in **SafeDirectorySearcher**

**Comment by PavelAgejkin** [comment]
```C#
internal static IEnumerable<string> EnumerateFiles(string path, string searchPattern, SearchOption searchOption)
        {
            try
            {
                var dirFiles = Enumerable.Empty<string>();
                if (searchOption == SearchOption.AllDirectories)
                {
                    dirFiles = LongPathDirectory.EnumerateDirectories(path)
                        .SelectMany(x => EnumerateFiles(x, searchPattern, searchOption));
                }

                return dirFiles.Concat(LongPathDirectory.EnumerateFiles(path, searchPattern));
            }
            catch (UnauthorizedAccessException)
            {
                return Enumerable.Empty<string>();
            }
        }
```

**Comment by danielpalme** [comment]
Thanks for reporting this issue.

I try to solve the problem without LongPathDirectory.
Could you please try this beta and let me know if this works for you or if you get any errors:
https://www.nuget.org/packages/ReportGenerator/2.1.3-beta1

Thanks

**Comment by danielpalme** [comment]
Did you have a chance to test the beta? Does it work?

**Comment by PavelAgejkin** [comment]
Hi,
Can i have exe install?

On Wed, Mar 11, 2015 at 3:12 PM, Daniel Palme <notifications@github.com>
wrote:

> Did you have a chance to test the beta? Does it work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielpalme/ReportGenerator/issues/8#issuecomment-78259769>
> .
>



-- 
pavel

**Comment by danielpalme** [comment]
Please download the beta here: http://1drv.ms/1AnAUtH

**Comment by PavelAgejkin** [comment]
Thank you,
Nice work, no more crash on super long path.
Waiting for new version!

**Comment by danielpalme** [comment]
New release is available!
