### ISSUE TITLE
coverage of namespaces

### ISSUE THREAD

**Issue by francispauli** [danielpalme/ReportGenerator#82]
Hi
im trying to generate a report from a coverage.xml file i generated with CodeCoverage.exe (from a C++ console app)
When i convert it to html with ReportGenerator.exe i can only browse classes, no namespaces or free functions. Though i can see the .xml file contains info about namespace coverage.
Am i missing something here ?

**Comment by danielpalme** [comment]
Well, that's how ReportGenerator works.
ReportGenerator retrieves all classes it can find in the coverage file(s).
Then it generates a report for each class and a summary listing all classes grouped by assembly/namespace.

**Comment by francispauli** [comment]
I got something working with C/C++ which might be of interest to others.
Using the OpenCppCoverage Visual Studio plugin to generate a Cobertura coverage file, i got a nice report from ReportGenerator where coverage is listed per file instead.
At first ReportGenerator detected the Cobertura file as mprof.
So to the top tag <coverage>  i added the attibute 'version="2.1.1"' (as seen in the ReportGenerator example files) and it worked.
Thanks for the tool :)
