### ISSUE TITLE
Extend VerbosityLevel

### ISSUE THREAD

**Issue by patricksadowski** [danielpalme/ReportGenerator#85]
Currently it's not possible to fine tune the verbosity level.
1. In some scenarios it would be nice to switch off the output. In our case we want to get rid of all output on CI builds.
2. If verbosity level is set to _Error_ the output still contains warnings. That doesn't seem to be consistent. This can lead to confusion.

We suggest to add the verbosity levels _Warning_ and _Off_.

**Comment by danielpalme** [comment]
I will have a look at this within the next days.

**Comment by danielpalme** [comment]
New release available: https://www.nuget.org/packages/ReportGenerator/2.5.4

**Comment by danielpalme** [comment]
The Off option is not yet working. Have to fix that.

**Comment by danielpalme** [comment]
New release available: https://www.nuget.org/packages/ReportGenerator/2.5.5
