### ISSUE TITLE
Scrap value is coming in coveragexml file.

### ISSUE THREAD

**Issue by abhijeetka** [danielpalme/ReportGenerator#86]
When I am converting and testing my DLL's with this, I am getting weird values.

Please find below,

        `<function id="8348" token="0x6000276" name="MoveNext()" type_name="RepositoryBase.&lt;FindByAsync&gt;d__0&lt;TEntity&gt;" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="16" lines_covered="0" lines_partially_covered="0" lines_not_covered="2">
          <ranges>
            <range source_id="0" covered="no" start_line="37" start_column="13" end_line="37" end_column="80" />
            <range source_id="0" covered="no" start_line="38" start_column="9" end_line="38" end_column="10" />
          </ranges>
        </function>`

because of the bold values are coming with special characters, i am unable to parse it in sonar.

**Comment by danielpalme** [comment]
Sorry, but this piece of XML is not produced by ReportGenerator.
I can't help with that.
