### ISSUE TITLE
Coverage History not working anymore since 2.5.3

### ISSUE THREAD

**Issue by stefantinger** [danielpalme/ReportGenerator#87]
Hi!

The coverage history xml files are empty since v2.5.3.
Working fine with 2.5.2. I just use the default behavior to save the files to a folder on the disk.

Probably caused by: https://github.com/danielpalme/ReportGenerator/issues/78

KR

**Comment by danielpalme** [comment]
Thanks for reporting this issue.

It's now fixed:
https://www.nuget.org/packages/ReportGenerator/2.5.6
