### ISSUE TITLE
Jenkins integration wiki unclear

### ISSUE THREAD

**Issue by Razzeee** [danielpalme/ReportGenerator#88]
Hey there,

I'm struggeling with the instructions in https://github.com/danielpalme/ReportGenerator/wiki/Integration#jenkins which state
```
Navigate to the Configure page of your project and add the following artifact path:
```

I can't find anything named `artifact path`, maybe they changed the name with the jenkins 2.0 release?

Cheers

**Comment by FlutteryChicken** [comment]
I think you want to add a Post-Build action of "Archive the artifacts"

**Comment by danielpalme** [comment]
My instructions are written for Jenkins 1.
2.0 seems to be quite different.

Maybe this helps:
https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/
