### ISSUE TITLE
Wrong number of branch points with OpenCover

### ISSUE THREAD

**Issue by CookieNick** [danielpalme/ReportGenerator#9]
We're having trouble with the number of branch points displayed in the ReportGenerator. The number of branch points total does not seem to match what I execpt or what the OpenCover XML shows. The single 'if' statement in the source code shows 2 out of 8 branches covered, but I expect 2 out of 2.

We're having this in every class, this is just an example of a simple validation. The maximum is 50% branche coverage in a file with a single 'if' statement', which still shows as 2 out of 4.

Source code excerpt;
```CS
public class ValidatePeriod : BaseValidationAttribute
{
	protected override ValidationResult IsValid(object value, ValidationContext validationContext)
	{
		IPeriod relativePeriod = value as IPeriod;

		DateTime startTime = relativePeriod.StartTime;
		DateTime endTime = relativePeriod.EndTime;
		DateTime startDate = relativePeriod.StartDate;
		DateTime endDate = relativePeriod.EndDate;

		if (DateTimeHelper.MergeDateAndTime(endDate, endTime) <	DateTimeHelper.MergeDateAndTime(startDate, startTime))
			return new ValidationResult("Startdate is set sooner than the end date.");
		return null;
	}

	public override bool IsValidFor(Type checkType)
	{
		return (typeof(IPeriod).IsAssignableFrom(checkType));
	}
}
```

XML excerpt;
```XML
<Class>
  <Summary numSequencePoints="9" visitedSequencePoints="9" numBranchPoints="4" visitedBranchPoints="4" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" />
  <FullName>X.ValidatePeriod</FullName>
  <Methods>
    <Method visited="true" cyclomaticComplexity="2" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
      <Summary numSequencePoints="8" visitedSequencePoints="8" numBranchPoints="3" visitedBranchPoints="3" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" />
      <MetadataToken>100665878</MetadataToken>
      <Name>System.ComponentModel.DataAnnotations.ValidationResult X.ValidatePeriod::IsValid(System.Object,System.ComponentModel.DataAnnotations.ValidationContext)</Name>
      <FileRef uid="3073" />
      <SequencePoints>
        <SequencePoint vc="4" uspid="108867" ordinal="0" offset="0" sl="16" sc="4" el="16" ec="46" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="4" uspid="108868" ordinal="1" offset="7" sl="18" sc="4" el="18" ec="50" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="4" uspid="108869" ordinal="2" offset="14" sl="19" sc="4" el="19" ec="46" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="4" uspid="108870" ordinal="3" offset="21" sl="20" sc="4" el="20" ec="50" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="4" uspid="108871" ordinal="4" offset="28" sl="21" sc="4" el="21" ec="46" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="4" uspid="108872" ordinal="5" offset="36" sl="23" sc="4" el="23" ec="114" bec="2" bev="2" fileid="3073" />
        <SequencePoint vc="2" uspid="108873" ordinal="6" offset="58" sl="24" sc="5" el="24" ec="79" bec="0" bev="0" fileid="3073" />
        <SequencePoint vc="2" uspid="108874" ordinal="7" offset="69" sl="25" sc="4" el="25" ec="16" bec="0" bev="0" fileid="3073" />
      </SequencePoints>
      <BranchPoints>
        <BranchPoint vc="2" uspid="108875" ordinal="0" offset="56" sl="23" path="0" offsetend="58" fileid="3073" />
        <BranchPoint vc="2" uspid="108876" ordinal="1" offset="56" sl="23" path="1" offsetend="69" fileid="3073" />
      </BranchPoints>
      <MethodPoint xsi:type="SequencePoint" vc="4" uspid="108867" ordinal="0" offset="0" sl="16" sc="4" el="16" ec="46" bec="0" bev="0" fileid="3073" />
    </Method>
    <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
      <Summary numSequencePoints="1" visitedSequencePoints="1" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
      <MetadataToken>100665879</MetadataToken>
      <Name>System.Boolean X.ValidatePeriod::IsValidFor(System.Type)</Name>
      <FileRef uid="3073" />
      <SequencePoints>
        <SequencePoint vc="1" uspid="108877" ordinal="0" offset="0" sl="30" sc="4" el="30" ec="57" bec="0" bev="0" fileid="3073" />
      </SequencePoints>
      <BranchPoints />
      <MethodPoint xsi:type="SequencePoint" vc="1" uspid="108877" ordinal="0" offset="0" sl="30" sc="4" el="30" ec="57" bec="0" bev="0" fileid="3073" />
    </Method>
    <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
      <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
      <MetadataToken>100665880</MetadataToken>
      <Name>System.Void X.ValidatePeriod::.ctor()</Name>
      <SequencePoints />
      <BranchPoints />
      <MethodPoint vc="3" uspid="108878" ordinal="0" offset="0" />
    </Method>
  </Methods>
</Class>
```

We're running OpenCover 4.5.3723 and ReportGenerator 2.1.3.0. We've updated yesterday, which added the branch coverage to the reports.

I can't see anything obvious in your source code that can help me fix this problem.

**Comment by danielpalme** [comment]
Your XML contains this information about branches:
```
<BranchPoints>
  <BranchPoint vc="2" uspid="108875" ordinal="0" offset="56" sl="23" path="0" offsetend="58" fileid="3073" />
  <BranchPoint vc="2" uspid="108876" ordinal="1" offset="56" sl="23" path="1" offsetend="69" fileid="3073" />
</BranchPoints>
```
This seems to be correct. And then the HTML report will show 2 of 2 branches covered.
I created a similar class and I get 2 branches with both are shown as covered in the report.

Do you pass a single coverage report to ReportGenerator or several files?

**Comment by CookieNick** [comment]
Thanks for your amazingly fast response.

I have a batch file which executes the coverage, which just uses one results.xml. The line of code which executes the Report Generator is this;

```
..\packages\ReportGenerator.2.1.3.0\reportgenerator.exe -reports:results.xml -targetdir:CoverageReport
```

I do execute three unit test projects through OpenCover (which calls mstest with three testcontainer arguments). To be sure, I've checked the file id's, but there's only one file with id '3073' as in the example.

**Comment by danielpalme** [comment]
Could you provide the full results.xml?
You can send it to danielpalme82 [at] gmail.com

**Comment by danielpalme** [comment]
I took a look at the results.xml you have sent me.
I think I found the reason why you get strange results.

Each of your unit test assemblies use a separate copy of the X.BusinessLayer.dll.
The X.BusinessLayer.dll is referenced 4 times. One test assembly covers the two branches the others don't cover the relevant code.
ReportGenerator groups the assemblies by their name and then shows 2 of 8 branches as covered.

To fix this issue try using the following option when executing **OpenCover**: -mergebyhash

Please let me know if this helps.

**Comment by CookieNick** [comment]
Yes, this helps. My issue helps. Thanks a lot for your outstanding support!

**Comment by jrnail23** [comment]
@danielpalme, I think I have a similar problem, but OpenCover's `-mergebyhash` isn't working for me.
The OpenCover XML is reporting significantly different numbers than I'm getting from ReportGenerator.

I'd be happy to send along my files for troubleshooting.

**Comment by danielpalme** [comment]
Please send me your OpenCover file (danielpalme82@gmail.com).
And (if possible) a class file, where you think something is wrong.

**Comment by jrnail23** [comment]
@danielpalme, I'll be sending you my file soon.
Specifically, I'm not sure if my branch point data is inaccurate, but ReportGenerator says I have 1897 classes and 56.7% branch coverage, while my OpenCover output says I have 2443 classes (1549 visited) and 60.63% branch coverage.

**Comment by jrnail23** [comment]
@danielpalme, just realized I should tell you I emailed my file to you, in case it gets caught in your spam filters :smile:

**Comment by danielpalme** [comment]
I received your files. I will look into them within the next days.

**Comment by jrnail23** [comment]
Thanks, I appreciate the help!
