### ISSUE TITLE
Inline styles for VSTS compatible eye candy?

### ISSUE THREAD

**Issue by mkontula** [danielpalme/ReportGenerator#90]
Because of: https://github.com/Microsoft/vsts-tasks/issues/2357 would it possible to add switch for forcing styles to be inlined to report files? It of course would greatly increase the file sizes and it's by any standards wrong but since VSTS is apparently paranoid of meta tags and links, I would see this approach as a viable workaround.

**Comment by danielpalme** [comment]
Should be possible. Will come back to you within the next 1-2 weeks

**Comment by mkontula** [comment]
Most appreciated!

**Comment by danielpalme** [comment]
Could you please test this release:
https://www.nuget.org/packages/ReportGenerator/2.5.8-beta1

You should use the following command line argument:
-reportypes:HtmlInline

instead of 
-reportypes:Html

**Comment by nulltoken** [comment]
@danielpalme Gave this beta package a try. Works pretty well. Thanks!

**Comment by danielpalme** [comment]
@nulltoken 
Did you test it with VSTS?

**Comment by nulltoken** [comment]
Indeed. Otherwise I wouldn't have reported my test :wink:

As the html is displayed within an iframe, navigating within the report is a bit clunky (lack of a link back to the main page, and mandatory usage of the right mouse button, then select the "back" menu item) but a definitive enhancement compared to previous behavior.

![image](https://cloud.githubusercontent.com/assets/92363/26078315/5f4b4704-39bf-11e7-97fd-a57e02e928e1.png)

![image](https://cloud.githubusercontent.com/assets/92363/26078478/fdc652a2-39bf-11e7-8d89-12b98f69905d.png)

Few minor findings, though: 
- No "Collapse all / Expand all / Grouping/ Filtering " feature of the main page.
- The white "i" in the blue circle picture doesn't seem to be displayed next to "Cyclomatic complexity  / NPath complexity ..." titles in the type detail page.

**Comment by nulltoken** [comment]
The chrome console displays messages similar to the one below:

```
Blocked script execution in 'https://xxxxxxxx.visualstudio.com/xxxxxxxxxxx-dddd-cccccc-dddd-qqqqqqqqqqqq/_…owse/000001/Code%20Coverage%20Report_13370/XXXXXXXX_1.htm' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by mkontula** [comment]
Similar test results here. Mr. Trump would say "This is HUUUGE,  I mean, HUUUUUGE improvement". Lack of scripts is understandable, due to vsts' paranoia.

**Comment by mkontula** [comment]
Well played Sir! Keep up the good work and don't hesitate to ask for another hand anytime! Would be happy to help!

**Comment by dzfweb** [comment]
could some one give a sample of how to integrate it with vsts

**Comment by danielpalme** [comment]
Some hints would be great. I would also like to add them to the wiki:
https://github.com/danielpalme/ReportGenerator/wiki/Integration

**Comment by danielpalme** [comment]
@dzfweb 
I managed to create a basic setup with the following steps

1. Setup of a VSTS build agent which runs on my machine: https://YOURACCOUNT.visualstudio.com/CoverageTest/_admin/_AgentQueue
2. Commit/Push a sample project to VSTS. I created this project: 
[VSTS_CoverageSample.zip](https://github.com/danielpalme/ReportGenerator/files/1603594/VSTS_CoverageSample.zip) It contains a .NET class library and a test project based on xUnit. It also contains two _bat_ files which:

    - Executes the tests with [OpenCover](https://github.com/OpenCover/opencover)
    - Generates a Cobertura file using [OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter)
    - Generates HTML report using [ReportGenerator](https://github.com/danielpalme/ReportGenerator)

3. Setup of build definition in VSTS. In this case I used the ".NET Desktop" template and made some modifications:
    - Removed the **VsTest** step
    - Added a **Batch Script** step after **Build solution** which executes the bat file with the following command: `RunTests_$(BuildConfiguration).bat`
![bat](https://user-images.githubusercontent.com/859606/34569010-c1bb2a3e-f167-11e7-995d-01ae5df88691.png)
     - Added a **Publish Test Results** step after **Publish symbols path**. This uploads the xUnit results to VSTS
![test_results](https://user-images.githubusercontent.com/859606/34568705-f43e21ec-f166-11e7-833b-d0090e873167.png)
    - Added a **Publish Code Coverage Results** step after **Publish Test Results** using the following configuration:
![publish_code_coverage](https://user-images.githubusercontent.com/859606/34568696-ef829476-f166-11e7-93de-9bab5c7459c4.png)

4. Execute build and see results
![result](https://user-images.githubusercontent.com/859606/34568864-69f93f5c-f167-11e7-8c0e-75c26c37a872.png)

Hope this helps!

**Comment by dzfweb** [comment]
@danielpalme thank you!!! It'll be realy helpful.

**Comment by danielpalme** [comment]
@dzfweb 
I updated the wiki as well: https://github.com/danielpalme/ReportGenerator/wiki/Integration

**Comment by dzfweb** [comment]
thanks again @danielpalme,

another thing is how to do this whit MSTests? I'm not using xUnit, is it needed?

**Comment by danielpalme** [comment]
xUnit is not required.
You have to make some modifications:

- Modify the bat file(s) to execute _MSTest_/_vstest.console.exe_ instead of _xunitconsole.exe_:
```
mkdir TestResults
mkdir TestResults\reports

%userprofile%\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -coverbytest:* -returntargetcode -mergebyhash -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "-targetargs:CalculatorTest\bin\Debug\CalculatorTest.dll /InIsolation /platform:x64" -filter:+[*]* "-output:TestResults\reports\opencover.xml"

%userprofile%\.nuget\packages\opencovertocoberturaconverter\0.2.6\tools\OpenCoverToCoberturaConverter.exe "-input:TestResults\reports\opencover.xml" "-sources:." "-output:TestResults\reports\cobertura.xml" "-includeGettersSetters:true"

%userprofile%\.nuget\packages\reportgenerator\3.1.1\tools\ReportGenerator.exe -reporttypes:HTMLInline "-reports:TestResults\reports\opencover.xml" "-targetdir:TestResults\reports" -verbosity:Info -historydir:TestResults\reports\history
```
- In step **Publish Test Results** change the _Test result format_ and _Test results files_

**Comment by dzfweb** [comment]
Nice,

i think the path 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe` won't work on vsts, wich path should i use?

**Comment by danielpalme** [comment]
Sorry, I don't know. I have used a local build agent.

**Comment by dzfweb** [comment]
Anyway, thank you so much for your time expended helping me, was realy helpful.

**Comment by dzfweb** [comment]
i've finally make it works, but now i want to know if is possible to view the html generated inside the code coverage tab of build result.

**Comment by danielpalme** [comment]
IMHO, that's not possible in VSTS.
Which path did you use for  _MSTest/vstest.console.exe_?
