### ISSUE TITLE
The sum of "total lines" counts the same file several times

### ISSUE THREAD

**Issue by zvib** [danielpalme/ReportGenerator#92]
The tool shows a report line for every class but "total lines" of the whole file containing the class..
So, if a file contains 10 classes then the summary would add up the file amount of lines 10 times instead of once.

**Comment by danielpalme** [comment]
That's the current behavior, correct.
But if you have several classes in a single file, it would not be easy to tell which line belongs exactly to which class (e.g. using statements, namespace declaration).
So this metric is not 100% perfect, but works quite well if still to the rule _one class per file_.

**Comment by zvib** [comment]
Hi Daniel
Thanks for your reply.
I understand that each class line will have the number of lines in the whole file.
I would just like to suggest that the when you sum the total lines column – identify that you already counted the lines of specific file and don't count it again.
The issue with each line is at least consistent. The issue with the summary (per assembly or main summary) just doesn't make sense.
My boss saw the numbers of "Coverable lines = 600K, total lines = 6 million" and his reaction was : we can't use OpenCover because it obviously misses 92% or our code…
Perhaps don't show it at all or add some comment..

Thanks
Zvika

**Comment by danielpalme** [comment]
Will have a look at it.

**Comment by danielpalme** [comment]
Could you please test this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.9-beta1

Total line count in summary table can now differ from sum of all classes:

![diff](https://cloud.githubusercontent.com/assets/859606/26761496/d5659b9e-4930-11e7-9841-c9b0b7c7e178.png)

**Comment by zvib** [comment]
Hi Daniel
Can I just get a zip file? I don't want to get it via nugget as I don't want it to be attached to any specific VS solution
Thanks

**Comment by zvib** [comment]
Ok, I created a dummy vs project and used the nugget console…
The number in the overall summary looks reasonable.
The number of total lines per assembly looks like it's still with the problem – I don't know if you intended to fix this as well or just the overall summary

Covered

Uncovered

Coverable

Total

404

7206

7610

1514907


Thanks
Zvika

From: Zvika Berkovich
Sent: Sunday, June 04, 2017 4:27 PM
To: 'danielpalme/ReportGenerator' <reply@reply.github.com>
Subject: RE: [danielpalme/ReportGenerator] The sum of "total lines" counts the same file several times (#92)

Hi Daniel
Can I just get a zip file? I don't want to get it via nugget as I don't want it to be attached to any specific VS solution
Thanks

**Comment by danielpalme** [comment]
The number of total lines per assembly is calculated on the fly based on your filters.
Here the values of all classes are summed up and therefore not 100% accurate.

**Comment by danielpalme** [comment]
New release is available:
https://www.nuget.org/packages/ReportGenerator/2.5.9
