### ISSUE TITLE
Simpler badge version enhancement

### ISSUE THREAD

**Issue by perezLamed** [danielpalme/ReportGenerator#93]
You have implemented an awesome badge in issue #25. Are you able to show it in a github readme file?
(When I look at your readme, sometimes it show and sometimes it does not.)

The problem I am struggling with is to get to show your awesome badge on github readme. [See Readme](https://github.com/perezLamed/LamedalCore/blob/master/README.md).  It just do not show. I have spend the whole day looking into svg to png converters, but none is able to render your badge. **Can you implement a simpler version of the badge?** This would help during the time needed for the technology to catch up.

Take a look at https://github.com/rebornix/DotBadge and https://gist.github.com/espadrine/8218740. These simple badge show perfectly on github.

**Comment by danielpalme** [comment]
If you use this URL, you can embed the badge directly without need to create a PNG:
```
![Result](https://rawgithub.com/perezLamed/LamedalCore/master/pics/badge.svg)
```
See this question on SO for further information:
https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

**Comment by perezLamed** [comment]
Thanks for the update. It works perfectly.

**Comment by jmbeach** [comment]
I would like exporting as png to be a feature so that you can use relative paths. I understand why you build the image as SVG, but maybe a library exists to convert it to png easily?

I am using the program inkscape to do this manually.

**Comment by danielpalme** [comment]
I will add a PNG output in the next release

**Comment by danielpalme** [comment]
Please have a look at the latest release:
https://www.nuget.org/packages/ReportGenerator/2.5.11
