### ISSUE TITLE
Exclude "excludebyfile" from report output

### ISSUE THREAD

**Issue by MarkPflug** [danielpalme/ReportGenerator#94]
I'm wondering if this is possible:

I'm using OpenCover and ReportGenerator to analyze code coverage for some projects. The projects I'm covering has a *lot* of generated code. I can instruct OpenCover to exclude these files from it's analysis using "-excludebyfile:*\*.g.cs". However, the contents of those files still shows up in the ReportGenerator output. I'm wondering if there is a way to instruct the ReportGenerator to not include these. There is so much generated code that it overwhelms the user-written code and makes it hard to consume the reports.

Great tool, thanks so much!

**Comment by danielpalme** [comment]
Have you tried the -classfilters parameter in ReportGenerator?

Example:
-classfilters:-SomeClass.cs

See also:
https://github.com/danielpalme/ReportGenerator#usage

**Comment by MarkPflug** [comment]
I have tried that, but I might be doing it wrong. This is from my custom MSBuild script:
``` XML
	<Target Name="BuildCoverageReport" BeforeTargets="Build">
		<RemoveDir Directories="$(ReportFolder)"/>
		<MakeDir Directories="$(ReportFolder)"/>
		<Exec Command="$(CoverageReportExePath) -reports:$(CoverageXmlReport) -targetdir:$(ReportFolder) -classfilters:-*\*.g.cs"/>
	</Target>
```

I'm not trying to exclude classes, but files. The situation is that I have a lot of files that contain generated partial classes (.g.cs), and the user provides custom logic in a sibling partial class (.cs). I want to exclude the generated "files" from the report, but include the user authored half of the code only. This is such an odd scenario that I'd be surprised if it was given any consideration.

Thanks for the quick response.

**Comment by danielpalme** [comment]
ReportGenerator currently only supports filtering assemblies and classes, but not files.
So your filter will not match any class name.

Maybe it makes sense to add a filter option for files too. Have to think about it and take closer look in my code base.

**Comment by MarkPflug** [comment]
I'm looking at the code myself. It looks pretty trivial to add this support, I've got it roughly working in 15 minutes. This should be a testament to how nice your code is! Would you accept a PR if i get this working satisfactorily?

**Comment by danielpalme** [comment]
Sure

**Comment by MarkPflug** [comment]
Took longer than it should have because of tabs/spaces issue (please don't judge me) that I didn't notice until I was about to send the PR. #95


Thanks again for your excellent software.

**Comment by mu88** [comment]
@MarkPflug what is the correct syntax for excluded Roslyn generated files? Using `"-filefilters:-LoggerMessage.g.cs"` still gives me the following ReportGenerator error:
```
Tool 'dotnet-reportgenerator-globaltool' was reinstalled with the latest stable version (version '5.1.6').
2023-10-25T11:38:48: Arguments
2023-10-25T11:38:48:  -reports:..\tests\**\*.opencover.xml
2023-10-25T11:38:48:  -targetdir:coveragereport
2023-10-25T11:38:48:  -filefilters:-LoggerMessage.g.cs
2023-10-25T11:38:48:  -reporttypes:HTMLInline
2023-10-25T11:38:49: File 'C:\source\Bitbucket\MyProject\src\AppStartup\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs' does not exist (any more).
```

**Comment by danielpalme** [comment]
@mu88
Please try `"-filefilters:-*LoggerMessage.g.cs"`

**Comment by mu88** [comment]
thx @danielpalme , it works
