### ISSUE TITLE
ReportGenerator not showing %Blocks covered

### ISSUE THREAD

**Issue by mpthegr** [danielpalme/ReportGenerator#96]
The generated report in html only shows %Lines covered,but not %Blocks

**Comment by danielpalme** [comment]
I don't have plans to track coverage of blocks.
How would this metric help to improve a code base's coverage?

Aren't line and brach coverage sufficient to get an impression about the coverage of each line?

**Comment by mpthegr** [comment]
Ahh.. I see.
Actually, I have many big blocks of code. and the block% gives me better numbers than line%.
ok thats fine. not a problem. I can do with lines%
