### ISSUE TITLE
Extract branch coverage instead of line coverage

### ISSUE THREAD

**Issue by Bheesma** [danielpalme/ReportGenerator#98]
I am using vstest.console.exe to generate .coverage report and codecoverage.exe to generate xml out of it. I see ReportGenerator provides only line coverage for this format. Is there any option to report branch coverage for this format?

**Comment by danielpalme** [comment]
Branch coverage is only support for OpenCover and Cobertura:
https://github.com/danielpalme/ReportGenerator/wiki/FAQ#which-coverage-tool-supports-which-features-in-the-html-report

The XML generated by vstest.console.exe and codecoverage.exe does not contain the necessary details.
