### ISSUE TITLE
Adding optional information to summary and history tooltip

### ISSUE THREAD

**Issue by stefantinger** [danielpalme/ReportGenerator#99]
Hi!

I am currently using opencover and reportgenerator on a weekly basis. I am covering a specific version of a software which will be implemented incrementally and therefore changes its code and also its version at least every day.

For me it would be interesting to see, especially in the history view, for which version the coverage run had been executed (not only the day). But I think this is not supported at the moment.

So maybe you can add an additional (string) parameter for "additional information" (in my case this would be the version of the software under test) and 
1. add this information to the summary of the generated report (we are only using Html and HtmlSummary) and 
2. also add it to the history files, where the information can then be visualized in the tooltip of a history entry.

**Comment by danielpalme** [comment]
Sounds like a perfect use case for a [custom report](https://github.com/danielpalme/ReportGenerator/wiki/Custom-reports)

**Comment by danielpalme** [comment]
Do you need any support on creating a custom report?

**Comment by danielpalme** [comment]
With this  [beta release](https://www.nuget.org/packages/ReportGenerator/3.0.0-beta1) I have added the requested functionality.
You can now use the following command line parameter:
```
-tag:YOUR_CUSTOM_INFORMATION
```

Would be great if you could give the new release a try:
https://www.nuget.org/packages/ReportGenerator/3.0.0-beta1

**Comment by stefantinger** [comment]
Thx for implementing it!
I will give it a try until end of this week!

**Comment by stefantinger** [comment]
Hi @danielpalme 

I just tried your implementation and it runs perfectly! Exactly what we needed :+1: 
Thx for implementing!
